### ISSUE TITLE
NPM Eth-mine-when-need Not Working w/ Parity (Looking for other solutions)

### ISSUE THREAD

**Issue by Dycedlp** [paritytech/parity-ethereum#10011]
- **Parity Ethereum version**: 2.1.7stable
- **Operating system**:  Linux
- **Installation**: one-line installer
- **Fully synchronized**:  yes
- **Network**: private
- **Restarted**: yes

I'm running a POA parity ETH blockchain w/ two validators.  When I first created this blockchain I installed 'emwn', it worked perfectly.  Recently, after I timeshifted back to a previous restore point before the emwn was installed, I attempted installing it the same way... One time it acted as if it were working, but wasn't and now its saying '/usr/bin/env: ‘node’: No such file or directory'.  I was wondering if theres a more stable/reliable solution for not mining blocks with nothing in them.  Ik in geth you can have a .js file running to prevent empty transactions going through.. wondering if theres something similar for parity...
------------------------------------------------------------------------------------------------------
 Also thanks for the earlier insight on how to remove, and install a new parity, I'm just not sure where to look for the downloaded binary.  The name and/or normal location on ubuntu 16.04 would be very helpful as well.

**Comment by joshua-mir** [comment]
You can use `echo $PATH` to list the default folders where your binaries are run from
It looks like you don't have nodejs installed. 
If you don't want to mine empty blocks, you should enable emptySteps in your chain config. 

We appreciate you coming here for help with your issues, but can you keep minor questions like these in gitter or riot parity support channels please?

**Comment by Dycedlp** [comment]
@joshua-mir Yes, absolutely. And thanks so much!  Didn't even know of those resources...  Also I highly appreciate the constant activity of this community,  ya'll are an amazing & epic group to say the least. Cheers!
