### ISSUE TITLE
parity >=2.1.6 using at least 2x disk space compared to <= 2.0.8

### ISSUE THREAD

**Issue by stephgosling** [paritytech/parity-ethereum#10023]
- **Parity Ethereum version**: 2.1.6, 2.2.2, 2.2.3
- **Operating system**: Ubuntu 18.04
- **Installation**: official docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes
- **Compute**: m5d.large, c5d.xlarge

We have been successfully running Parity (since about 1.10 to 2.0.8) on the above instance types and their ephemeral storage (~70GB and ~95GB respectively, all graphs below are based upon the 90GB instance). From a cold start and warp sync they end up using about 40GB storage and had been stable for weeks if not months (including the automatic upgrade from 1.11.x to 2.0.x). The warp sync + final catchup takes a couple of hours and things are happy:

![correct behaviour](https://ipfs.io/ipfs/Qme5ipDE15wvrqhrR9o5CaKp6sKN7D99RTAxNLnB52Ry9n)

(blue line is rootfs, red the ephemeral storage)

With 2.1.6, 2.2.2 and 2.2.3 our disk usage profile at start looks as below: again nice fast warp sync (faster perhaps) a brief period of stability and then increased usage until the disk fills and parity segfaults

![aberrant behaviour](https://ipfs.io/ipfs/QmVzRtAhd1RUdfR1nZiUowk1UMSJEDoDemQZEJ7yXXzBLV)

Parity output looks normal and the node otherwise is fine, other than the increased disk usage. 

Configuration for both was as follows:

```
[parity]
mode = "active"

[ui]
disable = true

[network]
min_peers = 100
max_peers = 100

[rpc]
disable = false
interface = "0.0.0.0"
port = 8545
apis = ["web3", "eth", "net", "rpc", "parity"]

[websockets]
disable = false
port = 8546
interface = "0.0.0.0"
origins = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]
max_connections = 1024

[footprint]
cache_size = 1024 # MB
# db_compaction = "ssd"   <--- made no difference whether left on auto or changed to ssd

[snapshots]
disable_periodic = true

[mining]
tx_queue_size = 16536
tx_queue_per_sender = 64 # MB
tx_queue_mem_limit = 64 # MB
```
As I said we were running comfortably since the summer well inside 70GB storage

Did other people see the same behaviour? (you may have and not realised as your disks may have been bigger), can anyone think of a default behaviour change that might have happened going from 2.0 to 2.1?

Any thoughts appreciated.

**Comment by tomusdrw** [comment]
@stephgosling have you tried with `--no-ancient-blocks`? I suppose it was broken and recently got fixed, so maybe the node is just succesfuly importing ancient (pre-warp) blocks & receipts, which would actually be expected behaviour.

**Comment by joshua-mir** [comment]
(this was my first thought as well, but wouldn't @stephgosling have noticed the ongoing ancient block sync in their logs?)

**Comment by stephgosling** [comment]
thanks guys, am syncing a 2.1.6 node now so will compare logs and rerun

**Comment by stephgosling** [comment]
ok I started 2.1.6 and a 2.2.3 and they both filled up in around 13 hours and 8 hours respectively (yey sync improvements in beta ;) ). the 2.0.8 node is still happy at some 39GB usage. 

Log and graph of 2.2.3 the disk usage [here](https://futr.io/ipfs/QmSeUDLCjC4uAsMKm21ZPkFZuvroBDA4tm7XkpbVTiBppd). No notifications about ancient blocks and the only thing I see at all in the logs is a `Reorg` which to me looks normal. Now restarted the 2.2.3 with `--no-ancient-blocks` to see if that makes any discernible difference.

**Comment by stephgosling** [comment]
ok! that does appear to be it!  With `--no-ancient-blocks` enabled the disk usage behaviour is now the same as with 2.0.8 and before. I am oing to run one more instance with alot of fast storage to see what the current storage requirements are as [this is now very out of date](https://wiki.parity.io/FAQ#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements)

**Comment by 5chdn** [comment]
You can compare it with my node

http://didtheethereumblockchainreach1tbyet.5chdn.co/

**Comment by stephgosling** [comment]
> You can compare it with my node
> 
> http://didtheethereumblockchainreach1tbyet.5chdn.co/

Cool, they tally. ![disk usage graph](https://futr.io/ipfs/QmYeyBWDWoj2gjuCcUJhNjwppmR6Wiy2jG3hXkMLDdwtic) (the 8GB discrepancy between yours and this one is because warp sync always appears to leave cruft in the snapshot directory...
