### ISSUE TITLE
[PROJECT] Revise Headline

### ISSUE THREAD

**Issue by lazaridiscom** [paritytech/parity-ethereum#10035]
(strictly speaking, this would be an PRODUCT issue)

## Problem

The current Project Description (here on github) is this one:

> The fast, light, and robust EVM and WASM client.

An understatement?

## Possible Solution

It could be changed to something like:

**The Industrial Strength Ethereum Node with Dual VM (EVM and WASM)**

or

**A Carrier-Grade Ethereum Node with Twin VM (EVM and WASM)**

or

**The Enterprise-Grade Ethereum Node with Twin VM (EVM and WASM)**

**Comment by 5chdn** [comment]
Thanks, but we are not trying to sell something.

**Comment by lazaridiscom** [comment]
related: #10034
