### ISSUE TITLE
how can i get test usdt from kovan testnet

### ISSUE THREAD

**Issue by ruguo220088** [paritytech/parity-ethereum#10044]
I'm running: Parity v2.1.9-stable

Which Parity version?: v2.1.9-stable
Which operating system?: MacOS
How installed?: via installer
Are you fully synchronized?: yes
Which network are you connected to?: kovan
I dont konw how can i get some testnet erc20 token like "testnet Erc20 token--Tether USDT" which token not i generate.
From website there is somebody said: you can tranfer ether to erc20 token contract address, then contract will give you some erc20 token.
but when i did like before, i keep receiving the following:
Contract 0xd92eee71478e115fcc5342fa44242e7896b8af3b  
 Warning! Error encountered during contract execution [Reverted] 
Can someone please help...

**Comment by joshua-mir** [comment]
Hey, this really isn't an issue for the parity-ethereum repository.

I can help you out more if you drop into our  [gitter](https://gitter.im/paritytech/parity) channel. But first I'd check out kovan.etherscan.net or another block explorer with your transactionhash to see what might have been the issue with the transaction.

**Comment by hiepnm** [comment]
I need some tether usdt erc20 too. @ruguo220088 do you have any coins? And How to get it?

**Comment by shabbir-bblab** [comment]
> I need some tether usdt erc20 too. @ruguo220088 do you have any coins? And How to get it?

Hey i need ERC-20 based USDT as well but couldn't find anywhere , how can i get it... pls help.
