### ISSUE TITLE
Obtaining revert reason after eth_estimateGas using trace

### ISSUE THREAD

**Issue by keikumata** [paritytech/parity-ethereum#10043]
- **Parity Ethereum version**: 1.10.6
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: Private PoA
- **Restarted**: no

I used Remix to deploy a contract and invoke a function that just reverts with a comment (ex. revert("Hello")). Using the txHash, I used [trace_replayTransaction](https://wiki.parity.io/JSONRPC-trace-module#trace_replaytransaction) to obtain the trace. This is the response I got:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "output": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000548656c6c6f000000000000000000000000000000000000000000000000000000",
    "stateDiff": null,
    "trace": [
      {
        "action": {
          "callType": "call",
          "from": "0xf7f80d1fccf17f78df1993ead5f73e97bb3d129a",
          "gas": "0x2d73a8",
          "input": "0xbfb4ebcf",
          "to": "0x1cf914f7e7a77584ef3cfb66dd350b9b40e2a61a",
          "value": "0x0"
        },
        "error": "Reverted",
        "subtraces": 0,
        "traceAddress": [],
        "type": "call"
      }
    ],
    "vmTrace": null
  },
  "id": 1
}
```

Now, following the feedback from this [issue](https://github.com/paritytech/parity-ethereum/issues/9887), I decoded my output of 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000548656c6c6f000000000000000000000000000000000000000000000000000000 to be "Hello".

When using eth_estimateGas however, I am unable to replay transactions and use trace_replayTransaction. I tried using trace_rawTransaction, but I was not able to get an output (my output was always just "0x").

Is there a way to obtain a trace and get the revert reason after estimating the gas?

**Comment by joshua-mir** [comment]
I believe you are looking for https://wiki.parity.io/JSONRPC-trace-module#trace_call here? You can't use trace_rawTransaction for this because that doesn't perform the actual transaction, only retrieves existing traces.

**Comment by keikumata** [comment]
@joshua-mir is there no way to retrieve the revert reason string at just the gas estimation level (before even submitting an actual transaction)?

**Comment by joshua-mir** [comment]
@keikumata you might be able to use https://github.com/paritytech/parity-ethereum/tree/master/evmbin with `--chain` specified to execute the transaction.
