### ISSUE TITLE
Remove dependency on libusb on Android

### ISSUE THREAD

**Issue by tomaka** [paritytech/parity-ethereum#10058]
Cross-compiling to Android is quite tricky because of libusb-sys.
https://github.com/paritytech/libusb-sys/pull/4 fixed the fact that we were in reality compiling for Linux when trying to compile libusb for Android.

However this unveiled the problem that libusb actually doesn't support Android that well: https://github.com/paritytech/libusb-sys/blob/4418e92c82509d1f049f7942dffe62a0bf5dd871/libusb/libusb/core.c#L60

There are instructions to build libusb for Android here: https://github.com/paritytech/libusb-sys/blob/4418e92c82509d1f049f7942dffe62a0bf5dd871/libusb/android/README
However you are supposed to use `ndk-build` to do that, and we don't necessarily want to rewrite this tool in Rust.

Right now on Android we are [building libusb manually](https://github.com/paritytech/scripts/blob/a241620cb3410eea2903425111bb67e85463c61b/docker-files-for-Gitlab-CI-rust/cross/android/Dockerfile#L55-L70), but in order to do so we apply [a patch](https://github.com/paritytech/scripts/blob/a241620cb3410eea2903425111bb67e85463c61b/docker-files-for-Gitlab-CI-rust/cross/android/libudev.patch) on the source code, which is extremely hacky.
Libusb on Android seems to have quite [a few runtime issues](https://github.com/paritytech/libusb-sys/blob/4418e92c82509d1f049f7942dffe62a0bf5dd871/libusb/android/README#L92) as well.

A final solution is to remove the dependency on libusb on Android. This is probably the most simple solution, and the one I would suggest. Nobody uses our Android build yet, so we won't break anything.

I'm opening this issue to gather opinion. Any comment on this?

cc #9893 @TriplEight

**Comment by ordian** [comment]
> However this unveiled the problem that libusb actually doesn't support Android that well: https://github.com/paritytech/libusb-sys/blob/4418e92c82509d1f049f7942dffe62a0bf5dd871/libusb/libusb/core.c#L60

I think for Android it defined OS_LINUX:
https://github.com/paritytech/libusb-sys/blob/4418e92c82509d1f049f7942dffe62a0bf5dd871/libusb/android/config.h#L36
