### ISSUE TITLE
Binaries for v 1.11.11 not found

### ISSUE THREAD

**Issue by Genysys** [paritytech/parity-ethereum#10079]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 1.11.11
- **Operating system**: Linux - CentOS 7.5
- **Installation**: from binary https://releases.parity.io/v1.11.11/x86_64-unknown-centos-gnu/parity_1.11.11_centos_x86_64.rpm
- **Fully synchronized**: N/A
- **Network**: N/A
- **Restarted**: no / yes

We have a script that currently installs parity 1.11.11 from binaries.

Expected behaviour:

```
rpm -i https://releases.parity.io/v1.11.8/x86_64-unknown-centos-gnu/parity_1.11.8_centos_x86_64.rpm

Parity Installed
```

Actual Behaviour:

```
rpm -i https://releases.parity.io/v1.11.8/x86_64-unknown-centos-gnu/parity_1.11.8_centos_x86_64.rpm

curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://releases.parity.io/v1.11.11/x86_64-unknown-centos-gnu/parity_1.11.8_centos_x86_64.rpm - transfer failed
```

From the gitter channel, I understand that the storage bucket have been `reogranized`. We really need this version and would appreciate any guidance on getting our hands on it.

**Comment by joshua-mir** [comment]
@5chdn and @gabreal can probably comment more on the reorganization. The response you will get here is "that version is EOL" but from our conversation on gitter you already know that. Your only real option here is to build from source for that specific version; we can't support your specific use case here, sorry!

**Comment by c0deright** [comment]
https://releases.parity.io/ethereum/v1.11.8/x86_64-unknown-centos-gnu/parity_1.11.8_centos_x86_64.rpm

**Comment by joshua-mir** [comment]
Thanks @c0deright!

**Comment by 5chdn** [comment]
Yes, we moved it in a subfolder on the releases bucket. I didn't bother to update the release notes for **unsupported** versions ;-)
