### ISSUE TITLE
Parity doesn't mine certain kind of transactions

### ISSUE THREAD

**Issue by naikmyeong** [paritytech/parity-ethereum#10074]
![default](https://user-images.githubusercontent.com/44437404/50055703-8edb4380-0195-11e9-9089-ca5221315d9d.PNG)

While geth does 😄

**Comment by veox** [comment]
What I see here is a `parity` node having 1 peer, which the dashboards colors red.

The block number is the same, the hash is the same.

Everything is fine.

**Comment by tomusdrw** [comment]
@naikmyeong I guess you believe that the `113` transactions from geth nodes should appear on parity nodes as well?
That's semi-true, the stuff that nodes keep in the queue is completely subjective, the major difference that most likely affects this is `--min-gas-price` setting. AFAIR geth uses a constant value, while Parity Ethereum's value depend on the ETH/USD price. This means that if Parity have this setting higher than geth it will just ignore such transactions.

Please check what minimal gas price settings both nodes have and what gas price the transactions specify.
