### ISSUE TITLE
Implement `eth_subscribe('syncing')`

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/parity-ethereum#10080]
Didn't find this in the issues, so posting it here.

_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.0
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: ethereum / ropsten / kovan / all
- **Restarted**: yes

**Repro**:
create a WS connection and send `{"id":2,"jsonrpc":"2.0","method":"eth_subscribe","params":["syncing"]}`

**Expected**:
works

**Actual**: 
```
{"jsonrpc":"2.0","error":{"code":-32000,"message":"This request is not implemented yet. Please create an issue on Github repo."},"id":2}
```

**Comment by Tbaut** [comment]
This issue got spotted thanks to Fether but it also happens on full nodes.

**Comment by tomusdrw** [comment]
It was intentionally not implemented, cause the definition of "syncing" is a bit vague :) I guess we should make it work using `is_major_sync` heuristic: on every block import check `is_major_importing` and trigger the notification if the flag flips.
