### ISSUE TITLE
Aura: get current validator set

### ISSUE THREAD

**Issue by Destiner** [paritytech/parity-ethereum#10090]
I'm trying to understand validator set in Aura and have some questions.

First, how do validators change the set (adding/removing other validators)? Do they vote on chain and then their votes are calculated?

Second, what is the easiest way to get the current or snapshotted list of active validators? I guess this is somehow related but not sure how to apply it: https://wiki.parity.io/Validator-Set.html

**Comment by joshua-mir** [comment]
If you have a hard-coded validatorSet (defined in your chain specification), the only way to change it is via a hardfork - all nodes need to simultaneously change their chain specification files.

If you define a validator spec contract, how the validator set changes and who is allowed to make that change is defined by the logic of the contract. In [Kovan](https://github.com/parity-contracts/kovan-validator-set) the validatorSet contract has an owner that can addValidators and removeValidators at will, but if you wish, you can implement a vote, a Proof of Stake system, or anything else.

You can call getValidators() on your validatorSet contract to get the active set of validators, minus any defined directly in the chain specification file - more references in the repo linked above.

**Comment by ddorgan** [comment]
@Destiner it's currently in the kovan spec file. although this is due to change to a contract based set at some stage. The current spec is at: https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/kovan.json#L9

**Comment by Destiner** [comment]
I see, thanks.
