### ISSUE TITLE
Disk space growing by a factor of 2.8 on a fully synced client in less than 12 hours

### ISSUE THREAD

**Issue by jleeh** [paritytech/parity-ethereum#10097]
- **Parity Ethereum version**: v2.1.6
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

It's hard to pin-point when I started seeing this issue, but I can say that the last version I haven't seen this happen on was 2.0.6, and since using >2.1.0 I can reproduce this issue every time a new Parity instance is created.

To give some context, I have a pipeline of creating Parity nodes that takes a template of the database and each new instance is created pulls down that template, syncs until it hits the latest block height and then becomes active in the cluster.

I created a freshly synced template on the 19/12, and then created new Parity instances from that template. Overnight, I then seen the disk utilisation grew substantially, from 48GB (already fully synced) to 138GB:
![image](https://user-images.githubusercontent.com/10528926/50355276-0cac9f80-0546-11e9-83dd-78d3d5ff1628.png)

I'm also seeing huge read/write rates on the disk during this time. There's nothing to indicate in the logs that it's doing anything different in the default log level.

Thought it was the `fat_db` option that could of been causing the issue, but on setting it to `off`, there was no change.

Footprint section of the config:
```
tracing = "auto"
pruning = "auto"
cache_size = 6096
db_compaction = "ssd"
fat_db = "off"
scale_verifiers = true
num_verifiers = 16
```

**Comment by joshua-mir** [comment]
Hey, this is likely just ancient blocks syncing in the background. https://github.com/paritytech/parity-ethereum/issues/10023#issuecomment-444825382 there was an issue where ancient block sync was broken in older versions which was fixed, and now your nodes are actually syncing completely.

**Comment by joshua-mir** [comment]
Will close this as it's expected behavior - check out the conversation in the linked issue if you want to intentionally prevent ancient blocks syncing.
