### ISSUE TITLE
eth_call to pending state of fully synced full history Parity node returns error

### ISSUE THREAD

**Issue by vbaranov** [paritytech/parity-ethereum#10096]
- **Parity Ethereum version**: 2.2.1-beta
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: POA core
- **Restarted**: yes

### Description of the Issue

`eth_call` to `pending` state with fully synced Parity full history node returns **This request is not supported because your node is running with state pruning. Run with --pruning=archive.**

```
MacBook-Pro-Viktor:~ viktor$ curl -X POST -H 'Content-Type: application/json'  --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to": "0x4316f704989157162de90997ce1a05cff3118680", "data": "0x8da5cb5b"}, "pending"],"id":676681188149}' http://localhost:8545
{"jsonrpc":"2.0","error":{"code":-32000,"message":"This request is not supported because your node is running with state pruning. Run with --pruning=archive."},"id":676681188149}
```

<img width="723" alt="screen shot 2018-12-21 at 13 16 03" src="https://user-images.githubusercontent.com/4341812/50338687-2c33d000-0526-11e9-9651-572ef21ea1df.png">

#### Parameters of archive node:

```
2018-12-21 13:48:10  Starting Parity-Ethereum/v2.2.1-beta-5c56fc5-20181114/x86_64-macos/rustc1.30.1
2018-12-21 13:48:10  Keys path ./parity_data/keys/Core
2018-12-21 13:48:10  DB path ./parity_data/chains/Core/db/39bb23edadd3d2d8
2018-12-21 13:48:10  State DB configuration: archive +Fat +Trace
2018-12-21 13:48:10  Operating mode: active
2018-12-21 13:48:10  Warning: Warp Sync is disabled because Fat DB is turned on.
2018-12-21 13:48:10  Configured for Core using AuthorityRound engine
```

- no CLI parameters
- [spec.json](https://github.com/poanetwork/poa-chain-spec/blob/core/spec.json)
- [bootnodes.txt](https://github.com/poanetwork/poa-chain-spec/blob/core/bootnodes.txt)
- [node.toml](https://gist.github.com/vbaranov/2e352c02e670afd3655bff0393c16c21#file-node-toml)

```
[parity]
chain = "./spec.json"
base_path = "./parity_data"

[network]
reserved_peers="./bootnodes.txt"
port = 30303

[rpc]
apis = ["web3","eth","net", "parity",  "traces" ]
port = 8545
interface = "0.0.0.0"
cors=["all"]

[websockets]
port = 8546
interface = "0.0.0.0"
max_connections = 1000
apis = ["web3","eth","net","parity", "pubsub", "traces"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"
#scale_verifiers = true
```

What is wrong with the configuration to get a response from `pending` state?

**Comment by tomusdrw** [comment]
@vbaranov try with `--force-sealing`. By default `pending` state is not available (unless running with `--force-sealing` or mining), the error message here is very misleading though and definitely should be improved.

**Comment by vbaranov** [comment]
@tomusdrw, I restarted archive node with `--force-sealing` flag from 0 block. The error for `pending` state is still there.

**Comment by ddorgan** [comment]
Replace the method from ```pending``` to ```latest```. It should fix the issue.
