### ISSUE TITLE
Disk space suddenly filling up, even after increasing volume size. 

### ISSUE THREAD

**Issue by lampshade9909** [paritytech/parity-ethereum#10098]
- **Parity Ethereum version**: Parity-Ethereum/v2.1.10-stable-b47e064-20181213/x86_64-linux-gnu/rustc1.31.0
- **Operating system**: Ubuntu Server 18.04
- **Installation**: bash <(curl https://get.parity.io -L) -r stable
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

My configuration:

parity --warp --pruning=fast --no-serve-light --max-peers=250 --snapshot-peers=50 --min-peers=50 --mode=active --tracing=off --db-compaction=ssd --cache-size=4096 --rpccorsdomain=* --rpcaddr=0.0.0.0 --jsonrpc-hosts=all &

I've been running parity nodes on two separate AWS instances for the last 3 months then suddenly during the last week or two (maybe related to an auto-update) I've been having the following issue: the disk space fills up to 100% and the parity node crashes.  Before the problem occurred, my volume size was about 69 GB and that was more than enough to run the node with my configuration listed above.  After the problem occurred, I increased the volume size, increasing from about 69gb to around 150gb.  I figured that should be more than enough based on documentation online.  Sure enough, after letting the node run for a while it filled up 100% again using up all 150 GB.  

**Error message I receive when running parity while the disk is full:**
```
ubuntu@ip-172-31-21-114:~$ parity --warp --pruning=fast --no-serve-light --max-peers=250 --snapshot-peers=50 --min-peers=50 --mode=active --tracing=off --db-compaction=ssd --cache-size=4096 --rpccorsdomain=* --rpcaddr=0.0.0.0 --jsonrpc-hosts=all &
[1] 1223
ubuntu@ip-172-31-21-114:~$ Option '--warp' does nothing. It's on by default.
Option '--rpcaddr' is deprecated. Please use '--jsonrpc-interface' instead.
Option '--rpccorsdomain' is deprecated. Please use '--jsonrpc-cors' instead.
2018-12-22 03:06:27 UTC Starting Parity-Ethereum/v2.1.10-stable-b47e064-20181213/x86_64-linux-gnu/rustc1.31.0
2018-12-22 03:06:27 UTC Keys path /home/ubuntu/.local/share/io.parity.ethereum/keys/ethereum
2018-12-22 03:06:27 UTC DB path /home/ubuntu/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-12-22 03:06:27 UTC State DB configuration: fast
2018-12-22 03:06:27 UTC Operating mode: active
2018-12-22 03:06:28 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col7, col6, col1, col0, col2, col3, col4, col5, attempting repair
Failed to open database Custom { kind: Other, error: StringError("IO error: No space left on deviceWhile appending to file: /home/ubuntu/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/MANIFEST-000001: No space left on device") }
```

That didn't make any sense to me, 150GB should be enough right?  So I left that instance intact and started up another instance with the same exact specs using the same exact configuration.  The second instance also has 150GB.  It's fully synced and working fine so far and the disk usage seems to be fluctuating around the 70's-80's of GBs out of 150GB.  I'm waiting to see if that one will fill to 100% or not, but so far it's fine.  

**Here's what the disk space looks like on the broken one:**
```
ubuntu@ip-172-31-21-114:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.6G     0  7.6G   0% /dev
tmpfs           1.6G  720K  1.6G   1% /run
**/dev/nvme0n1p1  146G  146G  620K 100% /**
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/930
/dev/loop1       13M   13M     0 100% /snap/amazon-ssm-agent/495
/dev/loop2       90M   90M     0 100% /snap/core/6130
/dev/loop3       88M   88M     0 100% /snap/core/5328
tmpfs           1.6G     0  1.6G   0% /run/user/1000
ubuntu@ip-172-31-21-114:~$ 
```

**Here's what the disk space looks like on the working one that was installed fresh about 10 hours ago that's been fully synced for at least 6 hours with the same exact configuration:** 

```
ubuntu@ip-172-31-18-116:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.6G     0  7.6G   0% /dev
tmpfs           1.6G  720K  1.6G   1% /run
**/dev/nvme0n1p1  146G   81G   66G  56% /**
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop0       88M   88M     0 100% /snap/core/5328
/dev/loop1       13M   13M     0 100% /snap/amazon-ssm-agent/495
tmpfs           1.6G     0  1.6G   0% /run/user/1000
/dev/loop2       90M   90M     0 100% /snap/core/6130
/dev/loop3       18M   18M     0 100% /snap/amazon-ssm-agent/930
```
 
**Questions:**
1.) Is it possible my parity node auto-updated and the new version is using significantly more memory?
2.) Is it possible that creating a new instance with the newest version of parity uses less disk space than an older which got upgraded one?  

Happy Holidays!

**Comment by joshua-mir** [comment]
1) The issue here is actually that older versions had a bug which caused them to never actually sync old/ancient blocks when using warp sync which *has* been fixed in recent versions. Check out the discussion here https://github.com/paritytech/parity-ethereum/issues/10023#issuecomment-444825382

2) Yes, if a node was synced with an older version, some of it's database might be in an older database format - a node synced from scratch will generally be closer to the predicted/expected disk usage than an older node.

For reference [you should expect around 133gb of disk space usage with your cleanly synced node atm](https://wiki.parity.io/FAQ#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements)

Happy holidays!
