### ISSUE TITLE
Can you publish EIP-712 as a crate?

### ISSUE THREAD

**Issue by jedahan** [paritytech/parity-ethereum#10092]
I'd love to be able to depend on a solid implementation of EIP-712 for my own projects, and vendoring out all of parity-ethereum seems pretty heavy handed.

**Comment by tomusdrw** [comment]
The repo it lives in doesn't matter that much, we can just `cargo publish` the crate while still keep it here.

Also in your project you can specify git dependency for `eip-712` crate and point to parity-ethereum repo to get that fetched.

CC @seunlanlege can you `cargo publish` your work and add `@partytech/core-devs` as maintainers on crates.io?

**Comment by jedahan** [comment]
> Also in your project you can specify git dependency for eip-712 crate and point to parity-ethereum repo to get that fetched.

I tried specifying both `git` and `path` in my Cargo.toml and cargo complained, is this what you meant?

**Comment by tomusdrw** [comment]
@jedahan you only need `git`, like here: https://github.com/paritytech/sol-rs/blob/master/solaris/Cargo.toml#L8
It should work without issues.

**Comment by jedahan** [comment]
woah that is cool, thanks @tomusdrw

**Comment by 5chdn** [comment]
https://github.com/jedahan/eip712 is missing a license, please add GPLv3 @jedahan

**Comment by jedahan** [comment]
@5chdn is this good? https://github.com/jedahan/eip712/commit/a078af612421b291065cc4af64d6c436dc220af0

**Comment by tomusdrw** [comment]
CC @seunlanlege @dvdplm I think it's easy enough to do right away. If we don't plan to publish let's close it.

**Comment by ordian** [comment]
Looks like it was published already on Dec 21, 2018: https://crates.io/crates/eip-712

**Comment by tomusdrw** [comment]
So I believe this issue is done an can be closed now :)
