### ISSUE TITLE
 https://vanity-service.parity.io/ server down

### ISSUE THREAD

**Issue by franciscomemoli** [paritytech/parity-ethereum#10100]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.10
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no

Hello there are a problem on the server https://vanity-service.parity.io/ to get the builds for example: https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&os=linux&version=v2.1.10.
I think it is down because I get an 521 http error from cludflare.

**Comment by joshua-mir** [comment]
Seems resolved now, thanks for the report.
