### ISSUE TITLE
Please support limiting upload bandwidth!!!

### ISSUE THREAD

**Issue by naikmyeong** [paritytech/parity-ethereum#10115]
I am paying like 300$ extra fees per month just for upload traffic caused my parity node,

Is there any solution to limit these upload traffics? I just don't want to share my bandwidth for uploading heavy traffics

**Comment by roninkaizen** [comment]
the active limitation is best done 
with reducing the amount of peers,
done with --min-peers 3 --max-peers 10
with this reductions i managed questions like yours on several nodes, 
like am.z.n and g..gle-> once you are sync, the bandwith limitation takes full effekt-
as you also want to limit the snapshot-peers it is also possible
with --snapshot-peers 10
information based on https://wiki.parity.io/Configuring-Parity-Ethereum
and personal experience in various datacenter-conditions

**Comment by joshua-mir** [comment]
Those are reasonable recommendations above - we don't have bandwidth limitations, if your node doesn't respond to requests, your peers will simply drop you. While you can limit your peer count, that's at the cost of your node's reliability.
