### ISSUE TITLE
Error in Ethereum Classic difficulty calculation?

### ISSUE THREAD

**Issue by cseberino** [paritytech/parity-ethereum#10118]
Parity version: 1.11.8 installed from Linux Ubuntu 18.04 package
Linux Ubuntu 18.04.1
fully synchonized on Ethereum Classic network

Parity 1.11.8 gives a difficulty of 0x7048c3a85d98 for ETC block 7116609 
but I'm thinking if it should be 0x7048c3a85d95.

I've discussed with leader of ETCDEV and get the 0x7048c3a85d95 value in both Java and Python code.

Here is how we calculated 0x7048c3a85d95.....

*************************************************

import java.math.BigInteger;

public class Diff {

  public static BigInteger calc(BigInteger dp, long sec) {
        return dp
                .add(dp.multiply(BigInteger.valueOf(1 - sec / 10))
                .divide(BigInteger.valueOf(2048)));
  }

  public static final void main(String[] args) {
        System.out.println(calc(new BigInteger("709d39938c3e", 16), 72).toString(16));
        System.out.println(calc(new BigInteger("709d39938c3e", 16), 71).toString(16));
        System.out.println(calc(new BigInteger("709d39938c3e", 16), 73).toString(16));
  }

}

*****************************************************************************************************************

% javac Diff.java 
% java Diff 
7048c3a85d95
7048c3a85d95
7048c3a85d95

**Comment by joshua-mir** [comment]
Is this still an issue on a recent (supported) release of parity? This has very likely already been addressed since 1.11.8, which has been EOL for a long while now. I'd imagine #9328, has already addressed this.

Please reopen if this is still an issue with a recent version of parity.

**Comment by joshua-mir** [comment]
Likely duplicate https://github.com/paritytech/parity-ethereum/issues/8397#issuecomment-411688770

**Comment by 5chdn** [comment]
@cseberino please upgrade to 2.1.10 or 2.2.5!

**Comment by cseberino** [comment]
Afri

Thanks for the suggestion!   But should I wait until it is out of beta?

cs

**Comment by joshua-mir** [comment]
2.1.10 is stable @csrberino, you've already updated as per the other issue you made, dw
