### ISSUE TITLE
Still Ethereum Classic difficulty error even with ver2.1.10 stable!?

### ISSUE THREAD

**Issue by cseberino** [paritytech/parity-ethereum#10120]
(Sorry old issue was closed before I could respond. I verified it also is the
same problem on latest Parity 2.1.10 stable!)

Parity version: 2.1.10 installed from Linux binary (Verified sha256 hash on Parity page.)

Linux Ubuntu 18.04.1
fully synchonized on Ethereum Classic network

Parity 2.1.10 gives a difficulty of 0x7048c3a85d98 for ETC block 7116610
but I'm thinking if it should be 0x7048c3a85d95.

I've discussed with leader of ETCDEV and get the 0x7048c3a85d95 value in both Java and Python code.

Here is how we calculated 0x7048c3a85d95.....

import java.math.BigInteger;

public class Diff {

public static BigInteger calc(BigInteger dp, long sec) {
return dp
.add(dp.multiply(BigInteger.valueOf(1 - sec / 10))
.divide(BigInteger.valueOf(2048)));
}

public static final void main(String[] args) {
System.out.println(calc(new BigInteger("709d39938c3e", 16), 72).toString(16));
System.out.println(calc(new BigInteger("709d39938c3e", 16), 71).toString(16));
System.out.println(calc(new BigInteger("709d39938c3e", 16), 73).toString(16));
}

}

% javac Diff.java
% java Diff
7048c3a85d95
7048c3a85d95
7048c3a85d95

**Comment by joshua-mir** [comment]
(sorry, I was fairly sure you could comment on closed issues, but this is fine as well.)

Is this causing any crashes or consensus failures? Afaik I haven't heard of any issues syncing from scratch on the classic network, and if there was a discrepancy in the difficulty between clients, it would be pretty obvious as we wouldn't be able to sync past that block.

**Comment by cseberino** [comment]
It isn't causing any syncing issues.  Just trying to figure out why my Java
and Python code give different difficulty than Parity.
I'm not sure why isn't causing syncing errors and I cannot reproduce the
difficulty Parity gives with my
aforementioned Java code.

**Comment by cseberino** [comment]
Nevermind.  I found my error.  All is fine now.  Nothing to see here.
It is important to be very careful about doing truncating instead of
rounding
and truncating in the exact places it is needed.  No more no less.

**Comment by joshua-mir** [comment]
🎉
