### ISSUE TITLE
Optimize for making lots of JSON RPC calls

### ISSUE THREAD

**Issue by lampshade9909** [paritytech/parity-ethereum#10132]
- **Parity Ethereum version**: Parity-Ethereum/v2.1.10-stable-b47e064-20181213/x86_64-linux-gnu/rustc1.31.0
- **Operating system**: Ubuntu Server 18.04
- **Installation**: bash <(curl https://get.parity.io -L) -r stable
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I'm making a significant amount of calls per minute to my nodes.  Some calls still take a significant amount of time and some even timeout.  How can I optimize my parity node to handle a lot of calls via the JSON RPC?  I have two software applications that interact with the Ethereum blockchain via a couple of my parity nodes.  Their interaction involves making a LOT of calls via JSON RPC (eth_call, eth_getLogs, eth_getTransactionReceipt, etc).  

Is there a way I can configure this parity node to get maximum performance?  For the instance which my parity node runs on, I've whitelisted TCP calls on port 8545 to only my application's IP addresses.  I've allocated 200gb SSD, 4 cores of 3.1 GHz, and 8 GB of RAM.  Based on monitoring data, it seems like more than enough.  It's typical CPU usage maxes out around 45% when I'm hammering it.  I can run one complex eth_call and have it return wicked fast, but if I run a bunch of them back to back, occasionally 1 will take forever or time out.  

I've read here:  https://github.com/paritytech/parity-ethereum/issues/6575#issuecomment-336899769  from user tomusdrw

> You should get much better performance by re-using connections, I can easily do 20k req/s using rust-web3.

Might this apply to my situation?  I'm making my calls using python requests using requests.post with my eth_calls in the payload of the request.  This is certainly making a new request every single time.  

Here is my config:

`parity --warp --pruning=fast --no-serve-light --max-peers=250 --snapshot-peers=50 --min-peers=50 --mode=active --tracing=off --db-compaction=ssd --cache-size=7168 --rpccorsdomain=* --rpcaddr=0.0.0.0 --jsonrpc-hosts=all &`

**Comment by joshua-mir** [comment]
That might help, note we also support batching json requests (you should be able to send multiple requests in one requests.post), so you should consider trying that out for any requests that don't need the output of a previous request.

You might also want to tweak `--jsonrpc-server-threads` (threads that accept parallel incoming requests) and `--jsonrpc-threads` (threads that actually process the requests while they are connected)

I'd recommend server-threads to be set to the number of requests you expect to see come in in parallel, and processing threads to match your thread/core count (of course, if all of your threads are occupied processing, you might lose peers or fall out of sync,)

**Comment by lampshade9909** [comment]
Is there any sort of limit I should expect from --jsonrpc-server-threads?  What if I set it to 100?  So --jsonrpc-threads should be based on core count, but not --jsonrpc-server-threads?  

I definitely don't want to fall out of sync.  So does that mean I should set --jsonrpc-threads to zero?  Or set it to a non-zero but less than my total number of cores?  Or not set --jsonrpc-threads at all?

**Comment by joshua-mir** [comment]
Depends on your use-case, I wouldn't recommend setting processing_threads low, especially if you want to improve rpc performance.

The defaults should be good enough for most usage, but
> set it to a non-zero but less than my total number of cores

Is reasonable. 

Re- setting server threads to "100", after a certain point you will just stop seeing any benefit in performance, (when server-threads > processing-threads)

You'll get the most benefit from taking advantage of batching requests.

**Comment by lampshade9909** [comment]
Ok, so something like:
jsonrpc-server-threads should be less than or equal to jsonrpc-threads.  
And jsonrpc-threads should be less than numOfCores?  
Or should (jsonrpc-server-threads + jsonrpc-threads) be less than numOfCores?  

> You'll get the most benefit from taking advantage of batching requests.

Excellent.  Thanks!

**Comment by joshua-mir** [comment]
@lampshade9909 I've just been told that --json-threads is broken and doesn't currently do anything, so optimal would be to set server-threads to your core count and that's currently the optimal setting.

**Comment by joshua-mir** [comment]
Will close this for now, feel free to continue this conversation in this issue or on gitter or riot
