### ISSUE TITLE
actions vanished in traces generated by parity 2.2.5-beta compared to earlier versions

### ISSUE THREAD

**Issue by gsalzer** [paritytech/parity-ethereum#10146]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: parity 2.2.5-beta
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Actual behaviour**
When requesting traces via the RPC API (with `trace_block` or `trace_transaction`) from an archive node running parity 2.2.5-beta, certain actions in traces are missing compared to earlier versions of parity. Within the first 1000000 blocks, there are 272 instances of this phenomenon. Each time the missing action is a call to the builtin contract 0x04 that failed with out-of-gas. The first case seems to happen in transaction 0 of block 660372. The previous behavior can e.g. be viewed at
[ https://etherscan.io/vmtrace?txhash=0xc8dae3da21e5259dedec4d0d5b07c476e432b3aa005304d9a97c78db7541da6c&type=parity]( https://etherscan.io/vmtrace?txhash=0xc8dae3da21e5259dedec4d0d5b07c476e432b3aa005304d9a97c78db7541da6c&type=parity)
Action [2] is the one missing in the trace delivered by parity 2.2.5-beta.

**Expected behavior**
Consistency of traces between versions (except if the actions having disappeared were actually errors).

**Comment by joshua-mir** [comment]
Similar/related to #9629 maybe?

**Comment by gsalzer** [comment]
Doesn't seem so.

**Comment by joshua-mir** [comment]
You found this first, but #10156 has more detail. Let's continue the conversation there 😅
