### ISSUE TITLE
Different version 

### ISSUE THREAD

**Issue by sicute** [paritytech/parity-ethereum#10148]
Hi everyone , 
I try update parity from source , but was stranger  the version build from source was 2.30 the release was 2.2.5-beta .
Here data i can share 
--Version 
docker run -v /mnt/ethdata/:/mnt/ethdata --net=host parity-main:latest --version
Loading config file from /mnt/ethdata/conf/config.toml
Parity Ethereum
  version Parity-Ethereum/v2.3.0-nightly-696dc05-20190108/x86_64-linux-gnu/rustc1.31.1
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

- OS : Linux Ubuntu 16.04
- **Installation**:  built from source
- **Fully synchronized**:  on going 
- **Network**:  ropsten 
- **Restarted**: yes

I check in github release was 2.2.5-beta ( https://github.com/paritytech/parity-ethereum/releases ) but when i complie form source was 2.3.0
 here my Dockerfile 

`cat Dockerfile
FROM ubuntu:16.04
MAINTAINER Parity Technologies <devops@parity.io>
WORKDIR /build
#COPY conf /conf
COPY entrypoint /entrypoint.sh
RUN chmod +x /entrypoint.sh
#ENV for build TAG
ARG BUILD_TAG
ENV BUILD_TAG ${BUILD_TAG:-master}

RUN echo "Build tag:" $BUILD_TAG
# install tools and dependencies
RUN apt-get update && \
        apt-get install -y --force-yes --no-install-recommends \
        # make
        build-essential \
        # add-apt-repository
        software-properties-common \
        make \
        cmake \
        curl \
        bash \
        wget \
        git \
        g++ \
        gcc \
        libc6 \
        libc6-dev \
        binutils \
        file \
        libudev-dev \
        pkg-config \
        dpkg-dev &&\
# install rustup
 curl https://sh.rustup.rs -sSf | sh -s -- -y && \
# rustup directory
 PATH=/root/.cargo/bin:$PATH && \
# show backtraces
 RUST_BACKTRACE=1 && \
# build parity
cd /build&&git clone https://github.com/paritytech/parity-ethereum && \
        cd parity-ethereum&& \
    git pull&& \
    git checkout $BUILD_TAG && \
        cargo build --verbose --release --features final && \
        strip /build/parity-ethereum/target/release/parity && \
 file /build/parity-ethereum/target/release/parity&&mkdir -p /parity&& cp /build/parity-ethereum/target/release/parity /parity&&\
#cleanup Docker image
 rm -rf /root/.cargo&&rm -rf /root/.multirust&&rm -rf /root/.rustup&&rm -rf /build&&\
 apt-get purge -y  \
        # make
        build-essential \
        # add-apt-repository
        software-properties-common \
        make \
        cmake \
        curl \
        wget \
        git \
        g++ \
        gcc \
        binutils \
        file \
        pkg-config \
        dpkg-dev &&\
 rm -rf /var/lib/apt/lists/*
# setup ENTRYPOINT
EXPOSE 8080 8545 8546 30303 30301 8180
ENTRYPOINT ["/entrypoint.sh"]`

**Comment by joshua-mir** [comment]
@sicute the releases are on git branches on the repo, the master branch is in-development and represents the *next* beta release. If you want to install a specific release from source, you need to `git checkout` the version you want, and then build.
