### ISSUE TITLE
call contract method failed when use web3.js

### ISSUE THREAD

**Issue by shicongbuct** [paritytech/parity-ethereum#10149]
Parity Ethereum version: Parity-Ethereum/v2.3.0-unstable-c90e279-20181219/x86_64-linux-gnu/rustc1.31.0
  Operating system: linux
  Installation:  built from source
  Network: private poa

  I deploy two node in my server,  there are config files in my public repo: [https://github.com/shicongbuct/parity_deploy](https://github.com/shicongbuct/parity_deploy)

I also deploy a contract in the parity, contract address is 0x3b7ea2baf1840ad9cda874b783488ec22a27e95a

there is a function in the contract , like this:
`function setFile(string fileHash, uint fileSize) public payable returns (bool) {
	    require(msg.value > ((fileSize /1024) + 1) * 1 ether);
	    this.send(msg.value);
		File memory file = File(bytes(fileHash), fileSize);
		fileMapping[msg.sender].push(file);
		return true;
	}`

I use web3.js in my application to call this function.
like this:
`let setResult = await canContract.methods.setFile(fileHash, parseInt(fileSize / 1024)).send({from: publicKey, value: fileCost, gas:2000000});`

and it failed with this information:
`2019-01-08T05:32:24.752Z info: Uploading files
total size is: 3
upload file size: 0
fileSize is: 3
fileCost is: 2002929687500000000
fileHash is: QmZoveDWWVMmXKcpibq1XtJSm1ewETD5JBXCReiPCD3RK8
set file failed with error: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xfa942bddd0cf95bf4fa9cf1af617e8008e564ea51be38579cb1d89ad09b261dd",
  "blockNumber": 1291,
  "contractAddress": null,
  "cumulativeGasUsed": 104851,
  "from": "0x36857a41adc4b4568c7f9c4d1b56a77eabd82f67",
  "gasUsed": 104851,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "root": "0x0751bcb88009abea3d4bb5c2728bc5a68ee63916b33349744c523098b83b8d77",
  "status": false,
  "to": "0x3b7ea2baf1840ad9cda874b783488ec22a27e95a",
  "transactionHash": "0xa4ebd21342bbdc7fbff1aa3a6823af16f9313d3c05136b5e30157bc9174d0cc7",
  "transactionIndex": 0,
  "events": {}
}
2019-01-08T05:32:30.315Z error: false`

I make this useful in the geth node before.

and I am sure my web3.js can connect to parity node. My test script is useful.

test_file.js
`const Web3 = require('web3');
const util = require('util');

//var web3 = new Web3("ws://39.106.7.24:8181");

var web3 = new Web3(new Web3.providers.WebsocketProvider('ws://39.106.7.243:8180'));

console.log("Hello World");

!async function() {
    let accounts = await web3.eth.getAccounts();
    let blockNumber = await web3.eth.getBlockNumber();
    console.log(accounts);
    console.log(blockNumber);

}();`

Who has ever encountered this problem? thank you.

**Comment by joshua-mir** [comment]
According to the output you've provided `Error: Transaction has been reverted by the EVM` the transaction likely failed. I can see several possible causes of it, most having to do with how js handles numbers. I'd recommend using the bigint library for any values that would be passed to Ethereum.

**Comment by joshua-mir** [comment]
Has this exact transaction (same file) worked on your geth node?

**Comment by shicongbuct** [comment]
> Has this exact transaction (same file) worked on your geth node?

year, the same file worked well on geth node. I will try bigint library. thank you.
