### ISSUE TITLE
Parity 2.1.11-stable - Linux Checksum

### ISSUE THREAD

**Issue by grittibaenz** [paritytech/parity-ethereum#10158]
- **Parity Ethereum version**: 2.1.11-stable
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

**Description:**
When I calculate the SHA256 checksum for the [Linux binary](https://releases.parity.io/ethereum/v2.1.11/x86_64-unknown-linux-gnu/parity) (version 2.1.11-stable) I get another checksum than displayed on the release page:
`3f34bcacf2f58ef7258bdb33f94c2bd7737d05699622cf528b5804e1fa3f210d`

```
$ wget https://releases.parity.io/ethereum/v2.1.11/x86_64-unknown-linux-gnu/parity
$ sha256sum parity
f3255a22e561f708c139f406715409665eb2fa519ccaa56d270e543efbc975e7  parity
```
Maybe I am doing something wrong, but I would be thankful if you could quickly check that I am wrong. Thanks for taking care of this.

**Comment by tomusdrw** [comment]
```
$ curl https://releases.parity.io/ethereum/v2.1.11/x86_64-unknown-linux-gnu/parity | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.6M  100 41.6M    0     0  2772k      0  0:00:15  0:00:15 --:--:-- 3695k
f3255a22e561f708c139f406715409665eb2fa519ccaa56d270e543efbc975e7  -
```
Getting the same it matches the sha256 sum file on the server though:
```
$ curl https://releases.parity.io/ethereum/v2.1.11/x86_64-unknown-linux-gnu/parity.sha256
f3255a22e561f708c139f406715409665eb2fa519ccaa56d270e543efbc975e7  parity
```

**Comment by 5chdn** [comment]
Thanks. This was the correct checksum for the wrong binary ;-)

You can always double-check the checksums against our vanity service by the way:

https://vanity-service.parity.io/parity-binaries?format=markdown&version=v2.1.11
