### ISSUE TITLE
VM execution error. Bad instruction 3d

### ISSUE THREAD

**Issue by jratwood** [paritytech/parity-ethereum#10153]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v1.11.8
- **Operating system**: Ubuntu
- **Installation**: docker image 
- **Fully synchronized**: yes
- **Network**: private POA
- **Restarted**: yes

Deploying contract using truffle
The contract deploys and tests fine with Ganache
The contract deploys fine to parity
When calling a particular view that has an modifier on it

I see the following in the parity logs 
2019-01-08 19:20:28 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Bad instruction 3d"},"id":131}.

I can not find any existing issues that have this same code

**Comment by tomusdrw** [comment]
Your chain doesn't have Byzantium enabled, specifically `RETURNDATASIZE` instruction is not available. You need to update your spec file.

**Comment by joshua-mir** [comment]
(and, ideally, also your client, as 1.11.X has been EOL for a long while now)

**Comment by jratwood** [comment]
I used the hex value instead of decimal and it seems to work...
