### ISSUE TITLE
Crash on getBlockByNumber for certain blocks

### ISSUE THREAD

**Issue by nventuro** [paritytech/parity-ethereum#10171]
- **Parity Ethereum version**: 2.1.11
- **Operating system**: Linux
- **Installation**: binary from releases page
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I'm getting crashes whenever I call `eth_getBlockByNumber` with certain blocks, such as 423155 (which [has no transactions](https://etherscan.io/block/423155), but that may be a red herring).

I've both hit this by calling `eth.getBlock(423155)` from a geth console, and with a pure jsonrpc query:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1}' http://<HOST>:<PORT>
```

I get the following error report:

```
Jan 11 16:44:42 parity[28612]: Thread '<unnamed>' panicked at 'View rlp is trusted and should be valid. Constructed in ethcore/src/encoded.rs on line 202: RlpExpectedToBeData', ethcore/src/views/view_rlp.rs:56
Jan 11 16:44:42 parity[28612]: This is a bug. Please report it at:
Jan 11 16:44:42 parity[28612]:     https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by splix** [comment]
Can confirm same issue on `Parity-Ethereum/v2.2.9-stable-5d5b372-20190203/x86_64-linux-gnu/rustc1.31.1`

**Comment by splix** [comment]
Also confirming for `Parity-Ethereum/v2.2.10-stable-7b1d3e1-20190213/x86_64-linux-gnu/rustc1.32.0` (i.e. wasn't fixed by JSON-RPC vulnerability fix)

**Comment by frangio** [comment]
@joshua-mir @seunlanlege Any progress on this?

**Comment by seunlanlege** [comment]
your db is most likely corrupt, unable to replicate.

**Comment by frangio** [comment]
Thanks for the suggestion @seunlanlege. To be clear, is this corruption something that you've run into before?

**Comment by joshua-mir** [comment]
@frangio yes, especially with higher IO loads or HDDs, but it's also happens randomly.

**Comment by splix** [comment]
@joshua-mir @seunlanlege any suggested workaround? Any way to figure out which blocks are corrupted and resync starting from that block (i.e. if I have backups)?

Btw, it happens for blocks which were just synced. I.e to head blocks as well. So it seems that parity keeps corrupting db once it got one corrupted block.
