### ISSUE TITLE
whisper cli: support bootnodes and devp2p port

### ISSUE THREAD

**Issue by realcodywburns** [paritytech/parity-ethereum#10183]
- **Parity Ethereum version**: N/A
- **Operating system**: Linux
- **Installation**: built from source

- **Network**: whisper

need support for adding enode addresses to whisper-cli as well as setting a static devp2p port. These options do not appear to be supported currently.

**Comment by niklasad1** [comment]
Hi, there is pending PR (https://github.com/paritytech/parity-ethereum/pull/10057) that solves this issue but it has copyright issues so can't be merged yet

**Comment by realcodywburns** [comment]
cool, let me test with gballet branch and see if that solves my issues

**Comment by niklasad1** [comment]
Closed by #10057?!

Please re-open if don't agree
