### ISSUE TITLE
Docker image crashes with preset --config=dev 

### ISSUE THREAD

**Issue by dakingha69** [paritytech/parity-ethereum#10187]
- **Parity Ethereum version**: v2.1.11-stable-e9194b0
- **Operating system**: Linux
- **Installation**: Image from Docker Hub
- **Fully synchronized**: N/A
- **Network**: Private Development Chain
- **Restarted**: N/A

I am using the parity docker image in a docker-compose file for running tests against a private dev chain. The compose file for the parity service looks something like this:
```yaml
  # ...
  parity:
    image: parity/parity:stable
    command: --config=dev
    # ...
```
When I start the service with `docker-compose up parity` it crashes with the following error:
``` bash
parity          | Loading config file from dev
parity          | There was an error reading your config file at: dev
parity          | Is a directory (os error 21)
parity exited with code 2
```
It works if I use the preset `--config=dev-insecure` though.

**Comment by ddorgan** [comment]
Confirmed on Parity-Ethereum/v2.1.11-stable-e9194b0-20190107/x86_64-linux-gnu/rustc1.31.1.

**Comment by ddorgan** [comment]
Is there a reason you are using v2.1.11? If you download the latest parity/parity:stable it seems to work fine. Can you run ``` docker pull parity/parity:stable ``` and use this image please.

**Comment by dakingha69** [comment]
No, there is no particular reason for using v2.1.11. Latest stable version works, thanks!
