### ISSUE TITLE
Parity importing blocks slower than ever

### ISSUE THREAD

**Issue by uurcm16** [paritytech/parity-ethereum#10184]
- **Parity Ethereum version**: 2.2.5 beta
- **Operating system**: Windows 10,  64 GB RAM
- **Installation**: 
- **Fully synchronized**: yes
- **Network**: ethereum...
- **Restarted**: yes

I've started synchronizing ethereum chain yesterday.
It seems it took more than **10 seconds** to import blocks.

Does importing blocks (8-10KB) really took more than 10 seconds or is there anything that i miss?
I think it is not related with my internet speed because I've 1Gbps download and upload. 

Here is the parameters that I use.
`parity --chain mainnet --mode active --no-ipc --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --cache-size 8096 --ws-interface all --min-peers 50 --max-peers 100 --author Wallet`

**Screenshot->** http://prntscr.com/m7bux2

**Comment by joshua-mir** [comment]
This actually looks like you're already in sync and the import time shown includes the time to see the block on the network and get it from a peer.

**Comment by uurcm16** [comment]
> This actually looks like you're already in sync and the import time shown includes the time to see the block on the network and get it from a peer.
> 
> I'd watch for a little longer and let us know if the "long import times" make you fall further from the chain head. Also : what kind of storage does this node use?

The blockchain files are stored in a normal disk. (7200rpm regular disk). I'll move the files to SSD but at first I just wanted to see how much storage that I need.

Sometimes, parity falls **back** from current chain. **Screenshot 1 ->** http://prntscr.com/m7en4w  **Screenshot 2 ->** http://prntscr.com/m7eor7

Parity is currently using 100% of the HDD. **Screenshot ->** http://prntscr.com/m7em3w

What I understand is, parity is fetching / importing block from peers in 10+ seconds because of high disk usage. Can it be true?

**Comment by joshua-mir** [comment]
Yes, that is your problem for sure, you can't sync mainnet with an HDD, you simply won't have enough iops.

**Comment by uurcm16** [comment]
@joshua-mir Ok, thank you! Is there a way to move theese files to SSD using Parity or should I just move files and start parity with --base-dir option?

**Comment by joshua-mir** [comment]
Just move files and start with --base-dir, if you want, you can just move chaindata and use --db-path instead.

**Comment by uurcm16** [comment]
@joshua-mir Thank you so much. Closing the issue. Sorry for the trouble :)
