### ISSUE TITLE
Compiling Parity - error: Edition 2018 is unstable and only available for nightly builds of rustc.

### ISSUE THREAD

**Issue by phaelon74** [paritytech/parity-ethereum#10193]
- **Parity Ethereum version**: v2.1.10-stable
-**Rust Version**: rustc 1.31.1c
- **Operating system**: Ubuntu 16.04
- **Installation**: Attempting to build from source
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: no

I saw the update about Ethereum Constantinople being postponed.  I'm trying to update my Parity client to 2.2.7.  Because I am running a parity executable that was built from source, there is no good way to upgrade outside of building it again in a different location and then moving the parity executable to the other location and launching it.

When I attempt to compile the source for Parity I get the following:
   Compiling ethcore-db v0.1.0 (/home/userdude/parity-ethereum/ethcore/db)
error: Edition 2018 is unstable and only available for nightly builds of rustc.

error: Could not compile `ethcore-db`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Any ideas why it's failing?

**Comment by 5chdn** [comment]
Weird. What's the exact output of `rustc --version`?

**Comment by ordian** [comment]
@phaelon74 you need to update rustup:
```bash
rustup self update
```

**Comment by phaelon74** [comment]
@5chdn I put it in my first post but here it is again:
somedude@us-central:~/parity-ethereum$ rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)

@ordian I did that as well, as per my searching that's where other people saw this issue, but it didn't help :(
somedude@us-central:~/parity-ethereum$ rustup self update
info: checking for self-updates
somedude@us-central:~/parity-ethereum$

So if there is an update, my system is not grabbing it.

**Comment by ordian** [comment]
@phaelon74 I've faced the same, but I'm not sure how it was resolved (maybe reinstalling the toolchain). 
In the meantime, you could try use beta or nightly toolchain to build parity-ethereum (e.g. with beta):
```bash
rustup toolchain add beta
cargo +beta build --release
```
I'm going to close the issue, since it's unrelated to parity-ethereum.

**Comment by phaelon74** [comment]
1. sudo apt remove rustc
2. curl https://sh.rustup.rs/ -sSf | sh

Than attempted compile of Parity and it was happy as a clam.  HOw bizarre.

**Comment by joshua-mir** [comment]
Perhaps there was a conflicting binary from the repos 🤷‍♂️

**Comment by phaelon74** [comment]
@joshua-mir perhaps.  it also doesn't help when it's 1am and you're like oohhh crapo, Constantinople is not happening.  need to update parity on the pool so it doesn't blow up!  lol  Fresh morning eyes always help.
