### ISSUE TITLE
2.2.7-stable New Error: Spec json is invalid: unknown field `eip150Transition`,

### ISSUE THREAD

**Issue by stone212** [paritytech/parity-ethereum#10203]
- **Parity Ethereum version**: 2.2.7-stable
- **Operating system**: Ubuntu 16.04
- **Installation**: binary
- **Fully synchronized**: yes
- **Network**: private blockchain
- **Restarted**: yes

Months ago I added `"eip150Transition": 0,` to the `params` section of a private chain specification.  The chain ran well until today when I upgraded to 2.2.7-stable.  Now I re-start Parity and I get this error:

```
$ ./parity 
Loading config file from /home/parity/.local/share/io.parity.ethereum/config.toml
Spec json is invalid: unknown field `eip150Transition`, expected one of `minimumDifficulty`, `difficultyBoundDivisor`, `difficultyIncrementDivisor`, `metropolisDifficultyIncrementDivisor`, `durationLimit`, `homesteadTransition`, `blockReward`, `blockRewardContractTransition`, `blockRewardContractAddress`, `blockRewardContractCode`, `daoHardforkTransition`, `daoHardforkBeneficiary`, `daoHardforkAccounts`, `difficultyHardforkTransition`, `difficultyHardforkBoundDivisor`, `bombDefuseTransition`, `eip100bTransition`, `ecip1010PauseTransition`, `ecip1010ContinueTransition`, `ecip1017EraRounds`, `difficultyBombDelays`, `expip2Transition`, `expip2DurationLimit` at line 15 column 35
```

**Comment by joshua-mir** [comment]
Which version are you upgrading from? If your `"eip150Transition": 0,` is in `ethash: { params: {...}} `,  you need to move it out to the `params: {...} ` section outside of `ethhash: {...} `.

This change was made in 2.0.0 and is in the [changelog](https://github.com/paritytech/parity-ethereum/blob/master/docs/CHANGELOG-2.0.md#parity-ethereum-v200-ethereum-2018-07-18) for that version. https://github.com/paritytech/parity-ethereum/pull/8614

**Comment by stone212** [comment]
@joshua-mir 

> Which version are you upgrading from?

2.1

> This change was made in 2.0.0 and is in the changelog for that version.

Why has it worked since then?  I looked at the changelog for 2.2.7 because that was the first where I got the error.

Okay I made the change.  It worked.  Question: what is the technical difference between these two sections?  Is it the difference between a change specific to ethash and change specific to the chain spec?

**Comment by joshua-mir** [comment]
Exactly: one is for params specifically for ethash, and the other is for things that are independent of the consensus engine you are using

**Comment by stone212** [comment]
@joshua-mir Why do you think it was working in 2.1?

**Comment by 5chdn** [comment]
@stone212 #9972

**Comment by stone212** [comment]
@joshua-mir I upgraded to v2.2.11-stable today and now I have the same problem with eipTransition170.  But I get it if I put it in the ethash or the params section.  The errors are slightly different and I thought I should post here before I start a new similar Issue ticket.

When it is in the Ethash params section this is the error:

```
Spec json is invalid: unknown field `eip170Transition`, expected one of `minimumDifficulty`, `difficultyBoundDivisor`, `difficultyIncrementDivisor`, `metropolisDifficultyIncrementDivisor`, `durationLimit`, `homesteadTransition`, `blockReward`, `blockRewardContractTransition`, `blockRewardContractAddress`, `blockRewardContractCode`, `daoHardforkTransition`, `daoHardforkBeneficiary`, `daoHardforkAccounts`, `difficultyHardforkTransition`, `difficultyHardforkBoundDivisor`, `bombDefuseTransition`, `eip100bTransition`, `ecip1010PauseTransition`, `ecip1010ContinueTransition`, `ecip1017EraRounds`, `difficultyBombDelays`, `expip2Transition`, `expip2DurationLimit` at line 15 column 25
```

When it is in the params section:

```
Spec json is invalid: unknown field `eip170Transition`, expected one of `accountStartNonce`, `maximumExtraDataSize`, `minGasLimit`, `networkID`, `chainID`, `subprotocolName`, `forkBlock`, `forkCanonHash`, `eip150Transition`, `eip160Transition`, `eip161abcTransition`, `eip161dTransition`, `eip98Transition`, `eip155Transition`, `validateChainIdTransition`, `validateReceiptsTransition`, `eip140Transition`, `eip210Transition`, `eip210ContractAddress`, `eip210ContractCode`, `eip210ContractGas`, `eip211Transition`, `eip145Transition`, `eip214Transition`, `eip658Transition`, `eip1052Transition`, `eip1283Transition`, `eip1283DisableTransition`, `eip1014Transition`, `dustProtectionTransition`, `nonceCapIncrement`, `remove_dust_contracts`, `gasLimitBoundDivisor`, `registrar`, `applyReward`, `nodePermissionContract`, `maxCodeSize`, `maxTransactionSize`, `maxCodeSizeTransition`, `transactionPermissionContract`, `transactionPermissionContractTransition`, `wasmActivationTransition`, `kip4Transition`, `kip6Transition` at line 33 column 21
```

Should I post a new issue or is this related?  I looked through stable versions changelogs.
