### ISSUE TITLE
why the double // in web3.version.node ?

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-ethereum#10215]
The instance string is 

    Parity-Ethereum//v2.2.3-beta-6b0a280-20181130/x86_64-linux-gnu/rustc1.30.1

instead of 

    Parity-Ethereum/v2.2.3-beta-6b0a280-20181130/x86_64-linux-gnu/rustc1.30.1

like in 

    Geth/v1.8.14-stable-316fc7ec/linux-amd64/go1.10.3

curious: why the double // ?

**Comment by joshua-mir** [comment]
The node in question here might have the `Identity` flag set to an empty string, or something along those lines.

**Comment by shazow** [comment]
Even setting `--identity`, the version string does not include the identity. Is this by design? Feels like a bug.

## Parity

```
$ parity --identity=foo
...
```

```
> web3.version.node
"Parity-Ethereum//v2.4.5-unstable/x86_64-linux-gnu/rustc1.34.0"
```

## Geth

```
$ geth --identity=foo
```

```
> web3.version.node
"Geth/foo/v1.9.0-unstable/linux-amd64/go1.12.1"
```
