### ISSUE TITLE
Parity tracing nodes failing in mysterious ways in the small hours of the morning. 

### ISSUE THREAD

**Issue by seanturner83** [paritytech/parity-ethereum#10235]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.7 / 2.3.0
- **Operating system**: Linux (Debian in Docker on CentOS 7)
- **Installation**: downloaded from releases, built into container (debian)
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Parity tracing nodes failing in mysterious ways in the small hours of the morning (GMT).

Six full tracing nodes running on 4TB SSD volumes on m5.xlarge EC2 instances. Nodes fall behind the blockchain (all at least ten blocks behind) but then catch up again. After they have caught up, tracing fails until the instances are terminated. Load average remains OK at around 3-4. Disk read activity drops massively but AWS say there isn't an issue (and e.g. latency is fine at single digit milliseconds). Didn't happen frequently on 2.1 releases. Started happening really often after cancelled fork / update to 2.2.7. Tried 2.3.0 but no different.

Troubleshooting tips / ways to reproduce outside of our application welcomed.

**Comment by joshua-mir** [comment]
Do you have a log file that you can share? It's extremely noisy and can add up to a significant size, but it might be helpful to add `"sync=debug"` to your log settings to get more information.

**Comment by seanturner83** [comment]
I've turned this on for one node - it is quite chatty yeah

**Comment by joshua-mir** [comment]
Ping @seanturner83 are you still seeing any of these issues, and have you tried the most recent releases?

**Comment by joshua-mir** [comment]
Will close as stale, lmk if you want to reopen this
