### ISSUE TITLE
DB corruption - No bad blocks

### ISSUE THREAD

**Issue by wschwab** [paritytech/parity-ethereum#10239]
- **Parity Ethereum version**: 2.3.0 (beta)
- **Operating system**: Linux (Fedora 29)
- **Installation**: I don't recall, but I think one-line installer (otherwise I built from source)
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

This is the second time I've started syncing a Prity node (no warp, warp was giving me problems before), only to have corruption issues. I've run `badblocks` on the relevant hard drive (SSD, if relevant), and have no bad sectors.

The error message is rather large, so I'm going to have to guess what to paste here - let me know if there's something relevant that I'm missing.

Here's part of the error messages from the crash (from the restart follow afterwards):
```
DB corrupted: Corruption: block checksum mismatch: expected 142563414, got 101266247  in /run/media/[redacted]/[redacted]/parity/ethereum/db/906a34e69aec8c0d/overlayrecent/db/105804.sst offset 28408718 size 13489. Repair will be triggered on next restart


====================

stack backtrace:
   0:     0x55b11415bbbd - <no info>
   1:     0x55b11415add2 - <no info>
   2:     0x55b11415ae49 - <no info>
   3:     0x55b114159f86 - <no info>
   4:     0x55b1129102a8 - <no info>
   5:     0x55b1141d1d46 - <no info>
   6:     0x55b1141d1891 - <no info>
   7:     0x55b1141d1775 - <no info>
   8:     0x55b11421b30c - <no info>
   9:     0x55b1130a5ac0 - <no info>
  10:     0x55b112e413b0 - <no info>
  11:     0x55b112e3f5b5 - <no info>
  12:     0x55b112e23c11 - <no info>
  13:     0x55b112d19356 - <no info>
  14:     0x55b1129e3dd2 - <no info>
  15:     0x55b1129e64c1 - <no info>
  16:     0x55b1128dd4d2 - <no info>
  17:     0x55b1141d1712 - <no info>
  18:     0x55b1141e3f29 - <no info>
  19:     0x55b1141b241a - <no info>
  20:     0x55b1129e6e24 - <no info>
  21:     0x7f7df6ddf412 - <no info>
  22:     0x55b112779038 - <no info>
  23:                0x0 - <no info>

Thread 'main' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:1009
```
And here's from the restart:
```
DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col5, col2, col4, col3, col1, col6, col0, attempting repair
Failed to open database Custom { kind: Other, error: StringError("Received null column family handle from DB.") }
```

Thanks!

**Comment by joshua-mir** [comment]
I've been seeing this kind of issue alot more than usual recently - just to double check could you please run a memtest to check your ram as well?

Warp should be pretty reliable at the moment, if you properly configure a `--warp-barrier` to skip old snapshots, if you want to resync again I'd consider trying it again to save time.

**Comment by wschwab** [comment]
Okay. it took me a while to get around to memtest. I've had memtest running for 13 hours, and still no errors. (Assuming I'm running it correctly - this is my first time working with it.)

Something else that might be of interest is that further experimentation after I opened the issue would seem to indicate that this is not an issue specific to Parity. Any attempt at syncing Geth, or even Bitcoin Core, also seem doomed to fail after repeated attempts at both. I certainly lack the expertise to draw conclusions from this, but I'm wondering if there are certain general pitfalls in chain syncing that may not be documented well. 

The only thing I can think of in my case is that I have reformatted the SSD drive I'm using in the past. It started off NTFS, and I made it two partitions, then made the whole thing FAT32, if my memory serves me right.

In any event, this doesn't seem to be a Parity-specific issue, so I recommend closing it. Still, I would like to be running a node, so if anyone has any words of wisdom, I'm all ears.

**Comment by wschwab** [comment]
Come to think of it, there is another perhaps relevant detail - the SSD drive is external. I've never seen this mentioned as a problem anywhere, so I always assumed that internal/external didn't make a difference, but I'm wondering if maybe the USB connection is causing some sort of issue.

**Comment by joshua-mir** [comment]
The reason you need an SSD is because of the additional thoroughput it gives you... Which is entirely moot if you are connected to it via a USB cable.

I'm also entirely certain your issue is with connectivity issues over your cable.

**Comment by wschwab** [comment]
Well, I guess that settles that, then. I guess I learn something new every day.

Thanks for the help, I'm closing the issue.
