### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'cannot recursively call into `Core'

### ISSUE THREAD

**Issue by jmrocco** [paritytech/parity-ethereum#10237]
Parity Ethereum version: 2.3.0 stable 
Operating system: Windows 
Installation: From release page 
Fully synchronized: gonna say no
Network: ethereum
Restarted: not sure 

I'm new to Parity, Ethereum and Blockchain In general. I'm trying to learn Parity. Anyway, I got the following error message:

PS C:\Users\jrocc\Downloads\kauri> .\parity
2019-01-23 12:12:20  Starting Parity-Ethereum/v2.3.0-beta-10657d96c-20190115/x86_64-windows-msvc/rustc1.31.1
2019-01-23 12:12:20  Keys path C:\Users\jrocc\AppData\Roaming\Parity\Ethereum\keys\ethereum
2019-01-23 12:12:20  DB path C:\Users\jrocc\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2019-01-23 12:12:20  State DB configuration: fast
2019-01-23 12:12:20  Operating mode: active
2019-01-23 12:12:21  Configured for Ethereum using Ethash engine
2019-01-23 12:12:21  Updated conversion rate to Ξ1 = US$118.13 (40310710 wei/gas)
2019-01-23 12:12:22  Multi-threaded server is not available on Windows. Falling back to single thread.

====================

stack backtrace:
   0:     0x7ff6368af3c7 - hid_error
   1:     0x7ff6368aef7e - hid_error
   2:     0x7ff6368aeffd - hid_error
   3:     0x7ff6368ae383 - hid_error
   4:     0x7ff635055e83 - <no info>
   5:     0x7ff636906c42 - hid_error
   6:     0x7ff636906744 - hid_error
   7:     0x7ff636906629 - hid_error
   8:     0x7ff636921fdc - hid_error
   9:     0x7ff636922052 - hid_error
  10:     0x7ff635c8b3ea - <no info>
  11:     0x7ff635c32da9 - <no info>
  12:     0x7ff635c1a72e - <no info>
  13:     0x7ff635c403b3 - <no info>
  14:     0x7ff635c2cd49 - <no info>
  15:     0x7ff635c327a3 - <no info>
  16:     0x7ff635c454fb - <no info>
  17:     0x7ff635bfdf5a - <no info>
  18:     0x7ff635c32036 - <no info>
  19:     0x7ff635bfdc9b - <no info>
  20:     0x7ff635bfd489 - <no info>
  21:     0x7ff635bfe34a - <no info>
  22:     0x7ff635bfd91b - <no info>
  23:     0x7ff635c27ebb - <no info>
  24:     0x7ff635c5fe19 - <no info>
  25:     0x7ff635c2e8e3 - <no info>
  26:     0x7ff635c2434a - <no info>
  27:     0x7ff63691e532 - hid_error
  28:     0x7ff635c2795d - <no info>
  29:     0x7ff636911342 - hid_error
  30:     0x7ff63690e0a9 - hid_error
  31:     0x7ffafb1b7e94 - BaseThreadInitThunk

Thread 'IO Worker #2' panicked at 'cannot recursively call into `Core`', libcore\option.rs:1008

If you need more information, I will try my best but I don't know where to begin with much of this. Help and guidance would be greatly appreciated.

**Comment by joshua-mir** [comment]
Hey, this issue is known and a release (2.3.1) containing the fix (https://github.com/paritytech/parity-ethereum/pull/10195) should be out pretty soon.

This issue isn't present in the stable release (2.2.7) if you want to try that instead.
