### ISSUE TITLE
Performance degression on Kovan

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-ethereum#10230]
- **Parity Ethereum version**: 2.3.0
- **Operating system**: Linux
- **Installation**: auto-updater
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

```
 > tac parity-error-1.log | grep Starting
2019-01-16 01:08 +00:00: 2019-01-16 01:08:51 UTC Starting Parity-Ethereum/v2.3.0-beta-10657d9-20190115/x86_64-linux-gnu/rustc1.31.1
2018-12-25 19:11 +00:00: 2018-12-25 19:11:07 UTC Starting Parity-Ethereum/v2.2.5-beta-7fbcdfe-20181213/x86_64-linux-gnu/rustc1.31.0
```

After upgrading from 2.2.5 to 2.3.0 on Kovan, the following happened:

![screenshot from 2019-01-22 13-55-51](https://user-images.githubusercontent.com/15729797/51537626-4f1c1180-1e4f-11e9-9949-b84fdca07daa.png)

**Comment by ddorgan** [comment]
There's also a large increase in bandwidth usage, Terabytes of traffic...:

![image](https://user-images.githubusercontent.com/11941563/51540553-a2419480-1e4e-11e9-9f76-5bc8c3a3560d.png)

**Comment by ddorgan** [comment]
@5chdn did you not see this on your QA systems?

**Comment by 5chdn** [comment]
I was fairly busy this week. Good thing @fevo1971 spotted this

**Comment by TriplEight** [comment]
that would be unbelievable if the discovery system is the cause.

**Comment by ddorgan** [comment]
It's pretty strange because the main net bootnodes don't seem to have the same issue....

**Comment by teodor-pripoae** [comment]
Hi, I'm having the same issue on kovan network. I've upgraded on 17 January from `v2.1.6` to `v2.2.7`. Traffic increased to terrabytes, it costs hundreds of dollars in the cloud.

On mainnet running the same version it uses max 500kb/s.

On kovan:

<img width="1439" alt="screenshot 2019-02-04 14 55 57" src="https://user-images.githubusercontent.com/393437/52210281-41bf4800-288f-11e9-9938-4ecf423a7c26.png">
<img width="1436" alt="screenshot 2019-02-04 15 08 02" src="https://user-images.githubusercontent.com/393437/52210287-4552cf00-288f-11e9-8f39-02e80cf82e70.png">

On mainnet:

<img width="1157" alt="screenshot 2019-02-04 15 11 31" src="https://user-images.githubusercontent.com/393437/52210294-4a178300-288f-11e9-9649-8bd08f986ea6.png">
<img width="1440" alt="screenshot 2019-02-04 15 14 11" src="https://user-images.githubusercontent.com/393437/52210342-74694080-288f-11e9-8304-ae37bd704d79.png">

**Comment by teodor-pripoae** [comment]
Downgrading to 2.2.6 solved the problem so I think the regression was introduced in 2.2.7.

<img width="1440" alt="screenshot 2019-02-04 15 40 45" src="https://user-images.githubusercontent.com/393437/52211680-33732b00-2893-11e9-8c55-dc471fb4f7e4.png">

**Comment by petehall73** [comment]
Hi @5chdn, I see you removed the P2 tag on this bug.  I'm not sure that's correct.  I understand that this is as a result of the security patch but the massive increase in traffic is a huge problem for anyone hosting a node in the cloud and is billed for outbound network traffic.  I'm managing the situation by restricting peers and pending peers but that's merely a workaround.  I'd like to see this given a higher priority as it would force me to seek alternatives.

**Comment by ddorgan** [comment]
@petehall73 somebody is working on fix on this, an update will be posted here once it's ready and tested.
