### ISSUE TITLE
Archive node often resync when restarting on docker

### ISSUE THREAD

**Issue by yxliang01** [paritytech/parity-ethereum#10248]
- **Parity Ethereum version**: 2.2.7-stable-b00a21f-20190115
- **Operating system**: Linux
- **Installation**: docker official image
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

This happens on two separated nodes with the same setup. The nodes are archive node, tracing on, on HDD, fat-db one on one off. Currently one at around 5000000 block one at around 2700000.

actual behavior
---

After shutdown the node whether gracefully or not, starting the node will often start syncing from 0. However, since at times it can sync from the highest head, the db doesn't seem corrupted.

expected behavior
---

Every time, after a restart, the node should sync from the highest block it has synced so far.

Thanks

**Comment by yxliang01** [comment]
@grittibaenz Do you mean that your problem happens only when you try to upgrade the Parity version?

**Comment by grittibaenz** [comment]
@yxliang01: That is indeed a good question. I am currently resyncing the blockchain and will do a snapshot once done. After that I will do some further testing and report back. It might take another 1-2 days.

**Comment by yxliang01** [comment]
@grittibaenz Hmm Okay :)

**Comment by nostdm** [comment]
I have the same problem with the latest 2.2.8 version:

I had deployed and fully synced a Parity Ropsten node version 2.1.10 with the --pruning=archive option.

It finished syncing a few days ago and is currently at the latest Ropsten block - the same block that ropsten.etherscan.io shows (currently 4936368).

When I upgrade the node to version 2.2.8, it starts syncing from the genesis block instead of reusing the existing state.

In the past when I upgraded the Parity version it would reuse the old state and keep syncing - in the worst case it would re-org the bad blocks, but with the latest version it seems to create a new state trie and starts syncing from the beginning.

**Comment by yxliang01** [comment]
@nostdm @joshua-mir Actually no, this is not a duplicate of https://github.com/paritytech/parity-ethereum/issues/10275 I think. The problem that I had is on a node that was synced from the very beginning using 2.2.7 . While https://github.com/paritytech/parity-ethereum/issues/10275 is trying to describe a similar outcome but then it happened right after upgrading from older version. The main difference is that **for my case, the originally synced head come back after some number of restarts, and reset to genesis again after some number of restarts**.

@nostdm @grittibaenz Would you like to try restarting your node multiple times to see whether the synced head can come back? If yes, then it's a duplicate. If not, this is no a duplicate.

**Comment by joshua-mir** [comment]
Thanks for figuring this out, we can definitely reopen #10275 if it's as you are describing. However I do suspect this is a problem with sync logic in general with 2.2.7 (freshly updated or not) so it might be valuable for @nostdm to try your workaround as well.

**Comment by nostdm** [comment]
Someone on Gitter suggested to rename the `keys` and `chains` directories from `test` to `ropsten` and it solved the issue.

**Comment by yxliang01** [comment]
@nostdm solved the issue as in, after renaming, you can continue syncing where you were at?

**Comment by joshua-mir** [comment]
(issue #10160 for reference, it might be what @grittibaenz is experiencing, but not what you are @yxliang01)

**Comment by yxliang01** [comment]
@joshua-mir I think you wrongly mentioned @grittibaenz (should be @nostdm I guess)

**Comment by joshua-mir** [comment]
Both actually.

**Comment by yxliang01** [comment]
@joshua-mir Hmm just wondering, is this issue being investigated? Or, is this backlogged?

**Comment by joshua-mir** [comment]
I don't believe there is anyone actively working on this issue at the moment, I haven't been able to reproduce this locally, are you still seeing this often?

**Comment by yxliang01** [comment]
@joshua-mir Yes. This is still reproducible. Are you using Parity in docker container? I believe this is a bug because this happens on two different and independent nodes with the same version.

**Comment by joshua-mir** [comment]
Whoops. Haven't tried in docker yet actually, let me try that now 🙏 are you mounting any volumes?

**Comment by yxliang01** [comment]
I am mounting the /home/parity/.local/share/io.parity.ethereum read-write.

**Comment by grittibaenz** [comment]
Sorry for never getting back to you. I had busy week(s) and reporting + testing issues with almost every Geth, Parity and IOTA IRI release is tedious.

As I didn't update our ETH Ropsten nodes because of this bug, we obviously ran into the wrong direction of the fork. This means I am currently again resyncing the full Ropsten blockchain with one node. The second node has now a garbage-chain, but I can do some testing with it:
```
2534877 <-2.2.9 (full node - resyncing)
4978107 <-2.2.9 (light node - up-to-date)
4975236 <-2.1.10 (full node - garbage-chain)
```

When updating from `2.1.10` to version `2.2.9` (after the fork, sadly), it again starts resyncing the full blockchain (as it did with `2.2.7`:

```
Loading config file from /app/parity/conf/config.toml

2019-02-07 16:34:59 UTC Starting Parity-Ethereum/v2.2.9-stable-5d5b372-20190203/x86_64-linux-gnu/rustc1.31.1

2019-02-07 16:34:59 UTC Keys path /data/parity/base/keys/ropsten

2019-02-07 16:34:59 UTC DB path /data/parity/db/ropsten/db/ae90623718e47d66

2019-02-07 16:34:59 UTC State DB configuration: archive +Trace

2019-02-07 16:34:59 UTC Operating mode: active

2019-02-07 16:34:59 UTC Configured for Ropsten Testnet using Ethash engine

2019-02-07 16:35:04 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    2/25 peers      8 KiB chain  0 bytes db  0 bytes queue   38 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:04 UTC Public node URL: enode://9c9574b070696ef6ce546c9826830703cfaecdac2645317bf5fbfcc1a486db40db37571bf3e54e423239d79b0bae0f494cb73942480598b009f62fa3a6b27c88@172.17.0.2:30303

2019-02-07 16:35:09 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    2/25 peers      8 KiB chain  0 bytes db  0 bytes queue   39 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:14 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    2/25 peers      8 KiB chain  0 bytes db  0 bytes queue   39 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:19 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    2/25 peers      8 KiB chain  0 bytes db  0 bytes queue   39 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:24 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    2/25 peers      8 KiB chain  0 bytes db  0 bytes queue   39 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:29 UTC Syncing       #0 0x4194…4a2d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed        #0    3/25 peers      8 KiB chain  0 bytes db  0 bytes queue   39 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

2019-02-07 16:35:34 UTC Syncing    #1808 0xb8c3…d98b   361.60 blk/s    4.4 tx/s    0.3 Mgas/s     76+   10 Qed     #1905    2/25 peers    642 KiB chain   14 KiB db  128 KiB queue  683 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
```

Please let me know what I can test for you. This problem **is**(!) reproducible.

**Comment by yxliang01** [comment]
@grittibaenz Thanks for your update. However, from what you said, looks like this problem occurs right after an upgrade. Would you like to try **restarting the upgraded node** to see whether a resync is performed? Since my problem occurs every time I restart it without any upgrading.

**Comment by brandoncurtis** [comment]
I just upgraded Parity from v2.3.0 to v2.3.2.

Upon restart, it began resyncing the Ropsten chain from genesis.

I took a look, and this is occurring because you changed the Ropsten directory name:

- old `~/.local/share/io.parity.ethereum/chains/test`
- new: `~/.local/share/io.parity.ethereum/chains/ropsten`

By renaming `test` to `ropsten`, it will continue syncing from where it left off before the upgrade.

**Comment by yxliang01** [comment]
@brandoncurtis The change of directory name, is it happening upon exiting Parity or upon starting Parity? Also, if you restarting for multiple times, does it recover automatically?

**Comment by brandoncurtis** [comment]
Upon restarting parity, it creates the new directory `chains/ropsten` and begins syncing from genesis there.

To fix the problem, I deleted this new directory and renamed the existing `chains/test`, which contains my fully-synced Ropsten node.  Upon restarting Parity, it continues to sync from where I left off before the upgrade.

**Comment by joshua-mir** [comment]
We're getting alot of reports that should be in #10160 on this issue, sorry @yxliang01

**Comment by yxliang01** [comment]
@joshua-mir Yeah. Confirm that there is no `chains/ropsten` and `chains/test` for my case (I know they shouldn't exist in my case anyways). By the way, are you now able to reproduce in `docker` environment?

**Comment by joshua-mir** [comment]
Haven't been able to. I suspect it's something to do with the blocks nearer to the chain head, so I'll try again with a node I'll keep running for longer.

**Comment by yxliang01** [comment]
@joshua-mir hmm as stated in the first thread, it happened ever since at 2700000. So, maybe you want to try to reach that height.

**Comment by sammisetty** [comment]
Is there any latest update on this? We had a fully synced archive node on 2.0.7. We upgraded it to 2.2.7 and had the same issue of node syncing from genesis block, we left for two weeks and the sync was very slow about 40K blocks for day. We again  updated the node from 2.2.7 to 2.2.11 and the sync started from genesis block again, the sync as fast till 2.6 Million blocks and after than it became very slow 11 Thousand blocks per day. Any help is much appreciated!!

**Comment by yxliang01** [comment]
@sammisetty I think slow down after 2.6 million blocks is related to the DOS on Ethereum (FYI, https://www.reddit.com/r/ethereum/comments/5es5g4/a_state_clearing_faq/ ). (well, my node is also syncing very slowly both around 2.6 million blocks and 4 million blocks and now stuck.) As far as I know, there's no progress on this issue since they can't reproduce. As this is not major to me at this moment, I am working on something having higher priority now and try not to shut it down... If you have time, maybe you can start your node with `-l trace` then post your log here?

**Comment by sammisetty** [comment]
@yxliang01 I will start the node with -l trace and post the log soon. 

I also have another question, db/chains/ethereum/db/uniqueId/snapshot folder has two sub-folders
1. Current with size 8GB and
2. In_Progress with size 1.4 GB

Is there any reason that you know for two folders?

**Comment by yxliang01** [comment]
Hmm I no longer encounter this problem recently and this issue is stale (no other new people reported encountering same issue recently). I suggest closing this issue. If anyone or me counter this again, we can reopen or create a new issue :) . @joshua-mir Sounds good?
