### ISSUE TITLE
Wrong hexnumber format in JSON rpc

### ISSUE THREAD

**Issue by mssalnikov** [paritytech/parity-ethereum#10244]
- **Parity Ethereum version**: branch stable
- **Operating system**: Ubuntu
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: testrpc
- **Restarted**: yes

I'm trying to connect to parity from golang, using go-ethereum source. When I call PendingNonceAt, the code crashes, because as per [spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) hex numbers should not have leading zeros, yet parity pads them with zeroes to even length:

```
$: curl -X POST http://localhost:8545 -d '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb33cde97680d9c37f0b9514cffa5889606d9dd10", "pending"],"id":1}'
{"id":1,"jsonrpc":"2.0","result":"0x05"}
```

and go-ethereum's hexutil crashes with error:

https://github.com/ethereum/go-ethereum/blob/master/common/hexutil/hexutil.go line 49

**Comment by mssalnikov** [comment]
@niklasad1 Hi! Sorry, my bad. I was wrong to blame parity for this, turns out we use parity stable for production builds and some outdated testrpc for development, so I got confused. Checked out parity -- everything works. So you can close this probably.

PS. I read somewhere on stackoverflow about even padding, trying to resolve this, so I could be all sorts of wrong

**Comment by joshua-mir** [comment]
Thanks for getting back to us
