### ISSUE TITLE
Parity sync bug

### ISSUE THREAD

**Issue by rerub22** [paritytech/parity-ethereum#10250]
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-130-generic x86_64)

parity --chain kovan --pruning fast  --snapshot-peers 200 --snapshot-threads 25 --cache-size 1024 --mode active --tracing on --log-file /home/kovan.log -lrpc=debug

> Thread 'IO Worker #1' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 2646357839, got 36454732  in /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/239837.sst offset 15532879 size 3781") }', libcore/result.rs:1009
> 
> This is a bug. Please report it at:
> 
>     https://github.com/paritytech/parity-ethereum/issues/new
> 
> 
> 
> ====================
> 
> stack backtrace:
>    0:     0x5632d36e4bbd - <no info>
>    1:     0x5632d36e3dd2 - <no info>
>    2:     0x5632d36e3e49 - <no info>
>    3:     0x5632d36e2f86 - <no info>
>    4:     0x5632d1e992a8 - <no info>
>    5:     0x5632d375ad46 - <no info>
>    6:     0x5632d375a891 - <no info>
>    7:     0x5632d375a775 - <no info>
>    8:     0x5632d37a430c - <no info>
>    9:     0x5632d2ce5a19 - <no info>
>   10:     0x5632d2bf3d1e - <no info>
>   11:     0x5632d26dabde - <no info>
>   12:     0x5632d26dc992 - <no info>
>   13:     0x5632d26ef4d6 - <no info>
>   14:     0x5632d26f388c - <no info>
>   15:     0x5632d26de83c - <no info>
>   16:     0x5632d2706543 - <no info>
>   17:     0x5632d26f2f56 - <no info>
>   18:     0x5632d2705fa1 - <no info>
>   19:     0x5632d2705bf8 - <no info>
>   20:     0x5632d2706914 - <no info>
>   21:     0x5632d270636b - <no info>
>   22:     0x5632d26f2c35 - <no info>
>   23:     0x5632d26eeb6c - <no info>
>   24:     0x5632d26efd44 - <no info>
>   25:     0x5632d26ebda6 - <no info>
>   26:     0x5632d376cf29 - <no info>
>   27:     0x5632d26f7467 - <no info>
>   28:     0x5632d37571dd - <no info>
>   29:     0x5632d3741d95 - <no info>
>   30:     0x7f637f4276b9 - <no info>
>   31:     0x7f637ef4741c - <no info>
>   32:                0x0 - <no info>
> 
> Thread 'IO Worker #2' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 2646357839, got 36454732  in /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/239837.sst offset 15532879 size 3781") }', libcore/result.rs:1009
> 
> This is a bug. Please report it at:
> 
>     https://github.com/paritytech/parity-ethereum/issues/new
>

**Comment by rerub22** [comment]
> root@gserv:~# parity --version
> Parity Ethereum
>   version Parity-Ethereum/v2.3.0-beta-10657d9-20190115/x86_64-linux-gnu/rustc1.31.1
> Copyright 2015-2018 Parity Technologies (UK) Ltd.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> By Wood/Paronyan/Kotewicz/Drwięga/Volf
>    Habermeier/Czaban/Greeff/Gotchac/Redmann

**Comment by joshua-mir** [comment]
@rerub22 this issue is often seen due to hardware failure, so I'd suggest running a memcheck and testing the drive that Parity is using - closing as duplicate as there are several issues matching this like #10219
