### ISSUE TITLE
Web3 subscription - Couldn't parse parameters: newPendingTransactions 

### ISSUE THREAD

**Issue by or2008** [paritytech/parity-ethereum#10256]
- **Parity Ethereum version**: 2.3.0
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: ethereum mainet
- **Restarted**: yes

hello, I am running a local node on my machine using this command:
`parity --tx-queue-size 32000`

and I am trying to subscribe to pending transactions on mainet, using web3.subscribe method, this is the code:

```
const eventProvider = new Web3.providers.WebsocketProvider('ws://localhost:8546');
const web3 = new Web3(eventProvider);

eventProvider.on('connect', () => {
    web3.eth.subscribe('pendingTransactions', async (error, txHash) => { ... });
});

```

it connects successfully to the WebScoket, but when calling the web3.eth.subscribe an error occur:
```
Error: Provider error: Error: Node error: {"code":-32602,"message":"Couldn't parse parameters: newPendingTransactions","data":"\"Expected no parameters.\""}
    at /Users/orbachar/work/front-running/node_modules/web3-providers/dist/web3-providers.cjs.js:334:15
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
when using the same code with infura as the provider, it works well, what am I missing?

**Comment by joshua-mir** [comment]
Hey, which version of web3 are you using?

I'm unsure why this would work with infura, but my first thought is that this might be because the second optional parameter isn't the callback but the options according to the web3 documentation - I'd change the code to something like

```
eventProvider.on('connect', () => {
    subscription = web3.eth.subscribe('pendingTransactions');
    subscription.subscribe(async (error, txHash) => { ... });
});
```

**Comment by or2008** [comment]
Thank you for the reply, you are right, it was just a mistake when I copied the code to here, and I changed it a bit just to make it more readable, this is the actual code I am using: 

```
    const web3 = web3Service.getInstance();
    web3.eth.subscribe('pendingTransactions')
        .on('data', txHash => {
            onData(txHash);
        })
        .on('error', error => {
            onError(error);
        });
```

I am using the lateset web3 version: 1.0.0-beta.41.

I am also used your provided code, just in case, but still same error 
`Couldn't parse parameters: newPendingTransactions`

**Comment by joshua-mir** [comment]
@or2008 it might be the case that web3 is passing a parameter (maybe even an empty object) which is the only reason parity would respond with this error - could you please try with other versions of web3 - it's probably worth noting that the post-1.0 releases of web3 are still unstable and it might be valuable to report this issue to them as well.

**Comment by or2008** [comment]
Thank you, just checked and looks like they add a potential fix

https://github.com/ethereum/web3.js/pull/2346/files

let's see if it fixes my issue

**Comment by or2008** [comment]
ok, checked and it did fix the problem, thank you @joshua-mir for the great help
