### ISSUE TITLE
Redundant implementation of `BlockProvider` on test structs

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-ethereum#10253]
The `TestBlockChain` struct from `ethcore/src/verification/verification.rs` and the `TestBlockChainClient` struct from `ethcore/src/client/test_client.rs` both implement the `BlockProvider` trait.

Instead of having these two redundant implementations we should use one (possibly by replacing `TestBlockChain` with `TestBlockChainClient` in `verification.rs`), and share this one for tests.

**Comment by niklasad1** [comment]
`ethcore::client::TestBlockChainClient` doesn't implement `BlockProvider` anymore closing as stale.
