### ISSUE TITLE
Question about transactions in mempool when amount is not enough

### ISSUE THREAD

**Issue by fanatid** [paritytech/parity-ethereum#10269]
- **Parity Ethereum version**: 2.2.7
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

If we send tx wich spent all available ETH and right after send another tx with incremented nonce which spent same amount again, is this expected that second tx will be in mempool some time? i.e. will not be kicked because account do not have required amount now? It's looks strange that tx stay in mempool, because if we will try broadcast tx which spent more than available we will receive error.

JS code which sent 2 such tx:
```js
const EthereumTx = require('ethereumjs-tx') // ^1.3.7
const ethUtil = require('ethereumjs-util') // will be available, when ethereumjs-tx will be installed
const fetch = require('node-fetch') // ^2.3.0

const PRIVATE_KEY = '3499689c467b0fc14994e5c784ff39991d3e3e05729d14a283ec4d0fceecf73f'

const makeRequest = async (url, body) => {
  const opts = !body ? {} : {
    method: 'post',
    headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  }

  const res = await fetch(url, opts)
  const text = await res.text()
  try {
    return JSON.parse(text)
  } catch (err) {
    throw new Error(`JSON parse error: ${text}`)
  }
}

;(async () => {
  const pk = Buffer.from(PRIVATE_KEY, 'hex')
  const address = '0x' + ethUtil.privateToAddress(pk).toString('hex')
  console.log(`Ethereum Address: ${address}`)

  const [
    { result: rawBalance },
    { result: rawNonce },
    { result: rawGasPrice }
  ] = await Promise.all([
    makeRequest(`https://api.etherscan.io/api?module=account&action=balance&address=${address}`),
    makeRequest(`https://api.etherscan.io/api?module=proxy&action=eth_getTransactionCount&address=${address}`),
    makeRequest(`https://api.etherscan.io/api?module=proxy&action=eth_gasPrice`)
  ])

  console.log(`Found: nonce -- ${rawNonce}, balance -- ${rawBalance}, gas price -- ${rawGasPrice}`)

  const gasPrice = Math.ceil(parseInt(rawGasPrice, 16) * 1.2) // add 20% for fast confirmation
  const gas = new ethUtil.BN(gasPrice).imuln(21000)
  const amount = new ethUtil.BN(rawBalance, 10).isub(gas)

  const txParams = {
    gasPrice: ethUtil.addHexPrefix(gasPrice.toString(16)),
    gasLimit: '0x5208',
    to: '0x7758d79c8fa4747a44577b8780ed8534d5e1945f',
    value: ethUtil.addHexPrefix(amount.toString('hex'))
  }

  const tx1 = new EthereumTx({ ...txParams, nonce: rawNonce })
  tx1.sign(pk)
  const tx1Hex = tx1.serialize().toString('hex')
  console.log(`TX1: ${tx1Hex}`)

  const tx2 = new EthereumTx({ ...txParams, nonce: ethUtil.addHexPrefix(parseInt(rawNonce, 16) + 1) })
  tx2.sign(pk)
  const tx2Hex = tx2.serialize().toString('hex')
  console.log(`TX2: ${tx2Hex}`)

  console.log(await makeRequest(`https://api.etherscan.io/api?module=proxy&action=eth_sendRawTransaction&hex=${tx1Hex}`))
  console.log(await makeRequest(`https://api.etherscan.io/api?module=proxy&action=eth_sendRawTransaction&hex=${tx2Hex}`))
})().catch((err) => {
  console.error(err.stack || err)
  process.exit(1)
})
```

For example, address: https://etherscan.io/address/0x909f1828140cc70f635bae83d4b6e1f93742a11d (unconfirmed will be kicked later)
![address](https://user-images.githubusercontent.com/2633065/52041551-ce929a80-254b-11e9-9e68-ee9a44c93cac.png)
![address-tx-unconfirmed](https://user-images.githubusercontent.com/2633065/52041556-d18d8b00-254b-11e9-8908-8da4c98e4fa5.png)
![address-tx-confirmed](https://user-images.githubusercontent.com/2633065/52041563-d6ead580-254b-11e9-9d8f-aee232254696.png)

**Comment by joshua-mir** [comment]
You might receive enough eth to make the second transaction in the block including the first transaction..?

**Comment by fanatid** [comment]
Yes, it's possible, as possible send ETH to account and tx will be confirmed (if still will be in mempool). 
But if such situations possible, why then we receive error when try send tx which try spent more than account have?

**Comment by joshua-mir** [comment]
Because if you are in sync there's no point in keeping/broadcasting that transaction in the mempool - it is not valid until you have enough balance? If I'm understanding your question correctly.

**Comment by fanatid** [comment]
@joshua-mir sorry, you answer not clear for me =(

My point here that behaviour now is inconsistent: 1) Any transaction which spent more than address have will be rejected on broadcasting stage 2) Mempool can hold transactions which spent more than address have if previous transaction make such situation possible (i.e. for example: initial balance 10, first tx spent 6, second 6, both will be accepted, but second will be stuck while mempool not be overfilled).

If mempool can hold transactions which spent more than account have, why parity reject such transactions on broadcasting stage?

**Comment by joshua-mir** [comment]
Because we don't perform that check on *future* transactions, only transactions that can be immediately executed.
