### ISSUE TITLE
eth_getBalance very slow or time out

### ISSUE THREAD

**Issue by truongthaison** [paritytech/parity-ethereum#10268]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.8-unstable-2a7dc64-20190122/x86_64-linux-gnu/rustc1.32.0
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes

i'm run: `parity --light`

my config:
```
[parity]
base_path = "/root/parity/data"
light = true
no_persistent_txqueue = true
[mining]
gas_floor_target = "4712388"
[footprint]
db_compaction = "ssd"
```

i'm used RPC, call function:
```
{
"jsonrpc":"2.0",
"method":"eth_getBalance",
"params": [
	"0xe7912dbc7177133c7bacb829264624bcc17dfd00",
	"latest"
	]
,"id":1}
```

i'm get response very slow, some time i'm get error: time out:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32065,
        "message": "Timeout for On-demand query; 31 query attempts remain for query #0"
    },
    "id": 1
}
```
please help me know and config

**Comment by joshua-mir** [comment]
@truongthaison light clients have a limit in how many queries they can make to their light-serving peers. If you want to make many queries often, you shouldn't be running `--light`
