### ISSUE TITLE
parity 2.2.7 error Permission denied (os error 13)

### ISSUE THREAD

**Issue by girish979** [paritytech/parity-ethereum#10267]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.7
- **Operating system**: Ubuntu 16.04
- **Installation**: snap
- **Fully synchronized**: no 
- **Network**: POA
- **Restarted**: / yes

I am following the tutorial in this link
https://wiki.parity.io/Demo-PoA-tutorial

```
$ parity  --chain demo-spec.json -d /tmp/parity0 --port 30300 --jsonrpc-port 8540 --ws-port 8450 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts
Could not load specification file at demo-spec.json: Permission denied (os error 13)
```

The Ubuntu 16.04 VM is a fresh installation

I am getting the error in Step 2.
Could not load specification file at demo-spec.json: Permission denied (os error 13)

**Comment by joshua-mir** [comment]
@girish979 does your user have permission to access /tmp/?

**Comment by girish979** [comment]
Yes, the user has permissions, I tried with sudo as well.
seems the issue is with snap installer.
Tried directly with binary and it is working fine.

**Comment by joshua-mir** [comment]
There are known issues with snap and /tmp/ access from what I know, nothing really we can do here.
