### ISSUE TITLE
"ancient block sync is still in progress" even though it completed.

### ISSUE THREAD

**Issue by gmajoulet** [paritytech/parity-ethereum#10261]
- **Parity Ethereum version**: 2.3.0
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

1. Install parity with the one line installer
2. Run `parity --jsonrpc-server-threads=5 --min-peers 50 --max-peers 200 --geth --no-ancient-blocks` and wait for the node to be up to date (it started importing the latest block every ~10sec)
3. Got errors `Error: Block information is incomplete while ancient block sync is still in progress, before it's finished we can't determine the existence of requested item.` for anything I'd try to do (retrieving a tx, publishing one, anything).
4. Run `parity db kill`
5. Run `parity --jsonrpc-server-threads=5 --min-peers 50 --max-peers 200 --geth` and wait for the node to sync
6. Got the same errors mentioning `ancient block sync` again even though the node doesn't run with this parameter.

**Comment by joshua-mir** [comment]
Hey, could you share more examples of what requests you are making, and how you are making them? This looks like an error that only comes up if you try to call a command via eth_subscribe which isn't supported by it (use parity_subscribe instead, or just send the actual command you are attempting).

(for our reference, here's the code that emits the error message https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/rpc/src/v1/impls/eth_pubsub.rs#L295)

**Comment by joshua-mir** [comment]
If you disable `--no-ancient-blocks`, your node will be syncing ancient blocks in the background which you can verify that status of with https://wiki.parity.io/JSONRPC-parity-module#parity_chainstatus

**Comment by gmajoulet** [comment]
My node did sync the ancient blocks and is now working as expected, but this was not documented nor written anywhere in the CLI. :(
Would it help if I could repro the exact issue I had with using `--no-ancient-blocks`? I was executing a smart contract function, so I would need to investigate and test what was actually triggering the error, if that helps. If not, feel free to close this ticket.
Thanks!

**Comment by joshua-mir** [comment]
Well, it depends on what queries you were making - ordinary `eth_call`s shouldn't be emitting this error even if you are running with `--no-ancient-blocks` but getting transactions or block information from blocks you don't have is expected to throw this error.

**Comment by bonanblock** [comment]
try to call the rpc with the following command `{"jsonrpc":"2.0","method":"eth_getUncleByBlockNumberAndIndex","params":["0x649356", "0x0"],"id":1}`. all other rpc calls are working fine

**Comment by joshua-mir** [comment]
Have you tried https://wiki.parity.io/JSONRPC-parity-module#parity_chainStatus ?

**Comment by bonanblock** [comment]
tried `curl --data '{"method":"parity_chainStatus","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:2211`
Gives
`{"jsonrpc":"2.0","result":{"blockGap":null},"id":1}`

**Comment by bonanblock** [comment]
updates: this rpc call `eth_getUncleByBlockNumberAndIndex` is broken. It will return `Ancient block sync is still in progress` when there is no such uncle exist
`'{"jsonrpc":"2.0","method":"eth_getUncleByBlockHashAndIndex","params":["0x75e1271bdfa6bcbcc9e9a1ad8b340297215dc6dc9323e55c2c3e7816f7f93a19", "0x0"],"id":1}'` gives the correct response. `{"id": 1, "result": null, "jsonrpc": "2.0"}`
While `'{"jsonrpc":"2.0","method":"eth_getUncleByBlockNumberAndIndex","params":["0x726486", "0x0"],"id":1}'` will return ` {"id": 1, "error": {"code": -32000, "message": "Ancient block sync is still in progress"}, "jsonrpc": "2.0"}`
Even tho they are the same block

**Comment by joshua-mir** [comment]
@bonanblock could you please share what version you are running?

**Comment by bonanblock** [comment]
`version Parity-Ethereum/v2.4.4-beta-8f6911a-20190401/x86_64-linux-gnu/rustc1.33.0`
```
[parity]
base_path = "/srv/blockchain/eth"

[rpc]
interface = "127.0.0.1"
port = 2211
apis = ["web3", "eth", "net", "rpc", "parity"]
hosts = ["127.0.0.1/8"]

[websockets]
disable = false
port = 2223
interface = "127.0.0.1"
origins = ["none"]
apis = ["web3", "eth", "pubsub"]
hosts = ["127.0.0.1/8"]

[footprint]
db_compaction = "ssd"
pruning = "archive"
cache_size = 8192

[snapshots]
disable_periodic = false

[network]
snapshot_peers = 0
~
```

**Comment by joshua-mir** [comment]
So not only is ancient block sync not running, you are running an archive node. I can find the relevant error message and change it but I'm not certain what the correct error message would be for this situation.

**Comment by bonanblock** [comment]
I would suggest give the same response as `{"id": 1, "result": null, "jsonrpc": "2.0"}`. If it returns `{"id": 1, "error": {"code": -32000, "message": "Ancient block sync is still in progress"}`, it is misleading which makes the developers doubt if their node is fully synced but in reality it just means there no uncle blocks attached to this block

**Comment by seunlanlege** [comment]
Just investigated the code, found the reason for the misleading error messages,
