### ISSUE TITLE
Invalid KDF algorithm

### ISSUE THREAD

**Issue by danihodovic** [paritytech/parity-ethereum#10270]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.2.7
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: Custom PoA
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Parity does not recognize the keyfile generated by web3.py. The keyfile was created by `eth-keyfile==0.5.1`

```
    from web3 import Web3
    w3 = Web3()
    account = w3.eth.account.privateKeyToAccount(private_key)
    keyfile = account.encrypt(password)
    # Write file to disk as JSON
```

##### Generated keyfile
```
{"address": "e4eb4620a555179e7f9589d7a301d9c8c61c50b0", "crypto": {"cipher": "aes-128-ctr", "cipherparams": {"iv": "3c893d78db458e6632e07ec73eac54cb"}, "ciphertext": "4abb0edcb6b53790b01995b98dea8763e60465279c1a9d05311a166316a1b134", "kdf": "scrypt", "kdfparams": {"dklen": 32, "n": 262144, "p": 1, "r": 8, "salt": "3163eae86fb80fb8a4f0f7ff0d3bece3"}, "mac": "6b30649b5c8eb36723063997d905d6fdd8d583cfb9407449b6810b45472b9e66"}, "id": "5f594e20-8589-408a-b3b8-3e5aed07b53a", "version": 3}
```

##### Parity logs
```
2019-01-31 18:39:26 UTC Invalid key file: "/opt/parity/keys/ambnet-dev/keyfile" (Error("Invalid KDF algorithm", line: 1, column: 296))
```

**Comment by joshua-mir** [comment]
@danihodovic can you confirm wether these keyfiles can be loaded into other software like MyCrypto and MyEtherWallet?

**Comment by joshua-mir** [comment]
Ping? Will close as this is pretty stale. Let me know if you want to reopen it.
