### ISSUE TITLE
Thread 'jsonrpc-eventloop-2' panicked at 'byte index 2 is not a char boundary

### ISSUE THREAD

**Issue by vkachan** [paritytech/parity-ethereum#10287]
- Parity Ethereum version: 2.3.1-beta
- Operating system: CentOS 7
- Installation: built from source
- Fully synchronized: no
- Network: ethereum
- Restarted: yes

Parity crushed several times with the message:

  46:     0x7f15cf4dddd4 - start_thread
  47:     0x7f15ceff0eac - __clone
  48:                0x0 - <unknown>

Thread 'jsonrpc-eventloop-2' panicked at 'byte index 2 is not a char boundary; it is inside '∀' (bytes 0..3) of `∀∂∈∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∂∈ℝ∧∪≡∞ ↑↗↨↻⇣ ┐┼╔╘░►☺♀ ﬁ�⑀₂ἠḂӥẄɐː⍎אԱა \n && ';1'23,12;'312:L:!\" &&  ∂`[...]', libcore/str/mod.rs:2111

Firstly it crushed on the version 2.2.7 then I did upgrade to 2.2.8 and finally to 2.3.1. On all those versions similar behaviour. Before it has been working without any issues for a month.

**Comment by joshua-mir** [comment]
Hey, we are aware of this and a release addressing this is coming out asap.

**Comment by vkachan** [comment]
@joshua-mir thank you for an update! appreciated

**Comment by roderik** [comment]
I'm hit with the same issue in a PoA network.

**Comment by 5chdn** [comment]
Thanks for the report - please upgrade to latest nightly, 2.3.2 beta, or 2.2.9 stable.
