### ISSUE TITLE
ValidatorSets deadlock

### ISSUE THREAD

**Issue by akru** [paritytech/parity-ethereum#10293]
- **Parity Ethereum version**: 2.3
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan

Currently ValidatorSet is vulnerable to lock via down one of validators.

Reproduce:

- up private chain with two validators,
- down one authority
- second authority cannot drop first from list and cannot add new one

**Comment by akru** [comment]
Ok, @joshua-mir, how to remove offline validator in this case?

**Comment by joshua-mir** [comment]
https://wiki.parity.io/Validator-Set.html#reporting-contract implement `reportBenign()` - perhaps count the number of benign reports of a validator there are and then remove them from the validator set after a certain number of reports (fire out an initiateChange event with the new validator set as well)

**Comment by akru** [comment]
As I can see the `system` just don't call `finalizeChange` in this case, right?

**Comment by joshua-mir** [comment]
True - it's waiting for acknowledgement from the other validator - you should be able to call finalizeChange yourself as well, but only if you are certain you want to finalize that block.

**Comment by akru** [comment]
I try to finalize manually(by set relaySet address to EOA, send finalize and set again) but validator node just use previous version of validators set. I should send finalize in next block after `initiateChange`?

**Comment by akru** [comment]
I just want to known if delay for this is sensitive, thank you.

**Comment by joshua-mir** [comment]
Yes the logic is only triggered on a new block
