### ISSUE TITLE
Unexpected error while running testnet

### ISSUE THREAD

**Issue by nandubatchu** [paritytech/parity-ethereum#10290]
Block import failed for #10255212 (0xb907…8862): Parent not found (0x2bc8…314e)

====================

stack backtrace:
   0:     0x55d62e26af0c - <no info>
   1:     0x55d62e26a1a2 - <no info>
   2:     0x55d62e26a218 - <no info>
   3:     0x55d62e26901a - <no info>
   4:     0x55d62cced705 - <no info>
   5:     0x55d62e2c6cd3 - <no info>
   6:     0x55d62e2c6839 - <no info>
   7:     0x55d62e2c6735 - <no info>
   8:     0x55d62e31f31b - <no info>
   9:     0x55d62cf9764f - <no info>
  10:     0x55d62cd8c4df - <no info>
  11:     0x55d62cc624f0 - <no info>
  12:     0x55d62cc64343 - <no info>
  13:     0x55d62d699f8a - <no info>
  14:     0x55d62d3550fa - <no info>
  15:     0x55d62d35ac44 - <no info>
  16:     0x55d62d0220dc - <no info>
  17:     0x55d62ce6e45a - <no info>
  18:     0x55d62ce7850e - <no info>
  19:     0x55d62ce6e45a - <no info>
  20:     0x55d62cf22e96 - <no info>
  21:     0x55d62ce78a7f - <no info>
  22:     0x55d62cd4456b - <no info>
  23:     0x55d62df9832a - <no info>
  24:     0x55d62df9638d - <no info>
  25:     0x55d62df958c3 - <no info>
  26:     0x55d62df8f49b - <no info>
  27:     0x55d62e2f2b99 - <no info>
  28:     0x55d62df973ca - <no info>
  29:     0x55d62e2e0a2a - <no info>
  30:     0x55d62e2c74f5 - <no info>
  31:     0x7fafe8e9d6b9 - <no info>
  32:     0x7fafe89bd41c - <no info>
  33:                0x0 - <no info>

Thread '<unnamed>' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:1009

**Comment by nandubatchu** [comment]
====================

stack backtrace:
   0:     0x55ee720a96dd - <no info>
   1:     0x55ee720a88f2 - <no info>
   2:     0x55ee720a8969 - <no info>
   3:     0x55ee720a7aa6 - <no info>
   4:     0x55ee707c5218 - <no info>
   5:     0x55ee72121c96 - <no info>
   6:     0x55ee721217e1 - <no info>
   7:     0x55ee721216c5 - <no info>
   8:     0x55ee7216b25c - <no info>
   9:     0x55ee72161311 - <no info>
  10:     0x55ee70a434f1 - <no info>
  11:     0x55ee70a5ee5f - <no info>
  12:     0x55ee7081276d - <no info>
  13:     0x55ee70a68f5a - <no info>
  14:     0x55ee70a2aa92 - <no info>
  15:     0x55ee709de0b9 - <no info>
  16:     0x55ee70842c17 - <no info>
  17:     0x55ee709c2c07 - <no info>
  18:     0x55ee708d4840 - <no info>
  19:     0x55ee709c8378 - <no info>
  20:     0x55ee70a98424 - <no info>
  21:     0x55ee70a9b74c - <no info>
  22:     0x55ee70afb4a2 - <no info>
  23:     0x55ee70aac1f9 - <no info>
  24:     0x55ee7078925d - <no info>
  25:     0x55ee7078a62b - <no info>
  26:     0x55ee7078a62b - <no info>
  27:     0x55ee707bf790 - <no info>
  28:     0x55ee70807c02 - <no info>
  29:     0x55ee70805f39 - <no info>
  30:     0x55ee708f1a66 - <no info>
  31:     0x55ee70782b16 - <no info>
  32:     0x55ee71e50d41 - <no info>
  33:     0x55ee71e51795 - <no info>
  34:     0x55ee71e546b0 - <no info>
  35:     0x55ee72133e79 - <no info>
  36:     0x55ee71e53a9b - <no info>
  37:     0x55ee71e4b2b5 - <no info>
  38:     0x55ee71e4a39d - <no info>
  39:     0x55ee71e312d5 - <no info>
  40:     0x55ee71e31611 - <no info>
  41:     0x55ee71e314c8 - <no info>
  42:     0x55ee71e29f45 - <no info>
  43:     0x55ee71e525cc - <no info>
  44:     0x55ee71e52a5e - <no info>
  45:     0x55ee71e532b1 - <no info>
  46:     0x55ee71e546fb - <no info>
  47:     0x55ee72133e79 - <no info>
  48:     0x55ee71e4fbcf - <no info>
  49:     0x55ee7211e12d - <no info>
  50:     0x55ee72108ce5 - <no info>
  51:     0x7fae3a4186b9 - <no info>
  52:     0x7fae39f3841c - <no info>
  53:                0x0 - <no info>

Thread 'jsonrpc-eventloop-0' panicked at 'byte index 2 is not a char boundary; it is inside '∀' (bytes 0..3) of `∀∂∈∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∂∈ℝ∧∪≡∞ ↑↗↨↻⇣ ┐┼╔╘░►☺♀ ﬁ�⑀₂ἠḂӥẄɐː⍎אԱა \n && ';1'23,12;'312:L:!\" &&  ∂`[...]', libcore/str/mod.rs:2111



====================

stack backtrace:
   0:     0x55ee720a96dd - <no info>
   1:     0x55ee720a88f2 - <no info>
   2:     0x55ee720a8969 - <no info>
   3:     0x55ee720a7aa6 - <no info>
   4:     0x55ee707c5218 - <no info>
   5:     0x55ee72121c96 - <no info>
   6:     0x55ee721217e1 - <no info>
   7:     0x55ee721216c5 - <no info>
   8:     0x55ee7216b25c - <no info>
   9:     0x55ee72161311 - <no info>
  10:     0x55ee70a434f1 - <no info>
  11:     0x55ee70a5ee5f - <no info>
  12:     0x55ee7081276d - <no info>
  13:     0x55ee70a68f5a - <no info>
  14:     0x55ee70a2aa92 - <no info>
  15:     0x55ee709de0b9 - <no info>
  16:     0x55ee70842c17 - <no info>
  17:     0x55ee709c2c07 - <no info>
  18:     0x55ee708d4840 - <no info>
  19:     0x55ee709c8378 - <no info>
  20:     0x55ee70a98424 - <no info>
  21:     0x55ee70a9b74c - <no info>
  22:     0x55ee70afb4a2 - <no info>
  23:     0x55ee70aac1f9 - <no info>
  24:     0x55ee7078925d - <no info>
  25:     0x55ee7078a62b - <no info>
  26:     0x55ee7078a62b - <no info>
  27:     0x55ee707bf790 - <no info>
  28:     0x55ee70807c02 - <no info>
  29:     0x55ee70805f39 - <no info>
  30:     0x55ee708f1a66 - <no info>
  31:     0x55ee70782b16 - <no info>
  32:     0x55ee71e50d41 - <no info>
  33:     0x55ee71e51795 - <no info>
  34:     0x55ee71e546b0 - <no info>
  35:     0x55ee72133e79 - <no info>
  36:     0x55ee71e53a9b - <no info>
  37:     0x55ee71e4b2b5 - <no info>
  38:     0x55ee71e4a39d - <no info>
  39:     0x55ee71e312d5 - <no info>
  40:     0x55ee71e31611 - <no info>
  41:     0x55ee71e314c8 - <no info>
  42:     0x55ee71e29f45 - <no info>
  43:     0x55ee71e525cc - <no info>
  44:     0x55ee71e52a5e - <no info>
  45:     0x55ee71e532b1 - <no info>
  46:     0x55ee71e546fb - <no info>
  47:     0x55ee72133e79 - <no info>
  48:     0x55ee71e4fbcf - <no info>
  49:     0x55ee7211e12d - <no info>
  50:     0x55ee72108ce5 - <no info>
  51:     0x7fae3a4186b9 - <no info>
  52:     0x7fae39f3841c - <no info>
  53:                0x0 - <no info>

Thread 'jsonrpc-eventloop-1' panicked at 'byte index 2 is not a char boundary; it is inside '∀' (bytes 0..3) of `∀∂∈∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∂∈ℝ∧∪≡∞ ↑↗↨↻⇣ ┐┼╔╘░►☺♀ ﬁ�⑀₂ἠḂӥẄɐː⍎אԱა \n && ';1'23,12;'312:L:!\" &&  ∂`[...]', libcore/str/mod.rs:2111

**Comment by nandubatchu** [comment]
Trying to re-run the node, did not help either. Any suggestions?

**Comment by joshua-mir** [comment]
The second panic (#10287) you are seeing is unrelated to the first. Please update your node. https://www.parity.io/security-alert-parity-ethereum-03-02/

**Comment by joshua-mir** [comment]
Additionally @nandubatchu can you please share information about the network, sync mode, version, etc?

**Comment by debris** [comment]
I'm closing as we don't have enough information to do anything with this issue
