### ISSUE TITLE
Inconsistent docker image between stable and beta

### ISSUE THREAD

**Issue by ddorgan** [paritytech/parity-ethereum#10299]
- **Parity Ethereum version**: parity/parity: stable vs parity/parity:beta
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: n/a
- **Network**: any
- **Restarted**: n/a

The issue is around knowing the location of the entrypoint.sh and parity binary itself between the stable and beta release (and all tagged versions in fact).

**Stable:**
entrypoint: /home/parity/entrypoint.sh
binary: /home/parity/bin/parity

**Beta**
entrypoint: /entrypoint.sh
binary: /bin/parity

**Comment by TriplEight** [comment]
It's more about this: https://github.com/paritytech/parity-ethereum/pull/10059
But first we might discuss what should and should not be there.

**Comment by 5chdn** [comment]
Just make sure changes to docker files (and CI in general) are labelled "patch"

**Comment by ddorgan** [comment]
https://github.com/paritytech/parity-ethereum/pull/10335

**Comment by 5chdn** [comment]
We fixed that with 2.2.10 and 2.3.3
