### ISSUE TITLE
Got panic while starting the Parity Node. New Bug found asked to report

### ISSUE THREAD

**Issue by asimashfaq** [paritytech/parity-ethereum#10318]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.2.8-stable-ec81d67-20190130/x86_64-linux-gnu/rustc1.31.1
- **Operating system**: Linux
- **Installation**:  one-line installer
- **Fully synchronized**: yes
- **Network**: expanse
- **Restarted**: yes

root@couchbase:~# sh start-parity.sh 
Loading config file from config.toml
2019-02-10 07:18:53 UTC main INFO parity_ethereum::run  Starting Parity-Ethereum/v2.2.8-stable-ec81d67-20190130/x86_64-linux-gnu/rustc1.31.1
2019-02-10 07:18:53 UTC main INFO parity_ethereum::run  Keys path /root/.local/share/io.parity.ethereum/keys/expanse
2019-02-10 07:18:53 UTC main INFO parity_ethereum::run  DB path /root/.local/share/io.parity.ethereum/chains/expanse/db/fdd5db7f099445c9
2019-02-10 07:18:53 UTC main INFO parity_ethereum::run  State DB configuration: fast +Trace
2019-02-10 07:18:53 UTC main INFO parity_ethereum::run  Operating mode: active
2019-02-10 07:18:53 UTC main WARN parity_ethereum::run  Warning: Warp Sync is disabled because tracing is turned on.
2019-02-10 07:18:53 UTC main INFO ethcore_service::service  Configured for Expanse using Ethash engine

====================

stack backtrace:
   0:     0x55618417c8bd - <no info>
   1:     0x55618417bad2 - <no info>
   2:     0x55618417bb49 - <no info>
   3:     0x55618417ac86 - <no info>
   4:     0x55618417aa61 - <no info>
   5:     0x5561841f4e76 - <no info>
   6:     0x5561841f49c1 - <no info>
   7:     0x5561841f48a5 - <no info>
   8:     0x55618423e43c - <no info>
   9:     0x55618423e4b2 - <no info>
  10:     0x556183725d00 - <no info>
  11:     0x55618368e582 - <no info>
  12:     0x55618334b5d9 - <no info>
  13:     0x55618289cf14 - <no info>
  14:     0x5561828aeab3 - <no info>
  15:     0x55618295905b - <no info>
  16:     0x556182a9bc11 - <no info>
  17:     0x556182a9e721 - <no info>
  18:     0x556182869972 - <no info>
  19:     0x5561841f4842 - <no info>
  20:     0x556184207059 - <no info>
  21:     0x5561841d554a - <no info>
  22:     0x556182a9f084 - <no info>
  23:     0x7f8f8720582f - <no info>
  24:     0x5561827b9678 - <no info>
  25:                0x0 - <no info>

Thread 'main' panicked at 'Best block is from a known block hash; qed', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

Aborted (core dumped)

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by joshua-mir** [comment]
Hey, can you share your system specifications? This looks like either hardware failure of just an unfortunate bit flip. Do you still see this after restarting?

**Comment by asimashfaq** [comment]
Yes i did  now,i had deleted my chain and resyncing the db. So waiting for the results

OS is Ubunut 16.04

**Comment by asimashfaq** [comment]
After deleting the chain and resync everything is fine
