### ISSUE TITLE
Arithmetic operation overflow with badly fixed gas price

### ISSUE THREAD

**Issue by johnerfx** [paritytech/parity-ethereum#10319]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.2.9-stable-5d5b372f4-20190203
- **Operating system**: x86_64-linux-gnu
- **Installation**: built from source - /rustc1.30.1
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes

Node crashes when sending a transaction with badly fixed gas price.

> Thread 'jsonrpc-eventloop-0' panicked at 'arithmetic operation overflow', /home/*****/.cargo/regis
> try/src/github.com-1ecc6299db9ec823/ethereum-types-0.4.0/src/uint.rs:32

Gas prices were accidentally set like these:
`gasPrice: '0xa8e13c55.5555555551ab155a6bc5'` 
or
`gasPrice: '0x90c10f24.924924924ab6adb4ad3e'`

After rounding it to something like:
`gasPrice: '0xa8e13c55'` 
or
`gasPrice: '0x90c10f24'`
There is no problem.

**Comment by joshua-mir** [comment]
@johnerfx can you share which rpc method you are using to get this error? I can't replicate with either eth_sendTransaction or personal_sendTransaction

**Comment by johnerfx** [comment]
I think it is `eth_sendTransaction`.

**Comment by joshua-mir** [comment]
@johnerfx (while this is definitely an issue we should handle, it's *also* a bug in truffle, might be worth letting them know.)

**Comment by joshua-mir** [comment]
@johnerfx - when you built from source, did you specify the `--release` flag?
