### ISSUE TITLE
Event logs from the new blocks are suddenly available when the outdated node imports old blocks

### ISSUE THREAD

**Issue by LordotU** [paritytech/parity-ethereum#10322]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.7-stable-b00a21f-20190115/x86_64-linux-gnu/rustc1.31.1
- **Operating system**: Linux
- **Installation**: binary file
- **Fully synchronized**: no
- **Network**: ropsten
- **Restarted**: yes

**Actual:**

I'm listening my contracts events via *web3@1.0.0-beta.37* which is connected to Parity via WS.

The code seems like:

```javascript
const web3 = new Web3(provider)

const contract = new web3.eth.Contract(
  abi,
  address,
)

const contract.events.Event({
    fromBlock: 'latest'
  })
  .on('data', async function (event) {
    // bla-bla-bla
  })
```

So, my node is not fully synchronized with current Ropsten state and the gap is ~17 hours. When the event emits with the fresh Ropsten block, my code also find it out (but the latest block for my node is the block, which was released 17 hours earlier).

Or, maybe, this behavior is correct?

**Expected:**

My code should find out relevant event log when an appropriate block will be imported by Parity.

**Comment by joshua-mir** [comment]
Am I understanding correctly that your node is emitting events for blocks it hasn't seen yet? 🤔

I don't understand how that would be possible

**Comment by LordotU** [comment]
> Am I understanding correctly that your node is emitting events for blocks it hasn't seen yet? 
> 
> I don't understand how that would be possible

Yes, for example:

1. Tx was occured and event was emitted in a block *4997667*
2. My Ropsten node imported block with number *4992830*
3. Code has reacted with *onData* handler for block with number *4992830*
4. And the event with data from block *4997667* was found

**Comment by joshua-mir** [comment]
https://wiki.parity.io/FAQ#what-does-paritys-command-line-output-mean

Are you certain that the blocks being imported are not historical blocks, ie, are you running a node that has been warp-synced?

**Comment by LordotU** [comment]
> https://wiki.parity.io/FAQ#what-does-paritys-command-line-output-mean
> 
> Are you certain that the blocks being imported are not historical blocks, ie, are you running a node that has been warp-synced?

Yes, my node works in a warp node. Current logs are:

```
2019-02-11 15:23:46 UTC Imported #4993912 0x01b1…9c60 (8 txs, 5.19 Mgas, 40 ms, 19.08 KiB)
2019-02-11 15:23:50 UTC Syncing #4993912 0x01b1…9c60     0.10 blk/s    0.8 tx/s    0.5 Mgas/s      0+    0 Qed  #4993911   41/50 peers      6 MiB chain   68 MiB db  0 bytes queue  260 KiB sync  RPC:  5 conn,    0 req/s,  815 µs
2019-02-11 15:23:55 UTC Syncing #4993912 0x01b1…9c60     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #4993879   41/50 peers      8 MiB chain   68 MiB db  0 bytes queue  260 KiB sync  RPC:  5 conn,    0 req/s,  815 µs
2019-02-11 15:24:00 UTC Syncing #4993912 0x01b1…9c60     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #4993398   41/50 peers      8 MiB chain   68 MiB db  0 bytes queue  260 KiB sync  RPC:  5 conn,    0 req/s,  815 µs
```

If I understand correctly it verifies old blocks an still not synchronized with the top. So, latest block in my case  - *4993912*

**Comment by joshua-mir** [comment]
Yes.

I noticed another issue, likely isn't related to your problem, but I should have seen before - you're on a bad fork because you haven't updated to 2.2.8 (or above)

**Comment by LordotU** [comment]
I have only one provider, which is connected to the subject node...

Will updating the node fix this problem?

**Comment by joshua-mir** [comment]
You should update your node (and probably resync) regardless because you aren't on the public ropsten chain at the moment.

**Comment by LordotU** [comment]
> You should update your node (and probably resync) regardless because you aren't on the public ropsten chain at the moment.

Ok, thanks. I will try and report when done.

**Comment by LordotU** [comment]
> because you aren't on the public ropsten chain at the moment.

How did you know that I'm on the wrong chain? Sorry for stupid question...

**Comment by LordotU** [comment]
With `Parity-Ethereum/v2.2.9-stable-5d5b372-20190203/x86_64-linux-gnu/rustc1.31.1` and resync it seems ok. Tnx, @joshua-mir

**Comment by joshua-mir** [comment]
> How did you know that I'm on the wrong chain? Sorry for stupid question...

@LordotU for future reference, I just compared the block hash in your logs with the blockhash for the same block number on a block explorer
