### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'specified instant was later than self', src/libstd/sys/unix/time.rs:298

### ISSUE THREAD

**Issue by oldcryptogeek** [paritytech/parity-ethereum#10320]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.9-unstable-5d5b372f4-20190203/x86_64-linux-gnu/rustc1.32.0
- **Operating system**: Ubuntu 18.04lts
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum classic
- **Restarted**:  yes

While running IBD with:

$ ./parity --chain="classic" --jsonrpc-port="8545" --jsonrpc-hosts="all" --jsonrpc-apis="all" --tracing on 
--jsonrpc-interface "all" --jsonrpc-cors "all" --no-periodic-snapshot --ws-hosts="all"

encountered error:

stack backtrace:
   0:     0x55f1d5e84bed - backtrace::backtrace::trace::h16f4d19e5ed7ab6a
   1:     0x55f1d5e83d12 - backtrace::capture::Backtrace::new::h53b2d57f7dd6d113
   2:     0x55f1d5e82ec6 - panic_hook::gen_panic_msg::h789f6f866eaa6e82
   3:     0x55f1d4630ad8 - panic_hook::set_with::{{closure}}::hd953e35032549999
   4:     0x55f1d5ef6329 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   5:     0x55f1d5ef6014 - std::panicking::begin_panic::hfe6a34bacdb12935
                        at src/libstd/panicking.rs:425
   6:     0x55f1d5f01298 - std::sys::unix::time::inner::Instant::sub_instant::{{closure}}::h1e63a8cfa92deeaf
                        at src/libstd/sys/unix/time.rs:298
   7:     0x55f1d5ef04d3 - <core::result::Result<T, E>>::unwrap_or_else::ha9caf5fed6f5aca4
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/result.rs:774
                         - std::sys::unix::time::inner::Instant::sub_instant::h9da75bb321c4cabd
                        at src/libstd/sys/unix/time.rs:297
                         - std::time::Instant::duration_since::h0db8b5aa21d5ce6e
                        at src/libstd/time.rs:185
                         - <std::time::Instant as core::ops::arith::Sub>::sub::h89c2f709b3ce6945
                        at src/libstd/time.rs:250
   8:     0x55f1d526b710 - ethcore_light::net::LightProtocol::make_announcement::h0c9bebca62be7c11
   9:     0x55f1d50a7cb9 - ethcore_network_devp2p::host::Host::with_context::h211a89335fc01daf
  10:     0x55f1d507071d - ethcore_network_devp2p::service::NetworkService::with_context::hdc60f4c07ab9d129
  11:     0x55f1d507838f - <ethcore_sync::api::EthSync as ethcore::client::chain_notify::ChainNotify>::new_blocks::h3f4cd86cc36ba3fd
  12:     0x55f1d5405d48 - ethcore::client::client::Importer::import_verified_blocks::h4a98482de2c07a91
  13:     0x55f1d5065180 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::hc3ef32eba9148745
  14:     0x55f1d5059185 - ethcore_io::worker::Worker::work_loop::h5d513e0a31ba094c
  15:     0x55f1d50426ef - std::sys_common::backtrace::__rust_begin_short_backtrace::h59e307ac7e33b6f0
  16:     0x55f1d5042aa6 - std::panicking::try::do_call::hd1b6f1c7cada29a0
  17:     0x55f1d5f0cdd9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  18:     0x55f1d5048357 - <F as alloc::boxed::FnBox<A>>::call_box::h4f2ae10a00f6affa
  19:     0x55f1d5f0096d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  20:     0x7f53b99b36da - start_thread
  21:     0x7f53b94c488e - __clone
  22:                0x0 - <unknown>
Thread 'IO Worker #2' panicked at 'specified instant was later than self', src/libstd/sys/unix/time.rs:298
This is a bug. Please report it at:
    https://github.com/paritytech/parity-ethereum/issues/new
2019-02-11 03:49:09 UTC Finishing work, please wait...

**Comment by oldcryptogeek** [comment]
After restart node is found to be fully synced and running normally.

**Comment by joshua-mir** [comment]
I'll close this, feel free to ask to reopen if you see this again (after making sure your system time is correct)
