### ISSUE TITLE
Problems performing Truffle migration on Tobalaba

### ISSUE THREAD

**Issue by dstreppa** [paritytech/parity-ethereum#10331]
- **Parity Ethereum version**: 2.3.0
- **Operating system**: Linux
- **Installation**: one-line installer 
- **Fully synchronized**: yes
- **Network**: tobalaba
- **Restarted**: yes

**steps to reproduce**
<pre>
# cd ~/run/truffle
# git clone https://github.com/JonathanWfels/ewf-dapptutorial
# cd ewf-dapptutorial
# truffle compile
# truffle migrate --network tobalaba
</pre>

Truffle info:
<pre>
queen@loki:~/run/truffle/ewf-dapptutorial$ truffle version
Truffle v4.1.15 (core: 4.1.15)
Solidity v0.4.25 (solc-js)
</pre>

**actual**
<pre>
queen@loki:~/run/truffle/ewf-dapptutorial$ truffle migrate --network tobalaba 
Using network 'tobalaba'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x43044bcfe49f89eeebd7ede30f35968f97a965983d6b928511bef8cda71cd4aa
  Migrations: 0x1e35a0fb557f05aee56782fe20ba1898a48b8511
Saving successful migration to network...
  ... 0xf93d7b0906cae068223d13af41c31bccaf36d9c3c3e039a9b87dff70b3aa7b40
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Block information is incomplete while ancient block sync is still in progress, before it's finished we can't determine the existence of requested item.
    at Object.InvalidResponse (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/queen/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
</pre>

**expected behavior**

Normal Truffle migration

<pre>
queen@loki:~/run/truffle/ewf-dapptutorial$ truffle migrate --network tobalaba 
Using network 'tobalaba'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x43044bcfe49f89eeebd7ede30f35968f97a965983d6b928511bef8cda71cd4aa
  Migrations: 0x1e35a0fb557f05aee56782fe20ba1898a48b8511
Saving successful migration to network...
  ... 0xf93d7b0906cae068223d13af41c31bccaf36d9c3c3e039a9b87dff70b3aa7b40
Saving artifacts...
Running migration: 2_deploy_contracts.js
	.....
Saving successful migration to network...
  ... 0x1234578....
Saving artifacts...
</pre>

Hi, I am pretty new with Parity and I am trying to deploy an example smart contract on Tobalaba. Unfortunately, when I launch the migration command I always have the aforementioned error, never seen with geth.
The first transaction [0xf93d7b0906cae068223d13af41c31bccaf36d9c3c3e039a9b87dff70b3aa7b40](https://tobalaba.etherscan.com/tx/0xf93d7b0906cae068223d13af41c31bccaf36d9c3c3e039a9b87dff70b3aa7b40) was successfully deployed, but then the same error always occured.

Can you help me please?

**Comment by joshua-mir** [comment]
While your node is in sync with the head of the chain and you should be able to transact with it normally, it is still performing "ancient block sync" and certain capabilities are restricted until that is complete.

To check the status, you can use this rpc call https://wiki.parity.io/JSONRPC-parity-module#parity_chainstatus - when there is no "blockGap" you will no longer see the error you are currently experiencing.

**Comment by dstreppa** [comment]
Thank you @joshua-mir for your fast answer. I've checked the sync:

<pre>
curl --data '{"method":"parity_chainStatus","params":[],"id":401697,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8547
{"jsonrpc":"2.0","result":{"blockGap":["0x63177","0x9f39b8"]},"id":401697}
</pre>

I tried more times and the gap values `{"blockGap":["0x63177","0x9f39b8"]} `never change. I expect to see the values changing :thinking:, instead they are fixed, like the sync is not running. is it normal?

**Comment by joshua-mir** [comment]
Not really... Can you try a restart?

**Comment by dstreppa** [comment]
I have restarted many times parity, but with no results

**Comment by dstreppa** [comment]
I've just done another restart, the curl response is always the same. Here the args of my launched parity, maybe they can help:
<pre>
/home/queen/.config/energyweb-ui/parity --chain tobalaba --jsonrpc-apis web3,eth,pubsub,net,parity,parity_pubsub,personal,traces,rpc,secretstore --jsonrpc-port 8547 --ws-port 8548 --no-ancient-blocks
</pre>

**Comment by joshua-mir** [comment]
> `--no-ancient-blocks`
... Well, that's probably why ancient block sync isn't progressing

**Comment by dstreppa** [comment]
Yeah, without that arg something is moving:

<pre>
$ curl --data '{"method":"parity_chainStatus","params":[],"id":401697,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8547
{"jsonrpc":"2.0","result":{"blockGap":["0x63f42","0x9f39b8"]},"id":401697}
$ curl --data '{"method":"parity_chainStatus","params":[],"id":401697,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8547
{"jsonrpc":"2.0","result":{"blockGap":["0x6409b","0x9f39b8"]},"id":401697}
</pre>

To understand better, this means that blocks in `[0x9f39b8-current]` are already synced and I have to wait the "old" part `[0x6409b","0x9f39b8]` before trying a new Truffle migration. Am I correct?

**Comment by joshua-mir** [comment]
Yep.

Ancient sync is much quicker than an ordinary sync however. Blocks are only verified for difficulty.

**Comment by dstreppa** [comment]
OK, thank you very much for your help. I will retry after the complete syncing.

**Comment by dstreppa** [comment]
Hi @joshua-mir. I've tried after the complete syncing and it works. Thank you very much again. I close the issue.
