### ISSUE TITLE
Where Parity client really execute the transactions of blocks in the source code?

### ISSUE THREAD

**Issue by bear987978897** [paritytech/parity-ethereum#10349]
- **Parity Ethereum version**: 2.4.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: private
- **Restarted**: no

I am studying parity-ethereum source code, and trying to figure out where the client really execute the transactions of blocks and change the state.

I found struct `Executive` is an instance of execution environment, and there is a method `transact` that can execute transactions.

I kept tracking, and found the `transact` method only be called in function `check_epoch_end_signal` in `ethcore/src/client/client.rs`.

But I think the transaction execution should directly related with state change or block verification, and `check_epoch_end_signal` seems not what I want, am I looking for the wrong place?

Can anybody give me some clues to figure it out?

**Comment by joshua-mir** [comment]
As far as I understand, the actual transaction execution is happening in https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/block.rs
