### ISSUE TITLE
Creating a website in Parity

### ISSUE THREAD

**Issue by ProyectsX** [paritytech/parity-ethereum#10363]
Creating a website in parity

How to create a website (.io-.net-.personal) using my Parity node.
what is the configuration to get a domain and see it while the node is working?

**Comment by joshua-mir** [comment]
@ProyectsX I'm not sure what you are describing here? Parity doesn't provide a web-facing frontend (anymore), only a few rpc endpoints.

**Comment by joshua-mir** [comment]
I'll close this issue since it doesn't seem relevant to parity-ethereum.
Please come say hi on gitter (gitter.im/paritytech/parity) if you have any additional questions 😅
