### ISSUE TITLE
parity export state only export at most 1000 storage keys

### ISSUE THREAD

**Issue by yxliang01** [paritytech/parity-ethereum#10370]
- **Parity Ethereum version**: master

**Expected behavior**

---
`parity export state` should output all storage keys for every deployed smart contracts. If this is not a good solution, the Parity wiki should have at least mentioned this.

**Actual behavior**

---

`parity export state` only outputs at most 1000 storage keys for every deployed smart contracts.

---

So, I am wondering where this "1000" come from. Was this number chosen randomly? Or, it has it's reasoning behind?

Related source code: https://github.com/paritytech/parity-ethereum/blob/af7dc3676b68a09f3024dbe4e2fc6237e40711a4/parity/blockchain.rs#L703

Related issue: https://github.com/paritytech/parity-ethereum/issues/10369

CC: @arkpar

**Comment by ordian** [comment]
I think it outputs 1000 keys *at a time*, not in total (see the loop)

**Comment by joshua-mir** [comment]
😅 Right, this was just a misreading
