### ISSUE TITLE
RPC call: disabling insufficient funds warning when sending transaciton

### ISSUE THREAD

**Issue by marko429** [paritytech/parity-ethereum#10379]
- **Parity Ethereum version**: 2.2.9
- **Operating system**: Linux
- **Installation**: archlinux 
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Hi, I am trying to send a transaction with a value greater than funds available via rpc call. Pretty much expected, I get back the "insufficient funds" error. I am wondering, however, if there is a way to suppress this error. The use case is sending several transactions, where prior transaction is expected to provide funds. Is there a way to do that? Thanks.

**Comment by joshua-mir** [comment]
@marko429 it doesn't look like there's a way to disable this check, as all transactions are verified before entering the txqueue.

**Comment by joshua-mir** [comment]
If you have more questions, please drop by the gitter channel (gitter.im/paritytech/parity)
