### ISSUE TITLE
Random shutdown under load

### ISSUE THREAD

**Issue by Pzixel** [paritytech/parity-ethereum#10380]
- **Parity Ethereum version**: 2.2.8
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

May be dupe of #10371 , but my logs differs a bit.

After fixing #10344 I tried to stress test my parity node. It worked like a charm until it just shutted down.

I started it as docker service which is not expected to finish but at some point it just exited.

I dumped 5GB log file and it ends with

```
... common logs with polling tx receipts as in mentioned issue
2019-02-19 12:13:56 UTC jsonrpc-eventloop-1 TRACE rpc  Request: {"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xff70959d8ffc98dc2791d4be49d5134115d9985c3e57d8f2082b98d39a1e4ead"]}.
2019-02-19 12:13:56 UTC jsonrpc-eventloop-0 TRACE rpc  Request: {"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x54c690e0e5245fb8d6de04c330d0008fb982d81c47fd92800a0f54be04b68305"]}.
2019-02-19 12:13:56 UTC jsonrpc-eventloop-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":null,"id":1}.
2019-02-19 12:13:56 UTC jsonrpc-eventloop-0 DEBUG rpc  Response: {"jsonrpc":"2.0","result":null,"id":1}.
2019-02-19 12:14:09 UTC main WARN parity_ethereum::run  Shutdown is taking longer than expected.
pthread lock: Invalid argument
./entrypoint.sh: line 2:     6 Aborted                 parity $@
```

The main point is that I didn't send any shutdown signals to the process. I just started the stress test and left my PC alone.

Docker logs shows following:

```
CONTAINER ID        IMAGE                              COMMAND                 CREATED             STATUS                        PORTS               NAMES
2253bc13438e        parity-poa-playground_authority0   "./entrypoint.sh --c…"  4 hours ago         Exited (134) 37 minutes ago                       parity-poa-playground_authority0_1
```

I'l try to create a brand new node again and repeat it there.

P.S. I understand that I provided almost no information, but this is because I have none. Logs looks innocent until it just quits. I'l provide any additional information, if required.

**Comment by Pzixel** [comment]
See https://github.com/paritytech/parity-ethereum/issues/10371#issuecomment-464789167

**Comment by joshua-mir** [comment]
I've marked this as a duplicate but won't close it unless we can confirm it's the same issue as #10371 - that issue has much more activity so it's probably where conversation about this should be focused.

**Comment by Pzixel** [comment]
I aggree. It might be different because I gatcher logs outside parity so I see these `pthread lock` and so on. After reading the whole linked thread I'm 99% sure it's the case. It has same symptoms, it also happend under high JSONRPC pressure... It's very likely to be the same issue.

**Comment by joshua-mir** [comment]
Alright, I'll close this for now. I'm already trying to gather eyes on that issue.
