### ISSUE TITLE
Kovan invalid blocks cripple nodes

### ISSUE THREAD

**Issue by seanturner83** [paritytech/parity-ethereum#10395]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.4
- **Operating system**: Linux
- **Installation**: released binary in Docker
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

Try to sync kovan with parity 2.3.4:

```
2019-02-21 14:50:43 UTC Stage 5 block verification failed for #10282918 (0x2a03…202f)
Error: Error(Block(InvalidStateRoot(Mismatch { expected: 0xd83515c8e80ca7c7a7378142e5b452049a48c1f55466e29c314060e0143d7590, found: 0xaa948a1adb093dbb8b6384b534cfa70e4ab5a6575fe88324e4afb0112b64f63f })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2019-02-21 14:50:43 UTC
Bad block detected: Error(Block(InvalidStateRoot(Mismatch { expected: 0xd83515c8e80ca7c7a7378142e5b452049a48c1f55466e29c314060e0143d7590, found: 0xaa948a1adb093dbb8b6384b534cfa70e4ab5a6575fe88324e4afb0112b64f63f })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

**Comment by joshua-mir** [comment]
Hey, this isn't new or unexpected behavior - I would first check whether you're on the right fork by looking at the blockhash of a successfully imported block, if you aren't you need to resync unfortunately - if you are on the right fork, a deleting your nodes.json and restarting *should* resolve this on the latest releases.

**Comment by seanturner83** [comment]
Will the fix differ for full/tracing nodes and normal warp/pruned nodes?

**Comment by joshua-mir** [comment]
The latest release has updated bootnodes, which is why this is *more likely* to be resolved by deleting your nodes.json - you start discovery again and should have less outdated peers giving you bad blocks.

**Comment by joshua-mir** [comment]
Let me know if you see this again and I will reopen this issue
