### ISSUE TITLE
Incorrect nonce when node creates a public transaction wrapping a private transaction

### ISSUE THREAD

**Issue by adetante** [paritytech/parity-ethereum#10390]
- **Parity Ethereum version**: master
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: Not applicable
- **Network**: private
- **Restarted**: yes

I'm testing Parity Ethereum’s private transactions feature.

I have a private contract successfully deployed. I want to make a state change for this private contract. I create a private transaction, signed by an External Owned Account (which has nonce = 0x1) by sending a signed tx to `private_sendTransaction` JSON-RPC endpoint.

Once validators signatures collected, the node creates a public transaction wrapping my private transaction. This public transaction is signed by `signer_account` configurated on this node. This `signer_account` has nonce = 0x0, but the public transaction crafted by the node has nonce = 0x1 caused by this piece of code:

https://github.com/paritytech/parity-ethereum/blob/master/ethcore/private-tx/src/lib.rs#L365-L371.

This implies that the public transaction is never executed.

I think this is not correct, node should use the current nonce value for `signer_account` and not the nonce from the original transaction?

**Comment by adetante** [comment]
With this fix [adetante@87761fd](https://github.com/adetante/parity-ethereum/commit/87761fd62fa288a361bf66530c191f8585ecef5b), the correct nonce is included in public transaction and the execution is OK

**Comment by grbIzl** [comment]
@adetante Great catch! We have never tested the scenario, when account signed the transaction is different from the account, which is creating the public transaction. From my point of view, this scenario is absolutely legit. I'll proceed with the review of PR
