### ISSUE TITLE
Use timestamp_checked_add in calc_next_timestamp in ethcore/src/engines/clique/block_state.rs

### ISSUE THREAD

**Issue by thefallentree** [paritytech/parity-ethereum#10409]
https://github.com/paritytech/parity-ethereum/blob/fcccbf3b756c89e81422f3d0d8d6d5c24927e72c/ethcore/src/verification/verification.rs#L51

as requested in review.

**Comment by joshua-mir** [comment]
Hey, it's probably not necessary to create issues for review feedback items you plan to address - that conversation should probably stay in the PR or in follow-up PRs 😅

(unless they are longer term issues you can't immediately address of course)

**Comment by soc1c** [comment]
is this resolved in #10383 ?

**Comment by niklasad1** [comment]
Fixed
