### ISSUE TITLE
[ethereum-types]: prefer `serde_json::to_string` over `format!` when converting to String

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-ethereum#10412]
I have benched the difference between `serde_json::to_string` vs `format!` and it appears that `serde_json` is 10 times faster (see below). 

So when you want a hex representation represented as `String` prefer `serde_json::to_string`, for examples [this](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/helpers/subscribers.rs#L40) should be replaced but there are many other places

```rustc
fn ser(h: H256) -> String {
    serde_json::to_string_pretty(&h).unwrap()
}

fn format(h: H256) -> String {
    format!("{:?}", h)
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("serde_json::ser", |b| b.iter(|| ser(H256::from(u64::max_value()))));
    c.bench_function("format!", |b| b.iter(|| format(H256::from(u64::max_value()))));
}
```

```bash
serde_json::ser       time:   [127.61 ns 128.17 ns 128.80 ns]                              
                        change: [-7.3356% -4.3934% -2.1108%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) high mild
  6 (6.00%) high severe

format!                 time:   [1.5287 us 1.5326 us 1.5368 us]                     
                        change: [-4.5861% -3.7062% -2.9010%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)

```

**Comment by debris** [comment]
I don't think we should pull `serde_json` everywhere just to display a string. Also, formatting is slower only because of parsing arguments of a `format!` macro. I don't really so the reason to do it. I also don't see where this optimization would be useful.

**Comment by niklasad1** [comment]
> I don't think we should pull `serde_json` everywhere just to display a string

Yeah, that makes sense to me

> I don't really so the reason to do it. I also don't see where this optimization would be useful

Ok, I don't understand what you mean exactly it is clearly faster. Do you mean that this `optimization` doesn't have any practical gain i.e, insignificant compared to other stuff?

Happy to close this if you can explain :P

**Comment by debris** [comment]
I believe the benchmark is created with wrong assumptions. 

We use hex representation only when we print out something to the console. Therefore the benchmark should look as follows:

```rust
format!("some comment, {:?}", h)
```

```rust
format!("some comment, {}", serde_json::to_string_pretty(h))
```

**Comment by niklasad1** [comment]
> We use hex representation only when we print out something to the console.

Yeah, I agree expect here https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/helpers/subscribers.rs#L40-#L42

BTW, I benched your example `serde_json` is still 6.5 faster (twice as slow with format!) now I'm getting a bit confused

**Comment by niklasad1** [comment]
Not a priority with these micro-benches ATM
