### ISSUE TITLE
Spec json is invalid: unknown field `eip170Transition`

### ISSUE THREAD

**Issue by stone212** [paritytech/parity-ethereum#10415]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.7
- **Operating system**: Linux
- **Installation**: binary
- **Fully synchronized**: yes
- **Network**: private blockchain
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After upgrading to 2.2.7 parity will not start on a private blockchain.

Error:

```
Spec json is invalid: unknown field `eip170Transition`, expected one of `accountStartNonce`, `maximumExtraDataSize`, `minGasLimit`, `networkID`, `chainID`, `subprotocolName`, `forkBlock`, `forkCanonHash`, `eip150Transition`, `eip160Transition`, `eip161abcTransition`, `eip161dTransition`, `eip98Transition`, `eip155Transition`, `validateChainIdTransition`, `validateReceiptsTransition`, `eip140Transition`, `eip210Transition`, `eip210ContractAddress`, `eip210ContractCode`, `eip210ContractGas`, `eip211Transition`, `eip145Transition`, `eip214Transition`, `eip658Transition`, `eip1052Transition`, `eip1283Transition`, `eip1283DisableTransition`, `eip1014Transition`, `dustProtectionTransition`, `nonceCapIncrement`, `remove_dust_contracts`, `gasLimitBoundDivisor`, `registrar`, `applyReward`, `nodePermissionContract`, `maxCodeSize`, `maxTransactionSize`, `maxCodeSizeTransition`, `transactionPermissionContract`, `transactionPermissionContractTransition`, `wasmActivationTransition`, `kip4Transition`, `kip6Transition` at line 33 column 21
```

The issue is related to https://github.com/paritytech/parity-ethereum/issues/10203 maybe but I put `eip170Transition` in the `params` section (also tried in the `Ethash` section).

**Comment by joshua-mir** [comment]
In parity-ethereum, for your chainspec eip170 is called `"maxCodeSize"` and the transition is `"maxCodeSizeTransition"`

Apologies that didn't click for me until now 😅

**Comment by stone212** [comment]
@joshua-mir This makes sense.  Thank you.

**Comment by stone212** [comment]
@joshua-mir Related question, why is eipTransion100 only acceptable in Ethash not params like all other params?

**Comment by joshua-mir** [comment]
Because eip-100 is related to how difficulty is calculated in ethash, which is only relevant to ethash 😅
