### ISSUE TITLE
how can I uninstall on ubuntu

### ISSUE THREAD

**Issue by qiluge** [paritytech/parity-ethereum#10413]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.0
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

while use one line install method to re-install, the cmd output is ```Upgrading parity from 2.2.0 to 2.2.11```, and the install completely, use cmd ```parity -v``` cat version is 2.2.0. And use 2.2.0, I cannot fully sync ropsten block, but in other machine, the 2.2.10 and 2.2.11 could sync block. So I want to upgrade parity but it always failed. If I can uninstall parity and re-install it? How can I uninstall parity?

**Comment by qiluge** [comment]
the 2.2.0 cannot sync block, the log is 
![image](https://user-images.githubusercontent.com/19525062/53319512-b117dd00-390d-11e9-90f6-cbeb4f1a796f.png)
the block height is always 5031823.

**Comment by qiluge** [comment]
should I remove /usr/bin/parity straightly?

**Comment by joshua-mir** [comment]
@qiluge - yes, feel free to do so. You can also use `which parity` to find out the location of the executable that is running if for some reason it isn't being installed correctly next time.

**Comment by qiluge** [comment]
But why cannot sync block data?

**Comment by joshua-mir** [comment]
Because there was a fork in ropsten, and version 2.2.0 did not support it. You should also wipe your local chaindata (`parity db kill --chain ropsten`) after updating because the bad chaindata is still present on your machine.

**Comment by qiluge** [comment]
OK , thank you very much. And there are another problem, use the command ```parity export  blocks  block.rlp``` and cannot export data in my normal parity (ropsten height is ).
![image](https://user-images.githubusercontent.com/19525062/53323045-1244ae00-3918-11e9-9479-1ed311f61572.png)

the block.rlp file is empty, 0 bytes.

**Comment by joshua-mir** [comment]
https://wiki.parity.io/CLI-Sub-commands#export-blocks export blocks / state requires you to sync with `fat-db` enabled. There should probably be an error message there, but the requirement is documented.

**Comment by qiluge** [comment]
Ok, thank you!

**Comment by joshua-mir** [comment]
Feel free to ask about anything else on gitter in the future (gitter.im/paritytech/parity)
