### ISSUE TITLE
Snapshot period is 5000 blocks - not 10000 as `--help` suggests

### ISSUE THREAD

**Issue by veox** [paritytech/parity-ethereum#10418]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.11-stable-8e31051c43-20190220/x86_64-linux-gnu/rustc1.32.0
- **Operating system**: Arch Linux
- **Installation**: `pacman` package manager
- **Fully synchronized**: irrelevant
- **Network**: irrelevant
- **Restarted**: irrelevant

[Here](https://github.com/paritytech/parity-ethereum/blob/v2.2.11/parity/run.rs#L69) ([same in `master`](https://github.com/paritytech/parity-ethereum/blob/master/parity/run.rs#L69)) sets it at 5000, but `--help` print-out suggests:

> ```
> Snapshot Options:
>     --no-periodic-snapshot
>         Disable automated snapshots which usually occur once every 10000 blocks.
> ```

**Comment by soc1c** [comment]
#6344
