### ISSUE TITLE
POA: chain id is not verified during transition submit

### ISSUE THREAD

**Issue by sh777** [paritytech/parity-ethereum#10411]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.7-stable
- **Operating system**: Linux
- **Installation**:  one-line installer 
- **Fully synchronized**:  yes
- **Network**: private-poa
- **Restarted**: no

Issue Description:
I build a private poa network with chainid other than ethereum's chainid 1. If I submit a transaction with a wrong chainid, for example chainid=1. A block will be created on the current node because chainid was not being verified during transition submittion. However this block will never being successfully boardcased to other nodes because verification will be failed during sync. Error log is:

 IO Worker #0 WARN client Stage 1 block verification failed for 0x9b03…9db9: Error(Transaction(InvalidChainId), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

I expected the wrong chainid transition will be rejected at the first place. Otherwise the chaindata on nodes are broken as this screen shot below: block height are not synced.

<img width="1352" alt="screen shot 2019-02-25 at 12 13 26 am" src="https://user-images.githubusercontent.com/5615648/53301813-48d7e580-3892-11e9-815a-31b4bb03c3e1.png">

**Comment by joshua-mir** [comment]
Thanks for this - it's definitely something we've noticed, do you have a minimal case you can share (ie, how you're submitting transactions, and your chain specification)?

**Comment by sh777** [comment]
@joshua-mir Thanks for quick response. I use MyCrypto to submit transition with wrong chainid. In MyCrypto, create a new network for your poa network(doesn't matter what chain id you configured, MyCrypto always send transition with chain id=1, this is MyCrypto's issue, and this is how I experienced this issue). Import your wallet. Submit a transfer and you will see what I described.  
The chain spec is irrelevant to this issue. You can always reproduce the issue with any kind of private poa network spec.
