### ISSUE TITLE
LruCache: provide `fn get(&self, &K) -> &V`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-ethereum#10434]
Our [LruCache](https://github.com/paritytech/parity-ethereum/blob/master/util/memory-cache/src/lib.rs) crate (which is a wrapper on top of another [other lrc-cache](https://crates.io/crates/lru-cache) doesn't provide the functionality to get an `immutable borrow` to the value which is quite annoying. 

Because the use case is often that the `LruCache` is stored in a `RwLock` where it forces to require `write()` on the `RwLock` which is more costly than `read()`

However, it might be painful to implement to because we use the API from [other lrc-cache](https://crates.io/crates/lru-cache) which doesn't provide `fn get(&self, &K) -> &V` and that would force to fork it or include all or functionality in `our` crate

**Comment by ordian** [comment]
In Least Recently Used cache strategy, on `get(key)` you need to make an update, that the key was used recently, hence the required mutability. Otherwise, we could replace recently used key when the cache is full. So this is an inherent limitation.

**Comment by niklasad1** [comment]
My bad it makes sense, missed that
