### ISSUE TITLE
Light client jsonrpc eth_gasPrice returning 0

### ISSUE THREAD

**Issue by tdrml** [paritytech/parity-ethereum#10437]
- **Parity Ethereum version**: 2.3.4-beta-0e95db1-20190220
- **Operating system**: Linux - Ubuntu 18.04.2 LTS
- **Installation**: one-line installer
- **Fully synchronized**: yes - light
- **Network**: ethereum
- **Restarted**: yes

running with following options: --light --jsonrpc-apis all --pruning archive

curl --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

**actual**
{"jsonrpc":"2.0","result":"0x0","id":1}

**expected behavior**
a result greater than 0.

**Comment by joshua-mir** [comment]
Hey, @tdrml is that the exact request you are sending?

**Comment by tdrml** [comment]
Hi, @joshua-mir here's my curl:

curl --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

**Comment by tdrml** [comment]
@joshua-mir FYI - after 24+ hours of returning 0, I am now getting 18gwei which is well above ethgasstation, but I understand that parity has an entirely different algo for calculating gas.

Looks like returning 0 is an intermittent issue.

**Comment by bejavu** [comment]
I have the same problem in my side-chain using parity clients:

```curl -s -X POST -H "Content-Type:application/json" -d '{"jsonrpc":"2.0","method":"eth_gasPrice", "params":[],"id":42}' https://rpc.fuse.io```
```{"jsonrpc":"2.0","result":"0x0","id":42}```

I am using this client:
`Parity-Ethereum//v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0`

**Comment by niklasad1** [comment]
Currently, we only read the local cache to get the gas_price when it is `outdated` and we return `0` but we should fetch the gas_price from the network instead
