### ISSUE TITLE
not enough ssd disk space

### ISSUE THREAD

**Issue by sasha14** [paritytech/parity-ethereum#10441]
I have 2tb ssd. I downloaded the blockchain with the --pruning archive option.
Disk space is over. The parameter --pruning-memory does not work. Parity Ethereum 2.3.4-beta.Win10.
Please tell me what to do?

**Comment by HCastano** [comment]
You might need to make sure that your `--db-path` is set to point to your SSD instead of another drive you have.

**Comment by sasha14** [comment]
Of course, the db-path is correct, I downloaded the whole blockchain. Here is my config.toml file

```
[parity]
base_path = "b:\\ethparity"
db_path = "b:\\ethparity\\chains"

[footprint]
db_compaction = "ssd"

[network]
port = 30303
min_peers = 1000
max_peers = 1000
```

File parity.bat
```
b:\ethparity\parity.exe --config "b:\ethparity\config.toml" --pruning-memory 1782579
pause
```
I want to maintain the blockchain network within 2tb. How do I cut the base? Why is the --pruning-memory option not working?

**Comment by joshua-mir** [comment]
@sasha14 you're running with `--pruning` set to archive, which is equivalent to an infinite `--pruning-history` (ie, *nothing is pruned!*) pruning-memory isn't relevant in this case. If you disable archival mode, you still need to resync/kill your db because parity won't do that for you.

**Comment by sasha14** [comment]
Thank. Do I have to delete this database on 2tb and sync again? Cut fail?
What parameters should I re-synchronize to maintain the base within 2tb?

**Comment by joshua-mir** [comment]
Yes, probably. `--pruning fast` (which is the default) should work (in other words, after deleting your existing db, your existing config should be fine).

If there was a specific reason you were running an archive node and you can't disable archive pruning, you're out of luck unfortunately.

**Comment by sasha14** [comment]
How much disk space will the database take with the --pruning fast option? Is this an easy client? I want a full node, but without an archive within 2tb.

Maybe I do not correctly cut the archive? How to do? Why am I out of luck?

**Comment by joshua-mir** [comment]
@sasha14 a a fast-pruned node is *still a full node*, but it only needs around 150 GB, not 2TB. If you want an *archive node, specifically* you are out of luck, because there is no way to make an *archive node* smaller.

**Comment by sasha14** [comment]
Is there a full node greater than 150GB but less than 2TB? I just want to support the network with a full node.

**Comment by joshua-mir** [comment]
Archive nodes don't support the network any more than ordinary pruned nodes do. If you want to increase your disk usage for the sake of increasing your disk usage, then you can run with `--fat-db` which allows you to export blocks or state separately, but little more than that 😅 If you have more questions like this we should probably move this conversation to the gitter channel (gitter.im/paritytech/parity)
