### ISSUE TITLE
2.2.10 can not synchronize to the latest block

### ISSUE THREAD

**Issue by zerochl** [paritytech/parity-ethereum#10460]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.10
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: Yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by joshua-mir** [comment]
Answered on gitter
