### ISSUE TITLE
Thread panic and shutdown

### ISSUE THREAD

**Issue by paulkeogh** [paritytech/parity-ethereum#10463]
Parity:  version Parity-Ethereum/v2.2.11-stable-8e31051-20190220/x86_64-linux-gnu/rustc1.32.0
Linux
One line installer
Fully synched
Ethereum
No restart - shutdown

Running with websockets RPC provider

====================

stack backtrace:
   0:     0x55586836375d - <no info>
   1:     0x555868362882 - <no info>
   2:     0x555868361a36 - <no info>
   3:     0x555866b462d8 - <no info>
   4:     0x5558683d5ff9 - <no info>
   5:     0x5558683d5ce4 - <no info>
   6:     0x5558683e0f68 - <no info>
   7:     0x5558683cffda - <no info>
   8:     0x555866a3ece9 - <no info>
   9:     0x555867543c24 - <no info>
  10:     0x55586752d15f - <no info>
  11:     0x55586752d586 - <no info>
  12:     0x5558683ecaa9 - <no info>
  13:     0x555867532e67 - <no info>
  14:     0x5558683e063d - <no info>
  15:     0x7f476a0456b9 - <no info>
  16:     0x7f4769b6541c - <no info>
  17:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'specified instant was later than self', src/libstd/sys/unix/time.rs:298

**Comment by joshua-mir** [comment]
@paulkeogh please update to the latest stable, this issue was already fixed in #10423
