### ISSUE TITLE
Unable to sync properly

### ISSUE THREAD

**Issue by ye21st** [paritytech/parity-ethereum#10485]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity Ethereum 2.3.5-stable
- **Operating system**: Windows 7
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**:  yes

_I waited for one morning, the snapshot part has been stuck at 103 and has not moved._

![image](https://user-images.githubusercontent.com/17704719/54580061-5a4f8000-4a41-11e9-8f68-9085e4624784.png)

**Comment by joshua-mir** [comment]
@ye21st can you try running with `--warp-barrier`? That said the current set of testnets probably shouldn't be synced with warp-sync at all at the moment, try `--no-warp` if you want to be sure you'll sync with the chain, but are willing to wait.

**Comment by ye21st** [comment]
I don't understand how to run。
I am running like this now. `F:\Wallet\Parity\parity.exe --config config-work.toml`

**Comment by joshua-mir** [comment]
`F:\Wallet\Parity\parity.exe --config config-work.toml --warp-barrier 5220000` or `F:\Wallet\Parity\parity.exe --config config-work.toml --no-warp` or edit config-work.toml and add:
```
[network]
warp = false
```
or 
```
[network]
warp_barrier = 5220000
```

**Comment by ye21st** [comment]
Ok, let me try it, thank you.

**Comment by ye21st** [comment]
This way, I tested it or stopped syncing the snapshot.

![image](https://user-images.githubusercontent.com/17704719/54595566-d95aad80-4a6d-11e9-8115-408c85eb5609.png)

**Comment by joshua-mir** [comment]
Try increasing or decreasing the blocknumber next to warp-barrier by 10000 - also, `syncing snapshot` should be relatively quick, so you shouldn't leave it running overnight. If you keep seeing this issue, you might want to replace `--warp-barrier ` with `--no-warp`

**Comment by ye21st** [comment]
This problem exists when I sync to a certain block. Is this normal?
![image](https://user-images.githubusercontent.com/17704719/54860341-a22d1a80-4d53-11e9-9dd4-620da9f9f015.png)

**Comment by joshua-mir** [comment]
There are certain blocks that are problematic to sync past unless you have significant resources on your machine, the fact you are trying to sync past them means that you set warp-barrier too low 😅

**Comment by ye21st** [comment]
Thank you, I will try it.

**Comment by ye21st** [comment]
![image](https://user-images.githubusercontent.com/17704719/54893656-c4f53580-4ef1-11e9-8a6f-1da932b006b3.png)
![image](https://user-images.githubusercontent.com/17704719/54893673-d5a5ab80-4ef1-11e9-9d32-dd47045987f4.png)
When I sync for a while, why does the console output more blocks than the block browser? Moreover, after a period of synchronization, the number of blocks will fall back to 275W. What is the reason?

**Comment by joshua-mir** [comment]
If you are warp syncing, after syncing with the head of the chain, you will begin downloading blocks before the warp-snapshot you synced too, that does not mean that you "went back", this process simply happens in the background of the nodes ordinary operation. If you have more questions, can you please ask in gitter.im/paritytech/parity?
