### ISSUE TITLE
stack backtrace

### ISSUE THREAD

**Issue by kxylxx** [paritytech/parity-ethereum#10499]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: stable
- **Operating system**:  MacOS 
- **Installation**: homebrew 
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Thread 'IO Worker #3' panicked at 'Cannot operate with an empty validator set.', ethcore/src/engines/validator_set/simple_list.rs:97

**Comment by joshua-mir** [comment]
Hey, you probably need to properly fill out your chain specification
