### ISSUE TITLE
Sha3/keccak256 hash calculation for binaries broken

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ethereum#10495]
The `sha3` hashes are calculated using `rhash --sha3-256` on linux, which is not what we wanted.
https://github.com/paritytech/parity-ethereum/commit/bceb883d9982780bc2b9cf582067fc0a18149a12#diff-73c06eb2ec63acc45dbb849c43b55f08R50

We should change the extension to `.keccak256` and produce correct hashes to avoid confusion.
Note the windows build is actually computing correct hash.

**Comment by General-Beck** [comment]
https://github.com/paritytech/parity-ethereum/pull/10509
