### ISSUE TITLE
NaN in log. High iowait

### ISSUE THREAD

**Issue by ds414** [paritytech/parity-ethereum#10501]
- **Parity Ethereum version**: Parity-Ethereum/v2.3.7-stable-7d1415a-20190320/x86_64-linux-gnu/rustc1.33.0
- **Operating system**: Ubuntu 18.04.2 LTS
- **Installation**: Downloaded Bin, started as service systemd
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Hardware**: AWS EC2, 8vCPU, 32G RAM, EBS (SSD gp2)
- **config.toml:**
> [parity]
> chain = "ethereum"
> base_path = "/etc/parity/data"
> [network]
>min_peers = 25
>max_peers = 50
>[footprint]
>pruning = "archive"
>[rpc]
>interface = "all"
>[misc]
>logging = "rpc=info"
>log_file = "/var/log/parity.log"

After full sync Parity worked fine fine several hours (~10-15) but after iotime suddenly increased (~50%) and in log messages have appeared "NaN" values, example:

>2019-03-21 05:27:01 UTC Syncing #7410248 0xd1d9…4ac6      NaN blk/s    NaN tx/s    NaN Mgas/s      0+   64 Qed  #7410309   26/50 peers      2 KiB chain   18 MiB db    6 MiB queue   43 KiB sync  RPC:  0 conn,    1 req/s,   21 µs
>2019-03-21 05:27:01 UTC Syncing #7410248 0xd1d9…4ac6      NaN blk/s    NaN tx/s    NaN Mgas/s      0+   64 Qed  #7410309   26/50 peers      2 KiB chain   18 MiB db    6 MiB queue   43 KiB sync  RPC:  0 conn,    1 req/s,   21 µs
>2019-03-21 05:27:01 UTC Snapshot: 188358 accounts 5000 blocks 133308474 bytes
>2019-03-21 05:27:01 UTC Syncing #7410248 0xd1d9…4ac6      NaN blk/s    NaN tx/s    NaN Mgas/s      0+   64 Qed  #7410309   26/50 peers      2 KiB chain   18 MiB db    6 MiB queue   43 KiB sync  RPC:  0 conn,    1 req/s,   21 µs
>2019-03-21 05:28:22 UTC Syncing #7410248 0xd1d9…4ac6     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   68 Qed  #7410313   26/50 peers    521 KiB chain   18 MiB db    6 MiB queue   43 KiB sync  RPC:  0 conn,    0 req/s,   21 µs
>2019-03-21 05:28:22 UTC Snapshot: 215089 accounts 5000 blocks 136626164 bytes

Peers count decrease to 0 and node has lag in block number.
After restart node work fine several hours again.

How can this problem be solved?

**Comment by joshua-mir** [comment]
@ds414 has this ever reoccured? I have never seen this other than in your report. Can you try with a recent version and let me know whether you still see it?
