### ISSUE TITLE
Could you publish `https://github.com/paritytech/bn` to crates.io?

### ISSUE THREAD

**Issue by gravitydaze** [paritytech/parity-ethereum#10500]
Hi, guys in paritytech, I used [https://github.com/paritytech/bn](https://github.com/paritytech/bn) as a dependency(It's really awesome!) in my lib, but the sad thing is that I could not publish my lib to crates.io because `bn` is not in `crates.io`.

Although I can copy the whole repo in my lib, but I really hope that you can public it at crates.io.

**Comment by gravitydaze** [comment]
`https://github.com/paritytech/bn` saved me a lot of time, It's really really good :)

**Comment by joshua-mir** [comment]
(cc @NikVolf)

**Comment by joshua-mir** [comment]
@gravitydaze the crate you're looking for is https://github.com/zcash-hackworks/bn
