### ISSUE TITLE
Invalid Snappy messages from Parity

### ISSUE THREAD

**Issue by tkstanczak** [paritytech/parity-ethereum#10515]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.7
- **Operating system**: Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

We experience invalid Snappy messages from Parity. Have you seen that reported in the past?

2019-03-23 19:24:20.2678|DEBUG|21|Error in communication with Parity-Ethereum/v2.2.7-stable-b00a21f-20190115/x86_64-linux-gnu/rustc1.31.1: DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown. ---> System.IO.InvalidDataException: Input is not a valid snappy-compressed block

**Comment by tkstanczak** [comment]
Can provide much more details - just trying to feel if you ever have this problem with other peers?

**Comment by joshua-mir** [comment]
Hey, could you please clarify what is communicating with Parity that is giving this output, and what transport this is over?

You aren't getting this message from parity, you're getting it from whatever you are talking to parity using.
