### ISSUE TITLE
parity PoA crashed

### ISSUE THREAD

**Issue by Edwin-L** [paritytech/parity-ethereum#10517]
- **Parity Ethereum version**: 2.3.5
- **Operating system**: Linux (Ubuntu 18.04)
- **Installation**: direct download binary
- **Fully synchronized**: not sure
- **Network**: localhost
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I followed the instruction in the "Demo PoA tutorial" https://wiki.parity.io/Demo-PoA-tutorial and setup 2 nodes on the same computers. They crashed soon after I connected the 2 nodes. Attached are the relevance config files & output logs.
[node0.log](https://github.com/paritytech/parity-ethereum/files/3001282/node0.log)
[node1.log](https://github.com/paritytech/parity-ethereum/files/3001284/node1.log)
[node0.toml.txt](https://github.com/paritytech/parity-ethereum/files/3001285/node0.toml.txt)
[node1.toml.txt](https://github.com/paritytech/parity-ethereum/files/3001286/node1.toml.txt)
[nodes.json.txt](https://github.com/paritytech/parity-ethereum/files/3001288/nodes.json.txt)

**Comment by joshua-mir** [comment]
```

====================

stack backtrace:
   0:     0x564bfa470b3d - <no info>
   1:     0x564bfa46fc62 - <no info>
   2:     0x564bfa46ee16 - <no info>
   3:     0x564bf8c3f228 - <no info>
   4:     0x564bfa4e1319 - <no info>
   5:     0x564bf9b79594 - <no info>
   6:     0x564bf99ed571 - <no info>
   7:     0x564bf9bb160c - <no info>
   8:     0x564bf9b45b09 - <no info>
   9:     0x564bf9baf32c - <no info>
  10:     0x564bf99a3a1c - <no info>
  11:     0x564bf98e0648 - <no info>
  12:     0x564bf990485c - <no info>
  13:     0x564bf99b5a0c - <no info>
  14:     0x564bf9a7f5a2 - <no info>
  15:     0x564bf98fcfc6 - <no info>
  16:     0x564bf9a80387 - <no info>
  17:     0x564bf9a80041 - <no info>
  18:     0x564bf9a7f3fa - <no info>
  19:     0x564bf9a7fa54 - <no info>
  20:     0x564bf98fcc75 - <no info>
  21:     0x564bf99e976c - <no info>
  22:     0x564bf98eb64e - <no info>
  23:     0x564bf9b79b06 - <no info>
  24:     0x564bfa4f7dc9 - <no info>
  25:     0x564bf9ab5be7 - <no info>
  26:     0x564bfa4eb95d - <no info>
  27:     0x7fe9517cc6da - <no info>
  28:     0x7fe9512dd88e - <no info>
  29:                0x0 - <no info>

Thread 'IO Worker #3' panicked at 'Cannot operate with an empty validator set.', ethcore/src/engines/validator_set/simple_list.rs:97
```

**Comment by Edwin-L** [comment]
I downloaded the latest stable version(2.3.8), deleted the whole data directories and start from scratch. Now it seems to be fine.

**Comment by joshua-mir** [comment]
I'm assuming you won't be able to replicate this anymore. Let me know if you see this again and I will reopen.
