### ISSUE TITLE
I would like to get listtransactions for ether like in bitcoin.

### ISSUE THREAD

**Issue by malenchelon** [paritytech/parity-ethereum#10518]
![Screenshot 2019-03-25 at 5 55 51 PM](https://user-images.githubusercontent.com/16664028/54919929-00125b80-4f28-11e9-9206-252370245867.png)
![Screenshot 2019-03-25 at 5 56 22 PM](https://user-images.githubusercontent.com/16664028/54919936-01dc1f00-4f28-11e9-9e04-bb6ee7ff2384.png)

_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.8
- **Operating system**: Linux
- **Installation**:  one-line installer 
- **Fully synchronized**: yes
- **Network**:  kovan 
- **Restarted**: yes
-** Version Type ** : Light

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

i would like to get the list of transactions that happened in the local parity server. i just installed parity in my linux server and started it using light with rpcapis=safe. and got 1 ether from kovan testnet faucet into my server. 

i tried parity_localTransactions,parity_allTransactions,parity_allTransactionHashes for getting the list of transactions happened in my server. im unable to see them. Please help

**Comment by joshua-mir** [comment]
Parity doesn't keep track of exactly which transactions it has historically made after they are included in the blockchain. The methods you've mentioned query *future transactions* that are still in the queue, not past transactions that are already included in the blockchain.

**Comment by malenchelon** [comment]
I too studied but the future transactions method but is deprecated in favour of parity_allTransactions. so i tried that method but didn't get any list.

**Comment by joshua-mir** [comment]
I'm saying that the methods you mentioned all query pending transactions exclusively, there is no method to query historical transactions done via your node.

**Comment by malenchelon** [comment]
Okay. i even tried the methods while the transaction is in queue but didn't get any result. it just gave empty.

**Comment by malenchelon** [comment]
Hello! i would like to get the incoming transactions happening in my server ! what is the best rpc call ???

**Comment by joshua-mir** [comment]
The most reliable method would probably be to enable `--logging rpc` (or `txqueue` or `txpool`) and to parse your logs for transactions. Kovan has a very fast blocktime and you likely aren't an authority so there's probably a high rate of churn of transactions coming into your node and being culled virtually immediately.

**Comment by malenchelon** [comment]
so you want me to start parity with -l (--logging=[logging])?

**Comment by joshua-mir** [comment]
Yes, and have some method to parse your logs. You can query your logs over rpc with https://wiki.parity.io/JSONRPC-parity-module#parity_devlogs if that's more convenient.

**Comment by malenchelon** [comment]
is there any other way to check the incoming transactions to my server other than via any rpc call or something

**Comment by joshua-mir** [comment]
@malenchelon I'm not sure what you mean - we don't have the feature you want - I recommended parsing logs do what you are describing, and you can get those logs via rpc or your command line. lmk if you want me to reopen this as a feature request.

**Comment by gituser** [comment]
@malenchelon yes you can.

Use `trace_filter` RPC call and start parity with `--tracing=on` and `trace` json-rpc subsystem enabled.

Check more about trace module here: https://wiki.parity.io/JSONRPC-trace-module#trace_filter

**Comment by joshua-mir** [comment]
@malenchelon this is now implemented in #10558
