### ISSUE TITLE
Parity Syncing stuck at certain block number

### ISSUE THREAD

**Issue by thotheolh** [paritytech/parity-ethereum#10516]
An Ethereum Parity node I am running on v2.3.8 is consistently stuck at syncing a particular block number. Is this a bug and what can I do to fix it ?

Ethereum Parity: Parity Ethereum
  version Parity-Ethereum/v2.3.8-stable-a39aaac-20190322/x86_64-linux-gnu/rustc1.33.0

Linux: Linux 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Syncing Command: /usr/bin/parity --light --cache-size=16 --log-file=/root/parity/parity.log --no-secretstore

Log:
Mar 24 03:55:06 parity-01 parity[4861]: 2019-03-24 03:55:06 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  30/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    3 req/s,   22 µs
Mar 24 03:55:11 parity-01 parity[4861]: 2019-03-24 03:55:11 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  30/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    2 req/s,   21 µs
Mar 24 03:55:16 parity-01 parity[4861]: 2019-03-24 03:55:16 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  29/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    2 req/s,   21 µs
Mar 24 03:55:21 parity-01 parity[4861]: 2019-03-24 03:55:21 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  30/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    3 req/s,   30 µs
Mar 24 03:55:26 parity-01 parity[4861]: 2019-03-24 03:55:26 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  30/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    3 req/s,   30 µs
Mar 24 03:55:31 parity-01 parity[4861]: 2019-03-24 03:55:31 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  29/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    2 req/s,   29 µs
Mar 24 03:55:36 parity-01 parity[4861]: 2019-03-24 03:55:36 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  29/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    2 req/s,   26 µs
Mar 24 03:55:41 parity-01 parity[4861]: 2019-03-24 03:55:41 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  29/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    5 req/s,   25 µs
Mar 24 03:55:46 parity-01 parity[4861]: 2019-03-24 03:55:46 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  31/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    3 req/s,   25 µs
Mar 24 03:55:51 parity-01 parity[4861]: 2019-03-24 03:55:51 UTC Syncing #7289999 0x2cf8…27b4     0.0 hdr/s      0+    0 Qed  33/50 peers     37 KiB cache  0 bytes queue  RPC:  0 conn,    3 req/s,   28 µs

**Comment by joshua-mir** [comment]
`--cache-size 16` is probably the source of your problem. That denotes 16kb of cache which means that you are basically doing everything directly from on-disk, that will be too slow to do anything useful.
