### ISSUE TITLE
Parity 2.3.8-stable malicious windows binary

### ISSUE THREAD

**Issue by marriva** [paritytech/parity-ethereum#10523]
Hi 

KAV detected the malware in Parity 2.3.8-stable windows binary
![image](https://user-images.githubusercontent.com/11379362/54984936-f0932100-4fc0-11e9-9ca6-b9ed1686a20b.png)

https://releases.parity.io/ethereum/v2.3.8/x86_64-pc-windows-msvc/parity.exe
sha-256 76b431c7571cdf0cc4dde2a05ea4395fa3d0091424f879e0685dc42b568f29a6

Could you check this please?

**Comment by joshua-mir** [comment]
@marriva this is a false-positive I've seen before. If you look up that specific threat name, you'll quickly see the virus Kaspersky claims is infecting parity is completely unrelated.
