### ISSUE TITLE
Clean up chain specs and network configurations

### ISSUE THREAD

**Issue by soc1c** [paritytech/parity-ethereum#10522]
```
network    sync   connections   result   comment
---------------------------------------------------
poasokol   warp      7 peers    pass
kotti      full      5 peers    pass     no snapshot peers
goerli     full      5 peers    pass     no snapshot peers
rinkeby    full     16 peers    pass     deprecated / no snapshot peers
kovan      warp     10 peers    pass     deprecated
ropsten    warp     12 peers    pass     deprecated
morden     warp      4 peers    pass     deprecated
callisto   full     25 peers    pass     no snapshot peers
mix        warp     10 peers    pass
social     none     no peers   *fail*    scam according to bitcointalk / inactive according to coingecko
easthub    none     no peers   *fail*    website down / github inactive for 1 year
ellaism    warp      7 peers    pass
musicoin   warp      7 peers    pass
expanse    warp     20 peers    pass	
tobalaba   warp      8 peers    pass
poacore    full      2 peers    pass     can't seem to find more peers / no snapshot peers
classic    warp      9 peers    pass
ethereum   warp     25 peers    pass
```

**Comment by soc1c** [comment]
after #9981

**Comment by soc1c** [comment]
### Callisto #9534

> `callisto   full     25 peers    pass     no snapshot peers`

@yograterol are you guys operating any parity-ethereum bootnodes that could generate snapshots?

### POA Network #9413

> `poacore    full      2 peers    pass     can't seem to find more peers / no snapshot peers`

@phahulin do you have some updated bootnodes for us?

### Clique chains #9981 

> `kotti      full      5 peers    pass     no snapshot peers`
> `goerli     full      5 peers    pass     no snapshot peers`

@fevo1971 can you help me checking if our clique bootnodes generate snapshots (checking the logs, checking if there is a snapshot on disk)

**Comment by phahulin** [comment]
@soc1c thanks for reaching out.
  * for POA Core list is unchanged,
  * for POA Sokol please update to [this list](https://github.com/poanetwork/poa-chain-spec/blob/sokol/bootnodes.txt)
