### ISSUE TITLE
Return block.nonce when engine is clique

### ISSUE THREAD

**Issue by mpetrunic** [paritytech/parity-ethereum#10534]
- **Parity Ethereum version**: clique-v5
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: goerli

Since for clique block.nonce field is used for voting, it would be useful to get it with `eth_getBlockByHash` or `eth_getBlockByNumber`. Currently that field is excluded from response since it's not needed for rest of POA networks. (https://wiki.parity.io/JSONRPC-eth-module#eth_getblockbyhash)

**Comment by jleni** [comment]
This could be possible through the changes I've been working on to expose Clique in the REST API.
At the moment, this involves some refactoring in the Clique engine that is part of that PR.
