### ISSUE TITLE
PARITY WILL NOT OPEN, NO WEB SITE, NO WALLET. FUNDS ALL LOST 

### ISSUE THREAD

**Issue by Jkennedy160** [paritytech/parity-ethereum#10538]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I AM ON A DIFFERENT COMPUTER, Dont know the versions and DONT CARE. All my fucking funds are on Parity and when i double click the icon NOTHING HAPPENS. The website used to open right up with my wallet, NOW NOTHING. I FUCKING UNINSTALLED IT AND REINSTALLED IT AND IT DID NOTHING. I HAVE NO IDEA WHAT THE FUCK TO DO. HOW THE FUCK DO I GET MY FUNDS BACK NOW

**Comment by Jkennedy160** [comment]
ANYONE???????

**Comment by Jkennedy160** [comment]
This is absolutely NO SUPPORT from this wallet is there huh??

**Comment by soc1c** [comment]
Hi! Of course, there is! You can just use your backups with https://mycrypto.com or https://myetherwallet.com or import it into https://metamask.io

**Comment by Jkennedy160** [comment]
> 
> 
> Hi! Of course, there is! You can just use your backups with https://mycrypto.com or https://myetherwallet.com or import it into https://metamask.io

No idea how I can access my Parity account from those sites.

**Comment by Jkennedy160** [comment]
This is literally ridiculous. I deleted the whole Parity and now when I re download it just opens up some stupid DOS window. WHERE THE FUCK DO I SEE MY WALLET ON PARITY???

**Comment by joshua-mir** [comment]
@Jkennedy160 there's a file path here: https://wiki.parity.io/Parity-Wallet#view-and-send-ether-and-tokens that will show you where your keyfile should be. You can load your keyfile on one of the wallets mentioned on that page as well

**Comment by Jkennedy160** [comment]
> 
> 
> @Jkennedy160 there's a file path here: https://wiki.parity.io/Parity-Wallet#view-and-send-ether-and-tokens that will show you where your keyfile should be. You can load your keyfile on one of the wallets mentioned on that page as well
Parity UI!!!! Thats what I needed!! Thank you thank you thank you, you beautiful man! Got that up and running and recovered my account from the phrase work and now i'm back in business!! THANK YOU AGAIN!!!
