### ISSUE TITLE
could not run git clone https://github.com/paritytech/parity-ethereum .. it cause hang for hours

### ISSUE THREAD

**Issue by saarshah** [paritytech/parity-ethereum#10539]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.4.3 (actually I have installed rustup (stable-x86_64-unknown-linux-gnu unchanged - rustc 1.33.0 (2aa4c46cf 2019-02-28)) 
- **Operating system**: Ubuntu 18
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**: local
- **Restarted**: no 

I just download a rust project (my_rust_project) and try to apply Clippy
Then I run cargo clean --> run cargo clippy into my own project it will cause following error (hang for long hours)
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: failed to load source for a dependency on `panic_hook`

Caused by:
  Unable to update https://github.com/paritytech/parity-ethereum#9519493e

Caused by:
  failed to fetch into /home/amir/.cargo/git/db/parity-ethereum-207188a8f2c4d794

Caused by:
  process didn't exit successfully: `git fetch --tags --quiet --update-head-ok 'https://github.com/paritytech/parity-ethereum' 'refs/heads/*:refs/heads/*'` (exit code: 128)

**Comment by joshua-mir** [comment]
Answered on gitter as well, but this is probably just a temporary issue with your (or github's) network connection.

**Comment by saarshah** [comment]
Yes I solved it ... As I am in China and due to restriction of internet...  I just run VPN then it works very well .. Thanks for your time..
