### ISSUE TITLE
Subscribing to events in pending block does not work.

### ISSUE THREAD

**Issue by ethernomad** [paritytech/parity-ethereum#10541]
- **Parity Ethereum version**: Parity-Ethereum/v2.4.3-beta-33860c3-20190322/x86_64-linux-gnu/rustc1.33.0
- **Operating system**: Linux
- **Installation**: Binary download from GitHub
- **Fully synchronized**: yes
- **Network**: MIX
- **Restarted**: yes

With Geth if I subscribe to a contract event in block 'pending' I get notified as soon as the node receives the transaction that creates the event.

I have configured Parity for the pending block to be updated on every transaction, but the event still does not occur until the transaction is mined.

```
./parity --chain mix.json --force-sealing --infinite-pending-block --reseal-on-txs=all --reseal-min-period=0
```

I think I saw another issue about this, but can't find it now.

**Comment by joshua-mir** [comment]
I don't believe we store event logs from the pending block until the block is actually included in the chain.

**Comment by weilbith** [comment]
Could it be that this has changed in the past?
