### ISSUE TITLE
How to enable multi thread/core cpu for process JSON RPC Batch request

### ISSUE THREAD

**Issue by biigpongsatorn** [paritytech/parity-ethereum#10556]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.4.3-beta
- **Operating system**: / Linux
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi, I have some questions.

1. I want to config the Parity node for proceeding a lot of request from web3.js with [batchRequest](https://web3js.readthedocs.io/en/1.0/web3-eth.html#batchrequest) (around 20K batch items)

example code.
```js
const contract = new web3.eth.Contract(abi, address);
const blockNumber = 7483576

const batch = new web3.BatchRequest();

// Has batch item like this around ~20,000 items
batch.add(web3.eth.call.request(
{
   to: '0x96B610046D63638d970E6243151311d8827D69a5',
   data: `0xd38d2bea00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000000`
},
blockNumber,
(err, data) => {
   console.log(data)
}));

batch.execute();
console.log("done !")
```

2. And currently, I run the Parity node via this command
`parity --jsonrpc-apis=all --jsonrpc-interface=all --ws-interface=all --jsonrpc-threads=8 --jsonrpc-server-threads=100`

3. I just try to run my code on my computer. It's so slow for responding from the Parity node.

4. I see the CPU workload on my Parity node that process with a single core.
![image](https://user-images.githubusercontent.com/10693658/55398308-67f12380-5572-11e9-9eec-ece26a106cc4.png)

My question is "how to config parity node to allocate CPU for processing thease requests?"

Ps. I use AWS EC2 `c5.2xlarge` instance type  to run the Parity node.
![image](https://user-images.githubusercontent.com/10693658/55398378-8fe08700-5572-11e9-9f86-751acdbbb9f6.png)

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html#cpu-options-supported-instances-values

**Comment by joshua-mir** [comment]
@biigpongsatorn `--jsonrpc-server-threads` is what you want but setting it to `100` will do nothing useful as your system likely does not have that many threads, this might be related to what you are seeing but at the moment parity handles one request per thread at a time - which means that your entire batch request is handled on a single thread. If you want to split your request over multiple threads, send multiple requests. `--jsonrpc-threads` currently does nothing.

**Comment by biigpongsatorn** [comment]
@joshua-mir  Thanks for your answer.

I tried to send multiple batch request to my node. The node works better but the node still takes time to process more than I want.

I will try another way to solve my issue.

Thank you.
