### ISSUE TITLE
Building from source always results in unstable version reported

### ISSUE THREAD

**Issue by gituser** [paritytech/parity-ethereum#10564]
- **Parity Ethereum version**: 2.3.9
- **Operating system**: inux
- **Installation**: built from source
- **Fully synchronized**: doesn't matter
- **Network**: doesn't matter
- **Restarted**: doesn't matter

```
./parity-v2.3.9-unstable-0b42826-20190401 --version
Parity Ethereum
  version Parity-Ethereum/v2.3.9-unstable-0b42826-20190401/x86_64-linux-gnu/rustc1.33.0
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

I build parity with cargo:

```
#update rust first
rustup update
git submodule init
git submodule update

#clean old files
cargo clean

#build
cargo build --release
```

Any idea why it's reporting unstable instead of stable?

Whilst there is clearly `stable` in the `util/version/Cargo.toml`:
```
$ grep track util/version/Cargo.toml 
# This versions track. Should be changed to `stable` or `beta` when on respective branches.
track = "stable"
# Indicates a critical release in this track (i.e. consensus issue).
```

**Comment by joshua-mir** [comment]
If you want to build stable, you need to check out the stable branch before building - master is always unstable/nightly

**Comment by gituser** [comment]
I do checkout `git checkout tags/v2.3.9`

It should also report properly?

**Comment by soc1c** [comment]
You need to enable the final feature.

```
cargo build --release --features final
```

**Comment by joshua-mir** [comment]
`tags/v2.3.9` is not equivalent to `stable` - you can go through the commits on the stable branch to find the version you are looking for 😅

**Comment by gituser** [comment]
> You need to enable the final feature.
> 
> ```
> cargo build --release --features final
> ```

Cheers, this did it!
