### ISSUE TITLE
High Importing Time.

### ISSUE THREAD

**Issue by uurcm16** [paritytech/parity-ethereum#10573]
- **Parity Ethereum version**: 2.3.9 stable
- **Operating system**: Ubuntu 18.04
- **Installation**:
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yeah

Hi there,

I'm trying to run Ethereum Blockchain (mainnet) on Ubuntu 18.04, 32 Core 2 x Xeon processor, 64 GB Ram.

At first, Parity was importing blocks in around 400-900 ms. 

No Raid, Single 512GB SSD, Screenshot => [http://prntscr.com/n8z48c](http://prntscr.com/n8z48c)

I tought that the bottleneck is the disk. Because CPU loads are too low. 
This server has 3 x 512 GB Samsung Pro SSDs and I've created **RAID 0** (with `mdadm`) with 2 disks, and the results are the same.

Raid 0, 2 x 512 GB SSD, Screenshot => [http://prntscr.com/n8z7su](http://prntscr.com/n8z7su)

Here is the commands : `./parity --chain mainnet --db-compaction ssd --mode active --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --cache-size 8096 --min-peers 150 --max-peers 256 --author WalletHere --ports-shift 250 --no-ws --no-ipc --base-path /mnt/md0/chains/eth --no-download --no-periodic-snapshot --extra-data "BlaBlaBla"`

Is there something that I miss? OR Is it just fine ? OR Is there any way that I can make it faster. Because it makes my pool to broadcast jobs late.

PS: What I see is, importing time increases when transaction count increases.

Best regards.

**Comment by joshua-mir** [comment]
Afaict this is within expected behavior - it does take an increased amount of time to process transactions in blocks that have more transactios/gas usage - its important to note that everyone needs to do this and you shouldn't actually be being disadvantaged by this.

**Comment by uurcm16** [comment]
@joshua-mir
 Thank you for the fast answer. 
Yes, I know that more transaction - more process.
So, you say that thoose timings are just fine.

You can see the 700ms importing time. Is it really fine to **broadcast job in ~1 second?** OR All of the blockchain runners has imported that block around 700ms? Even with the perfect setups (more cpu, more disk, more ram etc..)?

**Comment by joshua-mir** [comment]
You do still have a little room to improve, your cache-size is probably not big enough to hold the entire state *including the other things parity caches* - `--cache-size 12000` would be better, for example. But I would have expected an improvement moving to raid, which suggests the bottleneck in your case might have been processing power.

But yes, I believe you'd still be seeing the same *proportional* increase in import times in fuller blocks regardless of setup.

**Comment by uurcm16** [comment]
@joshua-mir 
An improvement :). 
Values are around 200-400 now. 
I'm not seeing 700 ms anymore. I'll give it a try and i will let you know the exact improvement rate.
