### ISSUE TITLE
Merge `Notifier` and `TransactionsPoolNotifier`

### ISSUE THREAD

**Issue by IntegralTeam** [paritytech/parity-ethereum#10581]
Merge `Notifier`
https://github.com/paritytech/parity-ethereum/blob/master/miner/src/pool/listener.rs#L33-L65

and `TransactionsPoolNotifier`
https://github.com/paritytech/parity-ethereum/blob/master/miner/src/pool/listener.rs#L123-L144

[#10558(comments)](https://github.com/paritytech/parity-ethereum/pull/10558#pullrequestreview-223738440)

**Comment by tomusdrw** [comment]
I rather think we should get rid of `Notifier` completely and just rewrite places where `Notifier` is used to use `TranactionPoolNotifier` instead and filter out only `Added` transactions.
