### ISSUE TITLE
parity_newAccontFromWallet and parity_exportAccount are not symmetric

### ISSUE THREAD

**Issue by nejucomo** [paritytech/parity-ethereum#10583]
- **Parity Ethereum version**: 2.4.4
- **Operating system**: Linux
- **Installation**: built from source (cargo)
- **Fully synchronized**: no (`[parity] light = true` mode)
- **Network**: unknown - `config.toml` doesn't have an explicit network, so it is the default.
- **Restarted**: yes

**Expected Behavior:**

Using the output of `parity_exportAccount` as the first argument to `parity_newAccountFromWallet` should import the same account as was exported (given an identical password).

This expectation is based on these docs:

The [docs for `parity_exportAccount`](https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_exportaccount) say the return value is "Standard wallet JSON."

The [docs for `parity_newAccountFromWallet`](https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_newaccountfromwallet) say the first argument is "Wallet JSON encoded to a string".
 
**Actual Behavior:**

The JSON-RPC call returns the error "Could not create account." The log file, in DEBUG level, has more detail, specifically:

> jsonrpc-eventloop-0 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32023,"message":"Could not create account.","data":"InvalidKeyFile(\"Invalid JSON format\")"},"id":1}.

I was able to parse the JSON with python's `json` module, verifying it is valid JSON. I suspected the parity parser didn't like spaces or newlines, so I also tried a compact form of the JSON using python's `json.dumps(walletjson, separators=(',', ':'))`. This elicited the same behavior.

**Steps to Reproduce:**

```bash
$ pip install jsonrpctool
$ PASSWD='hunter2'
$ ADDR='...an address...'
$ RPC_PORT='... your node rpc port ...'
$ export JSONRPC_ENDPOINT='http://127.0.0.1:$RPC_PORT/'
$ WALLETJSON="$(jsonrpctool parity_exportAccount "$ADDR" "$PASSWD")"
$ jsonrpctool parity_newAccountFromWallet "$WALLETJSON" "$PASSWD"
```

**Comment by seunlanlege** [comment]
looks like `parity_newAccountFromWallet` requires a presale wallet, and not the standard ethereum wallet.

also side-note. Those rpc methods are deprecated.

**Comment by seunlanlege** [comment]
huh on second look, it should actually work

```rust
self.accounts.import_presale(json.as_bytes(), &pass)
  .or_else(|_| self.accounts.import_wallet(json.as_bytes(), &pass, true))
  .map(Into::into)
  .map_err(|e| errors::account("Could not create account.", e))
```

will look into it

**Comment by seunlanlege** [comment]
can't replicate on master.
