### ISSUE TITLE
Can SecretStore HTTP API allow cross-origin requests?

### ISSUE THREAD

**Issue by adetante** [paritytech/parity-ethereum#10582]
- **Parity Ethereum version**: master
- **Operating system**:  MacOS
- **Installation**: built from source
- **Fully synchronized**: not applicable
- **Network**: not applicable
- **Restarted**: yes

HTTP requests with an Origin header are currently blocked by the API: see [SecretStore http_listener](https://github.com/paritytech/parity-ethereum/blob/master/secret-store/src/listener/http_listener.rs#L216).

Can it be less restrictive, and allow for example a configurable domain?
Could a dApp initiate a key generation session with the secret store, for example to encrypt content directly from the dApp?

**Comment by adetante** [comment]
I have just created [a PR](https://github.com/paritytech/parity-ethereum/pull/10584) with an implementation proposal

**Comment by svyatonik** [comment]
I believe it is closed by #10584
