### ISSUE TITLE
accounts created by rpc command is not returned by parity command

### ISSUE THREAD

**Issue by victorsinosunlabs** [paritytech/parity-ethereum#10597]
- **Parity Ethereum version**: 2.6.0
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
1) curl --data '{"method":"personal_newAccount","params":["hunter"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
-- create new accounts
{"jsonrpc":"2.0","result":"0x8fa.....bf9b","id":1}
2) curl --data '{"method":"eth_accounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
-- return created accounts
{"jsonrpc":"2.0","result":["0x8fa....bf9b"],"id":1}
3) parity account list
returns nothing. It should return the account created by rpc command.

**Comment by joshua-mir** [comment]
@victorsinosunlabs you need to specify the `--chain` that you are asking for with the cli subcommands.
