### ISSUE TITLE
Parity-Ethereum 2.4.5-stable being flagged as virus

### ISSUE THREAD

**Issue by theretohere** [paritytech/parity-ethereum#10598]
- **Parity Ethereum version**: 2.4.5
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

File: x64 parity.exe for windows

SHA256 Checksum: 55b5a49982475b0e2272752739910dc0de022443c790a9be66e510562e21ad8c

From: https://github.com/paritytech/parity-ethereum/releases/tag/v2.4.5

Can warnings from Kaspersky desktop about the file having a virus IM-Worm.Win32.Steckt be ignored?

Any chance someone from the project can submit the release files for whitelisting to prevent this for all users in the future?

**Comment by joshua-mir** [comment]
(@theretohere  yes this is a known false-positive.

agree that putting our binaries on AV whitelists should be a part of our CI pipeline at some point.

**Comment by s3krit** [comment]
@theretohere I've reached out to Kaspersky's virus whitelisting program and they have informed me that this will be fixed.

**Comment by joshua-mir** [comment]
I think we're on enough whitelists now to close this 👍
