### ISSUE TITLE
Parity wont start on Docker when data volume is mounted

### ISSUE THREAD

**Issue by mesudip** [paritytech/parity-ethereum#10593]
I created a docker service for parity
```
# docker service create --name parity  \ 
--mount type=volume,source=paritydb,destination=/home/parity/.local/share/io.parity.ethereum/ \ 
--network name=p9dlgqyptb2crguilewj1e4hi,alias=ropsten  parity/parity:stable \
--base-path=/home/parity/.local/share/io.parity.ethereum/ \
--chain ropsten --ws-interface=all --ws-origins=all --ws-hosts=all
```
It fails with the following error message
```
# docker logs -f parity.1.u1qubpp5ott0rcpfu22e38t5e
Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```
The error is not encountered when using the image without volume mount.

**Comment by joshua-mir** [comment]
Parity within docker runs with it's own user (`parity`/uid `1000`) - if you mount a volume to your container, you must either mount it so that user has access to the volume, or otherwise chown the directory you are mounting before mounting.

**Comment by mesudip** [comment]
I was following the parity commandline documentation and expected to work it the similar way in docker.

It would be awesome if the container's entrypoint fixed the directory permission before starting parity as another user.

**Comment by joshua-mir** [comment]
@mesudip if the docker container is (intentionally) not running as the root user, it doesn't have access to root permissions outside of the container, so can't alter permissions of directories outside of the container.
