### ISSUE TITLE
Accelerating Dapps?

### ISSUE THREAD

**Issue by nbt-rezaem** [paritytech/parity-ethereum#10601]
We'd like to accelerate *specific* Dapp contracts by caching their storage and events. We'd be happy to write the code to do that, but we wanted to check with the committers that this makes sense. A rough outline of this effort would be:

- Introduce a way to designate some addresses to be always cached. Possibly via config file and/or a new rpc endpoint (with auth?). Enabled via a command line arg.
- Implement permanent-caching of the contract storage and events.

We're targeting nodes that are owned by specific businesses (who own or work with specific contracts), not necessarily public utility nodes.

Is the idea sound? Any reason why such an implementation would not be merged?

**Comment by HCastano** [comment]
Hey, this sounds useful but I don't think this is something that should live in the client. You could build a caching layer on top of your node in a similar fashion to what's done here: https://github.com/tomusdrw/jsonrpc-proxy.

**Comment by nbt-rezaem** [comment]
@HCastano we considered that approach. Some things aren't too hard to cache outside (events), but most everything else would be very hard, including the contract's storage, from which all `view` calls are answered. Maybe I'm missing something... can you suggest a caching strategy that guarantees correctness for contract method calls? For context, we're talking about financial apps here, not approximate statistics (e.g. estimate gas) or less sensitive apps.

The client already includes significant layers of caching. Our proposal is to just extend that, so some entries don't expire out.

**Comment by joshua-mir** [comment]
@nbt-rezaem I feel like this is unfeasible due to the modifications to multiple components this would entail - feel free to comment if you want to reopen this to use as a tracking request for a PR or a feature request.
