### ISSUE TITLE
Reported benign validator misbehaviour - kovan validator smart contract

### ISSUE THREAD

**Issue by zerotrustconsortium** [paritytech/parity-ethereum#10619]
- **Parity Ethereum version**: 2.4.5 stable
- **Operating system**: Linux
- **Installation**: docker image
- **Fully synchronized**: yes
- **Network**: PoA
- **Restarted**: yes

Currently we are using the kovan validator set contracts to update the validators for a PoA AuRa chain on parity. Currently, we have 5 validators from various geographical regions connected, fully synchronized, and validating blocks. All nodes are timesynched.

We started the initial AuRa chain fix a static validator set, added the kovan smart contracts at a given block in the future. The switch to the smart contract validatorset was successfully done and confirmed by all nodes at the correct block.

Block validation still works fine, transactions are mined and the chain seems to work functional.

But after about an hour we received the first messages on the console of the first node (initial node), that is also the boot node for all the other nodes:
Reported benign validator misbehaviour

Within a day the amount of these messages went from 1 every several hours to currently 1 every 10 minutes. That messages seems to appear only on that node.

chain.json is pretty much default, except some of these values:

```
{
  "name": "...",
  "engine": {
    "authorityRound": {
        "params": {
            "stepDuration": "5",
            "validators" : {
                "multi": {
                    "0": {
                      "list": ["0x37C557....9d5E30442"]
                    },
                    "100": {
                      "contract": "0xbe492d2....aba31a2321b"
                    }
                }
            }
        }
        }
  },
  "params": {
    "transactionPermissionContractTransition": 70,
    "transactionPermissionContract": "0x080aa50...3249a3565",
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID": "0x8000",
    "gasLimitBoundDivisor": "0x400",
    "eip155Transition": 0,
    "eip140Transition": 0,
    "eip211Transition": 0,
    "eip214Transition": 0,
    "eip658Transition": 0,
    "wasmActivationTransition": 0
  },
  "genesis": {
    "seal": {
      "authorityRound": {
        "step": "0x0",
        "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "difficulty": "0x1",
    "gasLimit": "300000000"
  },
  "accounts": {
    "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
    "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
    "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
    "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
    "0x0000000000000000000000000000000000000005": { "builtin": { "name": "modexp", "activate_at": 5067000, "pricing": { "modexp": { "divisor": 20 } } } },
    "0x0000000000000000000000000000000000000006": { "builtin": { "name": "alt_bn128_add", "activate_at": 5067000, "pricing": { "linear": { "base": 500, "word": 0 } } } },
    "0x0000000000000000000000000000000000000007": { "builtin": { "name": "alt_bn128_mul", "activate_at": 5067000, "pricing": { "linear": { "base": 40000, "word": 0 } } } },
    "0x0000000000000000000000000000000000000008": { "builtin": { "name": "alt_bn128_pairing", "activate_at": 5067000, "pricing": { "alt_bn128_pairing": { "base": 100000, "pair": 80000 } } } }
  }
}


```

We're currently testing, but as we're about to migrate from a static validatorset to a smart contract based validation in our mainnet, we want to know, why that message possibly shows up and if its a thing to worry about.

**Comment by joshua-mir** [comment]
Unless you are handling benign misbehavior in your validatorSet contract and have logic set up to do something, benign misbehavior can usually be ignored. It is usually caused by blocks getting to the network late due to network conditions or misconfigurations of your validators time servers, so unless you haven't been synchronising system clocks properly between nodes, there is little you can do to resolve this.

Edit: if you have any blocks that approach your genesis gasLimit of 300000000 they will very likely take longer than your stepduration to process, causing your validator to miss its step and get hit with a benign misbehavior report our recommendation is to have a gasLimit of around 8M if you want to have a 5s step duration, and if you are confident that your validators can handle more, use the `gas_floor_target` and `gas_cap` (cli or config params) to retarget to higher gas limits.

**Comment by zerotrustconsortium** [comment]
actually we found the issue. And we're 99% sure that multiple nodes on Google Cloud machines (i.e. custom, 2 vCPUs, 9.5 GB memory, no ssd) are the issue. Whenever we used them as boot nodes and validators we ran into benign validator issues and eventually the node wasn't syncing anymore. After moving these nodes to more powerful machines on other datacenters all went back normal.

**Comment by joshua-mir** [comment]
That makes sense - I should clarify for anyone reading, benign misbehavior is reported whenever a node broadcasts a block out of turn (early, late, or simply misses their step)
