### ISSUE TITLE
Many Docker Builds Missing From DockerHub

### ISSUE THREAD

**Issue by yennieb** [paritytech/parity-ethereum#10627]
- **Parity Ethereum version**: 2.3.9
- **Operating system**: all
- **Installation**: Docker

We have client builds dependent on version 2.3.9, which has disappeared from DockerHub. The only two explicitly versioned tags now appear to be 2.5.0 and 2.3.3.

**Comment by joshua-mir** [comment]
with the recent security breach of DockerHub we cannot be sure about integrity of our previously uploaded images; we decided against rebuilding and reuploading EOL versions we no longer support.

**Comment by yennieb** [comment]
@joshua-mir please reconsider. These include versions which were latest stable releases a very short time ago. Anyone referencing something like parity/parity:2.3.9 in already released software, like us, is completely broken overnight when you pulled these.

Why 2.3.3 but not 2.3.9?

**Comment by yennieb** [comment]
Also noting that there is no 2.4.5 tag, despite it being the latest stable build. Surely a tag can be added to an existing build without affecting any security considerations?

**Comment by joshua-mir** [comment]
In my understanding, that was due to tobalaba support - I agree with your point regarding tags though, will see if that's possible 😅

**Comment by yennieb** [comment]
@joshua-mir thanks for your attention. 2.4.5 is something we were about to release against so it would be great to get that tag added to the stable build. I understand 2.3 was EOL support-wise but I think reasonably didn't expect it to disappear from existence yet and was a bit puzzled to find 2.3.3 (maybe by mistake?)

Cheers

**Comment by luarx** [comment]
I agree with @yennieb, 
We were using 2.4.5 version and when our container was restarted, it was not able to download again that image. *It is a problem because it's a production node* :( 

Also neither v2.3.3 version (it's not the last stable) nor v2.5.0 (beta) are versions that I wan't to use in my production cluster...

Should you upload *2.4.5* version at least?

**Comment by joshua-mir** [comment]
@luarx `stable` on dockerhub *is* `2.4.5` (but I agree that we should consider uploading the same image tagged with the version, is that possible @TriplEight?)

**Comment by TriplEight** [comment]
`v2.4.5` is on its way.

**Comment by luarx** [comment]
Great! Thank you very much :) 

I prefer to use for production images with a **version tag** so that I can control with version I'm using. 
The main reason is because I usually:
1. Test new versions in a **staging environment** where I have my own applications to know if there are any incompatibilities. 
2. After testing it for some days, deploy the new node version in **production**.

**Comment by TriplEight** [comment]
I understand that @luarx , generally it's a good practice.
Would be happy if you could share your ways of testing :)

**Comment by Pzixel** [comment]
Being said in linked issue, versions 2.3.X+ are flawed with, well, the linked issue. So I'd like to stick with latest 2.2.X version (2.2.11 IIRC). Any chance it gets reuploaded?

**Comment by mexican1973** [comment]
@yennieb  I am also running an aura node using parity. I installed the parity version 2.4.5 stable and it is having some memory leak issue so I do not recommend to use that version with auraD. We should wait till that memory issue is solved.

**Comment by TriplEight** [comment]
`v2.4.5`, is [back](https://cloud.docker.com/repository/docker/parity/parity/tags).

**Comment by joshua-mir** [comment]
> we decided against rebuilding and reuploading EOL versions we no longer support.

There have been a few pretty critical security fixes made since 2.2.X @Pzixel, there's a very good reason we aren't re-releasing old versions, it's a matter of local reliability vs network security and we prioritize the latter.
