### ISSUE TITLE
How to start the UI?

### ISSUE THREAD

**Issue by marsrobertson** [paritytech/parity-ethereum#10622]
#### 1. Website
![image](https://user-images.githubusercontent.com/44369284/57013499-b04c4180-6c03-11e9-9fb7-bcbffcf4b0e6.png)

#### 2. Download

![image](https://user-images.githubusercontent.com/44369284/57012541-f8b53080-6bfe-11e9-861b-194cd0ffe753.png)

#### 3. Releases on GitHub
https://github.com/paritytech/parity-ethereum/releases

#### 5. `./parity`

![image](https://user-images.githubusercontent.com/44369284/57013944-c78c2e80-6c05-11e9-86aa-3ff746d42f82.png)

_(after 2 hours seems like all blocks are in sync)_

----

I haven't run Parity in a long time...

### Not sure if I should expect any UI?

I'm fairly technical, I knew I have to launch a terminal and make downloaded file runnable. At this point I'm thinking and asking a question - are we building stuff for average users _(mainstream adoption)_ or developers?

It could be true that Parity is "developers only" and that positioning is fine as well.

~Another theory could be - preventing non-technical users from using Ethereum and accidentally losing their funds ~

Or maybe I'm missing some obvious flag `--with-UI`?

![ScreenFlow parity 2019-05-01 11_35_02](https://user-images.githubusercontent.com/44369284/57014953-44210c00-6c0a-11e9-80df-fa9ffaa37d80.gif)

Tried checking in the readme, are the syncing terminal logs all I should expect?

```
2019-05-01 12:15:50  Syncing #7674210 0x9433…6579     1.60 blk/s  257.0 tx/s   10.6 Mgas/s      0+  608 Qed  #7674821   23/25 peers   6 MiB chain 32 MiB db 61 MiB queue 9 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-05-01 12:15:55  Syncing #7674219 0xffa1…2a21     1.80 blk/s  343.5 tx/s   14.4 Mgas/s      0+  596 Qed  #7674821   23/25 peers   4 MiB chain 32 MiB db 60 MiB queue 9 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-05-01 12:16:00  Syncing #7674227 0xd66d…750d     1.60 blk/s  229.0 tx/s   12.7 Mgas/s      0+  584 Qed  #7674821   23/25 peers   4 MiB chain 32 MiB db 59 MiB queue 9 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
```

**Comment by joshua-mir** [comment]
The UI was separated from parity-ethereum (and deprecated) in 2.0 (see https://www.parity.io/parity-ethereum-2-0/ and https://wiki.parity.io/Parity-Wallet)

Yes, parity-ethereum is currently intended primarily for developer and infrastructure usage. The alternative we provide for the old wallet UI is github.com/paritytech/fether (if you only need simple transfers)

**Comment by marsrobertson** [comment]
### I didn't know about it!

>  First and most importantly, Parity Ethereum is built to serve as expert software for production use and shouldn’t be considered end-user software or an “Ethereum Wallet.”

Parity UI - not maintained anymore.

Feather - so minimalistic. Screenshot feature - is it just me or security precaution?

<img width="532" alt="Screenshot 2019-05-01 at 12 45 35" src="https://user-images.githubusercontent.com/44369284/57015981-74b77480-6c0f-11e9-882b-4b22539802e1.png">

![image](https://user-images.githubusercontent.com/44369284/57015922-3457f680-6c0f-11e9-8dc8-1aff0590f33d.png)

**Comment by joshua-mir** [comment]
Haven't seen that before - I don't believe it's intentional - if you believe it's an issue, you should probably report it on the fether repo 😅
