### ISSUE TITLE
parity not sync blocks 

### ISSUE THREAD

**Issue by DinoStray** [paritytech/parity-ethereum#10639]
- **Parity Ethereum version**: v2.4.5-stable-76d4064-20190408
- **Operating system**: Linux
- **Installation**: release binary file
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

The logs:
![image](https://user-images.githubusercontent.com/6963679/57422855-3ee44280-7244-11e9-8336-e0ff26d9a370.png)

I wait for many hours, and restart many times.
Parity not sync any block.

**Comment by DinoStray** [comment]
My config file:
[parity]
chain = "mainnet"
base_path = "/root/.parity/data"
db_path = "/root/.parity/data/chains"
keys_path = "/root/.parity/data/keys"
mode = "active"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false
identity = ""
light = false

[ui]
disable = true

[network]
port = 30303	
min_peers = 25
max_peers = 75
nat = "any"
id = 1
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false
reserved_peers = "/etc/parity/reserved_peers"

[rpc]
disable = false
port = 8545
interface = "all"
cors = []
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[websockets]
disable = true

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[mining]
author = "0x756f45e3fa69347a9a973a725e3c98bc4db0b5a0"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_gas_limit = "6283184"
tx_time_limit = 100 #ms
extra_data = "Parity"
remove_solved = false
refuse_service_transactions = false

[footprint]
tracing = "off"
pruning = "fast"
pruning_history = 64
pruning_memory = 500
cache_size_db = 64
cache_size_blocks = 8
cache_size_queue = 50
cache_size_state = 25
cache_size = 4096 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 6

[snapshots]
disable_periodic = false

[misc]
logging = "own_tx=trace"
log_file = "/root/.parity/parity.log"
color = true

**Comment by joshua-mir** [comment]
@DinoStray are you behind a firewall blocking port 30303?

**Comment by DinoStray** [comment]
After I remove all the config the same as default, parity sync success
