### ISSUE TITLE
AuRa Validator doesn't produce blocks when `debug` mode is used

### ISSUE THREAD

**Issue by varasev** [paritytech/parity-ethereum#10637]
- **Parity Ethereum version**: 2.4.5-stable
- **Operating system**: MacOS 10.13.6
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: AuRa testnet (see details below)
- **Restarted**: yes

Steps to reproduce:
```bash
$ git clone -b stable https://github.com/paritytech/parity-ethereum
$ cd parity-ethereum
$ cargo build
$ cd ..
$ git clone -b debug-mode-test https://github.com/varasev/test-block-reward
$ cd test-block-reward
$ npm i
$ npm start
...
$ npm run clear
```

After `npm start`, you will see the following picture: the second validator is not rewarded and block duration is 6 seconds [instead of 4](https://github.com/varasev/test-block-reward/blob/e1879be3c1da157f776ae93037cd5eee4042fe19/config/spec.json#L6)) as if the second validator is turned off.

<img src="https://user-images.githubusercontent.com/33550681/57377030-16a80580-71aa-11e9-8e05-60b721db42ce.png" height="500" />

If I try to build Parity with `cargo build --release --features final`, it works fine.

So, there is some problem with the `debug` version.

**Comment by joshua-mir** [comment]
@varasev it is very likely the case the validator cannot process the block quickly enough to produce a block within their step. Have you tried increasing the stepduration further to see whether this is still the case?

`build --release` is what tells cargo to optimize the build, the debug binary will be much slower, especially for things like the EVM, so running a validator in debug is unlikely to work the way you want.

**Comment by varasev** [comment]
@joshua-mir If I set `stepDuration` to 5 seconds, all validators participate, but there is a weird block time:

<img src="https://user-images.githubusercontent.com/33550681/57430800-77caea00-7239-11e9-8f81-8119e25a3b9d.png" height="500" />

If I set 10 seconds, I see

<img src="https://user-images.githubusercontent.com/33550681/57431001-0c354c80-723a-11e9-8bf5-159e1833a813.png" height="500" />

For the `release` mode everything is fine.

Can this be because of the same reason you described?

**Comment by joshua-mir** [comment]
Yep. Closing as we can't do anything about this for aura.
