### ISSUE TITLE
Question: Manual Syncing/Pruning

### ISSUE THREAD

**Issue by MatthiasLohr** [paritytech/parity-ethereum#10666]
Hello,

I have a question regarding syncing and pruning.

For a scientific experiment I need to crawl about all traces of the ethereum blockchain. I found the problem, that it seems to be impossible to sync an archive node even with a good and powerful server. Is there any possibility for like manually (via API) starting/stopping sync and pruning?

Best regards
Matthias

**Comment by joshua-mir** [comment]
https://wiki.parity.io/JSONRPC-parity_set-module#parity_setmode you can control sync via rpc after enabling the `parity_set` api, but not pruning settings unfortunately

**Comment by ltfschoen** [comment]
Is the ability to control pruning settings via rpc a desired feature?

**Comment by joshua-mir** [comment]
If we wanted to be able to change other config params via rpc, it might be easier to just make a general solution for any config parameter (although there might be a problem changing certain things mid-flight like pruning specifically, things involving sync or cache might also be problematic)

**Comment by joshua-mir** [comment]
I'll close this issue for now as the answer is "we don't support it currently" @MatthiasLohr

**Comment by MatthiasLohr** [comment]
Thanks for your replies!
