### ISSUE TITLE
Ghost transaction (hash but not existing)

### ISSUE THREAD

**Issue by nicolashardy** [paritytech/parity-ethereum#10668]
Hello all,

- **Parity Ethereum version**: 1.11.0
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: Custom blockchain
- **Restarted**: no

Hello, some of my transactions are created and return a proper txHash , but actually the transaction does not exist

getTransactionReceipt returns null 
not visible in etherchain light
getTransaction returns null ..

My nodes are fully synced and it happens randomly. Do you have an idea of the reason why ?

Thanks in advance

**Comment by joshua-mir** [comment]
@nicolashardy there have been many fixes to the txqueue made since 1.11.0 - I can't really answer this question as it would probably be resolved by updating your version of parity..

**Comment by joshua-mir** [comment]
I'll reopen this if you still have similar issues with a recent version of parity
