### ISSUE TITLE
v2.5.0 warp sync stuck

### ISSUE THREAD

**Issue by mgdzhxx** [paritytech/parity-ethereum#10675]
- **Parity Ethereum version**: 2.5.0
- **Operating system**: Linux
- **Installation**: github release
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Main run commands and parameters:
```
./parity --pruning fast --chain=mainnet --cache-size-db 4096
```

It is always stuck in an uncertain number,like this 
```
Syncing snapshot 725/3122  #3610937 ...
Syncing snapshot 725/3122  #3610937 ...
Syncing snapshot 725/3122  #3610937 ...
...
```

**Comment by joshua-mir** [comment]
Your config isn't  describing an archive node (`--pruning=archive`) - if you don't actually want to run an archive node and are okay warp-syncing, could you try running with `--warp-barrier 70000000`? If you still get stuck "Syncing snapshot", running with `--no-warp` will skip warp-sync entirely.

**Comment by joshua-mir** [comment]
Let me know if your question wasn't answered
