### ISSUE TITLE
setMode(offline) results in: Cannot sleep - syncing ongoing

### ISSUE THREAD

**Issue by MatthiasLohr** [paritytech/parity-ethereum#10687]
I want to control parity's syncing behavior with the `parity_setMode` api call (https://wiki.parity.io/JSONRPC-parity_set-module#parity_setmode). But this does not work reliable.

## System Details

- **Parity Ethereum version**: v2.5.1
- **Operating system**: Linux (Ubuntu 18.04 LTS)
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

## Actual Behavior

Calling `parity_setMode('offline')` only stops syncing if the queue size is small enough (https://github.com/paritytech/parity-ethereum/blob/21a27fee9f0e23777d9f14b3d3d74fa3d1b63a9d/ethcore/src/client/client.rs#L1211).

## Expected Behavior

If I call `parity_setMode('offline')` I would except that the sync process stops - regardless of queue size. If I want to stop the node, I'm completely ok with throwing the queue contents away. I can also see no reason for this limitation.

## Further Notes

  * The current behavior should be documented, there's nothing about this limitation
  * One solution could be to add a `force=True` parameter

**Comment by SvenPeldszus** [comment]
I also had this struggle, hopefully you can fix this behavior soon or add something like a "force" parameter

**Comment by MatthiasLohr** [comment]
@joshua-mir, thanks for scheduling this! Any idea when 2.6 will be released?

**Comment by joshua-mir** [comment]
@MatthiasLohr we don't use milestones to schedule features - they are implemented when they are implemented. They are primarily used to know which branch to backport features if they are implemented - so new features part of the 2.6 milestone, if labelled for backporting, would end up in 2.5.x Beta, and bugfixes would be in the 2.4.x Stable branch.

This process is currently in flux however, so most new features and fixes are sitting in nightly for now.

**Comment by MatthiasLohr** [comment]
Just found out there's also a bug here: If I set the mode via `parity_setMode` to `offline` and I get this error message, I would expect that `parity_mode` still says `active` - but it says `offline` (while parity is still syncing)!
