### ISSUE TITLE
web3 - can't subscribe to pending txs with light mode

### ISSUE THREAD

**Issue by or2008** [paritytech/parity-ethereum#10692]
- **Parity Ethereum version**: v2.5.1-beta
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes
- **Web3 version**: 1.0.0-beta.54

Hi I am using the following code to subscribe to pending transactions on local parity node. 
```
const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://127.0.0.1:8546'));
web3.eth.subscribe('pendingTransactions')
    .on('data', txHash => {
        console.log(txHash);
    })
```

it works properly when I am running the node in full mode, however when changing it to light mode, web3 connect successfully, but I don't receive txs anymore.

any idea why?

**Comment by joshua-mir** [comment]
@or2008 light nodes don't receive blocks or transactions from the network, only block headers from light-serving full-nodes, and the specific bits of information they ask for. They certainly don't have access to the pending block. Even full-nodes that don't have `--force-sealing` enabled don't have access to the pending block. 

web3.js is not designed with light nodes in mind, I would strongly recommend using www.parity.io/light-js-how-to-build-your-dapp-on-a-light-client/ if you plan on using light nodes as part of your backend.
