### ISSUE TITLE
Command-line option to disable snapshots not working

### ISSUE THREAD

**Issue by celeduc** [paritytech/parity-ethereum#10706]
Parity-Ethereum/v2.5.1-beta-adabd81-20190514/x86_64-linux-gnu/rustc1.34.1
- **Parity Ethereum version**: v2.5.1-beta-adabd81-20190514/x86_64-linux-gnu/rustc1.34.1
- **Operating system**: Ubuntu 18.04
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

While syncing Kovan, creating snapshots uses excessive CPU and disk I/O.  Using the command line option `--no-periodic-snapshot` does not stop snapshots from occurring. At suggestion from support, also tried `--no-periodic-snapshots` which is also ignored.

However, creating a `.toml` file with `[snapshots]` `disable_periodic = true` does prevent snapshots from happening, and resolves the high CPU & disk I/O issue.

**Comment by dvdplm** [comment]
I can't reproduce this with 2.5.1-beta or latest master. I'm running `parity --chain kovan --no-periodic-snapshot` (which is the correct switch) and I don't get snapshots (without the switch I do).
Maybe we're not running the same command?

**Comment by celeduc** [comment]
Looks like my alias to the binary was eating options. Sorry for the time-waster, guys.
