### ISSUE TITLE
Transaction cost exceeds current gas limit. Limit: 5000, got: 100000. Try decreasing supplied gas.

### ISSUE THREAD

**Issue by sg552** [paritytech/parity-ethereum#10703]
- **Parity Ethereum version**: Parity-Ethereum/v2.5.1-beta-adabd81-20190514/x86_64-linux-gnu/rustc1.34.1
- **Operating system**:  Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

My node is fully synced, and I can query the latest blocks.  but I can not send ERC-20 token from my address  using "personal_sendTransaction". 

( I want to transfer  some 3,700,000 CGW token from '0xb33e...34f7' to '...ce7e' , using gas price with 6.2 Gwei, and gas limit: 10, 000) 

```
 curl --data '{
    "method":"personal_sendTransaction",
    "params":[
        {
            // This is my ETH wallet
            "from":"0xb33e02deef664cd15ef2d93179c3ce119e1f34f7",
            // This is the contract address 
            "to":"0x977b0584b50cdd64e2f8185b682a1f256448c7c8",
            "data":"0xa9059cbb000000000000000000000000925ccd95f17640be707c4c8ae713177dfc91ce7e000000000000000000000000000000000000000000030f8166e38fd5a0000000",
            "value":"0x0",
            "gas":"0x186a0",  // 10,000  
            "gasPrice":"0x1718c7e00"   // 6.2 Gwei
        },
        "j0m%@jT...this is my password"
    ],
    "id":0,
    "jsonrpc":"2.0"
}
' -H "Content-Type: application/json" -X POST http://172.31.12.2xx:8xxx
```

and I always got: 

```
{
    "jsonrpc":"2.0",
    "error":{
        "code":-32010,
        "message":"Transaction cost exceeds current gas limit. Limit: 5000, got: 100000. Try decreasing supplied gas."
    },
    "id":0
}
```

Why?   I searched a lot, people saying that the "gas limit" is initially 5000, and will increase by case. 
How should I do? 
thanks a lot!

**Comment by sg552** [comment]
this is my config.toml:

```
[parity]

mode = "active"

base_path = "/opt/parity"

identity = "coiex"

[rpc]

apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts", "secretstore"]

server_threads = 2

port = 8xxx
interface = "172.31.12.2xx"

[websockets]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal"]

[misc]
log_file = "/opt/parity/logs/parity.log"
logging = "info"

[mining]
min_gas_price = 1 # 1 wei

```

and the blockchain data is costing 50+ G harddisk spaces.

**Comment by joshua-mir** [comment]
> I searched a lot, people saying that the "gas limit" is initially 5000, and will increase by case.
How should I do?

This is referring to the *block* gasLimit - you also define a gas limit for every transaction you make, (That would be `"gas":"0x186a0"` in your example) this is the gas provided to execute the contract logic, and any unused amount after the transaction is completed is refunded to your account. If you set this gas too low, as you are currently doing, the transaction will fail as you did not provide enough gas to complete whatever logic was required in the transaction. You can omit the value entirely, and parity will estimate a decent value - or, as that is often unreliable, manually overestimate a little bit (ie, most erc-20 token transfers should be "around 200000") as this is refunded to you anyways.

> and the blockchain data is costing 50+ G harddisk spaces.

This will grow to around 200gb as you download and verify "ancient blocks" (blocks from genesis until the warp snapshot your sync started at). 

If you think that's too much disk usage, I would recommend running in `--light` mode - (and maybe even consider using github.com/paritytech/fether or a user-centered tool like MyCrypto.com)

**Comment by sg552** [comment]
Thank you so much !  really helpful to me.

Yesterday when I post this issue, I tried 3 times of the "gas limit":   210000, 100000, and 10000 Gwei. 
All of them show me the error as `Transaction cost exceeds current gas limit. Limit: 5000, got: xx0000`

But this morning when I come to office, I run the same command and it's OK now! 

I think maybe it's because the Node is not synced completely ?  I don't know...

Anyway, really thanks for your help, and I really love Parity now.  ^_^

**Comment by anyluckwell** [comment]
Transaction cost exceeds current gas limit. Limit: 5000, got: 21000. Try decreasing supplied gas
I try to change the gas to 5000, and then prompt:
Transaction gas is too low. There is not enough gas to cover minimal cost of the transaction (minimal: 21632, got: 5000). Try increasing supplied gas
Is it really because the block is not synchronized? Is there any other solution

**Comment by anyluckwell** [comment]
I want  now  Transaction token ,May I have a suggestion
