### ISSUE TITLE
what does ` --tx-time-limit=100` mean?

### ISSUE THREAD

**Issue by wangke0809** [paritytech/parity-ethereum#10709]
Hi, I don't know what the following explanation means. Can you explain it more clearly?  

```
--tx-time-limit=[MS]
        Maximal time for processing single transaction. If
        enabled senders of transactions offending the limit will
        get other transactions penalized.
```

**Comment by joshua-mir** [comment]
In this case "time for processing" refers to the time spent executing the transaction on chain, ie, however long it takes to run the smart contract code a transaction might trigger.

The penalty for transactions that take longer than this limit to execute would be to deprioritize other transactions from the same sender (so they are executed after other transactions,)

**Comment by wangke0809** [comment]
@joshua-mir I see. Thank you very much.
