### ISSUE TITLE
Provide `MissingParent` Error-Recovery

### ISSUE THREAD

**Issue by lazaridiscom** [paritytech/parity-ethereum#10712]
moved to: https://github.com/lazaridiscom/parity-ethereum/issues/2

**Comment by lazaridiscom** [comment]
# Important

overworked a bit, messed some commits up, will restore first thing after wake up

**Comment by lazaridiscom** [comment]
all good, see reproduction section above

**Comment by lazaridiscom** [comment]
# Question

Which functionality is used internally, in order to switch the blockchain to a specific path/fork?

**Comment by joshua-mir** [comment]
https://github.com/paritytech/parity-ethereum/blob/dae5d75dd65d6a51873ecd9c1c4f159f49f2a9f3/ethcore/blockchain/src/blockchain.rs#L1049

You can see the important functions here, a route is created and then the block is inserted with the route - the blockchain reevaluates the `best_block` every insertion.

**Comment by lazaridiscom** [comment]
> /// If the block is already known, does nothing.

problem is the blocks are already in the database.

**Comment by joshua-mir** [comment]
The sentiment among the core-devs seems to be that this train of though is a little counterproductive. 

To elaborate we shouldn't be treating existing blocks as invalid after importing them in any case, as that would mean we imported them without validation at some point, any further chains built on top are ignored. More succinctly -> #10085 itself is the issue we should be looking into solving as it gets us into a scenario we explicitly don't want to handle, we should be fixing that, not handling the repurcussions of it afterwards.

**Comment by dvdplm** [comment]
So, I've tried to use the repro code to see if it can help us pinpoint the problem and unfortunately I cannot trigger the error. Blocks #6942 and #6943 seems to be imported properly and while #6882 does cause `2019-06-06 18:55:43 UTC Verifier #2   TRACE blockchain  #6882 0x28fd…5a04 - 0x273b…0377 HASH UNEQUAL, #6882` it does not trigger a panic or error.

Not sure if I'm doing something wrong here or if the repro does not work on all hosts or…?

**Comment by lazaridiscom** [comment]
@dvdplm, My repo contains the patch which avoids the Error being raised, and additional debug output. Either use the original poanet parity, or enable this line to have the error back:

https://github.com/lazaridiscom/parity-ethereum/blob/aura-pos/ethcore/blockchain/src/blockchain.rs#L1020

the "HASH UNEQUAL" location got additional debug, its an condition where 6942 has two instances.

**Comment by lazaridiscom** [comment]
@joshua-mir , with "core-devs", I refer to "original authors of code" or "authors which have extended/maintained the code in deep" (e.g. @HCastano, who worked already on this, too, and provided the reset-functionaliyt ). Those devs can usually answer directly and concretely to abstractly formulated questions (due to their extensive domain/code knowlege).

My "train-of-thought" itself anything else but counterproductive, simply because this is more or less "standard-procedure" for hidden sporadic bugs within a semi-documented semi-structured code-base without access to the original authors.

* #10085 in itself is invalid (even the message is wrong), it could be even closed, as it is splitted down (see: https://github.com/paritytech/parity-ethereum/issues/10085#issuecomment-498844113 
  * #10712 (this issue here) helps to identify "what is the result of the data-corruption", which can help to identify "where was the data-corruption introduced" and "under which conditions"
  * #10711 processes essentially the error-cause ("where was the data-corruption introduced")
-

I cannot discuss my processing here further, this will kick me totally out of my flow.

What I need mostly at this point is to eliminate the "nonsense" in my above text, and to get answers to questions. Takes a day or two if I do it myself, takes 10 min. in a chat-room with some devs.

I'll naturally switch over to #10711 once I've gathered enough information.

.

**Comment by lazaridiscom** [comment]
@dvdplm 
> they all create new DBs from scratch in dberr4copy/node{x}/DPoSChain/db/290f3b65d7836110 instead of …/db/216598bd9d2dcbd2

confirmed, it seems differnet machines create different foldernames. Trying to find a workaround.

**Comment by lazaridiscom** [comment]
* On windows 10 pro, WSL, i get: 216598bd9d2dcbd2
* On windows 10 pro, VirtualBox Ubuntu 18.04,i get: 290f3b65d7836110  (same as you)

Added comments, changed repo to 290f3b65d7836110  for now.

**Comment by lazaridiscom** [comment]
moved to: lazaridiscom#2
