### ISSUE TITLE
ERROR client   Bad block detected: TemporarilyInvalid(OutOfBounds { min: None, max: Some(SystemTime { intervals: 132037605151175335 ....

### ISSUE THREAD

**Issue by KyuJeongKim** [paritytech/parity-ethereum#10718]
Hello.

I need your help.

There is a problem with synchronization between the two nodes.

I configured my private network with parity.

Consensus is using POA.

The problem is

1. The consensus node creates a new block.
2. Receive new blocks from other nodes to import.
3. Synchronization of the new block received fails.
4. The consensus node creates a new block.
5. Synchronize blocks that previously failed to synchronize on other nodes.

There are five issues above: 100 blocks on the consensus node are the latest, and only 99 blocks on the other nodes are always present.

I am attaching the log portion of the problem below.

Additionally 

The consensus node is using parity v1.10.8-standable-bd20c45-20180628 (Linux).
The other node is using Win2012 R2 : parity v2.4.6-standable-94164e1ca-20190514.

****Log in the part of the problem:**

2019-05-31 16:15:00 IO Worker #0 ERROR Client 
Bad block detected: TemporarilyInvalid (OutOfBounds { min: None, max: Some(SystemTime { interval: 1320376055335 }), found: SystemTime { interval: 136060000 }
RLP: f90241f9023ca0d02b396a5795632b4ab58238eedb8aaaaaaad4a11da46a5b6130e40e40e01dcc4dec75db5676c123b129a2c0f86e5b48e01b996cadc001622fb5e363b421b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000029cab99ce1f7d5bd12a03bc3137e03dc050b72a5a438252f6a516e7bc8f1f3744b3bff3e7e1865db2bf411db2c0db0db0dc0dc0db0dc0dc0db0dc0dc0db0db0db0db0db0db0db0db0db0db0db0db0db0db0db0d
Header: Header { parent_hash: 0xd02b396a5795632b4ab58238368eedb8aaaaaaad4a11ba5b6130e40e9, timestamp: 15592866, number: 87341, autor: 015bbbc015bc0199347, extra_data: [213, 131, 1, 10, 8, 134, 80, 97, 114, 116, 121, 134, 49, 46, 50, 55, state_root: 0x1bbbb526de06907303bp3909bp9bp3909bp3909bp9bp3909bp9bp3909bp3bp9bp9bp9bp3bp3bp3bp3bp3bp3bp3bp3bp3bp3bp3bp3bp4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 40000000, difficult: 32823636430738417 3, 214, 194, 176, 80, 183, 42; 68, 68, 56, 37, 47, 106, 81, 110, 200, 223, 36, 241, 243, 116, 75, 255, 62, 126, 24, 101, 237, 116, 219, 116, 116, Sx7: home, 017: 07; 76, 71, 160, 77, Sx7; 71, 24x7; 71, 24x7; 76, 76, 76, 76, 76, 76, 77, 76, 76, 77, 77, 71, 24x7; 76, and 76, 77, 76, 76, 76, 76, 76, 76, 76, 77, 77, 7
Uncles: 
Transactions:

2019-05-31 16:15:00 IO Worker #0 DEBUG sync NewBlocks: Block temporily invalid: 0x0d7a179aaae728a8a9da6aecc03afbc07002b23830830908b197crest
2019-05-31 16:15:00 Verifier #7 DEBUG miner minimum_gas_price: Got gas price! 0
2019-05-31 16:15:00 IO Worker #3 DEBUG sync Finished Block Propagation, take 1 ms
2019-05-31 16:15:00 IO Worker #2 DEBUG txqueue Removed 0 stitched transactions. Pool: 0/8192 (0 senders; 0/4096 kB) [minGasPrice: 0 Mei, maxGas: 40000000]

2019-05-31 16:15:00 Verifier #7 INFO import Imported #87340 0xd02b...40e9 (0 txs, 0.00 Mgas, 1 ms, 0.57 KiB)
2019-05-31 16:15:00 IO Worker #1 DEBUG sync 0 -> Dispatching pack: 4
2019-05-31 16:15:00 IO Worker #1 DEBUG txqueue Re-computing Pending Set for Block: 87340
2019-05-31 16:15:01 IO Worker #2 DEBUG network connecting peer: 1 sessions, 2 pending + 0 started
2019-05-31 16:15:02 IO Worker #0 DEBUG network connecting peer: 1 sessions, 2 pending + 0 started**

**Comment by joshua-mir** [comment]
@KyuJeongKim it's incredibly important that your system clocks are in sync *to the second or better* if you want to connect to a network running Aura consensus, so that's the first thing I would fix - in addition v1.10.0 has many, many known issues and you'd have to update your consensus node to a more recent version before we can give you any additional advice here.

**Comment by KyuJeongKim** [comment]
@joshua-mir  Thank you for your help. We'll go ahead and check it out again.

**Comment by dvdplm** [comment]
@KyuJeongKim just noticed that one of your nodes is running a really old version of Parity. Please consider upgrading. I'm going to close this issue now, feel free to re-open if you need further assistance.
