### ISSUE TITLE
How to show rpc request log.

### ISSUE THREAD

**Issue by vietthang207** [paritytech/parity-ethereum#10743]
Hi parity team.

I can't find the log of request that send to parity api. I'm currently using the docker version.
I'm I missing any config?

Please pardon me if this is not the right place to ask user question.

**Comment by dvdplm** [comment]
cc @joshua-mir

**Comment by niklasad1** [comment]
@vietthang207 

I assume `parity API` == `rpc`.

```$ parity -l rpc=trace```

Alternatively, specify it in your `config.toml` instead

**Comment by niklasad1** [comment]
I think this answer it sufficient for your question, re-open if you don't agree
