### ISSUE TITLE
Block information is incomplete while ancient block sync is still in progress

### ISSUE THREAD

**Issue by natamartchouk** [paritytech/parity-ethereum#10777]
- **Parity Ethereum version**: 2.5.1 (dockerized)
- **Operating system**: Docker / Linux (AWS)
- **Installation**: Docker
- **Fully synchronized**:  yes
- **Network**: ethereum
- **Restarted**: yes

Start command parameters:
```
["--jsonrpc-apis","eth,net,web3,personal,parity","--jsonrpc-interface","all","--ws-interface","all","--ws-hosts","all","--unsafe-expose","--allow-ips","public","--no-discovery","--mode","active","--tracing","off","--pruning","fast","--db-compaction","ssd","--cache-size","1024"]
```

We are getting now and then, not regulary, when calling a smart contract:
`Block information is incomplete while ancient block sync is still in progress, before it's finished we can't determine the existence of requested item.` 

Expected behaviour:
As the the node is synchronized, we'd expect that the error should not happen.

After research we've seen in the similar issues that it might be correlated with the "block gap". Current status here is:

```
$ curl --data '{"method":"parity_chainStatus","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":{"blockGap":["0x5463e6","0x793b29"]},"id":1}
```

Steps to reproduce:
As described above, it's not clear, why the same call sometimes works and sometimes doesn't. 

We'd just want to understand, whether this error is temporary, is related to the block gap and will disappear when the gap is closed, or whether we need to do more investigation. As this is a productional environment, we expect a reliable behaviour.

Thanks!

**Comment by dvdplm** [comment]
@natamartchouk yes, the error is temporary and when the node has had time to sync the ancient blocks it should work as expected. :)
