### ISSUE TITLE
[CRITICAL] Parity produces orphan blocks

### ISSUE THREAD

**Issue by Snuff** [paritytech/parity-ethereum#10774]
- **Parity Ethereum version**: 2.4.7-stable
- **Operating system**: Linux
- **Installation**:  Docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Hi everyone,

We run an ethereum mining pool and use Parity for mining. We found a bug in eth_getWork. Let's look into the case when 2 different blocks arrive at the same height:

**Parity log**
```
2019-06-23 16:49:38 UTC Imported #8015441 0x10f9…a3d6 (130 txs, 7.94 Mgas, 460 ms, 23.15 KiB)
2019-06-23 16:49:39 UTC Imported #8015441 0x0222…332e (209 txs, 7.99 Mgas, 447 ms, 30.94 KiB)
```

**Mining Pool log**
```
2019/06/23 16:49:38.032497 [INFO] New block to mine on main at height 8015442 / 0x04c43ccf
```

After the first block `0x10f9…a3d6` arrived, Parity prepared a new mining work, when the second block `0x0222…332e` Parity did nothing, so our pool mined an **orphan** due to that.

```
2019-06-23 16:49:49 UTC Submitted block imported OK. #8015442: 15b7d443c6c3832d198a4b572f7720853fd4a693eadfe82944ddee15320d62c0
```

Geth, in that case, regenerates a new work.

**Comment by joshua-mir** [comment]
I'll leave a line here that the recommendation I gave for your other issue, https://github.com/paritytech/parity-ethereum/issues/10783#issuecomment-505594864, among other changes like tweaking txpool and resealing settings, should also help address this issue.

**Comment by dvdplm** [comment]
@Snuff can we close this issue now?

**Comment by Snuff** [comment]
Yeah, thank you very much for the help, --force-sealing resolved this issue.
