### ISSUE TITLE
Transaction hash missing when transaction is sent via attached geth console 

### ISSUE THREAD

**Issue by shashisingh111** [paritytech/parity-ethereum#10782]
- **Parity Ethereum version**:  Parity-Ethereum/v2.4.7-stable
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**:  local
- **Restarted**:  NA

I'm just beginning to tinker with parity locally. I opened two accounts on a single node and wanted to send money from one to another by `eth.sendTransaction()` . The console should show the transaction hash but actually it just hanged.

My [`parity.json`](https://github.com/paritytech/parity-ethereum/files/3325561/parityJson.txt)

Account creation
```
parity --base-path project --password password.txt account new
parity --base-path project --password password1.txt account new
```
Started a node
`parity --base-path project --chain parity.json --port 31337 --jsonrpc-port 8539 --jsonrpc-cors "all" --jsonrpc-hosts "all" --jsonrpc-apis "all"`

Tried sending a tx from one account to another:
```
$ geth attach http://localhost:8539
> eth.sendTransaction({from: '0x4800a16a26be29351cb9db17600298387b6d456b', to: '0x1518e417948745a4c1deb799a1f347c275b47947', value:'100'})
```
Expected behaviour:
console should show something like this:
```json
{"id": 11, "jsonrpc":"2.0", "result":"Tx. hash"}
```
Actual behaviour:
console hangs, there's no response from the node.

**Comment by dvdplm** [comment]
What if you submit the transaction with e.g. curl?

**Comment by shashisingh111** [comment]
The problem is resolved. I was not unlocking sender account before sending transaction that's why console  hangs and waiting.
