### ISSUE TITLE
Do I need to change daemon for ETC Atlantis Hardfork?

### ISSUE THREAD

**Issue by uurcm16** [paritytech/parity-ethereum#10815]
Hi,

I'm using Parity v2.4.7 for chain Classic. Do I need to update the daemon to the latest version for the ETC's Atlantis Hardfork?

**Comment by dvdplm** [comment]
Yes, the latest [beta release](https://github.com/paritytech/parity-ethereum/releases/tag/v2.5.3) includes the Atlantis HF.
