### ISSUE TITLE
Parameters required in domain for `personal_signTypedData` too strict?

### ISSUE THREAD

**Issue by pdobacz** [paritytech/parity-ethereum#10832]
- **Parity Ethereum version**: `Parity-Ethereum/v2.5.2-beta-ecbafb2-20190611/x86_64-linux-gnu/rustc1.35.0`
- **Operating system**: Linux
- **Installation**:  downloaded from releases
- **Fully synchronized**: yes
- **Network**: rinkeby
- **Restarted**: yes

#### Expected behavior

I'm not 100% sure, but it seems `personal_signTypedData` could accept a request even if some fields of the `domain` were missing, c.f. [in EIP712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#definition-of-domainseparator): 

> Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

In my case, I'd like to not handle `chainId` there

#### Actual behavior

`parity` returns an `Invalid params: missing field` error when attempting to make such calls.

#### Steps to reproduce

```
$ parity --ws-hosts=all --ws-interface=all --ws-origins=all --chain=rinkeby.json --jsonrpc-apis personal,eth,web3,parity_accounts --jsonrpc-hosts=* --jsonrpc-interface=all --jsonrpc-port=8545 --ws-port=8546 --port=30304 --jsonrpc-experimental
```

then

```
$ curl --data '{"method":"personal_signTypedData","params":[{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"verifyingContract","type":"address"}],"Mail":[{"name":"contents","type":"string"}]},"primaryType":"Mail","domain":{"name":"Ether Mail","version":"1","verifyingContract":"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"},"message":{"contents":"Hello, Bob!"}},"0xb60e8dd61c5d32be8058bb8eb970870f07233155","password"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

gives

```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: missing field `chainId`."},"id":1}
```

Similar behavior if one removes e.g. `verifyingContract`

**Comment by seunlanlege** [comment]
The enforced use of `verifyingContract` and `chainId` is for contract security so as to prevent being vulnerable signature replay attacks

**Comment by pnowosie** [comment]
@seunlanlege could you be kind and support your words with spec?
I found the opposite in [EIP-712#abstract](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#abstract)
> It does not include replay protection.

Replay protection was proposed in [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)

**Comment by seunlanlege** [comment]
> uint256 chainId the EIP-155 chain id. The user-agent should refuse signing if it does not match the currently active chain.

> address verifyingContract the address of the contract that will verify the signature. The user-agent may do contract specific phishing prevention
