### ISSUE TITLE
Transaciton results are different.

### ISSUE THREAD

**Issue by ysbae0928** [paritytech/parity-ethereum#10869]
The result is different when the raw transmission is sent in parity light mode and fast mode respectively.
Why is the result different?
I sent the same transition.

fast node result
{"id":"1","jsonrpc":"2.0","error":{"message":"Transaction nonce is too low. Try incrementing the nonce.","code":-32010}}

light node result 
{"id":"1","jsonrpc":"2.0","error":{"message":"Transaction with the same hash was already imported.","code":-32010}}

- **Parity Ethereum version**: 
version Parity-Ethereum/v2.4.7-stable-d6c5546-20190611/x86_64-linux-gnu/rustc1.35.0

- **Operating system**: 
Linux (Ubuntu 18.04)

- **Fully synchronized**: 
yes

- **Network**: 
ethereum

- **Restarted**: 
yes

**Comment by joshua-mir** [comment]
@ysbae0928 a light node has less information available to it than a full node, so error messages are generally less descriptive. In this case, it might be the case that the transaction you sent to get the first response was in the mempool of the node serving your light node.
