### ISSUE TITLE
I have met a problem on parity port issue. It works with same port.

### ISSUE THREAD

**Issue by PeterKimG** [paritytech/parity-ethereum#10879]
I made test1 files for running parity

and

test2 files with test1 file's enode.

First I run test1 parity and attach http://127.0.0.1 with geth.

But it didn't work with different port number so I change ports same with test1.

And... it worked.. why?

Please answer me...

**Comment by joshua-mir** [comment]
Hey, @PeterKimG if you want real-time communication, you might want to use https://gitter.im/paritytech/parity

I believe `geth attach` uses the default rpc ports unless configured otherwise - so using a non-standard port will likely not work, while using a standard port will.
