### ISSUE TITLE
AuRa node for chain with one validator does not reorg if has valid block with greater timestamp

### ISSUE THREAD

**Issue by VladLupashevskyi** [paritytech/parity-ethereum#10871]
- **Parity Ethereum version**: 2.5.5-stable, 2.5.3-beta, 2.4.6-stable, 2.4.9-stable
- **Operating system**: MacOS / Linux
- **Installation**: homebrew / one-line installer
- **Network**: custom aura with 1 validator
- **Restarted**: yes

Network members:
- **V** - validator node - has V,S1,S2 enodes in reserved peers and chain json
- **S1**, **S2** - nodes on server - have V,S1,S2 enodes in reserved peers and chain json
- **L** - local node - has only V enode in reserved peers and chain json

The issue happened when V node was restarted, it generated block B with timestamp T1, it got propagated to S1 and S2 (L was offline at that time), but this block hasn't been stored in V db (probably because of not graceful restart). After booting V has generated new block B, but with different timestamp T2 and continued mining blocks on top of new B.

S1 and S2 were stuck on the old block B(T1) and were not reorganized to the longest chain probably because they had block B with lower timestamp.

When I was trying to figure out the reason of this issue, I resynced S1 and S2 many times (not both at once) and they were getting stuck on this B(T1) again and again. The L node was syncing well (I noticed that reserved peers differ only during investigation).

The issue disappear only when I killed dbs on S1, S2 at the same time and let them resync (so there is no info about block B(T1) anywhere).

Although it's not recommended to use chain with 1 validator and this issue probably wouldn't appear on chain with more validator, I believe it worth at least checking the code where these checks happen in the code, because if this happens either all network participants need to kill dbs at once or the validator would need to do that (which might lead to loosing some transactions if was noticed late). I think it should reorg if it sees the longest chain even with greater timestamp in this case.

I would appreciate if somebody could have a quick look at the logic there (maybe it will be easy fix) or share the place in the code so I could also take a look at it (was having troubles finding it by myself).

**Comment by joshua-mir** [comment]
Thanks for the detailed report!

**Comment by joshua-mir** [comment]
The finality logic is described here: https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/engines/authority_round/finality.rs for aura - as you can see, if greater than half of authorities sign a chain it is considered finalized.

**Comment by VladLupashevskyi** [comment]
@joshua-mir Thank you very much for a quick reply. This explains a lot.

I would propose to add a line to the AuRa [documentation](https://wiki.parity.io/Aura) which would explicitly explain that and also note that it's not recommended to have it chain with one validator, because unexpected things can happen due to instant finality.

**Comment by joshua-mir** [comment]
https://github.com/paritytech/parity-ethereum/blob/34cdeac2a6a58f029c12cd89839b492e0ee4ee4f/ethcore/src/engines/validator_set/simple_list.rs#L38

Technically we already have some warnings about that - these are present in 2.6.0 beta for clarity.
