### ISSUE TITLE
Provide "num_workers" configuration option

### ISSUE THREAD

**Issue by ghost** [paritytech/parity-ethereum#10872]
re #10085 

`num_workers` is currently hard-coded to 4 
https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/util/io/src/service_mio.rs#L198_

A configuration-option should be provided, with a default of 4.

## Implementation

Look at the `num_verifiers` config option as a guideline.

## Compatibility

Using a default of 4, the behavior should be the same

**Comment by lazaridiscom** [comment]
@joshua-mir , this one is related to #10085 (which is still unsolved, possibly closed by automatism).

**Comment by debris** [comment]
eventually we want to get rid of `util/io` so this feature is not a priority
