### ISSUE TITLE
ethkey doesnt compile as a Cargo dependency

### ISSUE THREAD

**Issue by felipeargento** [paritytech/parity-ethereum#10894]
_Before filing a new issue, please **provide the following information**._
- **Parity Ethereum version**: 2.5.5
- **Operating system**:  Linux

**actual**:
Building parity-ethereum as a Cargo dependency on either master or stable branch fails with the following error - while compiling ethkey (v0.3.0):

`error[E0277]: the trait bound rand::OsRng: secp256k1::rand::RngCore is not satisfied`

Cloning the repository and using Cargo build directly on it is successful, but adding it to another projects Cargo.toml as a dependency produces this error.

**expected behavior**:
Should be able to compile normally as a cargo dependency without any errors.

**steps to reproduce**:
* Create a dummy project.
* Add a Cargo.toml with `ethkey = { git = "https://github.com/cartesi/parity-ethereum", branch = "stable" }` dependency.
* Add lib.rs with extern crate ethkey;.
* Run Cargo build

**how to fix**:
Modify eth-secp256k1 inside accounts/ethkey/Cargo.toml:
Change:
`eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1" }`
To: 
`eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1", rev = "ccc06e7" }`

**Comment by ordian** [comment]
@felipeargento `parity-ethereum` master (and beta) branch uses the `rand 0.6` and hence the latest revision of `eth-secp256k1` (https://github.com/paritytech/parity-ethereum/blob/14e7641835f2ece9d9fef66e6be53cce360d9c53/Cargo.lock#L776). For stable branch, a revision of `eth-secp256k1` is fixed inside of the `Cargo.lock`. We could add a `rev` to stable branch though to make it work for lib crates that depend on stable branch.

**Comment by niklasad1** [comment]
Fixed by https://github.com/paritytech/parity-ethereum/pull/11239
