### ISSUE TITLE
Implement retesteth for Parity Ethereum

### ISSUE THREAD

**Issue by sorpaas** [paritytech/parity-ethereum#10896]
cc @ledgerwatch

To implement the retesteth protocol in parity, we can do it in a similar way how it is done in go-ethereum. Basically, implement it as an entirely separate program with separate RPC methods. The program initializes a `Client` struct without any other services, and can just operate on the RPC thread for simplicity. When we need to set new config parameters, drop the existing `Client` and create a new one.

**Comment by grbIzl** [comment]
Duplicate for #10844 ?
