### ISSUE TITLE
There are too many transactions in the queue: v2.5.0

### ISSUE THREAD

**Issue by jbunce** [paritytech/parity-ethereum#10912]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.5.0
- **Operating system**: Linux
- **Installation**:  built from source (for rinkeby.json support) & Dockerised
- **Fully synchronized**: yes
- **Network**: Rinkeby
- **Restarted**: yes

We run blockchain services that use Parity with a substantial number of RPC usage (~1 million calls over a 24 hour period)

We run a gas price selection mechanism in an attempt to use lower gas on the root chain (Ethereum). This means that the same smart contract function is called, with the same nonce but slowly increasing the gas price until the transaction is picked up by a miner. This is one of the reasons we put pressure on Parity and this has resulted in:

`There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.`

Three questions:

1) This puts pressure on our application as it has to retry the same call until successful. We haven't configured `--tx-queue-size` yet. Is there a recommended value for this sort of load? Should we be using this with `--tx-queue-mem-limit` or separately? Do you have a ballpark figure we can use (per transaction/bytes) so we can set some sensible figures here?

2) According to https://wiki.parity.io/Transactions-Queue#dropping-logic the default dropping strategy is `gas_price`. How long do these transactions take to drop? Are they held in memory until the drop occurs?

3) Using `parity_allTransactions` in a test setup:

```
import requests

headers = {
    'Content-Type': 'application/json',
}

data = '{"method":"parity_allTransactions","params":[],"id":1,"jsonrpc":"2.0"}'

response = requests.post('http://localhost:8545', headers=headers, data=data)
```

```
len(all_transactions['result'])
4550
```

Where are these transactions stored? In memory or disk? What's the performance impact of holding a large transaction history here? Can we flush them somehow?

Thanks!

**Comment by joshua-mir** [comment]
1) transactions can vary wildly in size but the *minimum* is a little bit over 100 bytes per transaction. You should probably be using the two simultaneously - both are maximums, so you will likely be running at less than configured for both of those limits. 

2) transactions that are dropped are "dropped" immediately (a more accurate description would be "swapped out for" a higher rated transaction) 

3) parity_allTransactions responds with all of your pending transactions - (and yes, stored in memory iirc - but flushed to disk occasionally unless you are using `--no-persistent-txqueue` - which is one solution to flush transactions from your txpool, but requires you restart your node)

**Comment by jbunce** [comment]
Thanks for the fast response @joshua-mir! I'll try that and report back :)

**Comment by jbunce** [comment]
This was really useful @joshua-mir. `--no-persistent-txqueue` has a significant memory usage reduction and we're no longer getting that exception. If you're at DevCon in Osaka I'll buy you a beer! Cheers
