### ISSUE TITLE
Receipt for failed Wasm contract deployment includes contract address

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/parity-ethereum#10925]
When the creation of a Wasm contract exhausts its gas the transaction receipt includes the contract address. I would expect the contract address to be `null`

I deployed the `step-5` wasm contract from [`pwasm-tutorial`](https://github.com/paritytech/pwasm-tutorial) manually supplying to little gas. The receipt for the contract creation transaction included the following fields (some are omitted):
~~~json
{
  "root": "0x",
  "status": "0x0",
  "cumulativeGasUsed": "0xf4240",
  "contractAddress": "0x7c276dcaab99bd16163c1bcce671cad6a1ec0945",
  "gasUsed": "0xf4240",
  "from": "0x00a329c0648769a73afac7f9381e08fb43dbea72",
  "to": null
}
~~~
The `status` field clearly indicates that the transaction failed but the contract address is still provided. I’m not sure whether this is consistent with other ethereum implementations (assuming the same problems for EVM contracts) and whether `null` should be returned as the address if the contract is not created.

This behavior of `parity-ethereum` became a problem when using the [`rust-web3` client](https://github.com/tomusdrw/rust-web3). The client does not check the status field, instead it uses the presence of `contractAddress` [to determine whether a contract was successfully deployed](https://github.com/tomusdrw/rust-web3/blob/7c80ad3368d9a6d32ea92a91bca963268a16b9c2/src/contract/deploy.rs#L124-L125). I’m also opening an issue there.

I ran `parity --config dev` and used the development account.

---

- **Parity Ethereum version**: 2.6.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: dev
- **Restarted**: yes

**Comment by tjayrush** [comment]
This 'non-created' contract address has been part of the receipt since forever. It happens if the constructor throws or reverts (as best as we can tell). I don't think it can be changed in just Parity though. Aren't the contents of the receipt under consensus? (Just asking, don't know for sure.)

**Comment by joshua-mir** [comment]
Indeed - if the contract address wasn't in the receipt of a failed transaction, pwasm semantics wouldn't match the evm. Receipts are part of consensus.
