### ISSUE TITLE
Using parity for Exchange node

### ISSUE THREAD

**Issue by streetcrypto7** [paritytech/parity-ethereum#10934]
Hello, I would like to ask which sync mode should I use for exchange's node

I need a state db of erc20 contracts in order to enable deposit and withdrawal function of exchange.

I am referring this article https://dev.to/5chdn/the-ethereum-blockchain-size-will-not-exceed-1tb-anytime-soon-58a however I still can't figure out the right configuration for my node.

**Comment by joshua-mir** [comment]
@streetcrypto7 - erc-20 token transfers emit event logs, which should be available in any sync mode with the https://wiki.parity.io/JSONRPC-eth-module#eth_getlogs rpc method - the only reason you would need a heavier sync mode (like `--pruning archive --tracing on`) is if you want to enable your users to deposit Ether into your exchange *from smart contracts*, this is because you may need to look into internal transactions - even then you should just be able to occasionally poll the balance of deposit addresses if you don't care about the address that sent the funds to the deposit address.

**Comment by streetcrypto7** [comment]
@joshua-mir I've searched for the source code, and we don't use eth_getlogs for fetching erc20 transactions

![캡처](https://user-images.githubusercontent.com/52137633/62316544-aff96600-b4d2-11e9-97b7-b4b486e88cd7.PNG)

Instead we use `eth_getTransactionReceip`t and `eth_call`

**Comment by joshua-mir** [comment]
The answer doesn't change - you appear only to be using information from the `latest` block - that shouldn't require any node outside of the default.

**Comment by streetcrypto7** [comment]
@joshua-mir Right now I've tested with `eth_call` api with ropsten testnet, parity warp sync without ancient blocks configuration.

```
curl http://127.0.0.1:8545\
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_call","params": [{"to": "0x3e65b905f341208cd48df5f0da8e3e1aa231595e","data": "0x70a08231000000000000000000000000d8a7bec43a36c376d4b5735c98ba4cc0679bb7c0"}, "latest"],"id":1}'

{"jsonrpc":"2.0","result":"0x","id":1}
```

While infura does
```
curl https://ropsten.infura.io/v3/2ef32c821f5e4a5e974484ad97251471\
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_call","params": [{"to": "0x3e65b905f341208cd48df5f0da8e3e1aa231595e","data": "0x70a08231000000000000000000000000d8a7bec43a36c376d4b5735c98ba4cc0679bb7c0"}, "latest"],"id":1}'

{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000000000000000000000000000000000e8e686b300"}
```

**Comment by joshua-mir** [comment]
@streetcrypto7 are you already in sync? You can either use warp or `--no-warp` - a `--light` client probably will not be sufficient for your usecase. There is no sync mode secure enough to use in an exchange other than that.

**Comment by streetcrypto7** [comment]
I've finished the sync with warp mode but it is insufficient for dealing with ERC20 contracts, so I am trying with `--no-warp` instead of warp mode.

`--light` client of course is not a case for me 😂

**Comment by streetcrypto7** [comment]
@joshua-mir I've finished the sync with warp mode but it is insufficient for dealing with ERC20 contracts, so I am trying with `--no-warp` instead of warp mode.

`--light` client of course is not a case for me 😂

**Comment by Genysys** [comment]
Warp works eventually. It would go to the head of the chain and back fill.  When this returns nil, you would have fully synced and be able to query historic er20 contracts: https://wiki.parity.io/JSONRPC-parity-module#parity_chainstatus

**Comment by streetcrypto7** [comment]
@genysys How about '--no-ancient-block' option should I use them?

**Comment by joshua-mir** [comment]
@streetcrypto7 that's probably not secure enough to run an exchange on top of, at least on initial sync - it is trivial for someone to send you a bad snapshot of the chain and unless you manually compare blockhashes you won't know you are not on the correct network. Also you will have no historical block data (but it doesn't look like you are using it, so that might not be relevant).

Ultimately it's up to you to decide if that's in your threat model.

**Comment by streetcrypto7** [comment]
@joshua-mir I am not very interested for p2p or network security, I just want to know if the states for erc20 contract is availsble or not?

**Comment by joshua-mir** [comment]
Only unpruned states, same as a warp or no-warp sync. You can't get historic data unless you run an archive node. Can you confirm that you are only querying states in the `latest` block? Otherwise you likely need to run an archive node, which is significantly more resource intensive.

**Comment by streetcrypto7** [comment]
@joshua-mir So with `--no-warp -no-ancient-blocks' and after some time with parity_chainstatus returns nil I will be able to use eth_call for erc20 right? I will only use latest status right

**Comment by joshua-mir** [comment]
Yes. If you are still seeing nil on the latest block after you are in-sync, that is an issue and should be reported.

**Comment by streetcrypto7** [comment]
@joshua-mir Do you know how to understand the `parity_chainstatus` api?

```
curl http://127.0.0.1:8545\
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"parity_chainStatus","params":[],"id":1}'

{"jsonrpc":"2.0","result":{"blockGap":["0x1","0x5d27a9"]},"id":1}
```

What does this, `"blockGap":["0x1","0x5d27a9"` means?

I've synced from block 1 to 6105001 ?

**Comment by joshua-mir** [comment]
@streetcrypto7 https://wiki.parity.io/JSONRPC-parity-module#parity_chainstatus

You have a gap in the chain from 1 to 6105001 - you have synced however many blocks your normal logs say you have after 6105001

**Comment by streetcrypto7** [comment]
I've tested and parity warp default mode works fine with ERC20 contract, thank you!
