### ISSUE TITLE
The client is unable to import blockchain in hex format.

### ISSUE THREAD

**Issue by adilimroz** [paritytech/parity-ethereum#10942]
- **Parity Ethereum version**: 2.6.0
- **Operating system**: Linux
- **Installation**: Built from source
- **Fully synchronized**: Yes
- **Network**: Goerli
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
**Steps to reproduce**

1. Export the blockchain in hex format.
2. Delete the data for the chain and try importing the exported .hex format blockchain.
Observe the import doesn't work.

![BlockchainImportHex](https://user-images.githubusercontent.com/5220489/62415986-70588880-b650-11e9-8df0-9f27fbfb3b86.png)

![Screenshot from 2019-07-31 14-47-12](https://user-images.githubusercontent.com/5220489/62415987-7484a600-b650-11e9-9acf-82470917838c.png)

**Comment by seunlanlege** [comment]
@adilimroz can you share your hex file?

**Comment by adilimroz** [comment]
@seunlanlege Sorry! somehow missed this. Its a 1.5G file. I'll try sending it to you over riot or may be google drive.

**Comment by adilimroz** [comment]
The hex file - https://drive.google.com/file/d/17DJW1iPlVvrgUP4dpckdrUPyOkiXqDDA/view?usp=sharing
