### ISSUE TITLE
Bad block detected: TemporarilyInvalid on mainnet sync

### ISSUE THREAD

**Issue by streetcrypto7** [paritytech/parity-ethereum#10947]
- **Parity Ethereum version**: 2.6.0
- **Operating system**: Linux
- **Installation**: release file
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

I can't start my Parity node due to the IO error.

See full log on https://pastebin.com/6gdpZEdU

**Comment by streetcrypto7** [comment]
I am using warp sync and `parity db reset` doesn't work either, what can I do? Sync from scratch again?

**Comment by joshua-mir** [comment]
@streetcrypto7 can you make sure your system clock is in sync?

**Comment by streetcrypto7** [comment]
I've just find out my server time is slower than my local computer ( about 1 minute late )

**Comment by streetcrypto7** [comment]
It works! After updating the NTP server list and syncing time parity now works fine, thank you again @joshua-mir !
