### ISSUE TITLE
Cannot add reserved peers

### ISSUE THREAD

**Issue by streetcrypto7** [paritytech/parity-ethereum#10944]
- **Parity Ethereum version**: 2.6.0
- **Operating system**: Linux
- **Installation**: release file
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

I've tried 2 methods to add reserved peers as described on wiki ( node.txt file & `parity_addReservedPeer` ), and here is what I got.

When I add them on file, the node doesn't connect to the peers that I've defined, and for the `parity_addReservedPeer` rpc,

```
ubuntu@ubuntu:~$ curl http://127.0.0.1:8545\
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"parity_addReservedPeer","params":["enode://053d2f57829e5785d10697fa6c5333e4d98cc564dbadd87805fd4fedeb09cbcb642306e3a73bd4191b27f821fb442fcf964317d6a520b29651e7dd09d1beb0ec@shinji.veox.pw:30303"],"id":0}'
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}
```

It returns `Method not found` error.

Any advice available?

**Comment by joshua-mir** [comment]
@streetcrypto7 do you have the parity_set api enabled in your config.json's [rpc] section?

**Comment by streetcrypto7** [comment]
@joshua-mir After enabling the api parity_addReservedPeer works now, however I don't know why the reserved peer in text file doesn't work

Here is the command line

```
/usr/bin/parity --no-periodic-snapshot --jsonrpc-interface=127.0.0.1 --jsonrpc-cors=all --jsonrpc-hosts=all --jsonrpc-apis=all --db-compaction=ssd --scale-verifiers --warp-barrier=8000000 --cache-size=10000  --reserved-peers="/home/ubuntu/.peer.txt"
```

**Comment by streetcrypto7** [comment]
I think those peers I've added are dead 😂 ( I've founded them on https://www.ethernodes.org/network/1/nodes to speed up sync ), thanks for your big help @joshua-mir !
