### ISSUE TITLE
is there no way to secure the RPC with user:pass?

### ISSUE THREAD

**Issue by krtschmr** [paritytech/parity-ethereum#10951]
i didn't find one, i can only find snippets to secure it via nginx:http_auth

in the docs i can't find anything.

does geth have something like that?
 literally every node we run has something like that, what's the thoughtprocess on the decisionmaking why ethereum doesn't need it?

**Comment by joshua-mir** [comment]
@krtschmr this isn't implemented natively in parity, you would need to enable it on a proxy of some kind - adding it to wouldn't make your node more secure as you would still need to have an additional layer to encrypt requests to your node, which would need a proxy anyway. 

 this is also why we don't recommend having node traffic be publicly accessible at all, especially if you use key management on the node (which we want to remove), as the passwords to decrypt your accounts would be transmitted over plaintext.

**Comment by krtschmr** [comment]
@joshua-mir so best way is to have the exchange-sever talk to the node-rpc via private ip?

**Comment by joshua-mir** [comment]
Yes. Make sure `hosts` or `interface` (in the [rpc] section of your config) only allows the node to be communicated with by the exchange server.
