### ISSUE TITLE
eth_sendTransaction deprecated and no response

### ISSUE THREAD

**Issue by azastrael** [paritytech/parity-ethereum#10950]
## Information

- **Parity Ethereum version**:v2.5.5-stable-3ebc769757-20190708/x86_64-linux-gnu/rustc1.35.0
- **Operating system**: 5.2.2-arch1-1-ARCH (Linux)
- **Installation**: pacman
- **Fully synchronized**: no
- **Network**: `dev` config
- **Restarted**: yes

## Steps to reproduce

Using the following files:
- `truffle.config.js`: https://gist.github.com/azastrael/81eba44100b4f9d46f5c057330782f00
- `2_1_initial_migration.js`: https://gist.github.com/azastrael/c10cc7ead95c637abac5c4fa6e5aa522
- `migrations/1_deploy_contracts.js`: https://gist.github.com/azastrael/e2b87a28a96a241f930a480d9a4113db
- `contracts/Migrations.sol`: https://gist.github.com/azastrael/dd19679e5e5e2496a65529c587709f8c
- `contracts/Test.sol`: https://gist.github.com/azastrael/3df7f56948864d0e1f1c71f729e98aca

Running the following commands (in two different terminals):
- `parity --chain dev --logging rpc=trace`
- `truffle deploy --verbose-rpc`

## Expected behavior

The contract should be deployed.

## Issue

I get the following logs:
- parity: https://gist.github.com/azastrael/4b373ba23c0f80e2b4ebb23d6ab0d5c6
- truffle: https://gist.github.com/azastrael/fdea6fde769c21f463a1ae42b835e436

As you can see, parity indicates in the logs that `eth_sendTransaction` is deprecated but doens't respond anything to truffle.

**Comment by joshua-mir** [comment]
@azastrael the account you are using to deploy your contract needs to be unlocked or the rpc call will remain hanging indefinitely.

**Comment by azastrael** [comment]
@joshua-mir Oh, sorry for that, then ^^'. Anyway, thank you! :)
