### ISSUE TITLE
VM execution error

### ISSUE THREAD

**Issue by andrewtoth** [paritytech/parity-ethereum#10959]
- **Parity Ethereum version**: 2.5.0
- **Operating system**: Linux
- **Installation**: dockerfile
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

Sent an `eth_call` with the following params:
```
    [ { from: '0x7758d79c8fa4747a44577b8780ed8534d5e1945f',
       to: '0x1985365e9f78359a9b6ad760e32412f4a445e862',
       data:     '0xa9059cbb000000000000000000000000392921d2168e70e19bfdabdcedbced3f8cd997ab000000000000000000000000000000000000000000000000000eebe0b40e8000' },
     'latest' ]
```

Expect a proper response. Receive `VM execution error`.

**Comment by joshua-mir** [comment]
@andrewtoth are you certain that in the case of this transaction, an execution error isn't the expected result? The transaction you are simulating with `eth_call` in this case is a token transfer of the REP token - but the account that is making the transfer has no REP so the transaction failing seems expected...

**Comment by andrewtoth** [comment]
Ah thanks makes sense.
