### ISSUE TITLE
[2.6.0-beta] Syncing stops intermittently, requiring parity restart

### ISSUE THREAD

**Issue by c0deright** [paritytech/parity-ethereum#10960]
- **Parity Ethereum version**: 2.6.0-beta
- **Operating system**: Linux
- **Installation**: binary from github releases page
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

## Expected behavior

parity-ethereum is importing blocks without interruption

## Actual behavior

parity-ethereum stopped importing/syncing. parity was syncing the same block for ~39 hours before i restarted it. It then synced that block without problems.

Logfile: [parity-2.6.0-beta-syncing-same-block-for-39-hours.txt](https://github.com/paritytech/parity-ethereum/files/3491887/parity-2.6.0-beta-syncing-same-block-for-39-hours.txt)

**parity did get out of sync after running 9h23m**

**Comment by c0deright** [comment]
Just happened again yesterday with this config change:

```
[network]
no_serve_light = true
```

Right now the node reports 10 connected peers but it is stuck syncing #8339200

[parity-sync-freeze.txt](https://github.com/paritytech/parity-ethereum/files/3496801/parity-sync-freeze.txt)

**Comment by dvdplm** [comment]
How much RAM does the machine have?

**Comment by c0deright** [comment]
4GB and as mentioned in https://github.com/paritytech/parity-ethereum/issues/10371#issuecomment-520802721 parity did consume almost all of that when I killed the process (not sure how much RAM was used by parity when it got out of sync.

Wouldn't parity print something in the log if there was no more memory to allocate?

**Comment by dvdplm** [comment]
Do you have any way of trying with more RAM than 4Gb?

**Comment by c0deright** [comment]
Yes, I can increase RAM by changing the type of that ec2 instance and will do so tomorrow.

Right now I'm testing v2.6.0 (since yesterday) as outlined in https://github.com/paritytech/parity-ethereum/issues/10962#issue-479607874 under **v2.6.0 connected only to my own v2.2.9 nodes**:

> v2.6.0 not directly connected to the internet but only to two of my v2.2.9 full nodes (`reserved_peers`) acting as "proxy"

With this config, parity did **not** get stuck this night. It's running fine for ~21 hours now whereas the above mentioned freezes occured after 9 or 13 hours. Will let it run a bit more and then change back to 'directly connected to the internet' with 8GB of RAM.

**Comment by c0deright** [comment]
@dvdplm 

Looks like upgrading the VM from 4GB to 8GB did the trick.

No more intermittend syncing that were happending with 4GB and no more freezing being stuck at a single block for a long time. Peer count is stable at the min level (`10/10 peers`, min=10, max=15) in contrast heavy fluctuation when running with 4GB of RAM.

Upgrading from 4GB to 8GB also resolved https://github.com/paritytech/parity-ethereum/issues/10962

FYI my config.toml contained

```
[footprint]
tracing = "off"
db_compaction = "ssd"
pruning = "fast"
cache_size = 2000
```

When reducing `cache_size` it might be able to run v2.6.0 at an increased possibility of higher disk IO, especially reads.

You might wanna note 8 GB of RAM as a requirement for running v2.6.0 or at least mention that 4 GB might result in strange - not obviously caused by low RAM - issues.

**Comment by dvdplm** [comment]
> You might wanna note 8 GB of RAM as a requirement for running v2.6.0 or at least mention that 4 GB might result in strange - not obviously caused by low RAM - issues.

Indeed, I believe even 8Gb is tight for some workloads.

Thank you for your patience and all the testing! :)
