### ISSUE TITLE
No traces available when in dev mode (instantSeal engine)

### ISSUE THREAD

**Issue by andrewtoth** [paritytech/parity-ethereum#10988]
#7686 Is now occurring when running in v2.5.5.

**Comment by dvdplm** [comment]
What was the last version you used where this worked?
Also: can you provide the full configuration you’re using?

**Comment by andrewtoth** [comment]
I haven't used this before.
`parity --config dev --jsonrpc-apis all --tracing on --pruning fast`

**Comment by andrewtoth** [comment]
I removed the `DevelopmentChain` folder and started again and I have traces now. I originally started without `--tracing on`, so it looks like it saved that.

**Comment by dvdplm** [comment]
Yeah that would explain it. Glad you figured it out. :)
