### ISSUE TITLE
How to stop Parity? 

### ISSUE THREAD

**Issue by sg552** [paritytech/parity-ethereum#10997]
How to stop parity in Linux ? 

I searched but got no answer. 

is it "kill -9 <parity process id>"  or  "kill -1 <parity pid> " ? 

according to this script: https://raw.githubusercontent.com/paritytech/parity/master/scripts/parity.service

I found it actually used this command:  "kill -1 <pid>"

**Comment by joshua-mir** [comment]
I would use `kill -1` as `-9` may cause data corruption and make it necessary to resync.

**Comment by sg552** [comment]
I used kill -1 and waited for more than 2 minutes, but the parity doesn't stop.

**Comment by joshua-mir** [comment]
That sounds like #10364 - in that case you would *have to* use `SIGKILL`/`kill -9` unfortunately. If you already gave "warning" to parity, it should be safe.

**Comment by dvdplm** [comment]
`kill -9` should not be needed and would be a bug i believe. Can you stop parity with Ctrl-c or is it “stuck “?

**Comment by sg552** [comment]
OK, it seems that to close an Parity daemon, we should : 

step1. $ kill -1 [pid]

step2. wait for several minutes.  (more than 90 s ?)

step3. if parity still alive, $ kill -9 [pid] 

I did the above steps yesterday, and it restarted and runs well now.

thank you all! 

@dvdplm   I am running Parity in daemon mode, so there's no place to input Ctrl + c.
