### ISSUE TITLE
Make a proper and fast impl of the blake2 compression function (F)

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-ethereum#11020]
As noted in #11017 we need to refactor the `util/eip-152` crate into something more rusty.

Our preference is to use an established blake2 library but none of the ones surveyed expose the compression function in their public API. We can go about this in a few different ways, in order of preference:

1. make our case with the library maintainers, and if one of them agrees, make a PR that exposes the compression function
1. fork an established library and make our changes there
1. lift the existing code for the F function from one of the established libraries and maintain it ourselves
1. write our own fast implementation, complete with simd support

Included in this task is adding benchmarks to the `util/eip-152` crate from #11017 so we can compare before/after.

**Comment by niklasad1** [comment]
@seunlanlege does https://github.com/paritytech/parity-ethereum/pull/11056 close this? Otherwise, please update the issue description
