### ISSUE TITLE
Validating Aura node crashes on startup with 2.5.8

### ISSUE THREAD

**Issue by ngyam** [paritytech/parity-ethereum#11063]
- **Parity Ethereum version**: 2.5.8
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: Volta Testnet (POA/Aura)
- **Restarted**: yes

Validator node crashed with this error message, when upgrading from 2.5.7 to 2.5.8 right at startup:
```
parity_1            | Loading config file from /parity/config/parity-signing.toml
parity_1            | Spec json is invalid: missing field `eip1108_transition_base` at line 142 column 21
parity_1            | Loading config file from /parity/config/parity-signing.toml 
```

Expectations: backward compatibility. it shouldn't be necessary to include the new EIPs if not needed

**Comment by niklasad1** [comment]
yes, this was bad sorry about it... I'm trying to implement something more `scalable` for changing `builtin prices` https://github.com/paritytech/parity-ethereum/pull/11039. I will consider it there.

**Comment by joshua-mir** [comment]
Looks like last grumbles are being sorted out in the open PR above 👆

There will be a format change for people who *do* use eip1108
The issue will be resolved for people who *do not* use eip1108

**Comment by ngyam** [comment]
Thanks for the update!
