### ISSUE TITLE
Docs - no_consensus flag not defined

### ISSUE THREAD

**Issue by pooleja** [paritytech/parity-ethereum#11064]
I am looking at the documentation, and I see references to the `no_consensus` flag, but it is not defined anywhere what this actually does.  Am I missing something in the docs?  If not, can we include what this flag does?

**Comment by joshua-mir** [comment]
@pooleja https://paritytech.github.io/parity-config-generator/ has more information, it's also available with [`parity -h`](https://wiki.parity.io/Configuring-Parity-Ethereum#cli-options-for-parity-ethereum-client) 

> Forces Parity to run even if there are known issues regarding consensus. Not recommended.
