### ISSUE TITLE
[json-tests] stStaticCall blockchain test failures

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-ethereum#11076]
After https://github.com/paritytech/parity-ethereum/pull/11054  the following JSON tests fail in [`stStaticCall`](https://github.com/ethereum/tests/blob/f386934ce509fa0a4dbd1c68421b3361b01b2efa/BlockchainTests/GeneralStateTests/stStaticCall/static_callBasic.json#L388) and are added to the list of skipped tests in `ethcore/res/ethereum/tests-issues/currents.json`.

```
"static_callBasic_d0g0v0_ConstantinopleFix",
"static_callBasic_d1g0v0_ConstantinopleFix",
"static_callBasic_d2g0v0_ConstantinopleFix",
"static_callBasic_d3g0v0_ConstantinopleFix"
```

Fix the tests and "un-skip" them.

**Comment by ordian** [comment]
Closed by #11083.
