### ISSUE TITLE
[json-tests] stReturnDataTest blockchain test failures

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-ethereum#11074]
After https://github.com/paritytech/parity-ethereum/pull/11054  the following JSON tests fail in [`stReturnDataTest/`](https://github.com/ethereum/tests/blob/f386934ce509fa0a4dbd1c68421b3361b01b2efa/BlockchainTests/GeneralStateTests/stReturnDataTest/returndatasize_after_successful_callcode.json#L2) and are added to the list of skipped tests in `ethcore/res/ethereum/tests-issues/currents.json`.

```
"returndatasize_after_successful_callcode_d0g0v0_ConstantinopleFix"
```

Fix the tests and "un-skip" them.

**Investigation**

The issue here is about the genesis block not matching the test expectation. We end up with a genesis block with hash `0x3d3cd0c74d5040bd64c4077146499e075459c7facf999ebfcc2eac2bd81183e9` and the test block expects the parent hash to be `0x43dd448195341d2b9ff0683061d5003dfdef21c9dd5f9132c71df9982664a2d2` and so the block import fails with an `UnknownParent` error. 
The genesis block is constructed using the state from the `pre` section of the test file. The `state_root` we calculate from this data, `0x66bfe5cd9198e024259b887599af885c4f03ec4925b854ddf8525c60f404068c`, does not match what the test expects, `0x7c3eb449ede11443a1e9d714c211702d5f6e73d0c41f5af8936f9567ffde1a0f`. 

This is likely what causes the genesis blocks `hash` to be wrong (indeed, the `genesisRLP` from the test file is identical to `spec.genesis_block().to_hex()` except for the `state_root`).

This is most likely the same bug as https://github.com/paritytech/parity-ethereum/issues/11075.

As far as I can tell we deserialize the data properly from disk.

**Comment by ordian** [comment]
Closed by #11083.
