### ISSUE TITLE
Incorrect EIP-712 Hashing for Arrays of Structs Inside Structs

### ISSUE THREAD

**Issue by ptescher** [paritytech/parity-ethereum#11087]
- **Parity Ethereum version**: 2.5.7
- **Operating system**: Windows / MacOS / Linux
- **Installation**: built from source
- **Fully synchronized**: n/a
- **Network**: n/a
- **Restarted**: n/a

Had an issue trying to use the EIP-712 code to encode some typed data. The hash of the typed  data differs from https://github.com/ethereumjs/ethereumjs-util which results in an incorrect recovery address. The JS one seems to match up with solidity so this appears to be a parity issue.

Here is an example of a failing payload: https://github.com/ptescher/parity-ethereum/blob/fix-eip-712-arrays/util/EIP-712/src/encode.rs#L600

**Comment by dvdplm** [comment]
Thank you for the report and the test case, that is really helpful. Have you by any chance had time to dig into the parsing code and have an hypothesis about what we might be doing wrong here?

**Comment by seunlanlege** [comment]
@ptescher what function in eth-util are you using? can't seem to find anything

**Comment by dvdplm** [comment]
@seunlanlege take a look here: https://github.com/ptescher/parity-ethereum/tree/fix-eip-712-arrays/util/EIP-712/js-comparison

**Comment by ptescher** [comment]
@dvdplm I took a quick look at the code but couldn't come up with anything. What is weird is that `PrimaryType -> Array(OtherType)` works but `PrimaryType -> OtherTypeA -> Array(OtherTypeB)` does not. Something with the recursion seems to break.
