### ISSUE TITLE
beta tag on docker hub still ships 2.6.2

### ISSUE THREAD

**Issue by KaiRo-at** [paritytech/parity-ethereum#11101]
It looks like something is broken in shipping docker containers on docker hug, as the "beta" tag still ships 2.6.2 (and apparently "stable" and "latest" also have not been updated in a month), which is especially problematic with the istanbul hardfork on the test networks, see https://hub.docker.com/r/parity/parity/tags

**Comment by s3krit** [comment]
Hi, this was due to an oversight after a change to our release procedure. I've subsequently resolved the situation, could you confirm that it is fixed on your end? Apologies for any inconvenience!

**Comment by KaiRo-at** [comment]
I thought it would be an oversight like that :)
Thanks, looks good both on the Docker Hub site and when actually pulling! \o/
