### ISSUE TITLE
Transaction receipt is missing information.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity-ethereum#11109]
- **Parity Ethereum version**: 2.5.9
- **Operating system**: Windows
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When fetching a transaction receipt immediately after getting the transaction hash in response to a `eth_sendRawTransaction` call, the receipt has null for a lot of values that should never be null.

An example receipt response for a simple 0 value transfer:
```json
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": null,
        "blockNumber": null,
        "contractAddress": null,
        "cumulativeGasUsed": "0x5208",
        "from": null,
        "gasUsed": "0x5208",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "root": null,
        "status": "0x1",
        "to": null,
        "transactionHash": "0x2083491971605336023db17f2446d2af1561d4a6f788b4f2a1742b0ce70694f7",
        "transactionIndex": "0x0"
    },
    "id": null
}
```
While `blockHash` and `blockNumber` are expected to be null, `from` and `to` should _not_ be null.  The `root` being null is also bizarre, I would expect it to return the pending block root `root`, though I can appreciate why that is `null`.

The problem persists with a non-0 value transfer as well.

**Comment by joshua-mir** [comment]
> 2.5.7 and 2.5.9 both have the problem.

**Comment by niklasad1** [comment]
@MicahZoltu are you using `eth_getTransactionReceipt` to fetch the receipt?

AFAIK, we either call to fetch the receipt:
1.  `pending_receipt` which returns RichReceipt (it is missing blockHash, blockNumber, to, from)
2.  `transaction_receipt` which returns LocalizedReceipt (it has all the fields)

Could it be the case that your response is from a `pending receipt`?

You could enforce to always use `transaction_receipt`  if you enable `geth compabiltity` by  the flag `--geth`

Meanwhile, I will try to reproduce this.

/cc @tomusdrw any pointers regarding this?

**Comment by MicahZoltu** [comment]
@niklasad1 After submitting a raw transaction, I would get a transaction hash in the response.  I would immediately call `eth_getTransactionReceipt` which returned an incomplete transaction receipt.

**Comment by niklasad1** [comment]
> I think root is correctly null, as we don't produce intermediate state roots after EIP98. Although we might consider just not returning the field at all if it's null (#[serde(skip_serializing_if = "Option::is_none")])

None of the types (LocalizedReceipt, RichReceipt or Recept) has the field `root` so I guess it is better to remove it completely?
