### ISSUE TITLE
Full sync extremely slow through sweeper blocks

### ISSUE THREAD

**Issue by DanTalksCrypto** [paritytech/parity-ethereum#11104]
- **Parity Ethereum version**: 2.6.4 beta
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum classic
- **Restarted**: no

My parity node is synchronising extremely slowly through the blocks where the sweeper was being run. It’s taken almost 24hrs to synchronise 1000 blocks. Is this to be expected as I’m falling behind the network now?

**Comment by joshua-mir** [comment]
@DanTalksCrypto yes, sync is generally really slow around the blocks the spurious dragon hardfork occurred over, you are literally reliving the ddos that happened over those blocks when syncing over that period.

**Comment by DanTalksCrypto** [comment]
@joshua-mir I’m not sure I know when the dragon hardfork was but it’s only in the last 48hrs where I’ve been having an issue - have been synchronised up to around block 8,888,000 and it’s crawling along since then. Is this the same as the dragon hardfork you mention?

**Comment by DanTalksCrypto** [comment]
@joshua-mir I'm on MacOS. Basically I was fully synchronised until block 8,881,000 broadly and then it's been crawling ever since. It's been since the sweeper script has been running through the network. It is this contract: https://blockscout.com/etc/mainnet/address/0x39856bb3305997ad7aca33f8b21a8af9b86b79f4/transactions

This screenshot is effectively what's happening:

![screenshot](https://user-images.githubusercontent.com/53815946/65988954-b54a4100-e480-11e9-8b59-768c38f79b0d.png)

Just crawling along and it moves up a block every 10mins or so

**Comment by dvdplm** [comment]
Do you know what the purpose of the sweeper contract is? Do you know if it misbehaves like this on other clients as well?

**Comment by joshua-mir** [comment]
Sorry, I'm being so slow today, I should have paid closer attention to your original report. My original description of the situation was correct @dvdplm @DanTalksCrypto, the spurious dragon hardfork occurred on the foundation chain and involved the same sweeping - ETC didn't activate the EIP that allowed the state pruning that happened during spurious dragon until just now (in the Atlantis hardfork) so when I said:
> you are literally reliving the ddos that happened over those blocks when syncing over that period.
That would be an accurate description of what is currently happening on the ETC network. After you get past the blocks that have sweeper transactions, sync will return to normal speeds, and you will begin catching up again.

**Comment by DanTalksCrypto** [comment]
Ahh I see now - bit frustrating but will continue to crawl through. Hope it picks up soon!!

**Comment by dvdplm** [comment]
@DanTalksCrypto I hope you're over the "hump"! :) Will close this now.

**Comment by stone212** [comment]
@DanTalksCrypto I have a related problem.  What command line option are you using to do a full sync?
