### ISSUE TITLE
can I run multiple parity instances on the same storage

### ISSUE THREAD

**Issue by ayrat555** [paritytech/parity-ethereum#11125]
Is it possible to run two parity instances:
1. The first one will be syncing the chain and serving json rpc requests.
2. The second one will be run on the same database but with parameter `--mode offline`. This node will be only serving json rpc requests.

**Comment by joshua-mir** [comment]
@ayrat555 not currently, no. You can run a light client and a full node on the same machine and set them up as reserved_peers for each other (along with `--ports-shift`) to have a similar experience to what you are describing. But currently two nodes accessing the same db will panic.
