### ISSUE TITLE
stuck block #8862447 

### ISSUE THREAD

**Issue by sicute** [paritytech/parity-ethereum#11131]
- **Parity Ethereum version**: Parity-Ethereum/v2.5.9-stable-06c7096-20190926/x86_64-linux-gnu/rustc1.36.0
- **Operating system**: Linux ubuntu 16.04 x64 
- **Installation**: one-line installer 
- **Fully synchronized**:  yes
- **Network**: classic
- **Restarted**:  yes

I have node parity stuck at #8862447 and Block restoring , i have shutdown and restart over and over  no luck it's happen almost 2 days.
 

> 019-10-05 01:53:28 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     70 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:33 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     73 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:38 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     74 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:43 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     76 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:48 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     63 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:53 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     65 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:53:56 UTC Block restoration at #7720000
> 2019-10-05 01:53:58 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     67 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:03 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     69 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:08 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     71 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:13 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     73 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:18 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     75 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:23 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     77 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:28 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     76 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:33 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     68 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
> 2019-10-05 01:54:38 UTC Snapshot initializing (824 chunks restored)  #8862447   82/100 peers     70 MiB chain    7 MiB db  0 bytes queue   57 KiB sync  RPC:  0 conn,    0 req/s,   15 µs
>

**Comment by joshua-mir** [comment]
You might want to run with `--no-warp` if you have already been in sync before.

**Comment by sicute** [comment]
if i change config.toml a--no-wrap when i try start parity always get this . and stuck at #8862447

> 2019-10-05 10:54:57 UTC Stage 5 block verification failed for #8862448 (0x0ce1…8d9d)
> Error: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x88672cc495eabddfdb65c2ef950f4f5b40544fc45e6994335e0e004be66b9268, found: 0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
> 2019-10-05 10:54:57 UTC
> Bad block detected: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x88672cc495eabddfdb65c2ef950f4f5b40544fc45e6994335e0e004be66b9268, found: 0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
> RLP: f90270f901fca012ff8176d910e3576f9b490d4b8492b2b54dfd4983d2bfffa098f9da9cf494b8a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794401e7cc468cd63279f8e6c135bd5d5f4a95015efa05715780e2f69a5b2d4f5e8f7723ef4140edef7c7c19f630af36105166fb4e4dba0bf9153c4bd542a65c10118edcd0725a08918e38a3e57c9fc208d97ec4680b13ba088672cc495eabddfdb65c2ef950f4f5b40544fc45e6994335e0e004be66b9268b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008346dda783873af08347e7c4825208845d968b3e80a0216b93924d702588b1b8691b352d042e6a9b372b57ee807cc03d45d97327cc65884284c0349d2997f9f86ef86c018504a817c8008252089404c7440a56262aa72a3fa9950161b99908ab05f4876c12d42e11400080819ea0063149e4879e2e1bce5c7877319feb5890fdc026f517e04a9667199330ab325ea0762e65a50cce6d091c405eab2eb04cfdfe43f00f8aa02d6ee3802fbc3d256b9ec0
> Header: Header { parent_hash: 0x12ff8176d910e3576f9b490d4b8492b2b54dfd4983d2bfffa098f9da9cf494b8, timestamp: 1570147134, number: 8862448, author: 0x401e7cc468cd63279f8e6c135bd5d5f4a95015ef, transactions_root: 0xbf9153c4bd542a65c10118edcd0725a08918e38a3e57c9fc208d97ec4680b13b, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [], state_root: 0x5715780e2f69a5b2d4f5e8f7723ef4140edef7c7c19f630af36105166fb4e4db, receipts_root: 0x88672cc495eabddfdb65c2ef950f4f5b40544fc45e6994335e0e004be66b9268, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 21000, gas_limit: 4712388, difficulty: 4644263, seal: [[160, 33, 107, 147, 146, 77, 112, 37, 136, 177, 184, 105, 27, 53, 45, 4, 46, 106, 155, 55, 43, 87, 238, 128, 124, 192, 61, 69, 217, 115, 39, 204, 101], [136, 66, 132, 192, 52, 157, 41, 151, 249]], hash: Some(0x0ce1cf7d3da6c85e07e79e83f4e7d611144c744f34d47717b11c2166bb488d9d) }
> Uncles:
> Transactions:[Tx 0] UnverifiedTransaction { unsigned: Transaction { nonce: 1, gas_price: 20000000000, gas: 21000, action: Call(0x04c7440a56262aa72a3fa9950161b99908ab05f4), value: 30420000000000000, data: [] }, v: 158, r: 2800962586307125882853035295398271538330940243461086448672783789619420017246, s: 53454892623926131632169371222072102001136555101602211882063383408082027899806, hash: 0xf51c577d76c420f1ca0b3b3fb3b2d06f0925a3b2469f378afe2f454d5783b5db }
> 
> 2019-10-05 10:55:00 UTC Public node URL: enode://1b6d3fd88384fdf02483acf0b9c19df2c682734b6e958de29154ae1a4ac4a8c43ec24d9136951c9e9f90f2d08ae4c933ef7d297f17ac8eb8d8c706539435762d@10.0.140.92:30303
> 2019-10-05 10:55:10 UTC Syncing #8862447 0x12ff…94b8     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #8862569    2/500 peers     75 KiB chain    7 MiB db  0 bytes queue  416 KiB sync  RPC:  0

**Comment by joshua-mir** [comment]
@sicute if you check in your `$BASE_DIR/chains/classic/network` folder, there should be a `nodes.json` file. Could you try removing that file and restarting your node? That log (it is not an error) means one of your peers is sending you an invalid block - you can either wait for your node to find good peers, or delete `nodes.json` to forget all of your existing peers and start looking for new ones.

**Comment by AlexRychkov** [comment]
I have the same problem with light node (parity 2.6.4-beta, ropsten).
It starts one or two weeks ago and restarts were useful. But now it just stuck some block.
I tried to redownload blockchain a few times. 

What possible to do to fix this?

**Comment by sicute** [comment]
my solustion was fresh install in computer and redownload and resync againt, because old block will be resync and patch  from latest block download  to block 1 it's waste time.

**Comment by sicute** [comment]
my solustion was fresh install in computer and redownload and resync againt, because old block will be resync and patch  from latest block download  to block 1 it's waste time.
