### ISSUE TITLE
RlpStream manipulation manually

### ISSUE THREAD

**Issue by saarshah** [paritytech/parity-ethereum#11144]
I am not sure should I post this query here or not. If its irrelevant place then suggest me as per my questions. 

I want to do some manipulation on RlpStream manually.  I am confused how it work. For example considered following program;

extern crate rlp;
use rlp::*;

fn main () {
let name = "amir";
let age: u8 = 38;
let fname = "ali";
let mut stream = RlpStream::new_list(3);
stream.append(&name).append(&age).append(&fname);
let out = stream.drain();
println!("My RlpStream : {:?}",out);
}

The output of above programe is :

My RlpStream : [202, 132, 97, 109, 105, 114, 38, 131, 97, 108, 105]

as you can see there are 11 bytes in rlp list, whereas my code has 8 byte [i.e. "amir" = 4 bytes, age=38 = 1 byte, and "ali"=3 bytes]. I know amir=97, 109, 105, 114, age = 38 and ali=97, 108, 105... then why and how 202, 132, and 131 are inserted ????? If we want to calculate these bytes manually, is there any method/formula ????
furthermore, it become more complex for me to understand if my variable are not just regular variables. For example, NetworkPack,  i.e. MyNeworkProto (srcIP= 111.111.11.11, dstIP, timeStamp: u64, Hash:H256,  etc.) then how these bytes are calculated ?

Although, i am following this link [1](https://github.com/ethereum/wiki/wiki/RLP#rd), but could not fully understand the concept. Anyone could elaborate  in detail for beginner user like me.

**Comment by joshua-mir** [comment]
So, as the link you provide states, RLP stands for Recursive Length Prefix, which means before every list of items (where each item can also be a list), there is a prefix based on it's total length.

 `0xc0` is what you add the length of the list to to if you have a list of items, and `0x80` is what you add the length of a string to if you have a string.

In this case, 202 is `0xc0` (192) +  the length of the total list (10); 132 and 131 are `0x80` (128) + the length of the two strings in your stream, 4 and 3 respectively.

There are other cases for longer strings and lists on that page as well.

**Comment by saarshah** [comment]
@joshua-mir Thanks for your detailed reply. I could understand for above simple scenario, but when it become complex for large list or large string, then things become confused .. For example, i have following output in hex form , which may be some port no (7e 43) and some may IP address , and etc. ;
f9 02 ccf9 02 c7 f8 4d 84 41 34 c8 86 82 7e 43 82 7e 43
 b8 40 44 88 39 f2 90 0f 4a 22 ce 61 1b d6 6a 4f
c9 3f 8f a0 2a 4b 18 56 79 ba 89 07 8c 0b f9 c6
c9 32 8d 3d f7 7c 4c 84 51 fc a1 2f 2a 8d aa b5
3b 8f 38 76 2c 14 d6 f2 4b a6 89 7a 9d dd 79 98
84 74 f8 4d 84 0d 42 16 b2 82 7e 43 82 7e 43 b8
40 54 e1 d4 6b 03 52 7d 79 98 6e 3c 88 4e 6e f6
ce c0 9c fc 54 8f 7a d2 0d 8f 0c 99 63 96 cb e0
4b ea d6 f6 89 82 2e ae 2a b7 8b 08 e2 be 36 03
71 67 9d 94 f4 1f c7 56 45 ae 16 6c 55 7c 3c d7
e4 f8 4d 84 17 60 6c 60 82 7e 43 82 7e 43 b8 40
9a 3b 64 f2 65 2f e7 3d 57 3f a7 bd 87 7f 4f 02
f9 6f bc 4e 22 87 73 1b 59 d0 35 0f 80 a4 a2 43
7f 43 cd 06 70 96 b0 b3 af d6 e1 4a 5a f5 92 9c
97 19 af e4 2f d4 2c 11 43 de ea 99 42 fc 6d 38
f8 4d 84 34 8f b1 71 82 7e 43 82 7e 43 b8 40 20
71 29 bb a5 01 e6 a0 aa 8b e6 64 21 df c9 98 4f
f0 8d 9d 2d 14 f2 4c 4d b6 51 b3 e9 0e f7 7d 53
15 ab 4f 49 ef 7a 62 20 8d 95 96 c8 72 48 b6 e7
bf 25 88 6e 36 e2 a7 9a 0a e7 22 75 14 93 97 f8
4d 84 34 e7 a2 a7 82 7e 43 82 7e 43 b8 40 ca dd
4a ab b3 5b e7 ed bd 1c 8e 60 13 1c 90 eb 9c ec
50 2a 35 65 23 41 90 b7 92 29 22 00 78 38 ca f6
55 6f b3 2e 3e 53 fd 98 51 0f 78 9a 50 5b 68 db
4c 95 89 9d 6b 29 e2 06 c7 ad 3f 87 b1 06 f8 4d
84 2f 5d f1 d9 82 7e 43 82 7e 43 b8 40 7f ff f7
f1 4f 8f 73 fa 93 a9 53 09 80 3b bc 93 c7 62 c4
8b c8 73 a8 23 ac 40 50 04 71 ce 2e 3f f5 b5 af
36 c5 c7 f0 be f4 7c ec 4e 28 4c 40 ec 97 66 20
b6 94 1e c9 27 b0 08 91 ab c0 64 6a 65 f8 4d 84
0d 45 ba 2a 82 7e 43 82 7e 43 b8 40 99 91 bd 3f
5d 0e 61 4a 3f cc 86 40 fd fc be fb c0 e9 5d e7
fa 68 ba ff 4c b9 5f 86 14 fa 16 2b 08 0a 49 7b
ca 50 37 19 69 20 bf 68 ed 25 54 60 5f 29 b3 8b
a2 39 0b 4b c8 de 91 da c9 1e ab 34 f8 4d 84 27
6b 7f 44 82 7e 43 82 7e 43 b8 40 47 bd 00 be d8
e3 9e 51 fc 94 ed ca 06 7c f7 a0 d2 3c 67 68 98
41 a5 e9 43 7e 51 f4 30 c9 8e 46 3b 6c af 0d 8b
ed 25 76 39 36 20 ef ab ee 2a 53 19 02 93 87 59
d9 2e e2 89 a4 d8 ae 82 77 d2 54 f8 4d 84 7b 38
61 ab 82 7e 43 82 7e 43 b8 40 bd e6 28 10 1f a2
24 42 2b 48 4f f7 cd c4 48 3a a4 18 5c 98 cd f7
4f f1 1b 20 c0 cb e5 07 5d ae 8d bb 2e db 0a 60
f2 2d 94 f7 80 03 df 4b 2f 08 f9 42 c7 b1 d4 b7
84 04 a0 83 e4 6e e5 d7 8a ee 01 80

So could you show/distinguish  me which byte is here is for showing the length of list/string,  and which is itself a string ... ?  Is it possible for your to just differentiate list/string and RLP encoding bytes ? I shall be very thankful.

**Comment by joshua-mir** [comment]
```
 RLP encoding is defined as follows:

For a single byte whose value is in the [0x00, 0x7f] range, that byte is its own RLP encoding.

Otherwise, if a string is 0-55 bytes long, the RLP encoding consists of a single byte with value 0x80 plus the length of the string followed by the string. The range of the first byte is thus [0x80, 0xb7].

If a string is more than 55 bytes long, the RLP encoding consists of a single byte with value 0xb7 plus the length in bytes of the length of the string in binary form, followed by the length of the string, followed by the string. For example, a length-1024 string would be encoded as \xb9\x04\x00 followed by the string. The range of the first byte is thus [0xb8, 0xbf].

If the total payload of a list (i.e. the combined length of all its items being RLP encoded) is 0-55 bytes long, the RLP encoding consists of a single byte with value 0xc0 plus the length of the list followed by the concatenation of the RLP encodings of the items. The range of the first byte is thus [0xc0, 0xf7].

If the total payload of a list is more than 55 bytes long, the RLP encoding consists of a single byte with value 0xf7 plus the length in bytes of the length of the payload in binary form, followed by the length of the payload, followed by the concatenation of the RLP encodings of the items. The range of the first byte is thus [0xf8, 0xff].
```

Any byte greater than `0x7f` is a representation of length.
