### ISSUE TITLE
Question: Stage 5 block verification failed during normal syncing

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity-ethereum#11149]
Greetings!

I got many times `Stage 5 block verification failed` log entries during normal syncing with  `Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0`. The syncing works well.

Maybe some miners creating bad blocks?

I run the parity with the following parameters:
```
--cache-size 2048 --ipc-apis all --tracing on --no-serve-light --no-periodic-snapshot --jsonrpc-allow-missing-blocks --no-persistent-txqueue --jsonrpc-server-threads 32 --min-gas-price=10000000 --tx-queue-mem-limit=4096 --tx-queue-size=256000 --reseal-on-txs=all --force-sealing --base-path "/mnt/node-1/eth" --rpcport 8548 --port 30306 --no-ws --no-secretstore
```
Here is the log:
https://www.fusionsolutions.io/doc/ethstage.tar.gz

**Comment by gituser** [comment]
got the same issue, parity devs its URGENT look at it!

we're missing transactions and not crediting user deposits because of this issue

**Comment by dvdplm** [comment]
> Maybe some miners creating bad blocks?

Yes I believe this is the case. I have seen two such bad blocks in the last couple of days but syncing proceeds and the node has not been otherwise affected.
