### ISSUE TITLE
parity account new does not ask for password

### ISSUE THREAD

**Issue by stone212** [paritytech/parity-ethereum#11157]
- **Parity Ethereum version**: 2.3.9
- **Operating system**: Linux
- **Installation**: binary
- **Fully synchronized**: yes
- **Network**: Private Blockchain
- **Restarted**: yes

A parity node that has a config.toml file set up for mining (unlocked account and passwod) does not prompt for a new password when running `parity account new`.

Is this a feature that is not documented?  Does it default to the existing password or something like this?

**Comment by seunlanlege** [comment]
can you share your `config.toml`

**Comment by stone212** [comment]
@seunlanlege 

> If you have a password file set in the config, you won't be prompted for a password.

That is what I guessed (please see above) but I don't see that in the docs.  Could you send a link or maybe the doc can be updated with this?

Also how do I override this because not every account should have the same password?

**Comment by joshua-mir** [comment]
@stone212 it is mentioned throughout this page https://wiki.parity.io/Configuring-Parity-Ethereum and also in the parity config generator (paritytech.github.io/parity-config-generator) and help text. This file can either be a single value, or a single password per line of the file (this is stated in the config generator).

**Comment by stone212** [comment]
>  it is mentioned throughout this page https://wiki.parity.io/Configuring-Parity-Ethereum 

What?  I just looked at that page now.  I don't see this mentioned there even one time.

What is still not clear is: when you create a new account, and it does not prompt for a password, is it using the password in the file?  What if you have more than one?  Will it ask me to choose?  If this is answered in those pages you sent please tell me the text to search for because I do not see it and I just looked at both links.

**Comment by joshua-mir** [comment]
@stone212 all of the command line options (ie, `parity account new`) use the default config unless you specify differently - I agree with you that this is not clear enough in the docs for this specific case. This means, as you've figured, that if you have a password specified in a password file, the first one will be used instead of asking you for a password the same as using a password file for all other password prompts (ie, unlocking accounts).

**Comment by stone212** [comment]
@joshua-mir 

>  the first one will be used instead of asking you for a password t

Okay yes.  And that is what I assumed until you reminded me that there can be multiple passwords in the file.  So this answers this Issue.  It automatically uses the first one.

Really I think the issue is that the `parity` CLI is not fully documented unless there is something I am not seeing (the wiki search sometimes misses things).

This is off-topic but related: it would help to have  a way to override this when you do `parity account new`?  I can't think of any situation where I would want to re-use a password, but it is also inconvenient to turn the node off, change the config, re-start, change the config back, re-start.

**Comment by joshua-mir** [comment]
Adding options to the cli automatically overrides config file options, but if I understand you, you want to disable the password file via a cli option?

**Comment by stone212** [comment]
@joshua-mir 

Yes that is what I mean.  Override the default use of the password file but instead prompt for one.  The CLI does not give any indication that this is possible.  Where would the "empty string" go?  This is what you see when you want more info on the CLI.

```
# /home/parity/parity account --help
parity-account 
Manage accounts

USAGE:
    parity account <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

OPTIONS:


SUBCOMMANDS:
    import    Import accounts from JSON UTC keystore files to the specified --chain (default mainnet)
    list      List existing accounts of the given --chain (default: mainnet)
    new       Create a new account (and its associated key) for the given --chain (default: mainnet)
```
