### ISSUE TITLE
Same config - different disk usage

### ISSUE THREAD

**Issue by AlexRychkov** [paritytech/parity-ethereum#11150]
I have two nodes and they have different disk usage behavior that demonstrated on pics below
[First](https://imggmi.com/full/2019/10/9/fc5eea6e90bdcf10e8c0bfe95b214ac5-full.png.html)
[Second](https://imggmi.com/full/2019/10/9/773a84aa42250f26b625f879a6ec1e45-full.png.html)

If pics not loading:
The first have satisfactory behavior - for the last two days disk was used from 133 to 136 Gb with an average of 134;
But the second has strange behavior - for the last two days disk was used from 102 to 179 Gb with an average of 136.

Configs are the same. Blockchain was loaded at different times. 
How to make disk usage on the second node like on the first node?

**First**

one core & 2 Gb ram before 9 October and now 2 core & 4 ram
Parity Ethereum version: 2.5.7
Operating system: Linux
Installation: one-line installer
Fully synchronized: yes
Network: ethereum
Restarted: no

**Second**

two cores & 4 Gb ram
Parity Ethereum version: 2.5.9
Operating system: Linux
Installation: one-line installer
Fully synchronized: yes
Network: ethereum
Restarted: no

**Comment by dvdplm** [comment]
I don’t think there’s an anomaly here tbh. Disk usage is not deterministic and no two computers behave exactly the same.
