### ISSUE TITLE
Error while syncronizing

### ISSUE THREAD

**Issue by panicape** [paritytech/parity-ethereum#11154]
- **Parity Ethereum version**: v2.6.2-beta-25936ae-20190829/x86_64-linux-gnu
- **Operating system**: Ubuntu 18.06
- **Installation**:  installed from console/terminal
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

I'm  just trying to syncronize with: parity --chain=kovan and it is saying DB Corrupted and shows this:
stack backtrace:
   0:     0x55fc7b8b596d - <no info>
   1:     0x55fc7b8b29ae - <no info>
   2:     0x55fc7bb9c617 - <no info>
   3:     0x55fc7b8fd60a - <no info>
   4:     0x55fc7b8fd37e - <no info>
   5:     0x55fc7b91a7a5 - <no info>
   6:     0x55fc7b92084b - <no info>
   7:     0x55fc7ab48ff6 - <no info>
   8:     0x55fc7b375730 - <no info>
   9:     0x55fc7ad450d1 - <no info>
  10:     0x55fc7ad2d9a3 - <no info>
  11:     0x55fc7ad2ef9c - <no info>
  12:     0x55fc7ad2a509 - <no info>
  13:     0x55fc7ad2ec8e - <no info>
  14:     0x55fc7b91932e - <no info>
  15:     0x55fc7b91c53f - <no info>
  16:     0x7fb414b326da - <no info>
  17:     0x7fb41423788e - <no info>
  18:                0x0 - <no info>

Thread 'IO Worker #2' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 1126033476, got 1529842151  in /home/panicape/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/200469.sst offset 4810471 size 11442") }', src/libcore/result.rs:999

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

**Comment by dvdplm** [comment]
Looks like a bad harddrive. Do you have the possibility to try on a different one?
