### ISSUE TITLE
Critical: Parity spontaneously shuts down

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity-ethereum#11156]
Greetings, I have used `Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0` Parity. Now i have upgraded to the latest stable release (Parity-Ethereum/v2.5.9-stable-06c7096-20190926/x86_64-linux-gnu/rustc1.36.0).

I face with the issue on today morning at `2019-10-10 09:28:23` with the older parity that spontaneously quits and closes the process. After restarting the node, the issue comes back within 5-15 min.

The `syslog` is empty, memory more than enough, disk is okay, no other process closes the service.

Here are the logs:
https://www.fusionsolutions.io/doc/shutdown.tar.gz

**Comment by iFA88** [comment]
update: The issue is affected on both ETC and ETH node. And my archive node which uses only reversed peers are not affected. Maybe there is some magic packet which causes shutdown?

**Comment by iFA88** [comment]
Thanks for the fast support. Yes both parity versions are affected.

No updates happening, no script are affected for parity process or even the service.

I will try now starting from command line.

**Comment by iFA88** [comment]
Okay from the terminal we have at least an error:
```


====================

stack backtrace:
   0:     0x56420b8642ed - <no info>
   1:     0x56420b86139e - <no info>
   2:     0x56420b8d8247 - <no info>
   3:     0x56420b8a69d4 - <no info>
   4:     0x56420b8a674e - <no info>
   5:     0x56420b8c3375 - <no info>
   6:     0x56420b8c93bb - <no info>
   7:     0x56420abc2b36 - <no info>
   8:     0x56420b31944f - <no info>
   9:     0x56420abf2391 - <no info>
  10:     0x56420b18116b - <no info>
  11:     0x56420b147f2b - <no info>
  12:     0x56420b184317 - <no info>
  13:     0x56420b21efb4 - <no info>
  14:     0x56420b8c20be - <no info>
  15:     0x56420b8c4d4b - <no info>
  16:     0x7ff2bec074a3 - <no info>
  17:     0x7ff2be732d0e - <no info>
  18:                0x0 - <no info>

Thread 'Verifier #8' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("IO error: No space left on deviceWhile appending to file: /mnt/node-1/eth/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/2003780.log: No space left on device") }', src/libcore/result.rs:999

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


```

The ETH and the ETC produces the same error. I have 50GB free space.

**Comment by iFA88** [comment]
ETC rocksdb log:
https://www.fusionsolutions.io/doc/LOG
It seems they want to compile 1342633163 byte data..
I will try write 10-20gb to the disk, maybe that has some fault..

**Comment by dvdplm** [comment]
> It seems they want to compile 1342633163 byte data..

Compile? Not sure I understand.

**Comment by dvdplm** [comment]
Ah, you mean compaction? I see, yeah, rocksdb suffers from something called "deferred write amplification" where it reorganizes data into new files. This can require quite a lot of space. Really odd that the diskspace error did not show up in your logs though. 
Can you verify that your logging setup doesn't swallow stderr somehow? e.g. by provoking a deliberate error `parity --db-path=/some/inexistent/path` and check that the error shows up in your log?

**Comment by iFA88** [comment]
Sorry my wrong, i mean Rocksdb compact:
```
2019/10/10-11:27:08.882671 7f8777fff700 [/ci-cache/parity-ethereum/cargo/build-linux/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.5/rocksdb/db/compaction_job.
cc:1535] [col0] Compaction start summary: Base version 27 Base level 5, inputs: [765175(64MB)], [746516(64MB) 746517(64MB) 746518(64MB) 752734(64MB) 752735(64MB) 752736(64MB) 75
2737(64MB) 758092(64MB) 758093(64MB) 758094(64MB) 758095(64MB) 758096(64MB) 758097(64MB) 758098(64MB) 758099(64MB) 758100(64MB) 758101(64MB) 758102(62MB) 638742(64MB)]
2019/10/10-11:27:08.882689 7f8777fff700 EVENT_LOG_v1 {"time_micros": 1570699628882678, "job": 4, "event": "compaction_started", "compaction_reason": "LevelMaxLevelSize", "files_
L5": [765175], "files_L6": [746516, 746517, 746518, 752734, 752735, 752736, 752737, 758092, 758093, 758094, 758095, 758096, 758097, 758098, 758099, 758100, 758101, 758102, 63874
2], "score": 1.00461, "input_data_size": 1342633163}
```
I have successfully wrote 25gb `urandom` data to the disk so its not full.

**Comment by iFA88** [comment]
I have 25GB left and now I can not even start the node:
`Error upgrading parity data: CannotUpdateVersionFile(Os { code: 28, kind: Other, message: "No space left on device" })`

**Comment by dvdplm** [comment]
Yeah I bet rocksdb wants to finish the compaction before proceeding. While this is annoying I don't think it's a bug.

**Comment by iFA88** [comment]
OK looks like someting went wrong to my system. Thanks for the support! I will close now this issue.
