### ISSUE TITLE
No warp after block #8030000 (current block 8721800+)

### ISSUE THREAD

**Issue by AdvancedStyle** [paritytech/parity-ethereum#11165]
- **Parity Ethereum version**: 2.5.9 & 2.6.4-beta
- **Operating system**: Ubuntu 18
- **Installation**:  Linux 64 release
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

I've tried to sync a new node on every different machines and get the same result every time

When start parity with default settings (no flags) it is only downloading 3306 snapshots, which ends at block #8030000, when their are currently over 8700000 blocks.... it then starts syncing every block individually at a rate of about 0.5-3 blocks/seconds (depends on how powerful of a machine).  Which is going to take a very long time to sync the remaining 700,000 blocks.

I've tried running `parity --warp-barrier 8700000`, but that doesn't work, the node just sits there doing nothing and outputting something like this:

```
2019-10-12 00:30:37    16/25 peers   832 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    8 req/s,   45 µs
2019-10-12 00:31:07    25/25 peers   832 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    2 req/s,   26 µs
2019-10-12 00:31:37    25/25 peers   832 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    1 req/s,   32 µs
2019-10-12 00:32:07    25/25 peers   832 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    6 req/s,   27 µs
```
 
I've tried increasing the peers, such as `parity --warp-barrier=8700000 --snapshot-peers=100 --max-peers=100` but still doesn't work.

**Comment by dvdplm** [comment]
Yeah, there seems to be a dearth of full nodes offering snapshots lately. Not something we can fix easily I'm afraid. :/

**Comment by dvdplm** [comment]
If you want to run a full node, the only answer is "get faster hardware". Alternatively consider running a light node.
And when/if you do reach the tip, please consider running with `--snapshot-peers` set to a non-zero value to share your own snapshot to others in your same situation. Providing snapshots is a community effort and if nobody does, there are none to use. :/

**Comment by AdvancedStyle** [comment]
What's "faster hardware"?  One of the nodes is a c4.8xlarge node on AWS (which is pretty beefy, 32 cores +  60GB RAM)...even that can only achieve 3 blocks/second once it hits the end of snapshots.
