### ISSUE TITLE
Subscribing to 'syncing' does not return 'currentBlock' and 'highestBlock'

### ISSUE THREAD

**Issue by liamaharon** [paritytech/parity-ethereum#11168]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.6.3-beta-b7b1484-20190916
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**expected**
When subscribing to `sync` updates like this
```
web3.eth.subscribe('syncing')
  .on("data", function(sync) {
    // show some syncing stats
  })
});
```
(see https://web3js.readthedocs.io/en/v1.2.0/web3-eth-subscribe.html#subscribe-syncing)

`sync` should be the same result as if `web3.eth.isSyncing()` was called

```
web3.eth.isSyncing()
.then(console.log);
> {
    startingBlock: 100,
    currentBlock: 312,
    highestBlock: 512,
    knownStates: 234566,
    pulledStates: 123455
}
```

**actual**
when the node is syncing, `sync` is 
```
{ syncing: true,
  startingBlock: undefined,
  currentBlock: undefined,
  highestBlock: undefined }
```
I expected `currentBlock`, `startedBlock`, `highestBlock` not to be `undefined`

**Comment by dvdplm** [comment]
Sounds like an issue with the web3 js-library. Can you elaborate on how this is caused by a bug in `parity-ethereum`?

**Comment by seunlanlege** [comment]
actually, this is intended behavior. subscribing to `syncing` only notifies you when syncing state changes, as it would be too expensive to trigger a notification whenever a new block is imported.

**Comment by liamaharon** [comment]
Thanks
