### ISSUE TITLE
instantSeal engine wont seal more than one block

### ISSUE THREAD

**Issue by tristan** [paritytech/parity-ethereum#11173]
- **Parity Ethereum version**: >=2.5.8
- **Operating system**: Archlinux (kernel 5.3.6)
- **Installation**: pacman (for <=2.5.9) and built from source (for 2.6.4)
- **Fully synchronized**: N/A
- **Network**: custom instantSeal ([Chain file](https://gist.github.com/tristan/64cc72a211910000f71eefba3dff8876))
- **Restarted**: yes

After upgrading to 2.5.9 I noticed that my instantSeal network would no longer seal more than one block. i.e. The first transaction submitted correctly creates a new block, but after submitting a second transaction nothing happens.

I created a script to test this which can be found [here](https://gist.github.com/tristan/6d02fca748413c4855a9210c46d817a6). The script checks the parity version, creates the relevant chain file, starts parity, then attempts to submit a number of transactions, checking they have been included in a block before continuing to the next. Using parity 2.5.7, the script runs to completion as expected. Upgrading to 2.5.8 and later (including 2.6.4), the script will get stuck forever waiting for the 2nd block to be sealed.

From the logs (with `--logging own_tx=trace,rpc=trace,chain=trace,engine=trace,miner=trace,state=trace`) i see a bunch of things around the first transaction (which i don't really follow), but for the 2nd transaction all i see is the `Imported to the pool` message (from own_tx) and nothing else.

I've tried a bunch of different options including, different networkId, different starting nonces for my base account, different base accounts, sending the second transaction from a different account, none of which changed the outcome.

Parity is started using the following arguments
```
/usr/bin/parity 
    --port $PORT 
    --no-color
    --chain $TMP_DIR/chain.json 
    --author 0102030405060708090001020304050607080900 
    --tracing on 
    --node-key 74a32e8a5ea986ebb4becf4746a09b2bb7abb8ee09f6ead3bc4c0d8968fc27ed
    --base-path $TMP_DIR/data
    --jsonrpc-port $JSONRPC_PORT 
    --jsonrpc-hosts all 
    --ws-interface local 
    --ws-port $WS_PORT 
    --ws-origins all 
    --ws-hosts all 
    --min-gas-price 10000000000 
    --logging "own_tx=trace,rpc=trace,chain=trace,engine=trace,miner=trace,state=trace"
```
The chain file used can be seen [here](https://gist.github.com/tristan/64cc72a211910000f71eefba3dff8876).

**Comment by seunlanlege** [comment]
Hi @tristan the script you provided was very useful thank you for that.

The reason `InstantSeal` won't seal blocks when you send a transaction is because of command-line argument defaults `--reseal-max-period` which defaults to `120 seconds` and `--reseal-min-period` which defaults to `2 seconds`

In a future release, `parity-ethereum` will handle this automatically by setting them to zero for the `InstantSeal` engine. But for now, please run with these extra options `--reseal-max-period 0 --reseal-min-period 0` so `InstantSeal` can seal blocks immediately.

**Comment by tristan** [comment]
Thanks @seunlanlege ! adding these options fixed things for me.
