### ISSUE TITLE
Can no longer filter transactions with RPC API

### ISSUE THREAD

**Issue by lamafab** [paritytech/parity-ethereum#11189]
- **Parity Ethereum version**: v2.7.0-nightly-6960d35ab-20191019
- **Operating system**: Ubuntu 19.04
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Yesterday I was contacted by a stranger about a PR I did a few months ago #10506. The RPC API `parity_pendingTransactions` was able to accept filtering parameters in the following form:

```
{
    "from": {
        "eq": "0x5f3dffcf347944d3739b0805c934d86c8621997f"
    },
    "to": {
        "eq": "0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"
    },
}
```

This no longer seems to be the case. It's also not documented in the [docs](https://wiki.parity.io/JSONRPC-parity-module#parity_pendingtransactions). The changed I made are still part of the codebase.

**How to reproduce**
1. Run the parity node
2. Make the following RPC request:
```
curl --data '{"method":"parity_pendingTransactions","params":[{"from":{"eq":"0x5f3dffcf347944d3739b0805c934d86c8621997f"},"to": {"eq":"0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"}}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
3. The node returns the following error message:
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: map, expected usize."},"id":1}
```

**Expected behavior**
The node should return the filtered transactions (if any).

Please clarify whether this feature is actually intended to work/should have been implemented.

Thanks.

**Comment by lamafab** [comment]
I assume it has to do with the following definitions/parameters:

_rpc/src/v1/traits/parity.rs_
```
#[rpc(name = "parity_pendingTransactions")]
fn pending_transactions(&self, _: Option<usize>, _: Option<FilterOptions>) -> Result<Vec<Transaction>>
```

_rpc/src/v1/impls/parity.rs_
```
fn pending_transactions(&self, limit: Option<usize>, filter: Option<FilterOptions>) -> Result<Vec<Transaction>> {
```

**Comment by niklasad1** [comment]
Hey @lamafab 

Thank you such awesome bug report, however, it seems like the bug was introduced by https://github.com/paritytech/parity-ethereum/commit/3f61f2d8d9632d85838833da665d16ff6fdcb804
and has nothing to do with `removal of anonymous traits params`

1. 
```bash 
curl --data '{"method":"parity_pendingTransactions","params":[{"from":{"eq":"0x5f3dffcf347944d3739b0805c934d86c8621997f"},"to": {"eq":"0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"}}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
I think that deserialization will never work because it will be deserialized to Array[FilterOptions] in that case so either `params: [null, {}]` or something else would work I guess

2. 
```bash
[
    5,
    {
        "from": {
            "eq": "0x5f3dffcf347944d3739b0805c934d86c8621997f"
        },
        "to": {
            "eq": "0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"
        },
    }
]
```
Don't really but must be something sneaky with deserialization

**Comment by lamafab** [comment]
Thanks for the feedback. When I implemented and tested it, the `curl` requests went just fine. Maybe some upstream changes with the deserialization process? I don't know, I can look into this some more later.

**Comment by lamafab** [comment]
@niklasad1 Here you go  #11192. Fixing this was much easier than expected :)
