### ISSUE TITLE
Log settings changes via RPC.

### ISSUE THREAD

**Issue by afck** [paritytech/parity-ethereum#11199]
It would be helpful if the logs showed whenever settings were changed via the RPC interface.

Do you mind if I add `info!` logs to the methods in [`rpc/src/v1/impls/parity_set.rs`](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/impls/parity_set.rs)?

**Comment by niklasad1** [comment]
> We don't see any trace!(target: "rpc"... lines in the code, so it seems such messages are not provided in logs.

Right, it is hidden in the `jsonrpc crate` and not documented I guess, see https://github.com/paritytech/jsonrpc/blob/master/core/src/io.rs#L194-#L216

**Comment by varasev** [comment]
Ah, ok, thanks. Let's close this issue then
