### ISSUE TITLE
[rpc api]: `eth_sign` with locked account don't indicate error/warning

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-ethereum#11194]
If I make an `eth_sign` request without unlocking my `default account` the RPC request doesn't return or indicate any error or warning which is not user-friendly. Because, if the account could not be unlocked it is added to the [SigningQueue](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/impls/signing.rs#L127-#L134) and held there forever if the future is never resolved?

Thus, I suggest either just add `warning account X is locked` or return an error in the `RPC` interface. 

Note, `SigningQueueClient::dispatch` is used by several signing methods but I think bail early when the account is locked, is safe and is an enhancement.

**Comment by dtran320** [comment]
Still seeing this with `parity 2.5.9`. If it's helpful, running this on geth returns a `-32000` with the error message `unknown account`
