### ISSUE TITLE
I am running synchronization with Parity, when I disconnect the server from my client-side ssh interface, will the synchronization process be interrupted?

### ISSUE THREAD

**Issue by manhluna** [paritytech/parity-ethereum#11207]
- **Parity Ethereum version**: Lastest
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

**I am running synchronization with Parity, when I disconnect the server from my client-side ssh interface, will the synchronization process be interrupted?**

**Comment by joshua-mir** [comment]
Answered on gitter, run `parity daemon` or use our service file https://wiki.parity.io/FAQ.html#can-i-run-parity-ethereum-as-a-daemon-or-system-service
