### ISSUE TITLE
[devp2p] Unused `rustc_hex` import in devp2p implementation

### ISSUE THREAD

**Issue by jmcph4** [paritytech/parity-ethereum#11215]
- **Parity Ethereum version**: 2.7.0 (Parity-Ethereum/v2.7.0-unstable-0d3423cbe-20191028/x86_64-linux-gnu/rustc1.38.0)
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

## Actual Behaviour ##
When building from source on `master`, Rust complains of an unused import on this line:

https://github.com/paritytech/parity-ethereum/blob/0d3423cbe0b70964aa33d2c71685e663adae0315/util/network-devp2p/src/host.rs#L40

### Steps to Reproduce ###

    $ git clone git@github.com:paritytech/parity-ethereum.git
    $ cd parity-ethereum
    $ cargo run
    ...
       Compiling ethcore-network-devp2p v1.12.0 (/home/jmcph4/dev/deps/parity-ethereum/util/network-devp2p)
    warning: unused import: `rustc_hex::ToHex`
      --> util/network-devp2p/src/host.rs:40:5
       |
    40 | use rustc_hex::ToHex;
       |     ^^^^^^^^^^^^^^^^
       |
       = note: `#[warn(unused_imports)]` on by default
    ...

# Expected Behaviour #

Absence of any compilation errors and warnings.

**Comment by niklasad1** [comment]
@jmcph4 If you want to make an easy contribution just remove it and submit a PR

**Comment by dvdplm** [comment]
There is [this call to `to_hex()`](https://github.com/paritytech/parity-ethereum/blob/master/util/network-devp2p/src/host.rs#L1240) but tbh I'm not sure it comes from `rustc-hex`.

**Comment by niklasad1** [comment]
@dvdplm https://github.com/paritytech/parity-common/blob/master/parity-crypto/src/publickey/secret_key.rs#L86-#L89

Thus, should be fine to remove :P

**Comment by jmcph4** [comment]
This is fixed as at least 1b4d23fd2.
