### ISSUE TITLE
Error message comes up upon shutting down the client.

### ISSUE THREAD

**Issue by adilimroz** [paritytech/parity-ethereum#11214]
- **Parity Ethereum version**: 2.5.9 and other recent releases
- **Operating system**: Windows / MacOS / Linux
- **Installation**: built from source

**Steps to reproduce**

1. Try shutting down a running parity-ethereum client with Ctrl+C keyboard combination.
    Observe that the client shuts down but with a message
     `"unable to get mut ref for engine for shutdown"`

![Screenshot from 2019-10-28 23-56-45](https://user-images.githubusercontent.com/5220489/67706386-ab175600-f9de-11e9-89e6-c2b5898aec5a.png)

**Comment by dvdplm** [comment]
Probably over-zealous logging.

I suspect this is fixed on master or not shown in all modes of operation. @adilimroz do you see this even when just starting `parity` with default params? Or just when e.g. import/exporting blocks?

**Comment by niklasad1** [comment]
@adilimroz this should be fixed by #10691 and #10683

You can try https://github.com/paritytech/parity-ethereum/tree/v2.5.10-stable to verify

**Comment by adilimroz** [comment]
Thanks @niklasad1 . Verified in master as well.
