### ISSUE TITLE
WARN parity_rpc::v1::impls::eth  Fallback to `BlockId::Latest`

### ISSUE THREAD

**Issue by vogelito** [paritytech/parity-ethereum#11261]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.5.6-stable-ff398fe-20190812/x86_64-linux-gnu/rustc1.37.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Hi,

I'm seeing a lot of log lines that look like this:
```
2019-11-13 20:43:27 UTC jsonrpc-eventloop-0 WARN parity_rpc::v1::impls::eth  Fallback to `BlockId::Latest`
2019-11-13 20:43:32 UTC jsonrpc-eventloop-1 WARN parity_rpc::v1::impls::eth  Fallback to `BlockId::Latest`
2019-11-13 20:43:37 UTC jsonrpc-eventloop-0 WARN parity_rpc::v1::impls::eth  Fallback to `BlockId::Latest`
2019-11-13 20:43:42 UTC jsonrpc-eventloop-1 WARN parity_rpc::v1::impls::eth  Fallback to `BlockId::Latest`
```

I have a feeling this is because I'm not supplying some argument to an RPC call. Do you have documentation regarding that warning or any pointers as to where to look?

We definitely make a lof of RPC calls to this node.

Thanks in adavanced.

**Comment by joshua-mir** [comment]
@vogelito this warning can generally be ignored - if you make a query to [one of these methods](https://wiki.parity.io/JSONRPC-eth-module#the-default-block-parameter) specifying the `pending` block, and you don't *have* a pending block (you only have a pending block as a miner or block producer), the call falls back to the latest block.

**Comment by vogelito** [comment]
Understood! Thanks for the info. We'll just change those calls to `latest` instead of `pending`
