### ISSUE TITLE
Always been wrong KERNELBASE.dll windows

### ISSUE THREAD

**Issue by kkxiaodi** [paritytech/parity-ethereum#11275]
I found the same Windows version system, one computer can, the other one can not, whether it is related to hardware. Always been wrong KERNELBASE.dll

![image](https://user-images.githubusercontent.com/5546440/69299151-cfb3c600-0c4a-11ea-82a2-de0cae52ff0c.png)

![image](https://user-images.githubusercontent.com/5546440/69299183-e528f000-0c4a-11ea-8b9d-31979447b5f1.png)

**Comment by dvdplm** [comment]
Hello! I am sorry, but I do not understand what this report is about. Can you explain again, please?
