### ISSUE TITLE
(CentOS 7.x) Parity v2.6.6 & v2.7.0: Fails to Sync New Blocks After App Interruption & Relaunch

### ISSUE THREAD

**Issue by ymonye** [paritytech/parity-ethereum#11297]
#### Versions 
* OS: CentOS 7.7.1908
* Hardware: Dell PowerEdge R720 (Red Hat / CentOS 7.x is the latest supported OS)
* Storage: 9.6 TB SSD RAID-5 Array
* Parity v2.7.0-nightly-71f4f61-20191202
* Rustc 1.39.0

I re-built this version of Parity using the steps in the link below, as this was the only way to get a proper build on CentOS 7.x:
https://github.com/paritytech/parity-ethereum/issues/11291#issuecomment-560034022

Parity is able to fully compile and execute using the below commands:

`parity --pruning=archive --fat-db=on --tracing=on --db-compaction=ssd --keys-path=/data/ethereum/parity/mainnet/ --db-path=/data/ethereum/parity/mainnet/ --ipc-path=/data/ethereum/parity/mainnet/jsonrpc.ipc`

However, if I were to stop Parity (within the terminal window) at any place and attempt to re-sync, parity fails to sync any new blocks. In summary, the only way I can get Parity to sync on this machine is if I run it for the first time and _NEVER_ stop the application or close my terminal window.

Can anyone please explain why this is happening? Below is what I see under the console:

> 2019-12-04 17:59:04  Syncing #1223495 0x1a82…1a73     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed     #2517    2/25 peers   72 KiB chain 0 bytes db 0 bytes queue 761 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
> 2019-12-04 17:59:09  Syncing #1223495 0x1a82…1a73     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed     #3024    2/25 peers   72 KiB chain 0 bytes db 0 bytes queue 665 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
> 2019-12-04 17:59:14  Syncing #1223495 0x1a82…1a73     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed     #3537    2/25 peers   72 KiB chain 0 bytes db 0 bytes queue 766 KiB sync  RPC:  0 conn,    0 req/s,    0 µs

Thanks

**Comment by dvdplm** [comment]
If you’re running in archive mode you’ll want your node to keep running for a very long time (it takes weeks to sync on fast hardware) and you probably should look into using parity as a daemon using whatever facilities your OS provides for that. Also consider setting up some alerting/monitoring so you don’t run out of disk space. 
I am not entirely sure what your question is though so perhaps you can help me out by elaborating a bit more? You can start and stop your node whenever you want and it will pick up the sync where it left off.

**Comment by ymonye** [comment]
@dvdplm, it's very simple.

I've run archive nodes before, no issues. There's no way it'll fill up a 9.6TB RAID array anytime soon, and already have proper monitoring in place, that's a separate issue from what I'm addressing here.

If I were to run Parity from terminal and stop at a later point, which can be anywhere from 10 seconds to 1 day after running (either via Ctrl+C or closing terminal all-together), then re-attempt to run Parity with the same commands to re-sync from where I left off... Parity refuses to sync new blocks.

I don't know if this is an issue with the OS or something else.

**Comment by dvdplm** [comment]
> Parity refuses to sync new blocks.

What do you mean by "refuses"? Is the problem that the node does not find any peers?

You can try running parity with `-l discovery` to glean more info about what your node is seeing on the network.

> 
> I don't know if this is an issue with the OS or something else.

It could be related to the network setup, but it sounds odd that it works the first time and never again. Did you try syncing a different network (and not in archive mode)? Same issue?

**Comment by ymonye** [comment]
Hey again @dvdplm. I went ahead and upgraded my version of Parity to the latest (that supported Istanbul), and now I have a completely different issue. I am unable to build this on my machine.

I can't continue with this current issue until this new one is resolved:
https://github.com/paritytech/parity-ethereum/issues/11326

"CentOS 7.x (7.7.1908) - Parity v2.7.0 Installation: failed to run custom build command for `librocksdb-sys v6.2.4"

**Comment by ymonye** [comment]
Hey again @dvdplm. I was able to get Parity v2.6.6 built on this machine. I've also renamed this thread to include the issue on both v2.6.6 & v2.7.0.

To answer your earlier question, my blk/s (according to the terminal) remains at 0.00 after a 2nd sync attempt, even though terminal is showing at least 1 peer connected. Here are the parameters I'm sending to parity. I'd tried a series of different combinations (fast sync / no tracing, fat-db, or cache-size / default db-path), and this problem persists regardless of the sync configs... including a parity launch with no parameters.

`parity --pruning=archive --fat-db=on --tracing=on --db-compaction=ssd --cache-size=32768 --port=30306 --jsonrpc-port=8549 --ws-port=8550 --keys-path=/data/ethereum/parity/mainnet/ --db-path=/data/ethereum/parity/mainnet/ --ipc-path=/data/ethereum/parity/mainnet/jsonrpc.ipc -l discovery`

Here's a pastebin of what I see after adding -l discovery. On my first attempt, I'd closed down parity at block 154560. As you can see in this pastebin, parity only displays the previously synced block 154560 and only repeats that value while showing 0.00 blk/s:

https://pastebin.com/C8uZ8gVm

**Comment by ymonye** [comment]
Here's the pastebin for the v2.6.6 build process on CentOS 7.x, particularly for my own notes:
https://pastebin.com/3V0s3Ngf

During the build process, a lot of these warnings were thrown... perhaps breaking Parity in the process:

> warning: trait objects without an explicit `dyn` are deprecated

**Comment by dvdplm** [comment]
> During the build process, a lot of these warnings were thrown... perhaps breaking Parity in the process:

No, warnings have no impact on the machine code generated and that one in particular, while annoying, is innocuous (should also be fixed on master).

**Comment by ymonye** [comment]
Ok thanks.

Yeah it's been over a day and Parity hasn't synced any new blocks. Shows 1/25 peers. Again, this only happens if I were to manually interrupt the client... meaning if I were to launch Parity for the 1st time to sync at block zero, I better leave & pray my terminal window never closes or machine never loses power. 🤔

**Comment by ymonye** [comment]
I was able to resolve this by creating a text file with the enodes of my other existing archive nodes, then adding the following argument to my parity client:

`--reserved-peers nodes.txt`

Not sure what exactly was going on, but there's a good chance there was an issue with my networking somewhere.
