### ISSUE TITLE
Can't build master branch of parity-ethereum!!!

### ISSUE THREAD

**Issue by Suhar777777** [paritytech/parity-ethereum#11295]
Hi. Try to build from source master branch of parity-ethereum, but buiding stoped. I used ubuntu server. Distributor ID: Ubuntu, Description: Ubuntu 18.04.3 LTS, Release: 18.04, Codename: bionic.
 
Console log:
sudo ~/.cargo/bin/cargo build --release --features final
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/app-dirs-rs`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
  Downloaded libc v0.2.62
  Downloaded slab v0.4.1
  Downloaded matches v0.1.8
  Downloaded tokio-timer v0.1.2
  Downloaded indexmap v1.3.0
  Downloaded bytes v0.4.12
  Downloaded serde_json v1.0.40
  Downloaded quote v0.6.8
  Downloaded time v0.1.40
  Downloaded crossbeam-deque v0.6.3
  Downloaded docopt v1.0.2
  Downloaded textwrap v0.9.0
  Downloaded parking_lot v0.9.0
  Downloaded enum_primitive v0.1.1
  Downloaded mio v0.6.19
  Downloaded crossbeam-utils v0.6.6
  Downloaded scopeguard v1.0.0
  Downloaded bincode v1.1.4
  Downloaded rustc_version v0.2.3
  Downloaded kernel32-sys v0.2.2
  Downloaded log v0.4.8
  Downloaded env_logger v0.5.13
  Downloaded ansi_term v0.11.0
  Downloaded arrayvec v0.4.11
  Downloaded smallvec v0.6.10
  Downloaded toml v0.4.10
  Downloaded arrayref v0.3.5
  Downloaded num v0.1.42
  Downloaded derive_more v0.15.0
  Downloaded atty v0.2.11
  Downloaded tempdir v0.3.7
  Downloaded lru-cache v0.1.2
  Downloaded byteorder v1.3.2
  Downloaded http v0.1.17
  Downloaded itertools v0.8.0
  Downloaded rayon v1.1.0
  Downloaded futures v0.1.29
  Downloaded rand v0.5.5
  Downloaded tokio v0.1.22
  Downloaded rand v0.7.2
  Downloaded clap v2.33.0
  Downloaded winapi v0.2.8
  Downloaded tiny-keccak v1.5.0
  Downloaded regex v1.3.1
  Downloaded cid v0.3.0
  Downloaded serde v1.0.99
  Downloaded bit-set v0.4.0
  Downloaded home v0.3.3
  Downloaded kvdb-memorydb v0.1.2
  Downloaded fdlimit v0.1.1
  Downloaded crunchy v0.2.2
  Downloaded primal v0.2.3
  Downloaded ethabi-contract v9.0.0
  Downloaded jsonrpc-tcp-server v14.0.3
  Downloaded validator_derive v0.8.0
  Downloaded mime v0.3.12
  Downloaded validator v0.8.0
  Downloaded trace-time v0.1.1
  Downloaded memmap v0.6.2
  Downloaded ethabi-derive v9.0.1
  Downloaded target_info v0.1.0
  Downloaded elastic-array v0.10.2
  Downloaded slab v0.2.0
  Downloaded siphasher v0.3.0
  Downloaded multihash v0.8.0
  Downloaded transient-hashmap v0.4.1
  Downloaded ipnetwork v0.12.8
  Downloaded vergen v3.0.4
  Downloaded memory-db v0.15.0
  Downloaded xdg v2.1.0
  Downloaded hash-db v0.15.2
  Downloaded jsonrpc-ipc-server v14.0.3
  Downloaded ethbloom v0.8.0
  Downloaded either v1.5.0
  Downloaded order-stat v0.1.3
  Downloaded rpassword v1.0.2
  Downloaded static_assertions v0.3.3
  Downloaded plain_hasher v0.2.0
  Downloaded triehash v0.8.0
  Downloaded pwasm-utils v0.6.1
  Downloaded trie-db v0.16.0
  Downloaded failsafe v0.3.0
  Downloaded derive_more v0.14.0
  Downloaded linked-hash-map v0.5.1
  Downloaded ethabi v9.0.1
  Downloaded jsonrpc-derive v14.0.3
  Downloaded jsonrpc-pubsub v14.0.3
  Downloaded mime_guess v2.0.0-alpha.6
  Downloaded failure v0.1.3
  Downloaded parity-wasm v0.31.3
  Downloaded parity-crypto v0.4.2
  Downloaded igd v0.9.0
  Downloaded unicase v2.2.0
  Downloaded proc-macro2 v0.4.20
  Downloaded hyper-rustls v0.16.0
  Downloaded parity-wordlist v1.3.0
  Downloaded itertools v0.7.8
  Downloaded wasmi v0.3.0
  Downloaded hyper v0.12.19
  Downloaded backtrace v0.3.9
  Downloaded syn v0.15.26
  Downloaded itertools v0.5.10
  Downloaded parity-snappy v0.1.0
  Downloaded num_cpus v1.10.1
  Downloaded transaction-pool v2.0.1
  Downloaded jsonrpc-http-server v14.0.3
  Downloaded parity-daemonize v0.3.0
  Downloaded serde_derive v1.0.89
  Downloaded jsonrpc-ws-server v14.0.3
  Downloaded timer v0.2.0
  Downloaded parity-bytes v0.1.0
  Downloaded kvdb-rocksdb v0.1.5
  Downloaded kvdb v0.1.0
  Downloaded term_size v0.3.1
  Downloaded parity-util-mem v0.2.0
  Downloaded rustc-hex v1.0.0
  Downloaded number_prefix v0.2.8
  Downloaded keccak-hash v0.4.0
  Downloaded jsonrpc-core v14.0.3
  Downloaded ethereum-types v0.8.0
  Downloaded rustc-hex v2.0.1
  Downloaded parity-path v0.1.1
  Downloaded lunarity-lexer v0.2.1
  Downloaded edit-distance v2.0.1
  Downloaded url v2.1.0
  Downloaded lazy_static v1.4.0
  Downloaded fnv v1.0.6
  Downloaded rlp v0.4.4
  Downloaded rand_xorshift v0.2.0
  Downloaded semver v0.9.0
  Downloaded tokio-current-thread v0.1.6
  Downloaded net2 v0.2.33
  Downloaded unicode-xid v0.1.0
  Downloaded tokio-fs v0.1.6
  Downloaded rand_core v0.5.1
  Downloaded block-modes v0.3.3
  Downloaded vec_map v0.8.1
  Downloaded cfg-if v0.1.10
  Downloaded quote v1.0.2
  Downloaded tokio-service v0.1.0
  Downloaded num-traits v0.1.43
  Downloaded percent-encoding v2.1.0
  Downloaded webpki v0.19.1
  Downloaded rand_core v0.2.2
  Downloaded nodrop v0.1.12
  Downloaded termcolor v1.0.4
  Downloaded bitflags v1.0.4
  Downloaded sha2 v0.8.0
  Downloaded tokio-codec v0.1.1
  Downloaded jemallocator v0.1.9
  Downloaded heck v0.3.0
  Downloaded remove_dir_all v0.5.1
  Downloaded num-iter v0.1.37
  Downloaded sha2 v0.7.1
  Downloaded winapi-build v0.1.1
  Downloaded ws v0.9.0
  Downloaded rand v0.4.6
  Downloaded idna v0.1.5
  Downloaded tokio-uds v0.2.5
  Downloaded itoa v0.4.3
  Downloaded num-integer v0.1.39
  Downloaded autocfg v0.1.7
  Downloaded tokio-udp v0.1.2
  Downloaded proc-macro-crate v0.1.4
  Downloaded syn v1.0.5
  Downloaded slab v0.3.0
  Downloaded humantime v1.1.1
  Downloaded strsim v0.7.0
  Downloaded parking_lot_core v0.6.2
  Downloaded tokio-timer v0.2.11
  Downloaded futures-cpupool v0.1.8
  Downloaded tokio-executor v0.1.8
  Downloaded crunchy v0.1.6
  Downloaded idna v0.2.0
  Downloaded proc-macro2 v1.0.1
  Downloaded want v0.0.6
  Downloaded parking_lot v0.6.4
  Downloaded h2 v0.1.26
  Downloaded unicase v1.4.2
  Downloaded num-bigint v0.1.44
  Downloaded backtrace-sys v0.1.24
  Downloaded hashbrown v0.6.3
  Downloaded multibase v0.6.0
  Downloaded heapsize v0.4.2
  Downloaded scrypt v0.2.0
  Downloaded primal-estimate v0.2.1
  Downloaded impl-rlp v0.2.0
  Downloaded integer-encoding v1.0.5
  Downloaded jsonrpc-server-utils v14.0.3
  Downloaded nan-preserving-float v0.1.0
  Downloaded ripemd160 v0.8.0
  Downloaded aes-ctr v0.3.0
  Downloaded logos v0.7.7
  Downloaded interleaved-ordered v0.1.1
  Downloaded rustc-demangle v0.1.9
  Downloaded if_chain v0.1.3
  Downloaded primal-check v0.2.3
  Downloaded memory_units v0.3.0
  Downloaded malloc_size_of_derive v0.1.0
  Downloaded tokio-tcp v0.1.2
  Downloaded fixed-hash v0.5.0
  Downloaded pbkdf2 v0.3.0
  Downloaded impl-serde v0.2.1
  Downloaded rand v0.6.1
  Downloaded rprompt v1.0.3
  Downloaded aes v0.3.2
  Downloaded chrono v0.4.6
  Downloaded rayon-core v1.5.0
  Downloaded iovec v0.1.2
  Downloaded version_check v0.1.5
  Downloaded tokio-threadpool v0.1.16
  Downloaded httparse v1.3.3
  Downloaded tokio-io v0.1.9
  Downloaded error-chain v0.12.0
  Downloaded failure_derive v0.1.3
  Downloaded parity-rocksdb v0.5.1
  Downloaded num-traits v0.2.6
  Downloaded xmltree v0.8.0
  Downloaded attohttpc v0.4.1
  Downloaded primitive-types v0.6.0
  Downloaded digest v0.8.0
  Downloaded uint v0.8.1
  Downloaded tokio-reactor v0.1.6
  Downloaded regex-syntax v0.6.12
  Downloaded fs-swap v0.2.4
  Downloaded phf v0.7.23
  Downloaded aho-corasick v0.7.6
  Downloaded hmac v0.7.0
  Downloaded crossbeam-epoch v0.7.2
  Downloaded thread_local v0.3.6
  Downloaded unicode-width v0.1.5
  Downloaded memchr v2.2.1
  Downloaded textwrap v0.11.0
  Downloaded sha1 v0.5.0
  Downloaded strsim v0.8.0
  Downloaded zeroize v0.9.3
  Downloaded ct-logs v0.5.1
  Downloaded lock_api v0.3.1
  Downloaded rand_chacha v0.2.1
  Downloaded ryu v1.0.0
  Downloaded tokio-sync v0.1.6
  Downloaded bit-vec v0.4.4
  Downloaded subtle v2.1.0
  Downloaded hashmap_core v0.1.10
  Downloaded phf_codegen v0.7.23
  Downloaded parity-tokio-ipc v0.2.0
  Downloaded primal-sieve v0.2.9
  Downloaded getrandom v0.1.11
  Downloaded tokio-rustls v0.9.0
  Downloaded parity-secp256k1 v0.7.0
  Downloaded url v1.7.1
  Downloaded rustls v0.15.1
  Downloaded webpki-roots v0.16.0
  Downloaded crossbeam-queue v0.1.2
  Downloaded rand_core v0.3.1
  Downloaded block-buffer v0.7.3
  Downloaded fake-simd v0.1.2
  Downloaded parking_lot_core v0.3.1
  Downloaded rand_hc v0.1.0
  Downloaded rand_xorshift v0.1.1
  Downloaded block-buffer v0.3.3
  Downloaded synstructure v0.10.1
  Downloaded rand_isaac v0.1.1
  Downloaded subtle v1.0.0
  Downloaded byte-tools v0.2.0
  Downloaded try-lock v0.2.2
  Downloaded string v0.2.1
  Downloaded unicode-bidi v0.3.4
  Downloaded untrusted v0.6.2
  Downloaded digest v0.7.6
  Downloaded unicode-segmentation v1.2.1
  Downloaded sct v0.5.0
  Downloaded memoffset v0.5.1
  Downloaded crossbeam-deque v0.7.1
  Downloaded c2-chacha v0.2.2
  Downloaded semver-parser v0.7.0
  Downloaded generic-array v0.12.0
  Downloaded crypto-mac v0.7.0
  Downloaded block-cipher-trait v0.6.2
  Downloaded toml v0.5.1
  Downloaded xml-rs v0.7.0
  Downloaded parity-snappy-sys v0.1.2
  Downloaded unicode-normalization v0.1.7
  Downloaded block-padding v0.1.4
  Downloaded tokio-named-pipes v0.1.0
  Downloaded miow v0.3.3
  Downloaded crossbeam-utils v0.5.0
  Downloaded mio-named-pipes v0.1.6
  Downloaded cc v1.0.46
  Downloaded zeroize_derive v0.9.3
  Downloaded byte-tools v0.3.1
  Downloaded stream-cipher v0.3.0
  Downloaded quick-error v1.2.2
  Downloaded rand_chacha v0.1.0
  Downloaded impl-codec v0.4.1
  Downloaded local-encoding v0.2.0
  Downloaded phf_generator v0.7.23
  Downloaded mio-extras v2.0.5
  Downloaded rand_pcg v0.1.1
  Downloaded unicode-xid v0.2.0
  Downloaded rustc-serialize v0.3.24
  Downloaded phf_shared v0.7.23
  Downloaded hamming v0.1.3
  Downloaded static_assertions v0.2.5
  Downloaded base64 v0.9.3
  Downloaded arrayvec v0.5.1
  Downloaded mio-uds v0.6.7
  Downloaded lock_api v0.1.4
  Downloaded toolshed v0.6.3
  Downloaded globset v0.4.2
  Downloaded sha-1 v0.8.1
  Downloaded logos-derive v0.7.7
  Downloaded base-x v0.2.3
  Downloaded opaque-debug v0.2.2
  Downloaded primal-bit v0.2.4
  Downloaded jemalloc-sys v0.1.8
  Downloaded aesni v0.6.0
  Downloaded ring v0.14.6
  Downloaded percent-encoding v1.0.1
  Downloaded cmake v0.1.35
  Downloaded siphasher v0.2.3
  Downloaded generic-array v0.9.0
  Downloaded utf8-ranges v1.0.4
  Downloaded typenum v1.10.0
  Downloaded skeptic v0.4.0
  Downloaded owning_ref v0.3.3
  Downloaded parity-rocksdb-sys v0.5.6
  Downloaded lazycell v1.2.0
  Downloaded aho-corasick v0.6.8
  Downloaded socket2 v0.3.8
  Downloaded winapi v0.3.6
  Downloaded base64 v0.10.1
  Downloaded parity-scale-codec v1.0.5
  Downloaded fxhash v0.2.1
  Downloaded safemem v0.3.0
  Downloaded rand_core v0.4.2
  Downloaded scopeguard v0.3.3
  Downloaded ppv-lite86 v0.2.5
  Downloaded stable_deref_trait v1.1.1
  Downloaded spin v0.5.2
  Downloaded fs_extra v1.1.0
  Downloaded byte-slice-cast v0.3.2
  Downloaded bitvec v0.14.0
  Downloaded pulldown-cmark v0.0.3
  Downloaded getopts v0.2.18
   Compiling libc v0.2.62
   Compiling proc-macro2 v0.4.20
   Compiling unicode-xid v0.1.0
   Compiling cfg-if v0.1.10
   Compiling serde v1.0.99
   Compiling lazy_static v1.4.0
   Compiling byteorder v1.3.2
   Compiling semver-parser v0.7.0
   Compiling log v0.4.8
   Compiling cc v1.0.46
   Compiling arrayvec v0.4.11
   Compiling nodrop v0.1.12
   Compiling rand_core v0.4.2
   Compiling smallvec v0.6.10
   Compiling scopeguard v1.0.0
   Compiling getrandom v0.1.11
   Compiling rustc-hex v2.0.1
   Compiling futures v0.1.29
   Compiling crunchy v0.2.2
   Compiling ppv-lite86 v0.2.5
   Compiling typenum v1.10.0
   Compiling static_assertions v0.2.5
   Compiling slab v0.4.1
   Compiling bitvec v0.14.0
   Compiling itoa v0.4.3
   Compiling byte-slice-cast v0.3.2
   Compiling ryu v1.0.0
   Compiling stable_deref_trait v1.1.1
   Compiling scopeguard v0.3.3
   Compiling fnv v1.0.6
   Compiling autocfg v0.1.7
   Compiling num-traits v0.2.6
   Compiling heapsize v0.4.2
   Compiling crossbeam-utils v0.5.0
   Compiling memchr v2.2.1
   Compiling regex-syntax v0.6.12
   Compiling num-integer v0.1.39
   Compiling parity-bytes v0.1.0
   Compiling byte-tools v0.3.1
   Compiling opaque-debug v0.2.2
   Compiling crunchy v0.1.6
   Compiling hash-db v0.15.2
   Compiling fake-simd v0.1.2
   Compiling fs_extra v1.1.0
   Compiling subtle v1.0.0
   Compiling safemem v0.3.0
   Compiling rustc-hex v1.0.0
   Compiling arrayvec v0.5.1
   Compiling subtle v2.1.0
   Compiling matches v0.1.8
   Compiling unicode-normalization v0.1.7
   Compiling unexpected v0.1.0 (/home/tester/parity-ethereum/util/unexpected)
   Compiling either v1.5.0
   Compiling untrusted v0.6.2
   Compiling spin v0.5.2
   Compiling httparse v1.3.3
   Compiling linked-hash-map v0.5.1
   Compiling ansi_term v0.11.0
   Compiling try-lock v0.2.2
   Compiling hashmap_core v0.1.10
   Compiling rayon-core v1.5.0
   Compiling percent-encoding v2.1.0
   Compiling error-chain v0.12.0
   Compiling bit-vec v0.4.4
   Compiling nan-preserving-float v0.1.0
   Compiling hamming v0.1.3
   Compiling unicode-segmentation v1.2.1
   Compiling memory_units v0.3.0
   Compiling arrayref v0.3.5
   Compiling version_check v0.1.5
   Compiling primal-estimate v0.2.1
   Compiling ethabi-contract v9.0.0
   Compiling num-iter v0.1.37
   Compiling rustc-serialize v0.3.24
   Compiling static_assertions v0.3.3
   Compiling siphasher v0.3.0
   Compiling macros v0.1.0 (/home/tester/parity-ethereum/util/macros)
   Compiling bitflags v1.0.4
   Compiling time-utils v0.1.0 (/home/tester/parity-ethereum/util/time-utils)
   Compiling remove_dir_all v0.5.1
   Compiling percent-encoding v1.0.1
   Compiling rustc-demangle v0.1.9
   Compiling failure_derive v0.1.3
   Compiling unicode-width v0.1.5
   Compiling siphasher v0.2.3
   Compiling ipnetwork v0.12.8
   Compiling using_queue v0.1.0 (/home/tester/parity-ethereum/miner/using-queue)
   Compiling winapi v0.3.6
   Compiling slab v0.2.0
   Compiling parity-path v0.1.1
   Compiling byte-tools v0.2.0
   Compiling proc-macro2 v1.0.1
   Compiling xdg v2.1.0
   Compiling unicode-xid v0.2.0
   Compiling utf8-ranges v1.0.4
   Compiling syn v1.0.5
   Compiling mio-named-pipes v0.1.6
   Compiling home v0.3.3
   Compiling sha1 v0.5.0
   Compiling edit-distance v2.0.1
   Compiling base-x v0.2.3
   Compiling quick-error v1.2.2
   Compiling lazycell v1.2.0
   Compiling if_chain v0.1.3
   Compiling integer-encoding v1.0.5
   Compiling target_info v0.1.0
   Compiling termcolor v1.0.4
   Compiling winapi-build v0.1.1
   Compiling slab v0.3.0
   Compiling order-stat v0.1.3
   Compiling transient-hashmap v0.4.1
   Compiling winapi v0.2.8
   Compiling rprompt v1.0.3
   Compiling interleaved-ordered v0.1.1
   Compiling strsim v0.8.0
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling crossbeam-utils v0.6.6
   Compiling thread_local v0.3.6
   Compiling cmake v0.1.35
   Compiling rand_core v0.3.1
   Compiling lock_api v0.3.1
   Compiling rlp v0.4.4
   Compiling tokio-service v0.1.0
   Compiling parity-secp256k1 v0.7.0
   Compiling ring v0.14.6
   Compiling backtrace-sys v0.1.24
   Compiling c2-chacha v0.2.2
   Compiling owning_ref v0.3.3
   Compiling tokio-sync v0.1.6
   Compiling hashbrown v0.6.3
   Compiling indexmap v1.3.0
   Compiling bincode v1.1.4
   Compiling block-padding v0.1.4
   Compiling jemalloc-sys v0.1.8
   Compiling unicode-bidi v0.3.4
   Compiling itertools v0.5.10
   Compiling itertools v0.8.0
   Compiling itertools v0.7.8
   Compiling lru-cache v0.1.2
   Compiling bit-set v0.4.0
   Compiling primal-bit v0.2.4
   Compiling heck v0.3.0
   Compiling eip-152 v0.1.0 (/home/tester/parity-ethereum/util/EIP-152)
   Compiling unicase v2.2.0
   Compiling unicase v1.4.2
   Compiling ethcore-bloom-journal v0.1.0 (/home/tester/parity-ethereum/util/bloom)
   Compiling xml-rs v0.7.0
   Compiling getopts v0.2.18
   Compiling textwrap v0.11.0
   Compiling textwrap v0.9.0
   Compiling block-buffer v0.3.3
   Compiling app_dirs v1.2.1 (https://github.com/paritytech/app-dirs-rs#0b37f948)
   Compiling multibase v0.6.0
   Compiling humantime v1.1.1
   Compiling kernel32-sys v0.2.2
   Compiling tokio-timer v0.1.2
   Compiling tokio-executor v0.1.8
   Compiling crossbeam-queue v0.1.2
   Compiling rand_core v0.2.2
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling impl-rlp v0.2.0
   Compiling triehash v0.8.0
   Compiling parity-snappy-sys v0.1.2
   Compiling parity-rocksdb-sys v0.5.6
error: failed to run custom build command for `parity-secp256k1 v0.7.0`

Caused by:
  process didn't exit successfully: `/home/tester/parity-ethereum/target/release/build/parity-secp256k1-8e206e3b10968655/build-script-build` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by joshua-mir** [comment]
an illegal instruction error usually means that you are attempting to build on unsupported/old hardware. Could you share more information about the hardware you are building on/for?

**Comment by Suhar777777** [comment]
> an illegal instruction error usually means that you are attempting to build on unsupported/old hardware. Could you share more information about the hardware you are building on/for?

 description: Desktop Computer
    product: GA-MA770-UD3
    vendor: Gigabyte Technology Co., Ltd.
    width: 64 bits
    capabilities: smbios-2.4 dmi-2.4 smp vsyscall32
    configuration: boot=normal chassis=desktop uuid=30303234-3144-4436-4534-3732FFFFFFFF
  *-core
       description: Motherboard
       product: GA-MA770-UD3
       vendor: Gigabyte Technology Co., Ltd.
       physical id: 0
     *-firmware
          description: BIOS
          vendor: Award Software International, Inc.
          physical id: 0
          version: FJ
          date: 05/14/2010
          size: 128KiB
          capacity: 960KiB
          capabilities: isa pci pnp apm upgrade shadowing cdboot bootselect socketedrom edd int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial in
t17printer int10video acpi usb ls120boot zipboot biosbootspecification
     *-cpu
          description: CPU
          product: AMD Athlon(tm) 64 X2 Dual Core Processor 3600+
          vendor: Advanced Micro Devices [AMD]
          physical id: 4
          bus info: cpu@0
          version: AMD Athlon(tm) 64 X2 Dual Core Processor 3600+
          slot: Socket M2
          size: 1800MHz
          capacity: 3200MHz
          width: 64 bits
          clock: 200MHz
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp x86-64 3dnowext 3dnow
 rep_good nopl cpuid extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch vmmcall cpufreq
        *-cache:0
             description: L1 cache
             physical id: a
             slot: Internal Cache
             size: 128KiB
             capacity: 128KiB
             capabilities: synchronous internal write-back
             configuration: level=1
        *-cache:1
             description: L2 cache
             physical id: c
             slot: External Cache
             size: 256KiB
             capacity: 256KiB
             capabilities: synchronous internal write-back
             configuration: level=2
     *-cache
          description: L1 cache
          physical id: b
          slot: Internal Cache
          size: 128KiB
          capacity: 128KiB
          capabilities: synchronous internal write-back
          configuration: level=1
     *-memory
          description: System Memory
          physical id: 24
          slot: System board or motherboard
          size: 2GiB
        *-bank:0
             description: DIMM 667 MHz (1.5 ns)
             physical id: 0
             slot: A0
             size: 1GiB
             width: 64 bits
             clock: 667MHz (1.5ns)
        *-bank:1
             description: DIMM 667 MHz (1.5 ns)
             physical id: 1
             slot: A1
             size: 1GiB
             width: 64 bits
             clock: 667MHz (1.5ns)
        *-bank:2
             description: DIMM 667 MHz (1.5 ns) [empty]
             physical id: 2
             slot: A2
             width: 64 bits
             clock: 667MHz (1.5ns)
        *-bank:3
             description: DIMM 667 MHz (1.5 ns) [empty]
             physical id: 3
             slot: A3
             width: 64 bits
             clock: 667MHz (1.5ns)

**Comment by joshua-mir** [comment]
you're trying to build parity-ethereum on hardware that was released over 15 years ago (the AMD Athlon 64 CPU, to be specific), which I don't believe we can reasonably support, unfortunately.

**Comment by Suhar777777** [comment]
I am install little more newer CPU. But also error.
     *-cpu
          description: CPU
          product: AMD Athlon(tm) II X2 215 Processor
          vendor: Advanced Micro Devices [AMD]
          physical id: 4
          bus info: cpu@0
          version: AMD Athlon(tm) II X2 215 Processor
          slot: Socket M2
          size: 1500MHz
          capacity: 3200MHz
          width: 64 bits
          clock: 200MHz
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save cpufreq

Console log:
   Compiling parity-secp256k1 v0.7.0
error: failed to run custom build command for `parity-secp256k1 v0.7.0`

Caused by:
  process didn't exit successfully: `/home/tester/parity-ethereum/target/release/build/parity-secp256k1-8e206e3b10968655/build-script-build` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by dvdplm** [comment]
Probably missing hardware aes?

**Comment by Suhar777777** [comment]
> Probably missing hardware aes?

Ok. I'll try on intel CPU which has AES.

**Comment by Suhar777777** [comment]
On intel CPU with AES, master branch build was normal finished!!! dvdplm thx!!!

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Stepping:            3
CPU MHz:             3599.757
CPU max MHz:         3700.0000
CPU min MHz:         800.0000
BogoMIPS:            7392.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer **AES** xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

Console log:

   Compiling arrayvec v0.4.11
   Compiling parity-secp256k1 v0.7.0
   Compiling ring v0.14.6

....

   Compiling migration-rocksdb v0.1.0 (/home/tester/parity-ethereum/util/migration-rocksdb)
   Compiling parity-rpc-client v1.4.0 (/home/tester/parity-ethereum/cli-signer/rpc-client)
   Compiling cli-signer v1.4.0 (/home/tester/parity-ethereum/cli-signer)
   Compiling parity-ethereum v2.7.0 (/home/tester/parity-ethereum)
    Finished release [optimized] target(s) in 20m 28s
