### ISSUE TITLE
docker image doesn't work

### ISSUE THREAD

**Issue by vietthang207** [paritytech/parity-ethereum#11319]
Hi all, I would like to file a bug report.

- **Parity Ethereum version**: 2.5.10
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I've encounter this issue when upgrading from 2.4 to 2.5.10-stable

```
Dec 10 09:05:07 prod-parity-ethereum-server docker[32473]: Loading config file from /home/parity/io.parity.ethereum/config.toml
Dec 10 09:05:07 prod-parity-ethereum-server docker[32473]: Could not load specification file at homestead: No such file or directory (os error 2)
```

This works fine for every version upto 2.5.9, but it breaks on 2.5.10 and 2.5.11.

Here is my systemd unit file:

```
[Unit]
Description=Parity Ethereum Node
After=docker.service
Requires=docker.service

[Service]
Restart=on-failure
ExecStart=/usr/bin/docker run --name parity-ethereum \
                              --publish 8545:8545 \
                              --publish 30303:30303 \
                              --publish 30303:30303/udp \
                              --volume /var/lib/parity-ethereum/:/home/parity/io.parity.ethereum/ \
                              --volume /etc/parity-ethereum/config.toml:/home/parity/io.parity.ethereum/config.toml \
                              parity/parity:v2.5.10-stable \
                              --config /home/parity/io.parity.ethereum/config.toml \
                              --base-path /home/parity/io.parity.ethereum/
ExecStop=/usr/bin/docker stop -t 10 parity-ethereum
ExecStopPost=/usr/bin/docker rm -f parity-ethereum

[Install]
WantedBy=default.target
```

The volume directories do exist. Here is my config.toml content:

```
# Please refer to https://paritytech.github.io/parity-config-generator

# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
chain = "homestead"
# Parity continously syncs the chain
mode = "active"

[rpc]
disable = false
interface = "0.0.0.0"
port = 8545
# Threads for handling incoming connections for HTTP JSON-RPC server.
server_threads = 512
# Turn on additional processing threads in all HTTP JSON-RPC servers. Setting this to non-zero value allows parallel execution of cpu-heavy queries.
processing_threads = 4

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[footprint]
pruning = "fast"
cache_size = 1024
```

If I used 2.5.9, the node stuck on "Syncing #9069000" which is the Istanbul hardfork block

Thanks in advanced!

**Comment by dvdplm** [comment]
`chain = "homestead"` looks fishy; if you want your node on the current ethereum mainnet, use `chain = mainnet` or `chain = ethereum` or `chain = eth`.

(Also note that `server_threads = 512` is a pretty unusual value; I don't think you should go much above the number of CPUs on the machine).

**Comment by vietthang207** [comment]
Thanks @dvdplm, changing the chain does fix the problem. I didn't realize that we are over with homestead because my config survives several hard forks xD.
