### ISSUE TITLE
Sync stop at block #9070115

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity-ethereum#11323]
- **Parity Ethereum version**: 2.6.6
- **Operating system**:  Linux
- **Installation**: one-line installer 
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**: yes

> 
> 2019-12-11 09:42:05  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   41/100 peers     75 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs
> 2019-12-11 09:42:25  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   40/100 peers     72 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs
> 2019-12-11 09:42:45  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   42/100 peers     73 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs
> 2019-12-11 09:42:55  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   40/100 peers     75 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs
> 2019-12-11 09:43:00  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   43/100 peers     75 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs
> 2019-12-11 09:43:05  Syncing #9070115 0x4bde…7af0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #9069973   39/100 peers     76 MiB chain   32 MiB db  0 bytes queue   25 MiB sync  RPC:  0 conn,    0 req/s, 9957 µs

And, please don't delete eth_accounts, personal, etc... we use this in our websites

**Comment by joshua-mir** [comment]
@famfamfam you are unfortunately on a bad fork and need to resync. It was probably the case that you were running 2.6.5 over the fork block and updated to 2.6.6 after the fork.

**Comment by stephgosling** [comment]
Saw the same, a complete resync needed
