### ISSUE TITLE
An error about `parity_pendingTransactions`.

### ISSUE THREAD

**Issue by minchenzz** [paritytech/parity-ethereum#11340]
I follow this [example](https://wiki.parity.io/JSONRPC-parity-module#parity_pendingtransactions) to make a  request. But I got an error.

curl --data '{"method":"parity_pendingTransactions","params":[15,{"to": {"eq": "0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"},"gas": {"gt": "0x493e0"}}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://192.168.3.147:8545

{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid parameters: Expected from 0 to 1 parameters.","data":"\"Got: 2\""},"id":1}

version v2.5.11

**Comment by niklasad1** [comment]
I could reproduce this on `stable` but it works on `master and beta`. 

Stable is missing https://github.com/paritytech/parity-ethereum/pull/10506 and IIRC it will be introduced in `version 2.6`

@dvdplm is that correct?

So, please use master or beta and it should work.

**Comment by minchenzz** [comment]
@niklasad1 
I use `docker-2.6.6-beta` version. It worked. But the filter does not take effect.

I set `nonce` to be less than `0x02`, but the `nonce` in the return is `0x8c53`.

```curl --data '{"method":"parity_pendingTransactions","params":[1,{"nonce": {"lt": "0x02"}}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://192.168.3.147:8545```

```{"jsonrpc":"2.0","result":[{"blockHash":null,"blockNumber":null,"chainId":"0x4","condition":null,"creates":null,"from":"0xc17e0aeb794ccf893d77222fbeae37a4ddf64d7f","gas":"0x11170","gasPrice":"0x22ecb25c00","hash":"0x282f1fd3977861941cfd0320ec80cb1ed4f70f7f84f4c49d284d00c1e5d7798f","input":"0xeb4c4341ab97ab28502984a50421da51e8909671bd41ca8660f618132c6071c2b0ff571a8f27c8345cb49fbd7714ef9e427f1a6315443b05adbe1f7ac6dd988f","nonce":"0x8c53","publicKey":"0x5370eaeef3dafc8d2743c3260b6deebe339e6f6c406f7f80229bb9ce21a5243969e511101887b1c0ccbf5d7315ae5c000648807f7bb2951a2685bd2966f23fb7","r":"0xe7898f1c508651b00dbcefaf2cffa244db25be617d5c8826e4864173ae9ec189","raw":"0xf8a8828c538522ecb25c008301117094c17e0aeb794ccf893d77222fbeae37a4ddf64d7f80b840eb4c4341ab97ab28502984a50421da51e8909671bd41ca8660f618132c6071c2b0ff571a8f27c8345cb49fbd7714ef9e427f1a6315443b05adbe1f7ac6dd988f2ca0e7898f1c508651b00dbcefaf2cffa244db25be617d5c8826e4864173ae9ec189a018517ae6e47ce49dabc0b594ffdea23322f573e3c2803bfd3a3077cc57957301","s":"0x18517ae6e47ce49dabc0b594ffdea23322f573e3c2803bfd3a3077cc57957301","standardV":"0x1","to":"0xc17e0aeb794ccf893d77222fbeae37a4ddf64d7f","transactionIndex":null,"v":"0x2c","value":"0x0"}],"id":1}```

**Comment by niklasad1** [comment]
@minchenzz 

Right, I think it should be fixed by https://github.com/paritytech/parity-ethereum/pull/11227 available on master but it hasn't been backported yet.

**Comment by minchenzz** [comment]
@niklasad1 ```docker v2.6.8-beta``` problem still exists ... :cry:

**Comment by niklasad1** [comment]
@minchenzz yes, #11227 was not backported to `stable` and `stale` it is only available on master currently. It will probably be included in the next release.
