### ISSUE TITLE
parity 2.5.12 does not add blocks within 16 minutes of startup

### ISSUE THREAD

**Issue by kcanty** [paritytech/parity-ethereum#11350]
Ubuntu 18.04
32g ram
8 core
11 TB SSD
fully synced main ethereum history
Full archive node - full history + tracing

Attempted to upgrade from 2.5.11 (working fine) and upon installing 2.5.12 binary no new blocks added for 16 minutes - reverted back to 2.5.11 and new blocks started adding within 1 minute.

We would like to upgrade to 2.5.12 as to be ready for Muir Glacier upgrade prior to Jan 1 but cannot given this experience -

**Comment by niklasad1** [comment]
Can you please provide some logs on 2.5.11?

Seems strange that there's such different behavior between 2.5.11 and 2.5.12 since there are mostly `JSON` changes (transition parameters for  Muir Glacier hard fork) which is not activated yet.

**Comment by kcanty** [comment]
Here you go - we tried this about 5 days ago and it was 16 minutes not 30.  Thanks!

[parity-logs.txt](https://github.com/paritytech/parity-ethereum/files/3996620/parity-logs.txt)

**Comment by kcanty** [comment]
fixed by 2.5.13
