### ISSUE TITLE
Parity is stuck at block 9199999

### ISSUE THREAD

**Issue by cxd1995** [paritytech/parity-ethereum#11368]
- **Parity Ethereum version**: 2.5.11 stable
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**:  yes

Parity is stuck at the block number 9199999 for days. No error is reported during the process. **We also try restarting Parity but it could not solve the problem.**
![image](https://user-images.githubusercontent.com/45622921/71791380-b71f3400-306f-11ea-9537-82b203b16279.png)
![image](https://user-images.githubusercontent.com/45622921/71791772-1d588680-3071-11ea-9550-e6ea02e3b4d4.png)

**Comment by cxd1995** [comment]
Whether we should decrease the peer number? It seems hard to reach the peer requirement.

**Comment by AtkinsChang** [comment]
You should upgrade to at least 2.5.12 or better 2.5.13 for EIP-2384

**Comment by cxd1995** [comment]
Thanks you! It works.
