### ISSUE TITLE
Wrong version published?

### ISSUE THREAD

**Issue by mewwts** [paritytech/parity-ethereum#11361]
- **Parity Ethereum version**: 2.6.8
- **Operating system**:  linux
- **Installation**: wget https://releases.parity.io/ethereum/v2.6.8/x86_64-unknown-linux-gnu/parity
- **Fully synchronized**: yes
- **Network**: ethereum 

The v2.6.8 binary published in the releases as v2.6.8 reports its version as v2.6.7
```
$ ./parity -v
Parity Ethereum Client.
  version Parity-Ethereum/v2.6.7-beta-b463487-20191231/x86_64-linux-gnu/rustc1.
40.0
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf/Greeff
   Habermeier/Czaban/Gotchac/Redman/Nikolsky
   Schoedon/Tang/Adolfsson/Silva/Palm/Hirsz et al.
```

**Comment by tobg** [comment]
Same for docker

**Comment by Buttaa** [comment]
https://github.com/paritytech/parity-ethereum/commit/b463487b76382e9d5385c665519a2080e648c691#commitcomment-36620035

can anyone confirm?

**Comment by liamaharon** [comment]
```
liam@sleeper:~$ bash <(curl https://get.parity.io -L)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3857  100  3857    0     0   2933      0  0:00:01  0:00:01 --:--:--  2930
Release selected is: beta
Upgrading parity from 2.6.7 to 2.6.8
liam@sleeper:~$ parity -v
Parity Ethereum Client.
  version Parity-Ethereum/v2.6.7-beta-b463487-20191231/x86_64-linux-gnu/rustc1.40.0
```
🙁

**Comment by tjayrush** [comment]
I appears to be from 2019/12/31 whereas the previous version has (also 2.6.7) has this

```
Parity Ethereum Client.
  version Parity-Ethereum/v2.6.7-beta-ba1b879-20191216/x86_64-linux-gnu/rustc1.39.0
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf/Greeff
   Habermeier/Czaban/Gotchac/Redman/Nikolsky
   Schoedon/Tang/Adolfsson/Silva/Palm/Hirsz et al.
```
from 2019/12/16.

**Comment by dvdplm** [comment]
Yes, we are aware of this, an honest mistake. It is only the version string that is incorrect, the code is updated. :/

2.5.13 stable had the correct version string.

**Comment by mewwts** [comment]
Got it @dvdplm! :+1: 

I'll leave this open. Please close at your convenience!

**Comment by gabririgo** [comment]
> ```
> liam@sleeper:~$ bash <(curl https://get.parity.io -L)
> Release selected is: beta
> Upgrading parity from 2.6.7 to 2.6.8
> liam@sleeper:~$ parity -v
> Parity Ethereum Client.
>   version Parity-Ethereum/v2.6.7-beta-b463487-20191231/x86_64-linux-gnu/rustc1.40.0
> ```

+1

**Comment by tjayrush** [comment]
The one line shell script (`bash <(curl https://get.parity.io -L)`) now says there's a checksum error and that the installation is `abording` (sp?)

**Comment by gabririgo** [comment]
fixed on new year's eve, kudos to the devs

**Comment by tjayrush** [comment]
Is this fixed? I downloaded and installed the release from this morning that had the correct code but incorrect version number. Later this same day, I downloaded again (because I understood that you'all fixed the incorrect version problem), but now the download quits saying there's a checksum mismatch. Has anyone else seen this problem? I think I have the right code, but an incorrect version. I'm wondering if that's why it's reporting a checksum mismatch.

**Comment by icxcat** [comment]
@tjayrush  
If  u used stable version, just update to v2.5.13-stable.
The Ethereum Muir Glacier Upgrade Announcement:
https://blog.ethereum.org/2019/12/23/ethereum-muir-glacier-upgrade-announcement/

Latest Parity client (v2.6.8-beta) -> v2.5.13-stable

**Comment by tjayrush** [comment]
@icxcat I updated to the incorrectly labeled 2.6.8 (correct code wrong version). I then tried to upgrade again to use the correctly versioned one (correct code correct version), but got the error. I don't understand what you mean by "Latest parity client (v2.68-beta) -> v.2.5.13-stable" What does that mean?

**Comment by dvdplm** [comment]
@tjayrush sorry for hassle here. I was convinced this was fixed by now but now I'm noit so sure anymore, cc @s3krit?

**Comment by liamaharon** [comment]
Seems to be fixed for me @dvdplm 

Thank you Parity devs for being so quick on new year :tada:

**Comment by s3krit** [comment]
Hi all. First off, apologies for this issue. As dvdplm said, this was an honest oversight as a result of pushing out a security release in the very early hours over a holiday. The published binaries should now have the correct version string. As a result, I'm going to close this issue. @tjayrush it's possible you were attempting to install right around the time I was pushing the new binaries :sweat_smile:
