### ISSUE TITLE
Disk space needed for the db

### ISSUE THREAD

**Issue by natamartchouk** [paritytech/parity-ethereum#11376]
After the upgrade to 2.5.13 as discussed in https://github.com/paritytech/parity-ethereum/issues/11373 parity started resyncing and exited somewhen later with
`Encountered error during snapshot restoration: No space left on device (os error 28)`

I see that the db is 278G big right now, in detail:
`2.2G db/906a34e69aec8c0d/overlayrecent/db/blooms

4.0K db/906a34e69aec8c0d/overlayrecent/db/trace_blooms

223G db/906a34e69aec8c0d/overlayrecent/db

223G db/906a34e69aec8c0d/overlayrecent

1.4M db/906a34e69aec8c0d/snapshot/restoration/db/blooms

4.0K db/906a34e69aec8c0d/snapshot/restoration/db/trace_blooms

36G db/906a34e69aec8c0d/snapshot/restoration/db

9.4G db/906a34e69aec8c0d/snapshot/restoration/temp

45G db/906a34e69aec8c0d/snapshot/restoration

11G db/906a34e69aec8c0d/snapshot/current

55G db/906a34e69aec8c0d/snapshot

278G db/906a34e69aec8c0d

278G db`

How much disk space do we need for the following running parameters:
`"--jsonrpc-apis", "eth,net,web3,personal,parity", "--jsonrpc-interface", "all", "--allow-ips", "public", "--no-discovery", "--mode", "active", "--tracing", "off", "--pruning", "fast", "--db-compaction", "ssd", "--cache-size", "1024"`

Or may be we can sync in a different mode to save disk space? What would be your recommendation?

**Comment by natamartchouk** [comment]
If you need more information, please let me know. We have configured a 300G volume for parity database, parity was running since several month on the system and the db was growing with approx. 5 G per month. End of December we had 50G left, so we were sure that it will take time until we need to increase disk space. And yesterday all the remaining space was used while downloading snapshots. Do we need to increase? Is there a better way to solve this and use not so much space?

**Comment by tjayrush** [comment]
Just throwing this out there (not a dev for Parity). We run with `--no-periodic-snapshots` enabled (check the option's spelling -- not able to confirm right now). We used to have a similar problem. Since adding this option, running out of disc space stopped.

**Comment by dvdplm** [comment]
@tjayrush If everyone runs their nodes without producing snapshots will there will be no snapshots to sync from, causing trouble for all.

@natamartchouk It's hard to answer your questions with any certainty. The chain growth is not deterministic and the database can grow and shrink as data is compacted and shuffled around on disk to optimize access. Your best option to avoid surprises is to keep your servers monitored at all times. Downloading snapshots to re-sync a node that got too far out of sync can be turned off with `--no-warp`; the diskspace needed is roughly 5Mb * the number of snapshots but do note that when the snapshot chunks are uncompressed their size increase significantly, ~16Mb per chunk.

**Comment by natamartchouk** [comment]
Thx, @tjayrush Would be cool to have the confirmation from the parity guys and also an advice how to free up the already used space. It would be good if we could safely delete some subfolders. Wouldn't like to delete the whole db and start the sync from scratch.

**Comment by natamartchouk** [comment]
@dvdplm the node was out of sync for 1 week. Now we have no space left, I'm looking for the best way to clean up / free some space, and resync, best case without the need to delete the whole db and sync from scratch.

**Comment by ordian** [comment]
you can safely remove the `snapshot` folder and proceed with `--no-warp` option (although it might take a while to sync up for 1 week out of sync)

**Comment by natamartchouk** [comment]
Great, thx @ordian!

**Comment by natamartchouk** [comment]
Thanks for help, we are in sync again and have free space with the old volume, no need to increase right now. Closing this.
