### ISSUE TITLE
Mainnet boot nodes

### ISSUE THREAD

**Issue by voron** [paritytech/parity-ethereum#11389]
- **Parity Ethereum version**: 2.6.8
- **Operating system**:  Linux
- **Installation**: official docker image
- **Fully synchronized**: no 
- **Network**: ethereum mainnet
- **Restarted**:  yes

It looks like ETH mainnet boot nodes listed per [foundation.json](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/foundation.json) are outdated. I'm able to connect to 2 of 30 nodes.

**Comment by jlopp** [comment]
On gitter I was told that because Parity doesn't currently support [EIP 2364](https://eips.ethereum.org/EIPS/eip-2364) it may not be able to connect to recent versions of geth bootnodes.

**Comment by voron** [comment]
Fixed by https://github.com/paritytech/parity-ethereum/pull/11441/
