### ISSUE TITLE
2.7.1 Stucked sync with "Could not revert to previous block, last" error message

### ISSUE THREAD

**Issue by avolkov-dev** [paritytech/parity-ethereum#11470]
- **Parity Ethereum version**: 2.7.1
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no 
- **Network**:  ropsten 
- **Restarted**: no 

Syncing stucked at block 7117116.
Here is the logs
```

08:20:56
2020-02-08 08:20:56 UTC IO Worker #2 DEBUG sync NewBlocks: Could not revert to previous block, last: 7121294 (0xd6b4…080d)
```

My docker-compose is:

> version: "3"
> services:
>   node:
>     image: parity/parity:v2.7.1-stable
>     container_name: node
>     restart: on-failure
>     ports:
>       - "8545:8545"
>       - "30303-30304:30303-30304/tcp"
>       - "30303-30304:30303-30304/udp"
>     user: root      
>     volumes:
>     - ${dataDir}:/root/.local/share/io.parity.ethereum
>     command:
>      - --auto-update
>      - "none"
>      - --chain
>      - "ropsten"
>      - --tracing
>      - "on"
>      - --port
>      - "30304"
>      - --jsonrpc-port
>      - "8545"
>      - --jsonrpc-interface
>      - "all"
>      - --jsonrpc-apis
>      - "all"
>      - --jsonrpc-cors
>      - "all"
>      - --no-ws
>      - --no-ipc
>      - --no-warp
>      - --cache-size
>      - "4096"
>      - --db-compaction
>      - "ssd"
>      - --pruning
>      - "fast"
>      - -lsync=debug

**Comment by niklasad1** [comment]
Please update to [v2.7.2](https://hub.docker.com/layers/parity/parity/v2.7.2-stable/images/sha256-4a33438fe4cbd73a6ad37874becf3215c77ac3d7a567992ebd3ee4142fabdb5a)

**Comment by avolkov-dev** [comment]
Node is syncync further after upgrade to 2.7.2

**Comment by niklasad1** [comment]
Ok, glad to hear that is works. Closing, this because `2.7.1` was a release with a couple of major flaws and it should not be used.
