### ISSUE TITLE
[ipc] "expected a string for key `ipc.chmod`"

### ISSUE THREAD

**Issue by stone212** [paritytech/parity-ethereum#11477]
- **Parity Ethereum version**: 2.7.2
- **Operating system**: Linux
- **Installation**:binary
- **Fully synchronized**: does not apply
- **Network**: ethereum
- **Restarted**: yes

The new `[ipc]` features fails.

Based on https://wiki.parity.io/Configuring-Parity-Ethereum.html the `config.toml` file contains this:

```
[ipc]
chmod = 775
disable = false
path = "/home/parity/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]
```

Starting Parity 2.7.2 produces this error:

```
parity@explorer:~$ ./parity-2.7.2 
Loading config file from /home/parity/.local/share/io.parity.ethereum/config.toml
You might have supplied invalid parameters in config file.
invalid type: integer `775`, expected a string for key `ipc.chmod`
```

**Comment by ordian** [comment]
try putting quotes `"` around it, we probably need to update the docs

**Comment by stone212** [comment]
Confirmed.
