### ISSUE TITLE
Breaking changes should be in major versions and called out with a warning

### ISSUE THREAD

**Issue by BrendanChou** [paritytech/parity-ethereum#11488]
- **Parity Ethereum version**: 2.7.2-stable

- Breaking changes to the DB storage should not be provided in minor versions and instead should go into new major versions.

- They should also be called out in bold or with a warning sign.

- They should also be actually put into the list of changes.

- In the case of 2.7.2 which has a breaking DB change, the change is not even listed under the text `The full list of included changes:` in the release report.

**Comment by dvdplm** [comment]
It is stated quite clearly in the release notes: "Due to database format changes, upgrading from 2.5.x or 2.6.x is one-way only.".

**Comment by BrendanChou** [comment]
As mentioned:
- not called out as a breaking change in the "full" list of changes
- hidden in a minor version update
- not bolded, highlighted, or otherwise called out clearly

But okay as long as it's stated NOT in the full list of changes, but at the end of a paragraph about moving to `beta` and `stable` releases, I guess that counts as stated quite clearly 🤦‍♂

**Comment by dvdplm** [comment]
It is called out in the release notes, and in the tweet that announced the release. The DB upgrade was in no way "hidden" or unannounced; it was called out as clearly as it needed to be. I am sorry if you missed it and if it caused you trouble I am sorry for that too.
That said, this is github and the issue tracker is *not* your avenue for sharing thoughts and advice on best engineering practices. Unless you have a technical question or concern the conversation ends here.

**Comment by BrendanChou** [comment]
Got it, sorry for the antagonism, appreciate the work you're doing
