### ISSUE TITLE
[utils] move `rlp_compress` to `parity common`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-ethereum#11498]
Might be useful outside of parity-ethereum.

@ordian @sorpaas thoughts?

**Comment by dvdplm** [comment]
I think we should keep things where they are until there’s a concrete need for them elsewhere. Just my two cents though.

**Comment by niklasad1** [comment]
Ok, let's go with that for now.

**Comment by ordian** [comment]
I've discussed this with @sorpaas and @insipx.

It seem to be used to compress some data in the db https://github.com/paritytech/parity-ethereum/blob/4e2010f2d9570487f8a5a562b6a506e260c001d5/ethcore/blockchain/src/blockchain.rs#L810-L815, and will not likely be used outside of parity-ethereum.
