### ISSUE TITLE
Remove dead code for client not being dropped

### ISSUE THREAD

**Issue by cecton** [paritytech/parity-ethereum#11497]
Now that https://github.com/paritytech/substrate/pull/4929 has been merged to substrate. I believe the implementation done in #7695 is probably not needed anymore. We should clean-up the code when we update substrate here.

Related to #7695

cc @bkchr @arkpar @andresilva

**Comment by ordian** [comment]
> We should clean-up the code when we update substrate here.

parity-ethereum is not based on substrate

**Comment by niklasad1** [comment]
Right, and it seems like this is caused in substrate by https://github.com/rust-lang/futures-rs/issues/1470.

IIRC, we don't use `futures::ThreadPool` at all instead we use the deprecated `mio` and spawn the threads manually.

**Comment by cecton** [comment]
Oh... okay so this issue is invalid then
