### ISSUE TITLE
Network bandwidth utilization

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity-ethereum#2053]
- Add metrics for network traffic (expose network/src/stats.rs)
- Compare traffic usage to other clients for sync and idle scenarios.

**Comment by jacogr** [comment]
When available we start start thinking of exposing this on the web UI under "status".

**Comment by 5chdn** [comment]
This _footprint_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement. If so, please add an assignee and a milestone, or close otherwise.

**Comment by arkpar** [comment]
Still relevant

**Comment by debris** [comment]
I believe that ethereum will move to libp2p before we'll prioritize this task. Therefore I'm closing it
