### ISSUE TITLE
Improve verifier scaling algorithm

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity-ethereum#3708]
@keorn suggested a [PID controller](https://en.wikipedia.org/wiki/PID_controller), but it seems a bit overkill. Somewhere in the middle of current complexity and that would be nice.

Update time should also be reduced, once a minute is far too long.

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by rphmeier** [comment]
yes, i'd say it's still relevant. will probably revisit it fairly soon, but have been focusing on other things.

**Comment by folsen** [comment]
I can't really even make out what this means, @rphmeier if you have a more specific proposal that someone else could pick up, please reopen with that description.

**Comment by rphmeier** [comment]
This is about the `--scale-verifiers` flag which activates threads for parallel ethash verification dynamically.

**Comment by folsen** [comment]
Reopening as it might actually be some amount of boost in performance if we could parallelise more/better.

**Comment by debris** [comment]
I'm closing as this is not a priority right now and will not be in a foreseeable future
