### ISSUE TITLE
Feature request: Clique/Rinkeby PoA testnet support

### ISSUE THREAD

**Issue by tinybike** [paritytech/parity-ethereum#5687]
I think that PoA testnets are very useful for development, however at the moment geth and parity each have their own PoA implementations.  Creating this issue because I think it would be really terrific to have a PoA testnet that worked with both clients.

**Comment by rfikki** [comment]
I think this would be great to have also!!!

**Comment by skmgoldin** [comment]
Yes, it would make the experience of using Etherscan on Rinkeby much nicer. I understand they rely on some Parity specific features for EVM introspection which are missing in their Rinkeby UI.

**Comment by 5chdn** [comment]
Any volunteers? :)

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.

**Comment by 5chdn** [comment]
superseded by #7162

**Comment by 5chdn** [comment]
https://github.com/goerli/parity-goerli

**Comment by thefallentree** [comment]
why was it decided to use implement Aura in Geth instead of implementing Clique in Parity?  

I think the latter might be easier,  I've been trying to get it finished past couple of days and I think i'm really close actually, should I continue?

**Comment by 5chdn** [comment]
> I think I'm really close actually, should I continue?

Yes, please contact me on Gitter or drop me a mail afri at parity.io so we don't duplicate work here. https://gitter.im/goerli/testnet

**Comment by thefallentree** [comment]
ok, can someone reopen this issue and assign to me? I will get an working version this weekend.

**Comment by 5chdn** [comment]
Can't assign to non-members. Let me know if you need an early tester.

**Comment by thefallentree** [comment]
working towards  https://github.com/ethereum/EIPs/issues/225 on #9845

**Comment by 5chdn** [comment]
Can you check Gitter @thefallentree - thanks :)

**Comment by thefallentree** [comment]
status update:  #9845 is able to sync to rinkeby HEAD without issue now.

**Comment by 5chdn** [comment]
Moved to https://github.com/goerli/parity-goerli/ until it's mergable.

Discussion is public on Gitter https://gitter.im/goerli/clique
