### ISSUE TITLE
Nuke the client cache when possible

### ISSUE THREAD

**Issue by Vurich** [paritytech/parity-ethereum#5987]
Currently we never clear the cache (although I believe it's memory-bounded). I think a good place to start would be to simply clear it entirely when we go to sleep, but a better long-term solution would be to add user-controllable knobs to the cache so they can choose when it blows, how much memory to use, etc. Currently we have no choice but to make the memory-for-speed tradeoff in favour of speed, but if we make it possible to tweak we can reduce memory consumption in the case of compiling for raspberry pi or other similar small devices at the expense of speed. This could pave the way for a system of automatic tweaking based on heuristics in the future, but we can't automatically tweak knobs before we have knobs to tweak. I say let's get knobbing.

**Comment by rphmeier** [comment]
The light client cache can be nuked, but it's pretty small. Currently there is no "passive" or "dark" mode for the light client anyway. When we spoke last night, I meant we could clear the DB overlay and canonical state cache upon entering passive mode. Take a look at `Client::sleep` for more info.

**Comment by Vurich** [comment]
Gah, you're right. I remember now, that was just a stupid mistake on my part. I'll have a look.

**Comment by folsen** [comment]
@Vurich what was the outcome of your looking at this? Is it worth doing?

**Comment by debris** [comment]
I'm closing this issue as it is not very spicific
