### ISSUE TITLE
Differentiate between manual throw and natural gas exhaustion

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity-ethereum#6155]
In the light client, when executing `eth_call` or `eth_estimateGas`, we start with a small amount of gas and double it each time the result is exceptional, until the block gas limit is reached. Being able to differentiate between the request actually running out of gas and a deliberate throw would let us avoid making many redundant requests.

**Comment by rphmeier** [comment]
I think this is already handled but we don't have a test for it. We should just try the `rpc::light_helpers::execute_tx` with a proof of some call that throws. Probably easier said than done -- setting up the contract, state, and state proof necessary for that will probably be a nuisance.

**Comment by folsen** [comment]
@tomaka Anything you'd be interested in picking up?

**Comment by tomaka** [comment]
I can pick this up in the next few weeks.
