### ISSUE TITLE
`parity_call` light client implementation

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ethereum#6202]
Related #6195 
cc @rphmeier

**Comment by rphmeier** [comment]
A few things will be needed

1. v2 of PIP for sending a "delta" to the remote peer who will execute
1. corresponding changes in `prove_transaction` and `state::check_proof`
1. work out whether it's possible to fill the delta by back-reference or whether a single round trip per request is required.

**Comment by 5chdn** [comment]
Can we use this as tracking issue for light RPCs? What else is required?

**Comment by folsen** [comment]
@tomusdrw @rphmeier @tomaka What's the status on this? Is this required, if so, for what, and who can do it? It's tagged as a substantial issue so would need more description for anyone to actually pick up the issue and work on it.

**Comment by Tbaut** [comment]
Maybe @niklasad1 or @ordian can help to answer that ^ :)

**Comment by folsen** [comment]
Lets create a new issue if we find any relevance.
