### ISSUE TITLE
Keep existing blocks when restoring from a snapshot.

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity-ethereum#6350]
When restoring from a snapshot parity should try and re-import ancient blocks existing in the current database starting from genesis.

**Comment by 5chdn** [comment]
Upgrading this to major annoyance.

**Comment by Vurich** [comment]
I'll have a look at this

**Comment by rphmeier** [comment]
it shouldn't re-import per se but rather migrate over into the DB restoration is done into. But only after general warp restore has finished; otherwise it poses too much of a cost to start a warp sync.

**Comment by rphmeier** [comment]
@Vurich's patch should work fine to fix this, except for the snapshot service changes
