### ISSUE TITLE
WS Error <Internal>: Attempting to send a message to closed connection.

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-ethereum#6406]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux
> - **And installed**: binaries

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Probably related to #6387 - when closing the UI, the logs get spammed with 1000's of the following lines:

    WS Error <Internal>: Attempting to send a message to closed connection.

It's probably the piled-up RPC responses trying to talk to the close wallet session.

**Comment by tomusdrw** [comment]
Yup, should the warning be supressed?

**Comment by 5chdn** [comment]
Supressed or better integrated to the parity logging format (with timestamp, log level, colors, etc.).

**Comment by debris** [comment]
@tomusdrw is it still an issue?

**Comment by tomusdrw** [comment]
Will be fixed by https://github.com/paritytech/jsonrpc/issues/158 in near future, imho no reason to dig into it earlier (it doesn't happen that often now, when UI RPC spam has been fixed).

**Comment by folsen** [comment]
@5chdn @tomusdrw does this still happen? Looks like some PRs to jsonrpc in the meantime may have fixed the issue?
