### ISSUE TITLE
Gas used got by trace_transaction

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity-ethereum#6964]
> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Windows
> - **And installed**: via installer

I try to get gas used of a transaction. The gas used got by eth_getTransactionReceipt is 63082 and got by trace_transaction is as below. The sum of gas used of traces is not equal to 63082. 
And all value transfer have gasUsed 0.
Is the gas used of traces just an estimate value?
Can anyone share knowledge of implementation details of this?

Gas used of traces:
```
call contract1                         41810
  ->contract1 call contract2           15149
    ->contract2 transfer 1             0
    ->contract2 transfer 2             0
  ->contract1 transfer                 0
  ->contract1 call contract3           15149
    ->contract3 transfer 1             0
    ->contract3 transfer 2             0
```

**Comment by folsen** [comment]
@joshua-mir why was this moved back to needs assignment instead of done? It seems like it's done and should be closed?

**Comment by joshua-mir** [comment]
Sorry. The projects page on github let's you swipe tiles between categories on mobile... It must have moved when I was browsing. Usually I put it back 😖
