### ISSUE TITLE
RPC method to verify the signature of a message

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ethereum#7009]
```
parity_verifySignature(is_prefixed: bool, message: Bytes, signature: H512) -> Result<(Address, PublicKey), Error>
```

ec recovers the public key and returns it along with ethereum address (might be better to use some rich struct instead of a tuple.

**Comment by EvilJordan** [comment]
Does no method to verify a signed message currently exist in Parity? I definitely can't find it in the docs if it does...

**Comment by seunlanlege** [comment]
I'm picking this up 💪🏾
