### ISSUE TITLE
Parity Docker containers run as root

### ISSUE THREAD

**Issue by briskycat** [paritytech/parity-ethereum#7374]
Docker images defined in https://github.com/paritytech/parity/tree/master/docker run with UID 0, which is not very secure: although "containerized" `root` user has fewer capabilities than the real `root`, Docker developers recommend running container processes as unprivileged users.
Even if I specify unprivileged UID:GID in the `--user` option of the `docker run` command I still can not run these containers in unprivileged mode because of permissions violation. The images are configured so that the data directory is located in the /root directory of the image, which is owned by root.
It is [possible to remap root user inside a Docker container to an unprivileged user](https://docs.docker.com/engine/security/userns-remap/) on the host, but this is [not covered on the wiki page](https://github.com/paritytech/parity/wiki/Docker). 
It would also be nice if the images had special [mount points for external data volumes marked by the Docker VOLUME](https://docs.docker.com/engine/reference/builder/#volume) directive.

**Comment by tomusdrw** [comment]
@paritytech/ci Please have a look.

@briskycat PRs are very welcome.

**Comment by JohnnySheffield** [comment]
We have encountered similar issue with current docker images, and are preparing a PR for non-root CentOS image, as current one is not suitable for deploying on OpenShift (Kubernetes).

We had no luck in building current Parity CentOS Docker image, so we went on and created our own. Current image is wget-ing the rpm package, but we would like to build it from source.

The Dockerfile (and the Parity OpenShift template) is currently available [here](https://github.com/DAPowerPlay/parity-openshift), and the non-root image is published on [dockerhub](https://hub.docker.com/r/dapowerplay/parity/)

Can you please check out our current Dockerfile and give feedback is it PR ready, and provide us with info is [this code](https://github.com/paritytech/parity/blob/33284e988e13b15ebb520be29dad123fd646122b/scripts/gitlab-build.sh#L129) still used for building rpm package.

Cheers!

pinging @dec-

**Comment by onpaws** [comment]
I recently learned the same background and arrived at the same conclusion.
@JohnnySheffield did you manage to get anywhere with this?

**Comment by JohnnySheffield** [comment]
@folsen @onpaws Here's a nonroot centos image that i've finally got to build and start. Still needs more work to reduce final image size.

**Comment by onpaws** [comment]
Thanks for sharing! 
Will check this out over the weekend :)

**Comment by debris** [comment]
closed by #9689
