### ISSUE TITLE
Illegal highestBlock

### ISSUE THREAD

**Issue by ldn0x7dc** [paritytech/parity-ethereum#7625]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.6-beta-2d051e4-20180109/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: via One-line Binary Installer
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

The highest block from https://ethstats.net/ is 4,930,444。
Parity shows 

> eth.syncing
{
  currentBlock: 2431277,
  highestBlock: **5340842**,
  startingBlock: 2425977,
  warpChunksAmount: null,
  warpChunksProcessed: null
}

**Comment by kirushik** [comment]
Are you sure you're connected to `foundation` chain, not any other one? You can double-check the chain name in the bottom-right corner of your Parity's web interface, if you're running one.

**Comment by ldn0x7dc** [comment]
@kirushik 
I'm sure. After I kill the parity process and restart with same options, the number returned to normal.
But a few hours later, the highestBlock became incorrect again.
I was using --no-warp.


<img width="1090" alt="2018-01-19 7 55 45" src="https://user-images.githubusercontent.com/3940989/35149902-deae51a6-fd52-11e7-90d4-1579aeb6fe72.png">

**Comment by ldn0x7dc** [comment]
My another machine running parity. Same problem. https://ethstats.net/ shows highest block is 4,939,484.
<img width="887" alt="2018-01-20 4 24 14" src="https://user-images.githubusercontent.com/3940989/35181529-6526a3d6-fdfe-11e7-9546-d677082338b0.png">
I have to restart parity to make the highest block normal.

**Comment by Tbaut** [comment]
Closing as stalled. Please reopen if it happens again.
