### ISSUE TITLE
null transaction receipt returned for confirmed transactions

### ISSUE THREAD

**Issue by jlopp** [paritytech/parity-ethereum#7689]
> - **Which Parity version?**: v1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: from deb package
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

We recently discovered that we have seemingly random transactions missing from our indexing service. After adding some additional debugging it has become clear that sometimes parity returns null for eth_getTransactionReceipt every once in a while, even though we only query for receipts belonging to transactions that were confirmed in a block.

Our logs indicate that the rate of this occurring has increased recently and as far as we can tell, it only occurs during blockchain reorganizations. The logic flow goes like so:

1. Indexer requests a block
2. Indexer requests the transaction receipt for every transaction returned on the block
3. Indexer receives a null response for one or more receipts and skips trying to analyze the transaction

We think we've fixed the problem for now by changing our logic to perpetually request the transaction receipt until a non-null response is returned.

Here are some logs from a recent occurrence:

```
INFO notifyNewBestETHBlock 4965982: 0x664cc87be4774237372f486011b560b2ad1e69fdac65ee829d19320d20faf367

INFO RPCClient - Sleeping for 400ms trying to get a receipt for tx 0x070414750a3398d49b2f81f9f9b53500c56d8be76c7c242dc86ad3529f4f27df

INFO RPCClient - Sleeping for 200ms trying to get a receipt for tx 0x070414750a3398d49b2f81f9f9b53500c56d8be76c7c242dc86ad3529f4f27df

INFO RPCClient - Sleeping for 600ms trying to get a receipt for tx 0x070414750a3398d49b2f81f9f9b53500c56d8be76c7c242dc86ad3529f4f27df

INFO Indexer - Blockchain reorganization started

INFO Indexer - Chain split at block 0x340beb80693e54ee5a7557eb651f5784ae0e086e543e2f229a69445d802dc8af at height 4965981

INFO Indexer - Old chain block: 0x664cc87be4774237372f486011b560b2ad1e69fdac65ee829d19320d20faf367 at height 4965982

INFO Indexer - New chain block: 0xc0ffc5a79ac0a18f4d33247b9f76b51c2d979a49014b9747ecaced3650715f82 at height 4965982

INFO Indexer - New chain block: 0xaa23f5d9871f5bb7392de17bf2df64394c1b34b8540be75bf355c2d136eeb231 at height 4965983

INFO Indexer - Reorganize (revert) old block 4965982: 0x664cc87be4774237372f486011b560b2ad1e69fdac65ee829d19320d20faf367

INFO Indexer - Finished reverting reorganized block: 0x664cc87be4774237372f486011b560b2ad1e69fdac65ee829d19320d20faf367 at height: 4965982

INFO Indexer - Reorganize: setting new chain head to 0x340beb80693e54ee5a7557eb651f5784ae0e086e543e2f229a69445d802dc8af at height 4965981

INFO Indexer - Reorganize (index) new block 4965982: 0xc0ffc5a79ac0a18f4d33247b9f76b51c2d979a49014b9747ecaced3650715f82

INFO Indexer - notifyNewBestETHBlock 4965982: 0xc0ffc5a79ac0a18f4d33247b9f76b51c2d979a49014b9747ecaced3650715f82

INFO Indexer - Finished re-indexing reorganized block: 0xc0ffc5a79ac0a18f4d33247b9f76b51c2d979a49014b9747ecaced3650715f82 at height: 4965982

INFO Indexer - Reorganize (index) new block 4965983: 0xaa23f5d9871f5bb7392de17bf2df64394c1b34b8540be75bf355c2d136eeb231

INFO Indexer - notifyNewBestETHBlock 4965983: 0xaa23f5d9871f5bb7392de17bf2df64394c1b34b8540be75bf355c2d136eeb231

INFO Indexer - Finished re-indexing reorganized block: 0xaa23f5d9871f5bb7392de17bf2df64394c1b34b8540be75bf355c2d136eeb231 at height: 4965983

INFO Indexer - Blockchain reorganization complete
```

**Comment by kcanty** [comment]
Can the range of parity versions with this issue be defined or is it all up to and including 1.9.5?  Probably a side issue but any thought around adding an eth_getBlockTransactionReceipts rpc call? we may do this.

**Comment by folsen** [comment]
This is likely a result of how Parity handles RPC requests for blocks that are no longer part of the chain (e.g. regorgs). Requires investigation on what the correct answer is, not convinced it's a bug, but could be.

**Comment by Tbaut** [comment]
>any thought around adding an eth_getBlockTransactionReceipts rpc call

we've recently added `parity_getBlockReceipts` (merging the doc to the wiki soon, here is the description in the mean time : https://github.com/paritytech/wiki/blob/tbaut-automated-rpcs/JSONRPC-parity-module.md#parity_getblockreceipts )

Closing as this most probably solves your problems. Happy to reopen if there's still something wrong in your opinion.
