### ISSUE TITLE
Thread '<unnamed>' panicked at 'Fails only on invalid back-references; back-references here known to be valid; qed: NoSuchOutput', /checkout/src/libcore/result.rs:906

### ISSUE THREAD

**Issue by avrilmaomao** [paritytech/parity-ethereum#7749]
> I'm running:
>
> - **Which Parity version?**: 1.8.7
> - **Which operating system?**: Linux
> - **How installed?**: via  binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I was using light sync mode, after running for a while, it stopped like this, repeatedly run the command got the same error.

> root@iZ2ze2a915zh5g68uhxjy4Z:~# ./parity --light --jsonrpc-port=8888 --jsonrpc-interface=0.0.0.0
> 2018-01-31 11:41:42  Starting Parity/v1.8.7-stable-e322fd8-20180124/x86_64-linux-gnu/rustc1.23.0
> 2018-01-31 11:41:42  Keys path /home/zhiliang/.local/share/io.parity.ethereum/keys/Foundation
> 2018-01-31 11:41:42  DB path /home/zhiliang/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
> 2018-01-31 11:41:42  Path to dapps /home/zhiliang/.local/share/io.parity.ethereum/dapps
> 2018-01-31 11:41:42  Running in experimental Light Client mode.
> 2018-01-31 11:41:42  Removed existing file '/home/zhiliang/.local/share/io.parity.ethereum/jsonrpc.ipc'.
> 
> ====================
> 
> stack backtrace:
>    0:     0x7f947c707e0c - <no info>
> 
> Thread '<unnamed>' panicked at 'Fails only on invalid back-references; back-references here known to be valid; qed: NoSuchOutput', /checkout/src/libcore/result.rs:906
> 
> This is a bug. Please report it at:
> 
>     https://github.com/paritytech/parity/issues/new
> 
> Aborted

**Comment by tzapu** [comment]
same here, started a light client sync on the brew beta and got 
```
2018-04-10 08:24:22  Syncing #1613626 d917…27ee  2435 hdr/s  22986+    0 Qed  #1613626   13/50 peers   10 MiB cache 19 MiB queue  RPC:  1 conn,  3 req/s,  67 µs

====================

stack backtrace:

Thread '<unnamed>' panicked at 'Fails only on invalid back-references; back-references here known to be valid; qed: NoSuchOutput', src/libcore/result.rs:916
```

and can no longer sync

**Comment by tzapu** [comment]
a db kill and restart later and it synced

**Comment by brandoncurtis** [comment]
Exact same problem here with v1.10.0, amd64, kovan light client.  Killing the db and resyncing "fixed" it.

**Comment by Tbaut** [comment]
Did this happen recently to one of you? we've worked quite a lot on the light client part lately and if this happen again we can reopen and look at the logs closely.
