### ISSUE TITLE
Unlocking account fails on CLI on mainnet

### ISSUE THREAD

**Issue by travs** [paritytech/parity-ethereum#7814]
I'm running:
* `parity version Parity/v1.9.0-beta-53ec114-20180125/x86_64-linux-gnu/rustc1.23.0`
* ubuntu linux
* installed from binary
* fully synced
* mainnet
* tried to restart the node

I import an account like this: `parity account import /path/to/account`
Then I try to unlock it via:
```
parity \
  --geth \
  --datadir=/data \
  --chain mainnet \
  --jsonrpc-apis=all \
  --force-ui \
  --author="0x145a3bb5f5fe0b9eb1ad38bd384c0ec06cc14b54"  \
  --unlock="0x145a3bb5f5fe0b9eb1ad38bd384c0ec06cc14b54" \
  --password="/path/to/password"
```

The error I get is:
```
2018-02-05 21:38:49 UTC Starting Parity/v1.9.0-beta-53ec114-20180125/x86_64-linux-gnu/rustc1.23.0
2018-02-05 21:38:49 UTC Keys path /home/ubuntu/.local/share/io.parity.ethereum/keys/ethereum/Foundation
2018-02-05 21:38:49 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2018-02-05 21:38:49 UTC Path to dapps /data/dapps
2018-02-05 21:38:49 UTC State DB configuration: fast
2018-02-05 21:38:49 UTC Operating mode: active
Account 145a…4b54 not found for the current chain. You can create an account via RPC, UI or `parity account new --chain foundation --keys-path /home/ubuntu/.local/share/io.parity.ethereum/keys/ethereum`.
```

Am I using some incompatible options or something?

The account seems to have been imported, due to this:
```
$ parity account list
0x145a3bb5f5fe0b9eb1ad38bd384c0ec06cc14b54
```

**Comment by 5chdn** [comment]
Please try without `--geth`

**Comment by travs** [comment]
@5chdn 
It still occurs without `--geth`

**Comment by 5chdn** [comment]
Could you locate the key files for `0x006d5d75f56ee523f4b8827e753a35c8d26a3ef6` and `0x0008b3591f52464662111cf909ce59b9558368bb` on your disk?

**Comment by travs** [comment]
`0x0008b3591f52464662111cf909ce59b9558368bb` is in `~/.local/share/io.parity.ethereum/keys/ethereum`, and I could not find the other account.

**Comment by 5chdn** [comment]
Should be investigated.

**Comment by Tbaut** [comment]
Does this still happen? I wonder that's a parity issue. Happy to reopen if you can provide a simple a clear way to reproduce with a recent version.
