### ISSUE TITLE
Sending raw transaction causes parity to shutdown sometimes

### ISSUE THREAD

**Issue by kgcorps** [paritytech/parity-ethereum#7880]
stack backtrace:
   0:     0x561e0eeeeb6c - <no info>

Thread '<unnamed>' panicked at 'was either checked with verify_block_basic or is genesis; has 2 fields; qed (Make sure the spec file has a correct genesis seal)', /checkout/src/libcore/option.rs:874

occurs sometimes when I am sending out new transactions to network.

> I'm running:
>
> - **Which Parity version?**: 1.8.9 Stable
> - **Which operating system?**: Linux
> - **How installed?**: through debian dpkg (as in dpkg -i dpkgFileName.deb)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

While after restart it send it out smoothly (most of the times), it's just unbelievable that main function of sending transaction is not working 100% properly.

**Comment by 5chdn** [comment]
What kind of transaction are you sending?

**Comment by kgcorps** [comment]
Here are some examples:
0x9fce35ca498025dd16e8e134a97ef2e912aee423fd3096ec1ee7c742f128b0b6
0x42b743c9d06b89405e367695ab4eb978f0949e0dd2cc611080212762974f5a8a 
0xd21cf8c84ce0efd2159b8d93bd997037aa6800f63a71bd141d86d032825c33d0

Use cases:

- send through parity web application

- rpc send raw transaction method

both can manage to cause parity shutdown. In case you're wondering - node is running in archive +trace mode.

**Comment by kgcorps** [comment]
This is still an issue in version Parity/v1.10.0-nightly-8fb00fa-20180214/x86_64-linux-gnu/rustc1.23.0
Startup data:
2018-02-15 14:14:50  Starting Parity/v1.10.0-nightly-8fb00fa-20180214/x86_64-linux-gnu/rustc1.23.0
2018-02-15 14:14:50  Keys path /pathToKovan/.kovan/keys/Kovan
2018-02-15 14:14:50  DB path /pathToKovan/.kovan/chains/kovan/db/9bf388941c25ea98
2018-02-15 14:14:50  Path to dapps /pathToKovan/.kovan/dapps
2018-02-15 14:14:50  State DB configuration: archive +Trace
2018-02-15 14:14:50  Operating mode: active
2018-02-15 14:14:50  Warning: Warp Sync is disabled because tracing is turned on.
2018-02-15 14:14:50  Configured for Kovan using AuthorityRound engine
2018-02-15 14:14:50  Removed existing file '/pathToKovan/.kovan/jsonrpc.ipc'.
2018-02-15 14:14:55  Public node URL: enode://c88f99d695c13aa58739f6abcd6a9a40e38ece5f12fb06f7b997a2a59f23575fe5cc28c3f6d0c4a81107325e53d78f1bdfec73b53a559fc6b218f31b3552bc2e@10.1.1.229:30303

**Comment by andresilva** [comment]
I haven't been able to reproduce this but my setup was different than yours. I tested with version `1.9.2` on a pruned node. Can you test if this happens with a different origin account and/or on a pruned node?

**Comment by kgcorps** [comment]
I can, I also tried and reproduced this with 1.9.2.-Beta version.

This happens with different origin accounts as well, I have already tested that, which is actually my main reason for posting this issue. I will test it with a pruned node, however this will not work for my needs since I need to have access to all blocks and also their traces at any given time. Will get back with pruned node results tomorrow.

**Comment by kgcorps** [comment]
Tried it with 1.9.2 in pruning +trace mode, so far couldn't replicate the issue, so it most probably has to do something with archive mode. 

Which still is an issue.

**Comment by andresilva** [comment]
@kgcorps Thanks for your help! I'll try to reproduce the issue with an archive node so we can fix it. Regarding your question I think fast + trace should work for your use case, the reason you're getting null results is most likely because ancient blocks are still being downloaded.

**Comment by kgcorps** [comment]
@andresilva bad news (well at least for me), I managed to get the same error on fast + trace mode as well, it is highly weird since before I sent out around 30 transactions without any problems. Will repeat that with set interval of 5 seconds between those 30 tx's, maybe for some reason whenever some background process is in process and a broadcast request arrives it triggers this reaction, pure speculation this of course. Is there perhaps some sort of additional logging mode, so that I can give more detailed information? Other than that I might try switching to ropsten and see if that helps, don't have a lot of ropsten test ethers.

**Comment by andresilva** [comment]
I synced with tracing enabled and sent a transaction every 5 seconds (https://kovan.etherscan.io/txs?a=0x00aae21b82386f9bfad16d25d2bec31336448755) and was unable to replicate this so far. Are you able to reproduce this on another machine?

**Comment by kgcorps** [comment]
I think, I might have resolved the issue (don't want to jinx it). After doing the following I've broadcasted around 300-400 transactions without any problems. 
So the situation was that I initially had installed parity with version 1.6.8. Also I had installed some rust dependencies on my system. So what I did was uninstalled my current version of parity (1.9.2), uninstalled all rust related dependencies.
Then installed freshly 1.9.2. and simply run it with already existing database. 

Before I just installed over the old versions 1.9.2 on top of 1.8.9 on top of 1.6.8, maybe something went wrong whilst performing dpkg -i parity_.....deb
Now that I've performed a "clean" install everything seems to be in order.

**Comment by 5chdn** [comment]
Weird. Please let me know if this returns.

**Comment by kgcorps** [comment]
Managed to reproduce on **another machine** and on my **local machine** as well. On version 1.9.5-STABLE.
This seems to be a hard to reproduce bug since you can literally send several hundred transactions at first, but manage to hit a timing where parity shuts down several times in a row.

**Comment by kgcorps** [comment]
Are there any updates on this bug?

**Comment by Tbaut** [comment]
It didn't hit many users and was hard to reproduce, so it didn't get prioritized. Did it still happen to you on newer versions?

**Comment by kgcorps** [comment]
Yes, this still occurs on the latest version.

**Comment by 5chdn** [comment]
Fails at `header_step()` here:

https://github.com/paritytech/parity/blob/master/ethcore/src/engines/authority_round/mod.rs#L494-L498

I'm unsure why this is related to sending transactions. You are not running an Authority on Kovan, are you?

**Comment by kgcorps** [comment]
No, I am not running an Authority. I am running node with this configuration out of the box and no additional tinkering has been done with the config:
**parity --chain kovan --tracing on --datadir=~/kovan --jsonrpc-interface all**

**Comment by Tbaut** [comment]
re-closing as stale.. it doesn't seem to hit anyone else, or nobody bumps into this issue...
