### ISSUE TITLE
slow response of rpc interface parity

### ISSUE THREAD

**Issue by madnadyka** [paritytech/parity-ethereum#8007]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity 1.9.3
> - **Which operating system?**: Linux
> - **How installed?**: via binaries 
> - **Are you fully synchronized?**: no  
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I'm running fast+trace node, I make the rpc requests "eth_getBlockByNumber" every 20 seconds, and some of them are normal and some of them  are very slow: 20-60 sec, and probably delay occurs when parity imports new blocks.

**Comment by madnadyka** [comment]
Addition: the problem is actual when subscribe to parity_pendingTransactions is active!

**Comment by XertroV** [comment]
I'm having the same sorts of issues except running a full archive node on an i3.2xlarge AWS instance. (Version 1.10.0-beta via auto-update)

This is occurring on requests like `eth_getBalance`, `eth_gasPrice`, `eth_getTransactionCount`

During this time the node will run 100% CPU on _only one_ core (when usually it has no problem using all 8). There's no real RAM usage change during this time (currently parity is using about 6GB out of 60GB)

During this time no RPC requests will be responded to, and as far as I can see no syncing occurs.

Typical `iostat`:

```
Linux 4.4.0-1049-aws (eth-aws-syd-node-02) 	04/11/2018 	_x86_64_	(8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           9.89    0.00    1.76    1.76    0.04   86.55

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
xvda              0.80         4.54         6.06    9955380   13301380
nvme0n1        1457.03     29035.53     22549.32 63688912517 49461542412
```

Not too sure how to do more debugging.

**Comment by madnadyka** [comment]
Seems that this  issue persists, but can’t use 1.11 - another issue(more critical for me) is occurred:

https://github.com/paritytech/parity/issues/8702 <https://github.com/paritytech/parity/issues/8702>

**Comment by Tbaut** [comment]
Please have a look at the linked issue for a workaround (for instance [here](https://github.com/paritytech/parity/issues/8679#issuecomment-391183581)) and let us know if 1.11.1 fixed the OP issue.

**Comment by Tbaut** [comment]
closing as stale.
