### ISSUE TITLE
Add filtering capability to `parity_pendingTransactions`

### ISSUE THREAD

**Issue by AdvancedStyle** [paritytech/parity-ethereum#8269]
Is there a way to limit the information returned from parity_pendingTransactions over JSON RPC?

Currently it returns all transactions in mempool with full transaction data in JSON format....which takes a long time to parse.

Is it possible to get only the transaction hashes?

In my use case I'd like to be able to poll the mempool and then compare it against my previously list of mempool transactions and then only lookup the full details on the new ones (so probably lookup 5 or 10 new transactions every few seconds, as opposed to trying to pull details for 10000 transactions every time)

With only a list of transaction hashes this compare function can be performed quite quickly, but with not with parsing a massive JSON.

**Comment by tomusdrw** [comment]
Have you considered using `eth_subscribe(newPendingTransactions)`? Currently there is no way to get limited set of data, but I think it's a pretty good idea to allow that.

**Comment by ppeinsold** [comment]
Would love to have a way of filtering here.
Use Cases:
- Check if a transaction with given hash is still pending
- Get all pending transactions by sender
- Get all pending transactions by receiver

**Comment by ordian** [comment]
closed by #10506.
