### ISSUE TITLE
Parity consuming 200% CPU when fully synced

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ethereum#8478]
> I'm running:
>
> - **Which Parity version?**: 1.10.0
> - **Which operating system?**:  MacOS
> - **How installed?**:  from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

The problem goes away when running with `--mode=offline`.
It might have been transactions verification (Geth releases notes mentioned a bug that caused excessive transaction broadcast - might be related).

**Comment by dvdplm** [comment]
Can't repeat on master.

**Comment by folsen** [comment]
@tomusdrw Can you reproduce?

**Comment by tomusdrw** [comment]
It's been reported by @gavofyork I wasn't experiencing that.

**Comment by Pneumaticat** [comment]
I think I can reproduce. Using:

    Which Parity version?:Parity/v1.12.0-nightly-6771539-20180605/x86_64-linux-gnu/rustc1.26.2.
    Which operating system?: Linux
    How installed?: docker
    Are you fully synchronized?: yes
    Which network are you connected to?: ethereum
    Did you try to restart the node?: yes

**Comment by ymonster** [comment]
- Which Parity version?: Parity/v1.11.7 stable release download from parity.io
- Which operating system?: Windows10 Pro
- How installed?: windows exe
- Are you fully synchronized?: yes
- Which network are you connected to?: ethereum
- Did you try to restart the node?: yes

CPU usage:always higher than 20%

**Comment by Tbaut** [comment]
Is it a typo or did you mean 20% ?
