### ISSUE TITLE
Unable to deploy contract when constructor invokes functions from another contract

### ISSUE THREAD

**Issue by ntulsy** [paritytech/parity-ethereum#8525]
I'm running:
> - **Which Parity version?**: Parity v1.9.6-20180416 stable
> - **Which operating system?**: Windows 10 Pro
> - **How installed?**: running with docker
> - **Are you fully synchronized?**: using dev chain
> - **Which network are you connected to?**: dev chain
> - **Did you try to restart the node?**: yes.
> - **solc version: 0.4.23**
> - **truffle version: 4.1.7**
> - **web3 version: 0.18.4**

I ran into a weird issue with parity dev chain. To illustrate the problem, I have two simple contracts below:

Foo.sol:
```
pragma solidity ^0.4.23;

contract Foo {
    mapping (address => bool) public isAdmin;

    constructor () public{

    }

    function addAdmin(address admin)
    public
    {
        isAdmin[admin] = true;
    }
}
```
Bar.sol:
```
pragma solidity ^0.4.23;

import "./Foo.sol";

contract Bar {
    constructor (address fooAddress) public {
        require(
            Foo(
                fooAddress
            ).isAdmin(msg.sender)
        );
    }
}
```

I compiled the two contracts with truffle and used web3 to deploy them. Deployment of Foo works fine. I added one address as admin and used that address to deploy Bar, but it is giving error “The contract code couldn't be stored, please check your gas amount.” If I remove the check in constructor and move the check to normal functions, the "require" block works fine. additionally, the 
same deployment works fine with TestRPC. I have also tried using --geth flag and it still gives the same error. 

Would someone be able to share some light on it? 

Thank you!

**Comment by vincentserpoul** [comment]
The contract deployment works on go-ethereum, so it must be a parity issue.

**Comment by outofgas** [comment]
I can reproduce this issue on Parity v1.8.6 and v1.10.2 on an Ubuntu VM:

    contract Foo {
        uint public x = 42;
    }

    contract Bar {
        constructor(Foo foo) public {
            require(foo.x() == 42);
        }
    }

Contract `Bar` cannot not be deployed if compiled with 0.4.22 or greater; versions up to 0.4.21 are working.

**Comment by ntulsy** [comment]
@outofgas Thank you for verifying!

**Comment by folsen** [comment]
How are you deploying it and what gas are you giving it? The error from Parity indicates that you are giving it 21000 gas to deploy and it needs at least 71236.

**Comment by outofgas** [comment]
@folsen: I tried to deploy it via `truffle migrate`, via the builtin *deploy*, and via the builtin *develop/deploy* in Parity's web frontend. All with same results. Provided gas was 8M (set in `truffle.js` or *advanced sending options* in Parity's web frontend). Parity's *TxQueue viewer* and an Etherchain Light client connected to the same dev network show that a block was mined (by the InstantSealer) but the deployment failed due to "bad instruction*.
