### ISSUE TITLE
CORS Max-Age is not set resulting in 2 requests for each command on Firefox

### ISSUE THREAD

**Issue by ethernomad** [paritytech/parity-ethereum#8542]
Parity/v1.9.7-stable-7919629-20180423/x86_64-linux-gnu/rustc1.25.0
connected to MIX Blockchain

Currently every RPC command is 2 requests from Firefox. First the OPTIONS pre-flight and then the actual request. By setting CORS Max-Age to 10 minutes the number of requests can be cut in half. For high latency connections to the node, this has significant performance improvements.

Geth had the exact same problem: https://github.com/ethereum/go-ethereum/issues/3079
![screenshot from 2018-05-04 14-33-09](https://user-images.githubusercontent.com/161566/39616998-2c0379de-4fa8-11e8-8e7b-4ecf8f7d597b.png)

**Comment by Tbaut** [comment]
Thanks! PR always welcome :)

**Comment by tomusdrw** [comment]
Neat! Requires implementation in https://github.com/paritytech/jsonrpc

**Comment by debris** [comment]
implemented a long time ago in https://github.com/paritytech/jsonrpc/pull/280
