### ISSUE TITLE
light client: subscribe over websockets doesnt send new events

### ISSUE THREAD

**Issue by jacobrosenthal** [paritytech/parity-ethereum#8560]
Not sure if its related to the light client or websocket. If I use a recent from block I get some events, if I use latest I get nothing, and either way I never get any new events (as I can open a second script attached to infura's websocket)

```
target/release/parity -d /Volumes/vms --light
2018-05-07 11:43:18  Starting Parity/v1.12.0-unstable-f0c6d17ad-20180504/x86_64-macos/rustc1.25.0
2018-05-07 11:43:18  Keys path /Volumes/vms/keys/Foundation
2018-05-07 11:43:18  DB path /Volumes/vms/chains/ethereum/db/906a34e69aec8c0d
2018-05-07 11:43:18  Path to dapps /Volumes/vms/dapps
2018-05-07 11:43:18  Running in experimental Light Client mode.
2018-05-07 11:43:20  Imported #5572784 0x5aa1…b1ba (7.98 Mgas) + another 1 header(s)
2018-05-07 11:43:23  Public node URL: enode://c6622236c33a3ae026da0622472c37d77ee6f8194908d73adb3d00505fb63d29521b49d5588d3f8e202a9acd5fbcc65646a1e1c30d9bdeee3af5740857065db4@192.168.0.35:30303
2018-05-07 11:43:31  Imported #5572785 0x2cb3…143c (0.40 Mgas)
2018-05-07 11:43:40  Imported #5572787 0xf283…03ec (7.99 Mgas)
2018-05-07 11:43:48    14/50 peers   4 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
```

```
contract.events.allEvents(
{fromBlock: 5572785} //gets recent past events, but no new updates
//{} //nothing
//{fromBlock:'latest'} //nothing
, function(error, events){
console.log(error, events)
})
```

```
null { address: '0x06012c8cf97BEaD5deAe237070F9587f8E7A266d',
  blockHash: null,
  blockNumber: null,
  logIndex: null,
  transactionHash: null,
  transactionIndex: null,
  transactionLogIndex: null,
  type: 'pending',
  id: null,
  returnValues: 
   Result {
     '0': '0x5B49c5072750Ec45E63E1F300cc4A3a6C8CB7599',
     '1': '740439',
     '2': '740367',
     '3': '739104',
     '4': '511181029587041829902179471452593439812944709427753037147557425946068364',
     owner: '0x5B49c5072750Ec45E63E1F300cc4A3a6C8CB7599',
     kittyId: '740439',
     matronId: '740367',
     sireId: '739104',
     genes: '511181029587041829902179471452593439812944709427753037147557425946068364' },
  event: 'Birth',
  signature: '0x0a5311bd2a6608f08a180df2ee7c5946819a649b204b554bb8e39825b2c50ad5',
  raw: 
   { data: '0x0000000000000000000000005b49c5072750ec45e63e1f300cc4a3a6c8cb759900000000000000000000000000000000000000000000000000000000000b4c5700000000000000000000000000000000000000000000000000000000000b4c0f00000000000000000000000000000000000000000000000000000000000b472000004a10c218c74b8295c5ee180670c0c6210c40808734591394e52b8e90858c',
     topics: [ '0x0a5311bd2a6608f08a180df2ee7c5946819a649b204b554bb8e39825b2c50ad5' ] } }
```

_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
a7a46f425369fd662042cb4a1c9ffc301b3b5b75
and "web3": "^1.0.0-beta.34"
> - **Which operating system?**: Windows / MacOS / Linux
macosx
> - **How installed?**: via installer / homebrew / binaries / from source
source
> - **Are you fully synchronized?**: no / yes
yes, light client
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
mainnet
> - **Did you try to restart the node?**: no / yes
yes

**Comment by Tbaut** [comment]
Could you reproduce with a full node (you can try quickly syncing on kovan)?

**Comment by jacobrosenthal** [comment]
Im traveling atm so Ill try to get kovan going, any recommendations on a chatty contract to watch?

**Comment by jacobrosenthal** [comment]
OK got synced and found a random contract on etherscan. New events are coming through fine on kovan full node with any filter options, so maybe the light client code?

**Comment by Tbaut** [comment]
Thanks for narrowing down the scope. Can you edit your first post and title to reflect the fact that it's in the light client?

**Comment by jacobrosenthal** [comment]
I think this is worthy of inclusion on the light client dashboard? cc @tomaka

**Comment by tomaka** [comment]
My knowledge of events and the API around it is still limited, but I think this issue is here by design and not actually a bug.

cc @rphmeier

**Comment by rphmeier** [comment]
it should be sending new events. we should investigate if the `LightChainNotify` trait is ever firing and whether that leads to a filter update/push.

**Comment by rphmeier** [comment]
I'm not sure how well this will work unless synced in general though unless we pause syncing while we check every block for log updates.

**Comment by jacobrosenthal** [comment]
@rphmeier Happy to test, though not sure what. Can you link or provide a snippet?

**Comment by jacobrosenthal** [comment]
Also would like to learn how to gdb cargo builds but havent figured that out yet if anyone has a workflow for parity that would be ideal.
