### ISSUE TITLE
Generic request sender in sync is not generic enough

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ethereum#8605]
It seems that `Requester::send_request` only supports two protocols (ETH, PAR), while claiming it's generic:
https://github.com/paritytech/parity/blob/master/ethcore/sync/src/chain/requester.rs#L136

Actually it should take under consideration the protocols supported by remote peer and also other protocols than ETH and PAR.

**Comment by elferdo** [comment]
I just created a small PR for this issue: https://github.com/paritytech/parity-ethereum/pull/10295
