### ISSUE TITLE
Subscription "newPendingTransactions" doesn't work properly

### ISSUE THREAD

**Issue by madnadyka** [paritytech/parity-ethereum#8714]
> I'm running:
>
> - **Which Parity version?**: 1.11.1
> - **Which operating system?**: Linux
> - **How installed?**: binaries 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

Subscription "newPendingTransactions" doesn't work  properly - I am receiving only small part of all new pending transactions. In version 1.10.4 this subscription is ok.

**Comment by Tbaut** [comment]
Can you provide an example as well as how you subscribe to new pending transactions and verify that it's not working as expected?

**Comment by iFA88** [comment]
I also use this, it seems it works without issue with `Parity/v1.11.1-beta-6654d0216-20180515/x86_64-linux-gnu/rustc1.25.0`. I receive about 4-10 new pending TX in every 10 sec.

**Comment by madnadyka** [comment]
I display in my program quantity of received by subscription pending tx per minute. Displaying data is a dictionary, where key is timestamp and value is tx quantity (not sorted by timestamp, yellow color) :
parity v1.10.4:
<img width="1184" alt="2018-05-27 20 20 17" src="https://user-images.githubusercontent.com/29851936/40588963-a7625d6a-61f6-11e8-925e-54e868f98d80.png">
parity v1.11.1:
<img width="1600" alt="2018-05-27 20 59 34" src="https://user-images.githubusercontent.com/29851936/40588972-cb056e74-61f6-11e8-986b-ba914161fc37.png">
and after restart node parity v1.11.1:
<img width="1529" alt="2018-05-27 21 26 08" src="https://user-images.githubusercontent.com/29851936/40588981-e5e4106a-61f6-11e8-99d1-7749ae10e11d.png">

**Comment by Tbaut** [comment]
Can you share how you subscribe? This visual way of checking is not very straightforward for us to pinpoint problems?
Did you have a look at the resources of the computer? It could also miss events because of lagging behind (v1.11.1 is more demanding in terms of CPU usage: https://github.com/paritytech/parity/issues/8696). A safer way to make sure not to miss any transaction would be to use the trace API: https://github.com/paritytech/parity/issues/8696)

**Comment by madnadyka** [comment]
By websocket in my program (python): 

>   def subscribe_transactions(self):
>         self.ws.send_str('{"jsonrpc":"2.0","id": 2, "method": "eth_subscribe", "params": ["newPendingTransactions"]}')

CPU of server with my program - 2 GB, CPU of server with node - 8 GB

**Comment by Tbaut** [comment]
This could be due to the new transaction queue, @tomusdrw can you have a look?

**Comment by finndev** [comment]
Same issue here, the event is barely firing for us after upgrading to the latest beta. This is very bad, because we can't downgrade due to the recent security alert. Unfortunately our Rust skills are limited, so we can't really help.

**Comment by Tbaut** [comment]
>we can't downgrade due to the recent security alert

You can downgrade to the latest stable release, v1.10.6 that also has the security patch ;)

**Comment by iFA88** [comment]
Few months before I have issued also, that the` parity_pendingTransactions` request sometimes hanging forever, but then I have used filter to get the pending transactions.

**Comment by tomusdrw** [comment]
Yeah, `parity_pendingTransations` is quite heavy (especially with large pools), cause it has to get the entire pending set and serialize all transactions to JSON, the response payload on it's own is huge.

In 1.11.x series it has an optional `limit` parameter, that allows you to query only the tip of the pool (like 100 best transactions) - that should work much faster.

**Comment by iFA88** [comment]
Getting 10-15k pending transaction have taken 6-12 sec. This is great speed, idk why was hanging.

**Comment by tzapu** [comment]
@5chdn i don't think i have seen the `limit` param in the docs for `parity_pendingTransations`, is there some place specific we should look for the latest docs and not in the wiki? Does it have, or could it have a "just hashes" flag as well? :P

**Comment by 5chdn** [comment]
Yeah, the wiki. We are having automated API docs soon (tm), we just need to make the CI pipeline actually finish.

**Comment by tomusdrw** [comment]
Please re-open if the issues persists. We now also have #9745 to efficiently query the pool content.
