### ISSUE TITLE
Distance between nodes in node discovery

### ISSUE THREAD

**Issue by ayrat555** [paritytech/parity-ethereum#8721]
https://github.com/paritytech/parity/blob/master/util/network-devp2p/src/discovery.rs#L236

It looks like the distance between nodes is calculated as a common prefix of each byte. Shouldn't it be just a common binary prefix?

I wrote a test

```rust
    #[test]
    fn test_distance() {
        let id1 = H256::from(1_000_000_000);
        let id2 = H256::from(9_000_000_000);

        let distance = Discovery::distance(&id1, &id2);

        assert!(distance == 2);
    }
```
`1_000_000_000` - `[0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
 0, 0, 0, 0, 0, 0]`
`9_000_000_000` - `[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]`

So the common prefix is 2.
`Discovery::distance` returns 24

**Comment by sorpaas** [comment]
Might be related to https://github.com/paritytech/parity/pull/8589

**Comment by sorpaas** [comment]
From the literature I can find, Kademlia distance are defined via XOR metric. In Parity Ethereum we used `log2(XOR)` which should have similar effect. So looks like this function is correct.

Please feel free to re-open this issue if you find out I'm wrong!
