### ISSUE TITLE
up to 30 seconds delay to rpc response 

### ISSUE THREAD

**Issue by mikhail-manuilov** [paritytech/parity-ethereum#8746]
I'm running:

- **Which Parity version?**: 1.10.4
- **Which operating system?**: Linux
- **How installed?**: docker
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**: ethereum
- **Did you try to restart the node?**: yes

I'm running parity with nginx as a reverse tls-proxy on Digital Ocean instance with ssd disks 8GB ram, 4 vcpu.

It's fully synced, but I ran rsync to copy db from local parity.

Running 1800 requests using Chrome. For some reason I got up to 30 seconds delays to some "easy" requests with no shortage on io/ram/cpu as docker stats/ iostat / top tells me.

parity is using ~550 MB running for several days with no limit set in docker.

This request always tops responce time {jsonrpc: "2.0", id: 249, method: "net_version", params: []}.

But production parity v1.9.7 running in docker on VERY slow disks in azure and getting desynced sometimes have much better average and worst responce times with iowait for 20-30%, BUT using 10GB+ memory.

I can test 1.9.7 on DO, but I suppose 10GB is some db cache that makes parity reply much faster, what I am I doing wrong here?

**Comment by rudolfix** [comment]
we have exactly same issue, 4 nodes behind load balancer on Digital Ocean with significant traffic being handled nicely EXCEPT `net_version` method call which takes 10-30 seconds.
Is there a plan to fix it?

**Comment by ankitarora121** [comment]
Facing the same issue, `net_version` takes ~30 seconds. Strange!

**Comment by debris** [comment]
`net_version` was waiting to acquire read lock from networking thread. it does not wait for it any more
