### ISSUE TITLE
reading data performance

### ISSUE THREAD

**Issue by adirmola** [paritytech/parity-ethereum#8748]
> I'm running:
>
> - **Which Parity version?**: 1.12.0
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ropsten 
> - **Did you try to restart the node?**: yes

Hi,

I'm trying to run some process of reading data (stateDiff of blocks with "trace_replayBlockTransactions") from local parity node to mysql.
The problem i'm facing is speed.
The reading rate (before writing. i'm writing to sql per 10,000 txs) is in avg something like 6 txs/sec:
output of my process:
```
Amount of Txs: 73255
Start Time: 2018-05-31 07:57:09
End Time: 2018-05-31 11:27:13
```
Extremely slow.

The node is on offline mode.
The i/o performance are as following:
![image](https://user-images.githubusercontent.com/38461782/40780987-f02ee506-64e2-11e8-8703-4d1fbda5e460.png)
The wired stuff is that in the beginning of the reading (before all parity's processes comes full alive), the reading is extremely fast, but after couple of minutes it become very slow:

Time | NumOfTxs | TxDiff | TimeDiff (sec) | Txs/sec
-- | -- | -- | -- | --
13:38:50 | 3008 |   |   |  
13:39:07 | 6021 | 3013 | 17 | 177.24
13:39:28 | 9036 | 3015 | 21 | 143.57
13:39:56 | 12045 | 3009 | 28 | 107.46
13:40:18 | 15079 | 3034 | 22 | 137.91
13:40:41 | 18081 | 3002 | 23 | 130.52
13:41:06 | 21084 | 3003 | 25 | 120.12
13:44:10 | 24090 | 3006 | 184 | 16.34
13:52:42 | 27096 | 3006 | 512 | 5.87

Also I don't understand why it is so slow, because, as u can see the i/o rate are low (2 mb/sec).

**Comment by Tbaut** [comment]
Can you tell if this is a regression from v1.11.1 or 1.10.4? this would help.

**Comment by Tbaut** [comment]
Any chance you could try on a recent release? Happy to reopen if the annoyance is still there.
