### ISSUE TITLE
Data error (cyclic redundancy check).

### ISSUE THREAD

**Issue by asmodat** [paritytech/parity-ethereum#8764]
> I'm running:
>
> - **Which Parity version?**: 1.10.3
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

This error is extra annoying and happens 100% of the time on windows after few days/weeks of starting and stopping the node randomly. To fix this I have to use command: db kill ... so obviously the whole history has to resync over again.

This issue is the same for all parity for windows dating back to dozen releases in the past. Please investigate, because its unbearable user experience.

```
PS C:\WINDOWS\system32> parity ui
2018-06-01 21:50:59  Parity browser interface is deprecated. It's going to be removed in the next version, use standalon
e Parity UI instead.
2018-06-01 21:50:59  Standalone Parity UI: https://github.com/Parity-JS/shell/releases
2018-06-01 21:50:59  Starting Parity/v1.10.3-stable-b9ceda38a-20180507/x86_64-windows-msvc/rustc1.25.0
2018-06-01 21:50:59  Keys path C:\Users\xxxxxxx\AppData\Roaming\Parity\Ethereum\keys\Foundation
2018-06-01 21:50:59  DB path C:\Users\xxxxxxx\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2018-06-01 21:50:59  Path to dapps C:\Users\xxxxx\AppData\Roaming\Parity\Ethereum\dapps
2018-06-01 21:50:59  State DB configuration: fast
2018-06-01 21:50:59  Operating mode: passive
2018-06-01 21:50:59  Configured for Foundation using Ethash engine
2018-06-01 21:51:00  Updated conversion rate to Ξ1 = US$571.44 (8333166 wei/gas)
2018-06-01 21:51:00  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-06-01 21:51:00  Multi-threaded server is not available on Windows. Falling back to single thread.

Open: http://127.0.0.1:8180/#/auth?token=ssym-XXXXXXXXXXXXXX
to authorize your browser.
Or use the generated token:
ssym-XXXXXXXX
2018-06-01 21:51:00  Public node URL: enode://e2ef6e295ad5c534cb8ae044d19559672eeff520e182974d95f4fc88df1994d98446eb0bbe
81ea5369e5cb3ee2b68d279eded57d72eeb0d84907bade21f70efb@127.0.0.1:30303
2018-06-01 21:51:15  Syncing #5714873 3892…48ee     0 blk/s   50 tx/s   3 Mgas/s      0+  373 Qed  #5715247    2/25 peer
s    477 KiB chain   92 MiB db   43 MiB queue  131 KiB sync  RPC:  4 conn, 33 req/s, 23927 µs
2018-06-01 21:51:26  Syncing #5714880 71ec…7568     0 blk/s   78 tx/s   4 Mgas/s      0+  365 Qed  #5715247   12/25 peer
s    878 KiB chain   94 MiB db   43 MiB queue  131 KiB sync  RPC:  4 conn, 10 req/s, 12775 µs

====================

stack backtrace:
   0:     0x7ff692e200f3 - hid_error
   1:     0x7ff692e1f853 - hid_error
   2:     0x7ff692660f21 - <no info>
   3:     0x7ff692ef5181 - hid_error
   4:     0x7ff692ef4ff1 - hid_error
   5:     0x7ff692ef4ed2 - hid_error
   6:     0x7ff692ef4e42 - hid_error
   7:     0x7ff692f07a0d - hid_error
   8:     0x7ff6928746a9 - hid_error
   9:     0x7ff6927cbcf7 - <no info>
  10:     0x7ff69284d08c - hid_error
  11:     0x7ff6928cbc54 - hid_error
  12:     0x7ff69294c8aa - hid_error
  13:     0x7ff692effff2 - hid_error
  14:     0x7ff6927fbb53 - <no info>
  15:     0x7ff692efeadf - hid_error
  16:     0x7ff87d042784 - BaseThreadInitThunk

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("IO error: C:\\Users\\xxxxxx\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\db\\906a34e69aec8c0d\\ovrlayrecent\\db/157209.sst: Data error (cyclic redundancy check).\r\n"
), State { next_error: None, backtrace: None })', libcore\result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

PS C:\WINDOWS\system32>


```

**Comment by roninkaizen** [comment]
had almost the same error with samsung and seagate discs with win 7,8,10,
exchanging them against other vendors brought better results,
even with energy saving discs from western digital (former green line) caused such
"accidents" as you described above.
As you have the choice to switch, 
please also give feedback if this issue could be answered by diffentiated buy suggestions for parity "long term windows" node harddisc equipment.

**Comment by asmodat** [comment]
That is SSD OCZ-AGILITY 3, I had the same issue on other PC's too with different drives. It's the same system my OS is installed on, so if it was failing so horribly because of the drive It would be BSOD'ing as hell, which id does not.

**Comment by asmodat** [comment]
Here is theory what might be happening... (it might be it or not - didn't proven it)
I think it might have something to do with rapidly shutting down the parity process when its doing something with the files on the drive. Maybe it should be working on some tmp files and then rename them to whatever they supposed to be instead of corrupting the original ones and working on a live body.

**Comment by 5chdn** [comment]
Please reset your database and try again. If this persists, it's maybe a disk corruption? Also, try to cleanly shut down your parity node.

**Comment by asmodat** [comment]
Database reset - db kill of course works every single time, but then it takes 1-2 working days to resync... Which basically makes it useless as part of some production environment. What's extra odd is that its not the "latest" part of db that is breaking, but most often, something that was originally created by parity day, weeks or months ago... I don't understand how file that should most likely be only read gets corrupted, unless there is some funny stuff going on. Also I am not aware of any command to gracefully close parity, if I do Ctrl+C process will just halt and result is the same as if I stopped entire machine.

**Comment by Tbaut** [comment]
Closing as stale (and no traction)
