### ISSUE TITLE
Thread 'main' panicked at 'Logger is initialized only once; qed: "Cannot write to log file given

### ISSUE THREAD

**Issue by liberat0r** [paritytech/parity-ethereum#8842]
> I'm running:
>
> - **Which Parity version?**: latest/autoupdate (running parity --version causes the error below)
> - **Which operating system?**: Linux
> - **How installed?**: snap
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Hello,

Suddenly my parity node started throwing the following error upon init:

```
Loading config file from /root/snap/parity/13200/.local/share/io.parity.ethereum/config.toml

====================

stack backtrace:
   0:     0x55c340cecddc - backtrace::backtrace::trace::h9533b555511f03d8
   1:     0x55c340ceb5c2 - backtrace::capture::Backtrace::new::h88941f830ace4a5e
   2:     0x55c3402fe75a - panic_hook::panic_hook::h1a97da202e95177c

Thread 'main' panicked at 'Logger is initialized only once; qed: "Cannot write to log file given: /root/snap/parity/12080/.local/share/io.parity.ethereum/parity.log"', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted
```

**Comment by Tbaut** [comment]
It looks like you do you have the access to write the logs. It is related to the snap package (which I#ve seen a lot of problems with recently.

Could you try to uninstall parity and install it with the [one line installer](https://wiki.parity.io/Setup#one-line-binary-installer)

**Comment by liberat0r** [comment]
After installing parity via the one line installer and copying in my database to avoid a complete re-sync I am still getting the same error, but with slightly less details as it seems:
```
Loading config file from /root/.local/share/io.parity.ethereum/config.toml

====================

stack backtrace:
   0:     0x55d14f8d41fc - <no info>

Thread 'main' panicked at 'Logger is initialized only once; qed: "Cannot write to log file given: /root/snap/parity/12080/.local/share/io.parity.ethereum/parity.log"', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

**Comment by Tbaut** [comment]
What does `which parity` ouptut?
Can you launch partiy with `/usr/bin/parity` successfully (without this error)?

**Comment by liberat0r** [comment]
```
# which parity
/usr/bin/parity
```
```
# /usr/bin/parity
Loading config file from /root/.local/share/io.parity.ethereum/config.toml

====================

stack backtrace:
   0:     0x55781aca21fc - <no info>

Thread 'main' panicked at 'Logger is initialized only once; qed: "Cannot write to log file given: /root/snap/parity/12080/.local/share/io.parity.ethereum/parity.log"', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted
```

**Comment by liberat0r** [comment]
This was my bad, a remnant in my config file linked to the old (snap) install folder.

**Comment by liberat0r** [comment]
OK, fixing the config file solved this!

**Comment by 5chdn** [comment]
Should be easily fixable by checking permissions

**Comment by Genysys** [comment]
You should close this ...ran into the same issue and it was to do with permissions.
