### ISSUE TITLE
Decouple MemoryDB from RLP

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-ethereum#8950]
Currently the `memorydb` crate has a [hard dependency](https://github.com/paritytech/parity/blob/master/util/memorydb/src/lib.rs#L214) on `rlp`.

Make it generic over the encoding scheme using the `NodeCodec` trait from https://github.com/paritytech/parity/pull/8739.

**Comment by debris** [comment]
this is not trivial, because of how we treat `null_node` and `null_node_rlp`. it is exactly the same issue that prevents us from decoupling `NodeCodec` from rlp

**Comment by dvdplm** [comment]
Good point.

**Comment by cheme** [comment]
Something along the lines of (using associated const)
```rust
#[derive(Clone, PartialEq)]
pub struct MemoryDB<M: MemoryDBConf> {
	data: FastMap<M::H, (DBValue, i32)>,
	hashed_null_node: <M::H as KeyHasher>::Out,
}

pub trait MemoryDBConf {
  const NULL_VALUE: &'static [u8];
  type H: KeyHasher;
}
```
could do it, but I feel that the added complexity (new trait with impact everywher) may not be worth it.

**Comment by cheme** [comment]
This issue is fixed now (memorydb contains a null node hashed instance and there is no more deps to rlp). Note that memory db is no longer in parity-ethereum but shared with substrate.
