### ISSUE TITLE
RPC call to trace_filter not returning all block data that is available via trace_transaction

### ISSUE THREAD

**Issue by crueber** [paritytech/parity-ethereum#8956]
> I'm running:

Linux docker bin (on a huge box that has plenty of room to grow).

Version info: Parity/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0

Args: `--unsafe-expose --mode=active --jsonrpc-server-threads 10 --jsonrpc-threads 10 --tracing on --pruning archive --chain mainnet --cache-size 8192 --cache-size-state 1024 --cache-size-db 4096 --min-peers 25 --no-serve-light --no-ui --ws-interface=all --no-dapps --no-hardware-wallets --no-secretstore --no-secretstore-http --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-apis safe`

Fully synced to ETH mainnet. Restarting doesn't really apply to this problem I doubt, but I have restarted, regardless.

> - **Issue Description**

I have used an RPC `trace_filter` call to get lots of block data out of nodes, and I found some data that didn't appear to be pulled. So I went to verify that it should or shouldn't be there via curl, and got some problematic results... For block `0x50a6e7` (or 5285607), there should be a [trace](https://etherscan.io/vmtrace?txhash=0x6b6a58e63b0186cdf5ba4c387bed7eba2cc800ca2d08dacb860f41271f6c8c06&type=parity#raw). Which appears to be accurate on my local node with `trace_transaction`:

```sh
$ curl --data '{"method":"trace_transaction","params":["0x6b6a58e63b0186cdf5ba4c387bed7eba2cc800ca2d08dacb860f41271f6c8c06"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://localnode/ |jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   785    0   652  100   133   2127    433 --:--:-- --:--:-- --:--:--  2130
{
  "jsonrpc": "2.0",
  "result": [
    {
      "action": {
        "callType": "call",
        "from": "0x8547d336f6979a504db5c49e69236f31aeeef95c",
        "gas": "0xde08",
        "input": "0xa9059cbb000000000000000000000000c76bd99b4982633543a5291c756afee6cef6df0f00000000000000000000000000000000000000000003b8e97d229a2d54800000",
        "to": "0x55296f69f40ea6d20e478533c15a6b08b654e758",
        "value": "0x0"
      },
      "blockHash": "0x3cce2553f322137746be7a8dfa9418a625bc80c3df851df630c33030f88143e1",
      "blockNumber": 5285607,
      "result": {
        "gasUsed": "0x7593",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [],
      "transactionHash": "0x6b6a58e63b0186cdf5ba4c387bed7eba2cc800ca2d08dacb860f41271f6c8c06",
      "transactionPosition": 17,
      "type": "call"
    }
  ],
  "id": 1
}
``` 
but when I do a `trace_filter`, I don't get that particular entry:

```sh
$ curl --data '{"method":"trace_filter","params":[{"fromBlock": "0x50a6e7", "toBlock": "0x50a6e7"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://localnode/ |jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   145    0    37  100   108    147    429 --:--:-- --:--:-- --:--:--   428
{
  "jsonrpc": "2.0",
  "result": [],
  "id": 1
}
```

To make it more interesting, I checked the same things on `pmainnet.infura.io`, and received different results (and last I knew, they were on archive mode as well) (the following results are in respective order):

```js
// trace_filter:
{
  "jsonrpc": "2.0",
  "result": [],
  "id": 1
}

// trace_transaction: 
{
  "jsonrpc": "2.0",
  "result": null,
  "id": 1
}
```

Which is clearly not accurate, because it shows up on etherscan, and my local node.

Thoughts on how to fix the first case? The second case is interesting and concerning too, but I'm more interested in why data might not return from a `trace_filter` that does return in a `trace_transaction`...

**Comment by Tbaut** [comment]
I was not able to reproduce:

```
curl --data '{"method":"trace_filter","params":[{"fromBlock":"0x50a6e7","toBlock":"0x50a6e7"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

{"jsonrpc":"2.0","result":
[{
    "action": {
        "callType": "call",
        "from": "0xb34502197ef8df9d5ed3b8072183fe85162deff7",
        "gas": "0x2bb38",
        "input": "0x",
        "to": "0x36f3ff438cd96f095b1bcc03d1b197bd33777578",
        "value": "0x214e8348c4f0000"
    },
    "blockHash": "0x3cce2553f322137746be7a8dfa9418a625bc80c3df851df630c33030f88143e1",
    "blockNumber": 5285607,
    "result": {
        "gasUsed": "0x12c49",
        "output": "0x"
    },
    "subtraces": 3,
    "traceAddress": [],
    "transactionHash": "0x49b1c8d513be8550e36ec9d7aa7e9eec6b90da7383d302b8380031090badf930",
    "transactionPosition": 0,
    "type": "call"
}, 
....

 {
    "action": {
        "callType": "call",
        "from": "0x8547d336f6979a504db5c49e69236f31aeeef95c",
        "gas": "0xde08",
        "input": "0xa9059cbb000000000000000000000000c76bd99b4982633543a5291c756afee6cef6df0f00000000000000000000000000000000000000000003b8e97d229a2d54800000",
        "to": "0x55296f69f40ea6d20e478533c15a6b08b654e758",
        "value": "0x0"
    },
    "blockHash": "0x3cce2553f322137746be7a8dfa9418a625bc80c3df851df630c33030f88143e1",
    "blockNumber": 5285607,
    "result": {
        "gasUsed": "0x7593",
        "output": "0x"
    },
    "subtraces": 0,
    "traceAddress": [],
    "transactionHash": "0x6b6a58e63b0186cdf5ba4c387bed7eba2cc800ca2d08dacb860f41271f6c8c06",
    "transactionPosition": 17,
    "type": "call"
}, ...

 {
    "action": {
        "author": "0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c",
        "rewardType": "block",
        "value": "0x29a2241af62c0000"
    },
    "blockHash": "0x3cce2553f322137746be7a8dfa9418a625bc80c3df851df630c33030f88143e1",
    "blockNumber": 5285607,
    "result": null,
    "subtraces": 0,
    "traceAddress": [],
    "transactionHash": null,
    "transactionPosition": null,
    "type": "reward"
}], "id": 1
}
```

What do you get when being a little more precise with the `fromAddress`:
`curl --data '{"method":"trace_filter","params":[{"fromBlock":"0x50a6e7","toBlock":"0x50a6e7","fromAddress":["0x8547d336f6979a504db5c49e69236f31aeeef95c"]}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

**Comment by Tbaut** [comment]
This could be linked to https://github.com/paritytech/parity/issues/8217 (closed recently) could you check?

**Comment by joshua-mir** [comment]
@crueber please let us know if you want this reopened, closing as stale and likely resolved
