### ISSUE TITLE
Set Network IP For Node

### ISSUE THREAD

**Issue by gaia** [paritytech/parity-ethereum#8957]
> I'm running:
>
> - **Which Parity version?**: v1.11.3-beta-a66e36b-20180605
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: apt-get
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

how do i set
```
--interface=<IP>
Network interfaces. Valid values are 'all', 'local' or the ip
```

in the toml? I tried this with and without quotes around the IP
```
[network]
interface = <IP>
```

Since I am trying to get up and running quickly, I also tried to just put it into parity.service, with and without quotes:

`ExecStart=/usr/bin/parity --interface=<IP>`

Additionally, there is no option --interface under [Network] in in https://paritytech.github.io/parity-config-generator/ either

That being said, reason I want to set a specific IP for the node to use is I am trying to set parity (running at a home machine behind the router, using a dynamic IP) to use a static IP from a VPS (I am using wireguard to do this, and it is working - I can `curl v4.ifconfig.co` or `curl --interface wg0 v4.ifconfig.co` and get the static IP from the VPS back, not the home IP). Interface wg0 shows the VPS static IP in `ifconfig`

**Comment by roninkaizen** [comment]
![aw](https://user-images.githubusercontent.com/17592883/41803966-83a600fe-768f-11e8-8441-2515e6efbebb.JPG)
?

**Comment by gaia** [comment]
Can I add an IP after extip:? Because depending on the interface used, the external IP address will be different. There are two available, one is static the other is dynamic. I would like to force parity to use the dynamic one, with unmetered bandwidth.

**Comment by gaia** [comment]
Thanks for the reply, @Tbaut. What part of this ticket is being added to the 1.12 milestone?

If specifying an interface is not possible, I thought of two other solutions.

A) Let some other mechanism update a DDNS service, and enter a domain name in the config.
B) I will script updating the config with the dynamic IP and restarting parity on my own when the IP changes

**Comment by Tbaut** [comment]
The v1.12 is a running version tracker to see in what release the fix was deployed. It does not mean that it will be fixed in 1.12.

cc @ddorgan regarding the questions and suggestions

**Comment by gaia** [comment]
I have a machine at home which uses a static VPN from a VPS for other chains via a Wireguard tunnel.

Ethereum works well with IPs that change every couple months, and I hope Casper staking continues to do so. The other chains require static IPs (masternodes)

Given that parity uses most of the bandwidth, I'd like it on the physical interface running thru my home ISP, not the wireguard tunnel.

**Comment by joshua-mir** [comment]
Is this still an issue @gaia 

May I suggest running parity in docker and binding to an ip address associated with your interface (`--ip` flag) or directly to the interface itself (maybe look here: https://docs.docker.com/network/network-tutorial-macvlan/)

Closing, let us know if you would like to change this to a feature request.
