### ISSUE TITLE
5MB limit for RPC requests

### ISSUE THREAD

**Issue by littleskunk** [paritytech/parity-ethereum#8961]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.4 (issue first seen 1.9.5, working fine in 1.9.3)
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**expected behavior**

I am running a script. I use web3 batch to send one single rpc request containing a few thousend balanceOf requests. In parity 1.9.3 it was working fine.

**actual**

In parity 1.9.5 a hard 5MB limit was implemented with this commit: https://github.com/paritytech/jsonrpc/commit/06bec6ab682ec4ce16d7e7daf2612870c4272028

1.) Please add an option. I would like to increase that limit.
2.) For some reasons I did not receive the error message `PayloadTooLarge`. The error message gets lost somewhere. Please return the error message.

**steps to reproduce**

parity config `logging = "rpc=trace"`

Run this script:
```
'use strict';

const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545', 0));
const batch = new web3.BatchRequest();

const erc20ABI = [
	{"constant":true,
		"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf",
		"outputs":[{"name":"balance","type":"uint256"}],"payable":false,"type":"function"},
	{"constant":false,
		"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer",
		"outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"}];

const Contract = '0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac';
const ERC20 = new web3.eth.Contract(erc20ABI, Contract);

var count = 0;

function handleResult(error, ETHBalance) {
	if (error) {
		console.log('Error:', error.message);
		process.exit();
	}
	if (!ETHBalance) {
		console.log('Result:', ETHBalance);
		process.exit();
	}
	console.log(count++);
}

for(var i=0; i<25630; i++) {
	batch.add(ERC20.methods.balanceOf('0x0000000000000000000000000000000000000000').call.request(handleResult));
}
batch.execute();
```

25629 (-1 for the loop condition) will be loged as one single request with 5242840 bytes. 25630 is too large. No response and nothing on the logfile.

**Comment by andresilva** [comment]
There's already an option for this `--jsonrpc-max-payload`. The server is returning a 413 (Payload Too Large) HTTP status code but web3 is not handling this correctly (it just exposes an empty error). You can test this by making the batch request with curl and checking the returned status code.
