### ISSUE TITLE
Docker container exited with code 139

### ISSUE THREAD

**Issue by 1scrooge** [paritytech/parity-ethereum#8964]
> I'm running:
>
> - **Which Parity version?**: 1.10.7
> - **Which operating system?**:  Linux
> - **How installed?**: docker container
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum mainnet
> - **Did you try to restart the node?**:  yes

Sometimes docker container exit with code 139 and message:
```
ethereum_1  | 2018-06-23 18:02:18 UTC Reorg to #5841437 67a0…7f7f (cabf…f01e #5841435 cdb6…32ee f517…75a7)
ethereum_1  |
ethereum_1  | ====================
ethereum_1  |
ethereum_1  | stack backtrace:
ethereum_1  |    0:     0x560dc06cf04c - <no info>
ethereum_1  |    1:     0x560dc06cd832 - <no info>
ethereum_1  |    2:     0x560dbfd0b2ea - <no info>
ethereum_1  |
ethereum_1  | Thread '<unnamed>' panicked at 'Expected to find transaction hash. Database is probably corrupted', libcore/option.rs:916
ethereum_1  |
ethereum_1  | This is a bug. Please report it at:
ethereum_1  |
ethereum_1  |     https://github.com/paritytech/parity/issues/new
ethereum_1  |
ethparitynode_ethereum_1 exited with code 139
```
Helps restart docker. It is not periodically, different time. Yesterday was 2 times

**Comment by Tbaut** [comment]
Could you check your RAM and Disk for errors?

**Comment by 1scrooge** [comment]
@Tbaut I have 2 different virtual machines, and both have a problem

**Comment by Tbaut** [comment]
This is a database corruption that is most likely related to your hardware. Can you please run a disk test and Memtest?

**Comment by Tbaut** [comment]
Close as stalled. Please reopen if it happens again.
