### ISSUE TITLE
Health check endpoint checks eth_syncing rather than highestBlock?

### ISSUE THREAD

**Issue by stephgosling** [paritytech/parity-ethereum#9004]
I'm running:
- **Which Parity version?**: Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.1
- **Which operating system?**: Ubuntu 16.04
- **How installed?**: official .deb from github
- **Are you fully synchronized?**:yes 
- **Which network are you connected to?**: mainnet
- **Did you try to restart the node?**: n/a

Other information
- **Environment**: AWS
- **Instance type**: t2.medium
- **Instance storage**: gp2, 512GB (so 1536 IOPS + burst)

Background: we're evaluating running Parity services behind a loadbalancer for web and mobile clients, some of those clients will be connected via WebSocket. As such we need an health check that looks for parity availability but also state (broadly, up-to-dateness). In the above environment I'm curious as Parity sometimes disagrees with itself with regards to this.

Below are 3 curl commands run sequentially but in the same shell session: a call to the health endpoint, JSONRPC call asking for highestBlock, and the healthcheck endpoint again. I don't have timings between each but I'd expect it to be tens of milliseconds between them if not less.

(wrapped for readability):
```
root@ip-172-16-17-185:/var/log/nginx# curl -s localhost:8545/api/health | jq .; \
  curl -s -H "Content-Type: application/json" -X POST 
    --data '[{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1},
        {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}]' localhost:8545 | jq; \
  curl -s localhost:8545/api/health | jq .
{
  "Ok": {
    "peers": {
      "status": "ok",
      "message": "",
      "details": [
        34,
        100
      ]
    },
    "sync": {
      "status": "needsAttention",
      "message": "Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.",
      "details": true
    },
    "time": {
      "status": "ok",
      "message": "",
      "details": 137
    }
  }
}
[
  {
    "jsonrpc": "2.0",
    "result": "0x59091b",
    "id": 1
  },
  {
    "jsonrpc": "2.0",
    "result": {
      "currentBlock": "0x59091b",
      "highestBlock": "0x59091b",
      "startingBlock": "0x58d6e0",
      "warpChunksAmount": null,
      "warpChunksProcessed": null
    },
    "id": 1
  }
]
{
  "Ok": {
    "peers": {
      "status": "ok",
      "message": "",
      "details": [
        34,
        100
      ]
    },
    "sync": {
      "status": "needsAttention",
      "message": "Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.",
      "details": true
    },
    "time": {
      "status": "ok",
      "message": "",
      "details": 137
    }
  }
}
```

the healthcheck is returning unhealthy before-and-after, (with HTTP response 412, so would drop out of the balancer) yet currentBlock == highestBlock

**Comment by Tbaut** [comment]
Could not reproduce on Kovan.. needs investigation and check in the code.

**Comment by seanturner83** [comment]
I use this for now... https://github.com/seanturner83/eth-height-health

**Comment by joshua-mir** [comment]
/api/health was removed completely so this issue is no longer really relevant; more recently https://github.com/paritytech/parity-ethereum/pull/9847 was added to do what it used to do, but with behaviour closer to what you expected as per this issue.
