### ISSUE TITLE
The Parity doesn't send new transactions to network

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity-ethereum#9028]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.6
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

1) Im have tx in pending queue with low fee, tx not confirmed. When I send new tx via json-rpc api, parity return txid, but I can't see this transaction in etherscan, balance does not locked, I can create new full balance transaction and parity will return txid, but etherscan doesn't display it too... 
2) Can I change gasPrice for pending transaction via json-rpc api, how can I do it?

**Comment by alexcos20** [comment]
Same here:
Which Parity version?: Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.1
Which operating system?: Ubuntu 16.04
How installed?: via https://d1h4xl4cr1h0mo.cloudfront.net/v1.11.3/x86_64-unknown-linux-gnu/parity_1.11.3_ubuntu_amd64.deb
Are you fully synchronized?: yes
Which network are you connected to?: ropsten
Did you try to restart the node?: yes
Did you try to delete database and restart ?: yes
Runing like: screen -dmS parity-ropsten /usr/bin/parity --chain ropsten -d=/raid10/coins/parity-ropsten/basedata/ --rpcapi eth,net,web3,personal,parity,parity_set --ipc-apis eth,net,web3,personal,parity --log-file /var/log/parity-ropsten.log --jsonrpc-interface=192.168.244.144

sendTranzactions returns a valid tx hash... 
getTransactionReceipt returns null
getTransactionByHash shows a valid tranzaction 
wait 5 minutes
getTransactionByHash shows null, tx is gone

 
Here is the full rpc log, i will try to get parity more verbose





T 192.168.244.100:33302 -> 192.168.244.144:8545 [AP]  
  POST / HTTP/1.1..Content-Length: 100..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_blockNumber","jsonrpc":"2.0","params":[],"id":"92819954-38a3-4265-9d5f-af2ab402ef17"}

T 192.168.244.144:8545 -> 192.168.244.100:33300 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:45 GMT....52..{"jsonrpc":"2.0","result":"0x363feb","id":"92819954-38a3-4265-9d5f-af2ab402ef17"}...0....

T 192.168.244.100:33302 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 98..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"net_peerCount","jsonrpc":"2.0","params":[],"id":"130d7c25-2696-49c3-b1fb-9d0b600fe23a"}

T 192.168.244.144:8545 -> 192.168.244.100:33302 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:46 GMT....4E..{"jsonrpc":"2.0","result":"0x19","id":"130d7c25-2696-49c3-b1fb-9d0b600fe23a"}...0....

  POST / HTTP/1.1..Content-Length: 143..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_getBalance","jsonrpc":"2.0","params":["0x003f90fb2633df4c0a0f3bf98f3c2d64af701667"],"id":"e1cd2aa0-8e58-4611-a74d-087e64fa0303"}

T 192.168.244.144:8545 -> 192.168.244.100:33310 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....5B..{"jsonrpc":"2.0","result":"0xde0b6b3a7640000","id":"e1cd2aa0-8e58-4611-a74d-087e64fa0303"}...0....

T 192.168.244.100:33312 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 235..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_estimateGas","jsonrpc":"2.0","params":[{"from":"0x003f90fb2633df4c0a0f3bf98f3c2d64af701667","to":"0x00261727b40a23f00034f521ec73e886c29ccc77","value":"0x1000000000000000000"}],"id":"9ee8fc75-5494-4cdc-8fbf-c56d3fc3c16a"}

T 192.168.244.144:8545 -> 192.168.244.100:33312 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....50..{"jsonrpc":"2.0","result":"0x5208","id":"9ee8fc75-5494-4cdc-8fbf-c56d3fc3c16a"}...0....

T 192.168.244.100:33314 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 85..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_gasPrice","jsonrpc":"2.0","id":"7b730882-776f-42c7-9c4c-82d8cf53a913"}

T 192.168.244.144:8545 -> 192.168.244.100:33314 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....54..{"jsonrpc":"2.0","result":"0x1dcd6501","id":"7b730882-776f-42c7-9c4c-82d8cf53a913"}...0....

T 192.168.244.100:33316 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 169..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"personal_unlockAccount","jsonrpc":"2.0","params":["0x003f90fb2633df4c0a0f3bf98f3c2d64af701667","XXXXXXXX",null],"id":"2068c8bd-3a47-48c1-9471-684e7c4d477a"}

T 192.168.244.144:8545 -> 192.168.244.100:33316 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....4C..{"jsonrpc":"2.0","result":true,"id":"2068c8bd-3a47-48c1-9471-684e7c4d477a"}

T 192.168.244.100:33318 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 274..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_sendTransaction","jsonrpc":"2.0","params":[{"from":"0x003f90fb2633df4c0a0f3bf98f3c2d64af701667","to":"0x00261727b40a23f00034f521ec73e886c29ccc77","value":"0xde0ac3275bdfa00","gas":"0x5208","gasPrice":"0x1dcd6501"}],"id":"3bd5713b-d38d-4703-8103-5c33f9db8a3b"}

T 192.168.244.144:8545 -> 192.168.244.100:33318 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....8C..{"jsonrpc":"2.0","result":"0x59e054714ab9c4bda2ddf1823f81e9c9e443c25ca743e1503649928f60d5cc80","id":"3bd5713b-d38d-4703-8103-5c33f9db8a3b"}...0....

T 192.168.244.100:33320 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 178..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_getTransactionReceipt","jsonrpc":"2.0","params":["0x59e054714ab9c4bda2ddf1823f81e9c9e443c25ca743e1503649928f60d5cc80"],"id":"bf178eac-e51e-4183-bd92-8ed32e03cc89"}

T 192.168.244.144:8545 -> 192.168.244.100:33320 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....4C..{"jsonrpc":"2.0","result":null,"id":"bf178eac-e51e-4183-bd92-8ed32e03cc89"}

T 192.168.244.100:33322 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 177..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_getTransactionByHash","jsonrpc":"2.0","params":["0x59e054714ab9c4bda2ddf1823f81e9c9e443c25ca743e1503649928f60d5cc80"],"id":"050f3dfa-2513-4caa-901d-14faf402d2a7"}

T 192.168.244.144:8545 -> 192.168.244.100:33322 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:52 GMT....3EA..{"jsonrpc":"2.0","result":{"blockHash":null,"blockNumber":null,"chainId":"0x3","condition":null,"creates":null,"from":"0x003f90fb2633df4c0a0f3bf98f3c2d64af701667","gas":"0x5208","gasPrice":"0x1dcd6501","hash":"0x59e054714ab9c4bda2ddf1823f81e9c9e443c25ca743e1503649928f60d5cc80","input":"0x","nonce":"0x4","publicKey":"0x9dae4427bb55fbb1f850a5b0c2c0ac304c19d647d21f2a043c5b128bf5e59f3b715ffc1921b85e6c81cac9dcbd01beb4713d3098de5d2f3d4a385e298952d331","r":"0x11d4b60c837ac90c9480fc0182dd9e091b549187f828fdcf9b23fc4bd979a201","raw":"0xf86b04841dcd65018252089400261727b40a23f00034f521ec73e886c29ccc77880de0ac3275bdfa008029a011d4b60c837ac90c9480fc0182dd9e091b549187f828fdcf9b23fc4bd979a201a0104ca3d0ec307744885fb2af68c25ec1a2ff131578607ab31ef3346b6e98f6bb","s":"0x104ca3d0ec307744885fb2af68c25ec1a2ff131578607ab31ef3346b6e98f6bb","standardV":"0x0","to":"0x00261727b40a23f00034f521ec73e886c29ccc77","transactionIndex":null,"v":"0x29","value":"0xde0ac3275bdfa00"},"id":"050f3dfa-2513-4caa-901d-14faf402d2a7"}

T 192.168.244.100:33324 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 96..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_syncing","jsonrpc":"2.0","params":[],"id":"8b68374e-8c01-4cac-abe5-55d81ac2c4b7"}

T 192.168.244.144:8545 -> 192.168.244.100:33324 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:56 GMT....4D..{"jsonrpc":"2.0","result":false,"id":"8b68374e-8c01-4cac-abe5-55d81ac2c4b7"}

T 192.168.244.100:33326 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 100..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_blockNumber","jsonrpc":"2.0","params":[],"id":"d52395da-0141-4488-85ac-cc66349d29dd"}

T 192.168.244.144:8545 -> 192.168.244.100:33326 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:56 GMT....52..{"jsonrpc":"2.0","result":"0x363feb","id":"d52395da-0141-4488-85ac-cc66349d29dd"}...0....

T 192.168.244.100:33328 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 98..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"net_peerCount","jsonrpc":"2.0","params":[],"id":"40cd5383-e1d4-4cbf-a6f0-fd6c32acb3ec"}

T 192.168.244.144:8545 -> 192.168.244.100:33328 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:56 GMT....4E..{"jsonrpc":"2.0","result":"0x19","id":"40cd5383-e1d4-4cbf-a6f0-fd6c32acb3ec"}


T 192.168.244.100:33333 -> 192.168.244.144:8545 [AP]
  POST / HTTP/1.1..Content-Length: 143..Content-Type: application/json; charset=utf-8..Accept: application/json..Host: 192.168.244.144:8545..Connection: close....{"method":"eth_getBalance","jsonrpc":"2.0","params":["0x003f90fb2633df4c0a0f3bf98f3c2d64af701667"],"id":"e1cd2aa0-8e58-4611-a74d-087e64fa0303"}

T 192.168.244.144:8545 -> 192.168.244.100:33333 [AP]
  HTTP/1.1 200 OK..Content-Type: application/json..Transfer-Encoding: chunked..Date: Mon, 02 Jul 2018 15:52:51 GMT....5B..{"jsonrpc":"2.0","result":"0xde0b6b3a7640000","id":"e1cd2aa0-8e58-4611-a74d-087e64fa0303"}...0....


after a few minutes:

curl --data '{"method":"eth_getTransactionByHash","params":["0x59e054714ab9c4bda2ddf1823f81e9c9e443c25ca743e1503649928f60d5cc80"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 192.168.244.144:8545
{"jsonrpc":"2.0","result":null,"id":1}

**Comment by alexcos20** [comment]
after 2 restarts, everything is fine now..

i will try to duplicate...

**Comment by debris** [comment]
@tomusdrw I know that you recently fixed several things in transaction queue. Were those fixes somehow related with this issue? If not, do you know what may have caused the problem?

**Comment by tomusdrw** [comment]
Should be fixed with recent changes to local transactions. Regarding the low gas price transactions:
1. You can re-submit with higher gas price in TxQueueViewer
2. We cannot do much about `etherscan` not showing your local low-gas price transaction, their queues are most likely full as well.
