### ISSUE TITLE
Inconsistent API Health Check responses

### ISSUE THREAD

**Issue by ankitarora121** [paritytech/parity-ethereum#9030]
> I'm running:
>
> - **Which Parity version?**: v1.11.4
> - **Which operating system?**:  Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes?
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Expected Behavior:**
'API Health' should be a solid and reliable indicator of node health. I would expect a more accurate representation of the state of the node, so that I can kick in necessary mitigation procedures.

**Actual Behavior:**
Here are 3 calls to `/api/health` within a span of 3 minutes, with no changes to the node or network in between:

**1**
`{"Ok":{"peers":{"status":"ok","message":"","details":[4,25]},"sync":{"status":"ok","message":"","details":false},"time":{"status":"needsAttention","message":"Time API request timed out. Make sure that the clock is synchronized.","details":0}}}
`

**2**
`{"Ok":{"peers":{"status":"bad","message":"You are not connected to any peers. There is most likely some network issue. Fix connectivity.","details":[0,25]},"sync":{"status":"ok","message":"","details":false},"time":{"status":"needsAttention","message":"Time API request timed out. Make sure that the clock is synchronized.","details":0}}}
`

**3**
`{"Ok":{"peers":{"status":"ok","message":"","details":[2,25]},"sync":{"status":"needsAttention","message":"Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.","details":true},"time":{"status":"needsAttention","message":"Time API request timed out. Make sure that the clock is synchronized.","details":0}}}`

I do notice I'm running ~5-8 minutes behind the chain I see on Etherscan. Could be interrelated, but the point is that the health check has only confused me more instead of pointing me to the right direction.

**Steps to reproduce**

Hit `/api/health` RPC endpoint at ~30 second intervals.

**Comment by Tbaut** [comment]
Can you precise why it is inconsistent in your case and what would be a "more accurate representation of the state" ?

**Comment by debris** [comment]
There is nothing to do here
