### ISSUE TITLE
Feature request - connect to enode via rpc call

### ISSUE THREAD

**Issue by MarkusTeufelberger** [paritytech/parity-ethereum#9049]
I haven't found a way to hand parity an enode string and make it (try to) connect once or a few times to that host. This would be really useful in some situations (e.g. net splits, testing small networks).

I know that there's a "reserved_peers" setting, I'm proposing to add peers manually at runtime. There's also https://wiki.parity.io/JSONRPC-parity_set-module#parity_addreservedpeer, but I don't want to limit myself to only reserved peers. Probably something like a `parity_addPeer` RPC call.

**Comment by 5chdn** [comment]
add reserved peer is exactly what you are looking for.

you only limit yourself to reserved peers if you run parity with --reserved-only.
