### ISSUE TITLE
Receiving error when trying to transfer Erc20 tokens

### ISSUE THREAD

**Issue by IvIazen** [paritytech/parity-ethereum#9062]
I'm running: Parity v1.11.5

> - **Which Parity version?**: v1.11.5
> - **Which operating system?**: MacOS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum

Whenever I try to transfer my Erc20 token through contracts I keep receiving the following error:
Warning! Error encountered during contract execution [Reverted] 
I have confirmed through a query that I have a balance. Just as I side not I have transferred Erc20 tokens before without any issue. 

Can someone please help...

**Comment by Tbaut** [comment]
Please describe precisely the steps you perform (including the contract address etc).

**Comment by Tbaut** [comment]
Close as stalled. Please reopen if it happens again.
