### ISSUE TITLE
Should the Dockerfiles build the stable branch?

### ISSUE THREAD

**Issue by j4ys0n** [paritytech/parity-ethereum#9065]
Could be just me, but I feel like since Docker is often used for production automation, the Dockerfiles should checkout and build the stable branch (not master/unstable). Happy to put in a PR for this update but thought I'd ask first. Is this a good idea?

**Comment by debris** [comment]
I don't think that this is a good idea for multiple reasons:

- `master` and `stable` branch may require different dependencies
- current configuration of docker is flexible and allows you to easily build whatever you want. If you want to use stable, just do `git checkout stable`, if you want master, just `git checkout master`
