### ISSUE TITLE
parity private Transactions issue

### ISSUE THREAD

**Issue by zhjgit** [paritytech/parity-ethereum#9071]
How to ensure that the transaction is confirmed when performing a private transaction。
![111_20180709151902](https://user-images.githubusercontent.com/11417141/42436255-f8a24bc0-838b-11e8-80e6-99ff4801f933.png)

**Comment by zhjgit** [comment]
I still have a question, Is the zero step in the picture above.“0) (Pre-requisite) Contracts registry must be deployed on the chain. ”  what means contracts registry ?Is it a public contract that I want to deploy myself?

**Comment by zhjgit** [comment]
If you have a complete private Transactions contract tutorial please give me a link,thanks.

**Comment by Tbaut** [comment]
There is no difference with a normal transaction. It could probably be useful to have tests to make sure the private contract is working as expected.

 >what means contracts registry? Is it a public contract that I want to deploy myself?

You have to deploy it yourself yes, it looks like this: https://github.com/paritytech/contracts/blob/master/SimpleRegistry.sol

>If you have a complete private Transactions contract tutorial please give me a link, thanks.

We do not have it yet, but it's planned for soon: https://github.com/paritytech/wiki/issues/175

**Comment by Tbaut** [comment]
The tutorial is being reviewed, have a look at it here: https://github.com/paritytech/wiki/blob/Tbaut-private-transactions-tutorial/Private-Transactions-Tutorial-Overview.md
I'll close this issue, feel free to answer if you have other questions.
