### ISSUE TITLE
Non-standard port handling

### ISSUE THREAD

**Issue by wandergeek** [paritytech/parity-ethereum#9078]
I'm running:

>
> - **Which Parity version?**: Parity//v1.10.8
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private poa
> - **Did you try to restart the node?**: yes

## Actual
I have several parity processes spread across two VMs. The processes connect up to the bootnode ok, but the peers can't connect with one another. My environment is broken down as follows:

52.221.214.121
    'tx' - parity process on 30304

13.229.143.177
    'bootnode' - on port 30303
    'validator' on port 30302

When the nodes spin up, both validator and tx peer to the bootnode just fine. However validator and tx are unable to communicate. When I query the tx node for its enode, I get the following:

```
~
$ getenode
{"jsonrpc":"2.0","result":"enode://95592ae74f78ba221fbd322399ebf37040d4cd3dd0c87f709dfcd7b36f41d19814b14f26974bd96408a6bcbc4ea56368ddeb9611d93eca149dd82901c1931d15@52.221.214.121:30304","id":0}

```

When I query the bootnode logs for this enode, I get the following:

```
kubectl logs -f nonexistent-bear-i8-parity-poa-bootnode-86cbf6876-x5xbq -c bootnode | grep -a5 -b5  95592ae74f78ba221fbd322399ebf37040d4cd3dd0c87f709dfcd7b36f41d19814b14f26974bd96408a6bcbc4ea56368ddeb9611d93eca149dd82901c1931d15
1568832-2018-07-09 07:38:37 UTC IO Worker #3 TRACE discovery  Sent Ping to NodeEndpoint { address: V4(52.221.214.121:30303), udp_port: 30303 }
1568967:2018-07-09 07:38:37 UTC IO Worker #3 TRACE discovery  Inserting NodeEntry { id: 95592ae74f78ba221fbd322399ebf37040d4cd3dd0c87f709dfcd7b36f41d19814b14f26974bd96408a6bcbc4ea56368ddeb9611d93eca149dd82901c1931d15, endpoint: NodeEndpoint { address: V4(52.221.214.121:30303), udp_port: 30303 } }
```

As you can see, the bootnode is saying the tx's port is 30303 when it's really on 30304.

I'm launching the bootnode as follows:
```
/parity/parity --config=/parity/config/node.toml --nat=extip:13.229.143.177 
```

I'm launching the tx node as follows:
```
/parity/parity --config=/parity/config/node.toml --bootnodes=$(cat /parity/data/bootnodes) --nat=extip:52.221.214.121 --port=30304 
```

Shared config file is as follows:
```
    [parity]
    chain = "/parity/config/spec.json"
    base_path = "/parity/data"

    [rpc]
    interface = "0.0.0.0"
    cors=["all"]
    apis = ["all"]
    hosts = ["all"]

    [ipc]
    disable = true

    [footprint]
    pruning = "fast"
```

## Expected Behavior

I'd expect the bootnode to use the enode's actual ip and port, rather than just the ip.

## Steps to Reproduce

On two separate VM's, launch the following:

VM 1:
```
/parity/parity --config=/parity/config/node.toml --nat=extip:<VM 1 IP
/parity/parity --config=/parity/config/node.toml --bootnodes=$(cat /parity/data/bootnodes) --nat=extip:52.221.214.121 --port=30304 
```

VM 2:
```
/parity/parity --config=/parity/config/node.toml --nat=extip:<VM 2 IP --bootnodes=enode://<NODE ID>:30303
```

**Comment by Tbaut** [comment]
Is there any log mentioning an error/impossibility to connect?

As a workaround, can you connect your peers manually with reserved-peers (flag or RPC)?

How long did you let all VM run (discovery can take several hours)?

**Comment by Tbaut** [comment]
Close as stalled. Please reopen if it happens again.
