### ISSUE TITLE
Parity 1.11.6 is rejecting transactions from local accounts

### ISSUE THREAD

**Issue by ppratscher** [paritytech/parity-ethereum#9087]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.6
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

The new tx queue implementation in 1.11.6 seems to treat transactions from local accounts different compared to previous versions. Previously the tx queue always accepted transactions from local accounts. The new tx queue implementation rejects them with the following message:

```
2018-07-10 16:24:30  IO Worker #2 TRACE txqueue  [0x1af684a0ac8011232397277a8b62616b9009b087283a1ae946a58d27555f94a3] Rejected tx early, cause it doesn't have any chance to get to the pool: (gas price: 1000000000 < 13000000000)
2018-07-10 16:26:37  IO Worker #3 TRACE txqueue  [0x1af684a0ac8011232397277a8b62616b9009b087283a1ae946a58d27555f94a3] Rejected tx early, cause it doesn't have any chance to get to the pool: (gas price: 1000000000 < 10000000000)
```

Expected behavior: Transactions with sender = local account should never be rejected from the tx queue independent of the status of the tx pool.

Edit: Might be caused by https://github.com/paritytech/parity/pull/8934/commits/7f4d825d64eb1f3892f81f5e633185d9bd3079dc

**Comment by Tbaut** [comment]
@tomusdrw can you have a look?

**Comment by tomusdrw** [comment]
@ppratscher are you submitting the transactions via `eth_signTransaction` or `eth_sendRawTransaction`? The min effective gas price check is actually guarded by `!is_own` so the transaction submitted on a local node should never reach that check.

The situation is indeed a bit different if we have a local account, but the transaction is received over the network (i.e. sent from some other node). Is that the use case you are having?

**Comment by ppratscher** [comment]
Yeah, the node does receive that transaction via the P2P network and not via a local RPC call.

**Comment by tomusdrw** [comment]
I guess the solution would be to add a CLI flag to bring back the previous behaviour. The optimization here was introduced to improve performance of the node in case the queue is full, and avoid doing (very costly) ecrecover for every incoming transaction.

So with the flag it would be possible to opt-in to the less performant old behaviour.

@ppratscher As a workaround I'd suggest:
1. Running with larger queue size. 1.11.6 should be able to easily handle large transaction pools (we have one node running with 256k limit with 160k transactions in the pool).
2. Increasing min-gas-price, so that external transactions don't occupy the entire pool - this will allow local transactions to enter, since minimal effective gas price check won't be in place (it's only activated if the pool is saturated).

**Comment by ppratscher** [comment]
Thanks, we will try to increase the queue size and check how it affects the mining performance and uncle rate of the node. Unfortunately the second workaround is not really an option as we also need to include external transactions in the blocks.

Indeed it would be great to have an opt-in flag for the previous behavior available as the additional ecrecover operations should not be an issue with our hardware.

**Comment by tomusdrw** [comment]
@ppratscher The long time you are seeing is related to how the informant is implemented, it waits for all the local work to be finished before reporting the block time. Indeed clearing out larger queues takes longer (seconds), but recently in 1.11.6 new pending block is created before the queue is being cleared (see https://github.com/paritytech/parity/pull/9024#issue-198665155), so it shouldn't increase uncle rate or prevent propagation.

Let me know if that's not the case, I'll look into optimizing that further. A log captured with `-lclient=trace,miner=trace` would also be helpful (optionally with `perf=trace` if it doesn't produce too much).

**Comment by ppratscher** [comment]
@tomusdrw I sent you the logs directly via DM on gitter + some additional info

**Comment by Tbaut** [comment]
@ppratscher could you please also post it here (in a gist?) for the record :)

**Comment by tomusdrw** [comment]
@Tbaut stratum notification is being sent after `chain_new_blocks` is finished, so miners are not notified about the new pending block (even though it's already created). I'm preparing a patch soon.
