### ISSUE TITLE
Using gasprice oracle for a custom network

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity-ethereum#9089]
> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: -
> - **Which network are you connected to?**: -
> - **Did you try to restart the node?**: -

It looks like currently gasprice oracle can only be used for foundation chain

https://github.com/paritytech/parity/blob/da5de4a6ffd275961cff124798caaef7b9d57483/parity/configuration.rs#L655-L657

Maybe I'm missing something. Docs mention that
> --usd-per-eth=[SOURCE]
        USD value of a single ETH. SOURCE may be either an amount
        in USD, a **web service** or 'auto' to use each web service in
        turn and fallback on the last known good value. (default:
        auto)

but it doesn't seem to work even if the condition above is changed and parity recompiled (I tried `--usd-per-eth=http://localhost:8000`), because validation fails on this line:
https://github.com/paritytech/parity/blob/da5de4a6ffd275961cff124798caaef7b9d57483/parity/configuration.rs#L659
with error `Invalid transaciton price 's' given. Must be a decimal number.`

It would be nice to be able to use gasprice oracle for any custom network by providing url of oracle http service.

Also, when recalculating `wei_per_gas`
https://github.com/paritytech/parity/blob/da5de4a6ffd275961cff124798caaef7b9d57483/parity/configuration.rs#L644-L649
precision might be lost.

**Comment by Baranowski** [comment]
I just briefly skimmed through the code, and this seems easy. If you don't mind, I would like to take a stab at this as my first project in parity and in Rust in general.

One thing I would appreciate help with is a detailed (ideally, specific command lines and expected outputs) instruction how to test my patch. Or, even better, suggestion how to add an automated test, if feasible. Thanks in advance!

**Comment by dvdplm** [comment]
@Baranowski welcome, and we're very happy to accept contributions! We'll do out very best to be responsive ofc, feel free to post any questions here and maybe @phahulin would be willing to assist as well? :)

**Comment by joshua-mir** [comment]
@Baranowski looking at the tests [here](https://github.com/paritytech/parity-ethereum/blob/2af3140a2677b5a7e08b9fb8a133320a2d4ba908/rpc/src/v1/tests/mocked/eth.rs#L738) might be a good place to start - of course there are also a few tests[ in PriceInfo itself](https://github.com/paritytech/parity-ethereum/blob/16e0ad1288c794472297254e8c4ccd1ba9a2708a/miner/price-info/src/lib.rs#L116)

You could probably use either as reference.

**Comment by Baranowski** [comment]
Sorry, I won't implement this after all, as I mentioned in the closed PR above.

**Comment by rakanalh** [comment]
Opened a PR inspired by the work @Baranowski did previously.
