### ISSUE TITLE
eth_getFilterChanges returns "Filter not found" for a previously existing filter

### ISSUE THREAD

**Issue by cheeselord1** [paritytech/parity-ethereum#9122]
> I'm running:
>
> - **Which Parity version?**: 1.11.6-beta
> - **Which operating system?**: Linux
> - **How installed?**: via source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm using eth_getFilterChanges to check for specific events after each block confirmation. After creating a new Filter_ID, this will work without issue for several dozens of blocks until suddenly eth_getFilterChanges will return "Filter Not Found" and I'll have to recreate my filter.

Edit: I believe I only have this issue for filters created via eth_newFilter (specifying a specific list of topics), not for eth_newPendingTransactionFilter.

**Comment by andrevmatos** [comment]
Can confirm I've seen this too, sometimes as soon as 3min after filter install + polling started. I couldn't narrrow down the issue to any particular interaction, the app just polls the fiter, and suddenly crashes because of the above error.

**Comment by cheeselord1** [comment]
I think the issue may be that the filter is time'ing out, even though I call eth_getFilterChanges every confirmed block.  I haven't seen the filter timeout duration in the docs - anyone know what it is? I think Filter timeout should be set sufficiently high that it doesn't occur during a slightly longer-than-normal block interval. E.g. set it to maybe 5-10 minutes?

I updated my app to call eth_getFilterChanges a minimum of once every block OR 20 seconds, and I haven't had this issue since.

**Comment by Tbaut** [comment]
As per https://github.com/paritytech/parity/issues/8741#issuecomment-395690801 the filter indeed needs to be called at least every 60sec.

**Comment by Tbaut** [comment]
60sec seems to be enough for most cases. Please reopen if flexible setting is needed.

**Comment by Sword-Smith** [comment]
I would be very interested in a flexible setting for the filter timeout!
