### ISSUE TITLE
Split out bn128 helpers into a separate package

### ISSUE THREAD

**Issue by axic** [paritytech/parity-ethereum#9147]
This is kind of a feature request.

Currently the precompiled contracts are implemented in [ethcore/builtin](https://github.com/paritytech/parity/blob/c7f608ec740882eac94038249037ddd955b60d31/ethcore/src/builtin.rs). The bn128 ecadd/ecmul/ecpairing precompiles are implemented there as well, using the `bn` crate as the underlying library.

In ethereumjs-vm the same underlying library is used and part of the code is duplicated as a wrapper library [rustbn.js](https://github.com/ethereumjs/rustbn.js).

Now additionally we are experimented with writing the precompiles as contracts in the ewasm project and as a result we need the very same wrapper, hence we have split out the above code from `builtin.rs` into a crate of its own: https://github.com/ewasm/ethereum-bn128.rs

It can now be used by both rustbn.js and the contract.

This works well, but it seems like a bad idea to maintain a fork and such would like to invite the maintainers to consider splitting out that code into a crate maintained in this org and used by the Parity client too.

Would that be considered? Are there are any reasons against it? Would you accept a PR to do this?

**Comment by NikVolf** [comment]
Hi axic!

Sure, we will accept the pr, no reason against it.

But the code in ethcore/builtin is merely deserialization and serialization of points and field members, all the work is done in bn itself, what do you want to split out exactly?

**Comment by axic** [comment]
If you can have a look at https://github.com/ewasm/ethereum-bn128.rs/blob/master/src/lib.rs it has the parts we need to be split: the (de)serialisation and the test cases.

I'd assume these internal helpers would then be called by the `Builtin`
 implementation for the said precompiles.

The gas calculation could also go in there, but not necessarily.

**Comment by debris** [comment]
we just split builtins into it's own crate (#10850). for now, further splits are not planned
