### ISSUE TITLE
"geth attach" hangs

### ISSUE THREAD

**Issue by 4ntoine** [paritytech/parity-ethereum#9165]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 2.0.0-beta
> - **Which operating system?**: MacOS with Docker
> - **How installed?**: Docker image parity/parity:v2.0.0
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**:ropsten
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Background**

**Actual**
`geth attach http://127.0.0.1:8545` hangs:
```
$geth attach http://127.0.0.1:8545
Welcome to the Geth JavaScript console!

instance: Parity-Ethereum//v2.0.0-beta-6eae372-20180717/x86_64-linux-gnu/rustc1.27.1
coinbase: 0x0000000000000000000000000000000000000000
```

**Expected**
after `geth attach` I can see ">" to type commands 

Relates to 1.11.7 and 2.0.0-beta too, can not be reproduced 100% of times.

**Comment by Tbaut** [comment]
Why makes you think it's a parity problem? Can you tell what flags you launch parity with?

**Comment by 4ntoine** [comment]
Running it in docker with:

> --chain ropsten --cache-size ${CACHE_SIZE:-512} --reserved-peers /misc/ropstenpeers.txt --reserved-only --jsonrpc-interface "0.0.0.0" --jsonrpc-hosts all --ui-interface all --jsonrpc-apis eth,net,personal,rpc,web3,pubsub,parity --db-compaction ssd --pruning fast --mode active --tracing off --no-ipc

Any reasons to think it's not parity? I can check if you point up

**Comment by 4ntoine** [comment]
BTW it seems it's in sync and getting block number blocks the output

**Comment by Tbaut** [comment]
>Any reasons to think it's not parity?

You're asking in a parity repo why `geth` command doesn't answer :)

>getting block number blocks the output of geth attach

I don't get that.

**Comment by 4ntoine** [comment]
> You're asking why geth command doesn't answer :)

because `geth` requests block number from parity

> I don't get that.

See where it hanged - the following line should be block number in regular input message.

**Comment by Tbaut** [comment]
I can't reproduce on kovan, ropsten.. while syncing, while synced... The only difference I could have would be the reserved-peers. Could you try without them and let me know if you can reproduce?
