### ISSUE TITLE
Transactions have higher nonce value than it supposed to be and they are not listed in pendingTransactions

### ISSUE THREAD

**Issue by kerematam** [paritytech/parity-ethereum#9166]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.8-stable-bd20c45-20180628/x86_64-linux-gnu/rustc1.27
> - **Which operating system?**: Linux
> - **How installed?**: via Docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: Ropsten
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I've actually two issues where i believe they are related to each other.

1- Somehow Parity make transactions with future nonce values (as long as i wont set it manually). I might have done some previous transaction that are not mined which might causing this (Sorry i can reproduce the problem). But i dont understand how can i create transaction that cant not be mined in Ropsten. Even transactions with 0 gasPrice  are mined. How can i list if transactions that causing nonce value to start from higher values?

2- I cant see any previous transactions from my address on pendingTransactions and pendingTransactionsStats method calls. New transactions with higher nonce values are also not listed pendingTransactions and pendingTransactionsStats. I could only see pending transactions in those methods if i fix nonce value according to last mined transaction from address. I expect to see transactions with higher nonce values on my pending lists. 

Final question; can i manually set nonce variable to be auto incremented by sendTransaction for Parity?

Edit : After many restarts and around 5 hours; nonce value have returned to normal. I've no idea why. I still cant see transactions with nonce gap in pendingTransactions though.

**Comment by Tbaut** [comment]
In general, Parity Ethereum will increment the nonce automatically when a transaction is sent. There are multiple reasons for a transaction not to be mined, have a look at https://wiki.parity.io/Transactions-Queue#accepting-conditions. This usually means that your subsequent transaction will have a nonce gap and will not get mined. To prevent this you can reset the mem pool by launching parity with the flag :
```
    --no-persistent-txqueue
        Don't save pending local transactions to disk to be
        restored whenever the node restarts.
```
You can also manage the nonce yourself (this is recommended with high amount of transactions).
With parity 1.10 you can  see the list of future and local transactions with the rpc [parity_localtransactions](https://wiki.parity.io/JSONRPC-parity-module#parity_localTransactions) and parity_futureTransactions (<-- this rpc has been removed with v1.11 and replaced by parity_allTransactions)

**Comment by gituser** [comment]
this issue might be related to your case: https://github.com/paritytech/parity-ethereum/issues/9040

**Comment by Tbaut** [comment]
We can reopen if it happens again. The best would be to provide a way for us to reproduce.

**Comment by kerematam** [comment]
Thank you for the responses. It was indeed very related to issue you have sent.
