### ISSUE TITLE
db flush panic

### ISSUE THREAD

**Issue by crow123** [paritytech/parity-ethereum#9168]
Thread 'Verifier #0' panicked at 'DB flush failed.: Error(Msg("IO error: While open a file for appending: /root/snap/parity/14219/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/133213.log: Permission denied"), State { next_error: None, backtrace: None })', libcore/result.rs:945

**Comment by debris** [comment]
Process clearly doesn't have enough credentials to open the file.

Please provide more details. Does it happen on application start? Which version of parity? Is it run in a docker etc.

**Comment by Tbaut** [comment]
That a problem related to snap, could you please use the binaries?

**Comment by Tbaut** [comment]
Closing as stalled, please reopen if needed.
