### ISSUE TITLE
Parith RPC eth_call failing

### ISSUE THREAD

**Issue by mtbitcoin** [paritytech/parity-ethereum#9177]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: latest stable
> - **Which operating system?**: Windows 

Running the following curl command returns an empty value

```
curl http://localhost:8545 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"to\": \"0xd850942ef8811f2a866692a623011bde52a462c1\",\"data\": \"0x70a082310000000000000000000000001a2786c684a794d30f57b968e01dc4e40e3377b2\"}, \"latest\"],\"id\":1}" -H "Content-Type: application/json"
```

**Comment by mtbitcoin** [comment]
without the light command, this only breaks with the latest stable. 

The previous stable release works fine. I have been able to product these on multiple nodes with no other changes in the settings except for the parity version

**Comment by Tbaut** [comment]
As asked in the chat, please be precise on `latest stable` and also add how you launch parity (what flags you use).

**Comment by mtbitcoin** [comment]
Release: Parity 1.11.7-stable "Prosperity"

Launch: 
parity.exe" --tracing on --jsonrpc-interface 127.0.0.1 --jsonrpc-port 8545 --jsonrpc-hosts all  --no-dapps --cache-size 5000 --tx-queue-gas off --no-ws

**Comment by Tbaut** [comment]
Working without problem on linux with:
`$ curl --data '{"method":"eth_call","params":[{"to": "0xd850942ef8811f2a866692a623011bde52a462c1","data": "0x70a082310000000000000000000000001a2786c684a794d30f57b968e01dc4e40e3377b2"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000000","id":1}`

**Comment by mtbitcoin** [comment]
Figured this out, and just in case someone else run's into the same issue the "--jsonrpc-apis XXX" is now required or it blocks

**Comment by Tbaut** [comment]
>--jsonrpc-apis XXX" is now required or it blocks
The `eth` api is active by default. you must have omitted it in your config file)
