### ISSUE TITLE
Delay on Time transactions

### ISSUE THREAD

**Issue by redeyeSPB** [paritytech/parity-ethereum#9182]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.11.7-stable
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

when there was a parity UI, it became noticeably slower program, the main problem today is that when I send a transaction from my wallet (time transaction)  at a time says at, for example 5:00 I set the timer... and always get a delay of 2-3 minutes...(I mean transaction will be sent only 5:02-5:03 (help with this problem Please) earlier when I was working through the browser, everything was great. Thanks. 
(I'am trying to use different versions of parity+parity UI but the problems repeat)

**Comment by Tbaut** [comment]
This is most probably due to the gas price you use and the congestion of the network. You can pay more if you think it really needs to get through quickly.

**Comment by redeyeSPB** [comment]
it is not in the gas price problem.sorry, i'am not full idiot :))  when I submit a transaction with the same parameters without a timer everything goes perfectly. the timer itself has 1-2 delay :( i don't know why...
problem came with parity UI. Help please ;)

**Comment by Tbaut** [comment]
Parity UI repo is the following: https://github.com/Parity-JS/shell/issues
Please log your issue here. Note that Parity UI is not actively maintained anymore. This means that your issue will probably not get a lot of attention.

**Comment by Tbaut** [comment]
There are dozens of wallets out there. MyCrypto Desktop would be my choice of the day. Note that you can still connect it to your parity node to be totally free of any centralized node.
