### ISSUE TITLE
[Permissioning] Implement permissioning for RPC calls

### ISSUE THREAD

**Issue by grbIzl** [paritytech/parity-ethereum#9204]
"BC-1a-ApiCallPermissioning: Implementations SHOULD provide separate access control permissions for API calls which are Administrative, API calls which allow viewing the state of the distributed ledger or are View calls, API calls which result in a transaction, API calls which result in deploying a contract, and API calls which transfer Ether." from https://arxiv.org/pdf/1806.09834.pdf
The further details and use cases can be found in 2.2.1. of the referenced document

**Comment by grbIzl** [comment]
@tomusdrw FYI

**Comment by tomusdrw** [comment]
Available as a RPC proxy https://github.com/tomusdrw/jsonrpc-proxy
@dvdplm I believe we don't really plan to implement it so I think it's safe to close it.
