### ISSUE TITLE
DB Corrupted when running parity --geth first time

### ISSUE THREAD

**Issue by smaxzs** [paritytech/parity-ethereum#9205]
Parity/v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0

4.16.0-2-amd64 #1 SMP Debian 4.16.16-2

Binary executable, after initial sync and subsequent initialization of client with ~4 day breaks in between usage.

On ethereum network: using parity --geth when previous ~5 initializations just executed parity sans attributes.

```
2018-07-23 10:23:17  DB corrupted: Corruption: block checksum mismatch: expected 1931100700, got 420517280  in /home/username/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/023422.sst offset 51865987 size 16366. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x5572ffb6a67c - <no info>

Thread 'IO Worker #3' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1931100700, got 420517280  in /home/kms/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/023422.sst offset 51865987 size 16366"), State { next_error: None, backtrace: None })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

```

upon restart

```
2018-07-23 10:34:55  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col2, col0, col3, col1, col5, col6, attempting repair
Client service error: Client(Database(Error(Msg("Received null column family handle from DB."), State { next_error: None, backtrace: None })))


```

results in error and return to prompt.

killed db and currently rebuilding

**Comment by smaxzs** [comment]
stopped syncing snapshots at 27/1781 and began regular sync.

killed db again and executed parity -warp, eliminating some background processes that may be resource hungry (but i have over 10 threads free still)

**Comment by smaxzs** [comment]
`2018-07-23 12:25:01  Stage 2 block verification failed for 2cb5…c49c: Block(MismatchedH256SealElement(Mismatch { expected: a7f80137dcf8be8e34bade0bf774e415491598c6e08786dc10aee61c3d9f3f6a, found: fc8cc3439def8bd8b2f8e31cccd4acca0eb8cb92274ac904ac4a3ceb5402a6b0 }))`

seemed fine syncing via snapshop, walked away after 500+ of 1700 sync'd only to return to above error and multiple attempts to sync block 2769.

no need to nuke db restart of parity started snapshop sync over again.

**Comment by smaxzs** [comment]
of note while syncing snapshots block #2769 was listed entire process of snapshot download.. until sync then it started syncing from that block.

only 1657 snapshots are listed after this recent "parity kill db" execution, but its back to block 0.

previously 1797 snapshots were available to dl.

a few minutes in and its still only at snap 2/1657

**Comment by smaxzs** [comment]
`2018-07-23 14:32:05  Stage 2 block verification failed for f69f…dbca: Block(MismatchedH256SealElement(Mismatch { expected: 447dfbb9bdd51ec8906c465ec630d664ed2ad00aa53731a7b67bfe93dc404034, found: fdd6f300e8f2edfd8b4e28ea04503d0a36f3715194df4ed1a1ede3c9f8c9215a }))
`
manually nuking db, and user_defaults file

**Comment by smaxzs** [comment]
2018-07-23 22:35:00  DB corrupted: Corruption: Corrupted internal key not expected.. Repair will be triggered on next restart

at it again and its giving above error now.

snapshot syncing ceases at random places.. 107/1781 370/1781..

i am guessing i'll have to nuke my eth wallets and reinsert them after sync?

i'll let one more attempt at snapshot sync run its course.

**Comment by Tbaut** [comment]
This is most probably a hardware problem (RAM or SSD). Please verify them.

**Comment by Tbaut** [comment]
https://github.com/paritytech/parity-ethereum/issues/7748

**Comment by smaxzs** [comment]
ok.. so i did have some out of spec higher memory settings that i was getting by with mining but possibly were too much for parity.

no kernel alerts presented themselves at any point, i'm not sure its what resolved the issue in the end.

i downloaded the new parity 1.11.7 binary, and deleted the entire hierarchy down from .local/share/io.parity.ethereum

before resorting to this i tried light client which sync'd well but was unusable for transactions with parity-ui and did not seem compatible with geth at all.. and i also tried some high cache, no archive type warp syncs, along with barrier which was fruitless.

in the end the regular sync from scratch and fresh nuke of the data directory (and a higher cache) did the trick.

thanks for the tip on the memory, i'll keep it at the lower state although i'm missing 50 some odd H/s.. there is a 20%-40% chance that may have been it i say.
