### ISSUE TITLE
ERRR! Auto send transaction version beta

### ISSUE THREAD

**Issue by Vagabondtq** [paritytech/parity-ethereum#9208]
> I'm running: personal_sendTransaction
>
> - **Which Parity version?**: Parity-Ethereum/v2.1.0-unstable-4848c38-20180723/x86_64-linux-gnu/rustc1.26.2
> - **Which operating system?**:Linux
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:yes

when i update new version and send transaction with api rpc:

`personal_sendTransaction`

Data:

```
 [
  "from" => "0x3e524A4670e928A86d137aEE4531BC0449eec1d7"
  "to" => "0xc72bd07df099419c9d57b5c2c8fb813dfa0ab89f"
  "gas" => "0x5208"
  "gasPrice" => "0x9502f9000"
  "value" => "0x3782daa95cd1c00"
]
```
I get API is  **null**
But, wen i check: `parity_localTransactions`, i see transaction: 
`0x208f18ce3866a9746754238cbee54050b52c3226d3e1d8953922882dc31c3045`

 same time, same value but send to 
`0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58`

i don't know account.

**Comment by Tbaut** [comment]
Please paste your whole RPC here and answer.

**Comment by Tbaut** [comment]
closing as stalled.
