### ISSUE TITLE
Light Node Sending Pending Events Only

### ISSUE THREAD

**Issue by areebmajeed** [paritytech/parity-ethereum#9214]
> I'm running:
>
> - **Which Parity version?**: 2.0.0
> - **Which operating system?**: Linux
> - **How installed?**: installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I am running a light node which is run through the following command "parity --no-ancient-blocks --jsonrpc-hosts "all" --unsafe-expose --tracing off --warp --light".

I listen to a contract's Transfer logs using the code below.

`var Transfer = contract.Transfer({}, {fromBlock: 'latest', toBlock: 'latest'});`

While I am using a full node, the event logs I receive are with the status/type "mined", but with the same code, when I use the light node, the logs are returned with a status/type "pending" and most of the information such as transaction hash is not available.

I don't plan to keep a full node running for Parity. So can anyone point us what is the issue? Is there any to get the light node to send me "only mined Transfer events"?

**Comment by areebmajeed** [comment]
This is what the event looks like:

>  { address: '0xb8c77482e45f1f44de1745f52c74426c631bdd52',
    blockHash: null,
    blockNumber: null,
    logIndex: null,
    removed: false,
    transactionHash: null,
    transactionIndex: null,
    transactionLogIndex: null,
    type: 'pending',
    event: 'Transfer',
    args:
     { from: '0xd2355e862506fd647c5fbffbe2fa5e3a3e141a0a',
       to: '0xb36efd48c9912bd9fd58b67b65f7438f6364a256',
       value: [Object] } },

**Comment by areebmajeed** [comment]
Could this be related to https://github.com/ethereum/go-ethereum/issues/3752 somehow?

**Comment by Tbaut** [comment]
Can you show more of your code? this how is this `contract.Transfer` is supposed to get the logs?

As a side note: `--no-ancient-blocks`, `--tracing off` and `--warp` are useless in light mode as there is no warp-sync (yet), no tracing and no block download.

**Comment by areebmajeed** [comment]
```
const web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider(RPC_URL));
var contract = web3.eth.contract(abi).at(config.CONTRACT_ADDRESS);

var Transfer = contract.Transfer({}, {fromBlock: 'latest', toBlock: 'latest'});

Transfer.watch(function (err, e) {

    if (err) {

        console.log(err);

    } else {

        console.log(e);

    }

});
```

The same code returns ONLY MINED transactions when I am using a different node, but it shows ONLY PENDING transactions without transaction ID, block number, etc (basically all information that I need to identify that particular transaction).

**Comment by Tbaut** [comment]
Not sure the light client supports logs.
@axelchalon you can probably help us here.

**Comment by axelchalon** [comment]
not sure. cc @tomusdrw maybe?

**Comment by Tbaut** [comment]
My 2cents, I could reproduce the issue with the following code:
```
const Web3 = require('web3')
const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:8545/'))

const abi = [{"constant"..roval","type":"event"}];

const contractAddress = "0xaa..33";
const mainAccount = "0x00..22";

var contractInstance = new web3.eth.Contract(abi, contractAddress, {from: mainAccount})
  contractInstance.getPastEvents('Transfer', {
    fromBlock: 8137604,
    toBlock: 8137604
  }, function(error, events){	
	 console.log(events);
  }
);
```

I get the logs with a full node, an empty arry with a light node (kovan). Now I'm not 100% sure if there is a better way to do it (pubsub to get the logs from new blocks) or if it's not possible at all with the light client.

**Comment by Tbaut** [comment]
@tomusdrw can you have a look when you have a moment?
