### ISSUE TITLE
Unclean closing of long pending requests making node unresponsive

### ISSUE THREAD

**Issue by nandubatchu** [paritytech/parity-ethereum#9223]
> I'm running:
>
> - **Which Parity version?**: 1.11.5
> - **Which operating system?**: Linux
> - **How installed?**: source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Making some long pending RPC requests is not timing out and is forcing the client to close the request unclean while the process is not killed on the node end. With a couple of long pending requests, our node has become completely unresponsive to the RPC requests.

Curl command used to make the long pending request (a very broad block duration with large number of transactions):
```
curl --request POST \
--url localhost:8545 \
--header 'content-type: application/json' \
--data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock": "0x583ab3","toBlock": "latest","toAddress": ["0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208"]}],"id":1}'
```

Edit from Tbaut. From the chat, Parity launched with `parity --jsonrpc-hosts all --jsonrpc-interface all --tracing on --pruning archive --base-path /home/ubuntu/paritydb-archive --force-sealing --jsonrpc-server-threads=5 --ws-interface=all --ws-apis=all --ws-hosts=all --log-file=/tmp/parity.log -l INFO --min-peers 50 --max-peers 200 --mode active --jsonrpc-apis all`

Would like to know whether we can kill RPC responses from parity node based on timeout specifications? Or is this issue related to the jsonrpc-threads? How do we optimise the usage of these threads and kill the unresponsive requests without restarting the node?

**Comment by roninkaizen** [comment]
--reading again the last release

There will be no official support for any versions prior to 1.11.7, however (EOL).

it could be senseful to upgrade, to get help.

**Comment by nandubatchu** [comment]
@roninkaizen I just upgraded my parity node to 1.11.7. And tried to do couple of long-pending RPC calls with command:
```
curl --request POST \
--url localhost:8545 \
--header 'content-type: application/json' \
--data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock": "0x583ab3","toBlock": "latest","toAddress": ["0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208"]}],"id":1}'
```

The issue still persists. The RPC endpoint becomes unresponsive. Is there any way to timeout long-pending requests on the node? Or is there any method to kill these requests without restarting the node?

**Comment by Tbaut** [comment]
That curl is querying 300K blocks.. that would probably work on a beefy work station in a reasonable time.. The node I try it on definitely had troubles too. Not sure how we can handle that better.
The workaround is straightforward: smaller queries.

@ascjones can you share your expertise regarding how we can handle that better?

**Comment by joshua-mir** [comment]
The only way to ensure the server handles more simultaneous or heavy queries without blocking is to increase the `--jsonrpc-threads` (`--jsonrpc-server-threads` only increases the ability to handle multiple simultaneous requests to your node), but you should note this is still limited by your machine's ability to process these queries.
