### ISSUE TITLE
How do I migrate from version 1.9.5 to latest and keep using the wallet/keys?

### ISSUE THREAD

**Issue by MichaelA2014** [paritytech/parity-ethereum#9224]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity v1.9.5-20180321 stable

> - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: N/A
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: N/A

Hello. I have been running an old version of Parity . Parity v1.9.5-20180321 stable. I read that wallet has been deprecated in the latest version and I am a bit confused. I have two wallets in my vault. If I update the Parity will I loose access to those vaults/wallets?
Also I have an old key that I made in Geth when ethereum just started. Is it still possible to import old geth keys in to the Parity, assuming there is a way to use these keys in parity now.
So confused! Please help.

**Comment by Tbaut** [comment]
>  If I update the Parity will I loose access to those vaults/wallets?

No you should not loose anything. if you update parity, you will simply have to use [Parity UI](https://github.com/Parity-JS/shell/releases) to have a user interface and connect to your node. This replaces the older browser UI. 

Your key will still be on your pc. Before updating, make sure that you store your keystore files in a safe place (here is how to extract them: https://wiki.parity.io/Backing-up-&-Restoring.html). They are linked with a password that you should remember. In any case, if you have the recovery phrase for each account, you are safe.

>Is it still possible to import old geth keys in to the Parity

yes.

The only change that was made is that Parity Ethereum, the node, used to be packages together with a user interface (accessible thought the browser). Now the user interface is a separate application called Parity UI, that will connect to the node (Parity Ethereum).

Feel free to ask in our Gitter Channel if you have further questions: https://gitter.im/paritytech/parity
