### ISSUE TITLE
Irrelevant/confusing warning: Local tx [hash] below minimal gas price accepted

### ISSUE THREAD

**Issue by cheeselord1** [paritytech/parity-ethereum#9227]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.6-beta
> - **Which operating system?**: Windows
> - **How installed?**: via source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: n/a

My local node min_gas_price is set very high (e.g. 100gwei). Whenever I send a local transaction with lower than 100gwei gas price, I see a warning saying "Local tx [hash] below minimal gas price accepted"

However, does this impact local transaction broadcasting in any way, right? In my experience the localtransaction is still broadcasted just fine, so this message seems confusing

**Comment by Tbaut** [comment]
Why is this irrelevant/confusing ? If you set a limit and push local transactions below this limit, I find it normal to have a warning.

Local transaction are special as initiated by yourself, in this sense, they still make their way to the tx pool.

BTW, can you upgrade to 1.11.7 or 2.0 as some minor changes have been added.
