### ISSUE TITLE
Attempting to cull queued transactions

### ISSUE THREAD

**Issue by emiliomarin** [paritytech/parity-ethereum#9240]
> I'm running:
>
> - **Which Parity version?**: 1.11.7
> - **Which operating system?**: Linux
> - **How installed?**: installer 
> - **Are you fully synchronized?**: no, light mode
> - **Which network are you connected to?**:ropsten
> - **Did you try to restart the node?**: yes

So I'm sending many transactions at the same time, let's say 1000, via web3js. Some transactions get pending and you can see them on etherscan, around 100-200, then if I keep the node running, about 10 minutes later it will show the message:

`Attempting to cull queued transactions from 1 sender`

and if I check etherscan I will see that another 100-200 are there. Is it possible to reduce that time between each batch?

Update: more exact number would be -> 64 tx every 10 minutes.

**Comment by Tbaut** [comment]
This message is not related to your concern IMHO. It just shows that the node is cleaning the queue for Txs that where included in a block.
>Is it possible to reduce that time between each batch?

This is network dependant. Are you sure that your gas is high enough?

**Comment by emiliomarin** [comment]
Thanks for the answer @Tbaut, yes I'm using high gas since I'm testing for now. I had set 40gwei. 

Not sure if same behavior would apply to main network

**Comment by Tbaut** [comment]
The transaction throughput is linked to the network, there is not much we can do here unfortunately. If you wish to have a higher throughput while testing, you should try Kovan.
