### ISSUE TITLE
Thread '<unnamed>' panicked at 'other was less than the current instant'

### ISSUE THREAD

**Issue by adyshimony** [paritytech/parity-ethereum#9245]
> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**:  bash <(curl https://get.parity.io -Lk) 
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

* parity stopped working with this error:

stack backtrace:
   0:     0x56324107d1fc - <no info>

Thread '<unnamed>' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292

This is a bug. Please report it

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity-ethereum/issues/8444
