### ISSUE TITLE
Build of v1.11.8 failed on Debian Jessie 9

### ISSUE THREAD

**Issue by gituser** [paritytech/parity-ethereum#9247]
Trying to build `parity v1.11.8` on Debian Jessie 9 and build is failed because of the new cmake requirement:

```
   Compiling quasi v0.32.0
error: failed to run custom build command for `snappy-sys v0.1.0 (https://github.com/paritytech/rust-snappy#798408ff)`
process didn't exit successfully: `/home/build/parity/source/target/release/build/snappy-sys-b6fd33f28063eca5/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/build/.cargo/git/checkouts/rust-snappy-affd814aab166778/798408f/snappy-sys/snappy" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DCMAKE_INSTALL_PREFIX=/home/build/parity/source/target/release/build/snappy-sys-c516159895a8f4ef/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- Configuring incomplete, errors occurred!

--- stderr
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 3.0.2


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/build/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.31/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
```

It seems to require more recent cmake version for some reason? Is it really necessary ?

Can you guys fix this?

**Comment by 5chdn** [comment]
You can use the binary or just update cmake. We are not going to support any old Debian distributions. FYI, Jessie reaced EOL in June 2018.

**Comment by 5chdn** [comment]
We provide a lot of alternatives for you, if you don't want to get the binary, you can also use snapcraft.

Don't get me started on all the different Linux distros, if we want to support all of them, we would probably not do anything else than messing around dependencies :)

Personally, I'd recommend not to rely on distributions that only provide point releases, especially if you care about security and want to run them for more than 2 years, e.g., in a server environment.

**Comment by gituser** [comment]
@5chdn 
>Personally, I'd recommend not to rely on distributions that only provide point releases, especially if you care about security and want to run them for more than 2 years, e.g., in a server environment.

If you care about stability you won't use cutting edge versions of software rather you'd be conservative. Debian is so far a very good choice for us for server environment. Whilst Ubuntu is not good at all and tend to break things there.

Anyways, I'd appreciate if you guys stop breaking things in old release line. You have now another new branch out there `v2.0` or `v2.1` why not experiment there instead ? And as I said before `v1.11.7` built just fine on the same system.

**Comment by trapp** [comment]
@5chdn It's fine to change the build system and drop support for older distros but doing so in a minor release on the stable branch is not a very good practice. If v1.11.7 builds on a system, v1.11.8 should build there as well.

**Comment by 5chdn** [comment]
Agreed.

**Comment by MrGuga** [comment]
Same error happens in CentOS 7, which uses by default (at the time of this post) cmake version 2.8.12.2
You can however, install it with `yum install cmake3` (epel repo is needed)
to make it default for cargo, i put a link in cargo bin folder to the cmake3 binary: `ln -s /usr/bin/cmake3 ~/.cargo/bin/cmake`
