### ISSUE TITLE
How to send transaction ?  Parity gives me correct response but actually no  transaction happens. 

### ISSUE THREAD

**Issue by sg552** [paritytech/parity-ethereum#9249]
> I'm running:
>
> - **Which Parity version?**: 1.11.7
> - **Which operating system?**:  Linux  ( ubuntu ） 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  Maybe no.  ( the folder is 30GB.  )
> - **Which network are you connected to?**: ethereum  ( foundation ) 
> - **Did you try to restart the node?**: yes

Hi ,

  I switched my ETH node  from Geth to Parity , so I know something about ETH but not familiar with Parity. 
  Currently I am running a Parity node , with following config.toml: 

```
[parity]
mode = "active"
base_path = "/opt/parity"
identity = "coixxx"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts", "secretstore"]
server_threads = 2
port = 88xx
interface = "10.14x.0.2"

[websockets]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal"]

[misc]
log_file = "/opt/parity/logs/parity.log"
logging = "info"

[mining]
min_gas_price = 1 # 1 wei
```

    And my running command is :  parity -C config.toml    ( I am sure this config file is loaded correctly) 
   
   data fold is:  /opt/parity  .   and all sync is done. ( I can query the 
   
   So I send a transaction using following RPC command: (in the Geth way )
```
# step1.  unlock this account. 
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x088630bECCF2d492876719ACe853DF1b3Cxxxx", "latest"],"id":1}' 10.146.0.2:8800
{"jsonrpc":"2.0","result":"0x6ecba1baadeb0f3","id":1}

# step2. send the transaction  ( gas price: 12 Gwei )

~$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"eth_sendTransaction", "params":[{"from": "0x925ccd95f17640be707c4c8ae713177dfcxxxxxx", "to":"0x8f5aE589fd2467396C8b2xxxx637DBF5C440xxxx", "gas": "0x15f90", "gasPrice": "0x2cb417800", "value": "0x1988fe4052b8000" }], "id": 267}' http://10.14x.0.2:88xx
{"jsonrpc":"2.0","result":"0x4312e10258795e2409a212542bae8ccb1efe4f111cd9c26ffed843f18cdb8f21","id":267}
```
   
   so, from the result above, I can see Parity RPC returns a tx in the json result.  And in its log file ( /opt/parity/logs/parity.log ) everything looks fine: 

```
...... 
2018-07-30 01:09:58 UTC    0/25 peers    172 KiB chain   65 MiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s, 255107 µs
2018-07-30 01:10:33 UTC    0/25 peers    172 KiB chain   65 MiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s, 255107 µs
2018-07-30 01:11:08 UTC    0/25 peers    172 KiB chain   65 MiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s, 255107 µs
```
   
  But this transaction is not actually happened:  ( not found in etherscan.io ) 

https://etherscan.io/tx/0x4312e10258795e2409a212542bae8ccb1efe4f111cd9c26ffed843f18cdb8f21

  Why?   

  Also I checked my ETH data folder, total is 32G .  
  Is there something wrong with my config file?    

  A ton of thanks 

Siwei

**Comment by Tbaut** [comment]
As explained in our [security best practices](https://wiki.parity.io/FAQ#what-are-the-security-best-practices), please consider using personal_sendTransaction

You log show that you are not connected to any peers.
`2018-07-30 01:09:58 UTC    0/25 peers  `

Have a look here to understand what the logs mean: https://wiki.parity.io/FAQ#what-does-paritys-command-line-output-mean

Your transactions are not broadcasted (and mined) because of this, so it's normal not to see it on Etherscan.

**Comment by sg552** [comment]
got it~  thanks a lot!

**Comment by sg552** [comment]
found my problem : computer not connected to internet.  -_-!  
thanks a lot!
