### ISSUE TITLE
Add blockHash option to eth_getLogs (EIP 234)

### ISSUE THREAD

**Issue by fabioberger** [paritytech/parity-ethereum#9251]
As described in [EIP 234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md), `eth_getLogs` currently only supports querying logs by **block number** and not **block hash**. 

This makes it impossible to know whether the logs returned are from the expected block, or if a block-reorg happened and the logs returned are actually from another block. Help!

Since the EIP's acceptance, the `blockHash` param has been added to the [official Ethereum JSON RPC docs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs).

Geth also recently implemented EIP 234 (https://github.com/ethereum/go-ethereum/pull/16734), would it be possible for Parity to do the same? 

Getting a reliable stream of logs, regardless of re-orgs is not possible without this change.

**Comment by avonian** [comment]
this is a serious problem affecting my projects as well

**Comment by MicahZoltu** [comment]
Killing Augur at the moment as well.

**Comment by nionis** [comment]
EIP 234 helps alot with quarantining consistency of state due to reorgs when using indexers, right now the only alternative has a bandwidth trade off

**Comment by joshua-mir** [comment]
I'm assuming this issue has been addressed by #9256? Correct me otherwise.
