### ISSUE TITLE
Parity docker image: update documentation

### ISSUE THREAD

**Issue by EZS-JD** [paritytech/parity-ethereum#9261]
Looks like parity versions >1.10 no longer include the UI (parity wallet), correct?
=> please update the docker documentation and explain 
a) which version still includes the wallet
b) how to best deal with the new situation when running parity in docker (e.g. https://github.com/parity-js/shell/issues/28)

**Comment by EZS-JD** [comment]
Didn't see the Link to the docker wiki section, thanks for that.

I was talking about the docker image description on [Docker Hub](https://hub.docker.com/r/parity/parity/)

> Parity comes with a built-in wallet. To access Parity Wallet simply go to http://web3.site/ (if you don't have access to the internet, but still want to use the service, you can also use http://127.0.0.1:8180/). It includes various functionality allowing you to:
> 
> create and manage your Ethereum accounts;
> manage your Ether and any Ethereum tokens;
> create and register your own tokens;
> and much more.

Given you have outsourced the relevant information to your wiki, I'd suggest you remove most of the information on hub.docker.com and make the link to the wiki more prominent.
Most of the info on your docker hub page seems misplaced or outdated to me.

**Comment by Tbaut** [comment]
Definitely, thanks a lot for the heads-up.

**Comment by Tbaut** [comment]
Updated, I'll close this issue.
