### ISSUE TITLE
Parity 1.11.X panicing with "No space left on device" error despite having plenty of disk space.

### ISSUE THREAD

**Issue by etscrivner** [paritytech/parity-ethereum#9262]
> I'm running:
>
> - **Which Parity version?**: 1.11.(17,18)
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

This issue appeared after attempting to upgrade from 1.10.6 to 1.11.8. It reappears on 1.11.7 as well. Nodes reliably and repeatedly die despite having plenty of remaining disk space after syncing a few blocks. These nodes are using the ext4 filesystem and the nodes are being started using pre-existing data from a 1.10.6 node.

This seems isolated to mainnet for unclear reasons, as ropsten nodes initialized from 1.10.6 backups were able to upgrade and continue functioning just fine.

Expected behavior would be that this does not happen and the nodes successfully utilize available disk space.

Stack trace for this issue:

```
0:     0x5654e63e670c - backtrace::backtrace::trace::h1b6615cc6b5020ee
2:     0x5654e5b1d17a - panic_hook::panic_hook::hb26dda341f403bb0
1:     0x5654e63e5d32 - backtrace::capture::Backtrace::new::h307ef90faea654f5
Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("IO error: No space left on deviceWhile appending to file: /data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/518305.sst: No space left on device"), State { next_error: None, backtrace: None })', libcore/result.rs:945
This is a bug. Please report it at:
https://github.com/paritytech/parity/issues/new
====================
```

**Comment by sorpaas** [comment]
What's your file system? Is it BTRFS?

**Comment by etscrivner** [comment]
@sorpaas It's ext4

**Comment by sorpaas** [comment]
@etscrivner Can you run `df -i` to see whether it's caused by having too many files on this system? Also, I remember that Linux by default reserves 5% disk space to `root`, can you check you have more than 5% disk space free?
