### ISSUE TITLE
Errors and `failure`

### ISSUE THREAD

**Issue by c0gent** [paritytech/parity-ethereum#9282]
Has the use of the [`failure`](https://crates.io/crates/failure) crate been considered lately?

Has replacing use of `error_chain` been discussed considering the [author would like to deprecate it](https://github.com/rust-lang-nursery/failure/issues/181)?

Would it be ok to start importing `failure` and using it within Parity?

I'm well aware that the [error handling story in Rust is incomplete](https://github.com/rust-lang/rfcs/pull/2504) and I can completely understand any hesitance to start introducing new error handling conventions but I would strongly recommend beginning to standardize on the conventions introduced by `failure`. It seems likely that something reasonably close to its current API will eventually become the preferred method.

Forgive me if I've missed a discussion about this somewhere other than #7077.

I'll also note that `failure` can easily consume `error_chain` (or other) errors which do not implement `Sync` via the use of [`SyncError`](https://docs.rs/failure/0.1.2/failure/struct.SyncFailure.html). This will allow for a gradual and seamless transition.

**Comment by ordian** [comment]
Hi @c0gent! Yes, eventual migration to `failure` [is](https://github.com/paritytech/parity-ethereum/pull/9161#discussion_r205086730) planned. PRs are welcomed :)

**Comment by c0gent** [comment]
Ok great, that's what I was hoping to hear :)
