### ISSUE TITLE
parity bug

### ISSUE THREAD

**Issue by panosVeran** [paritytech/parity-ethereum#9284]
im getting this error, any suggestions guys? thanks 

![parityproblem](https://user-images.githubusercontent.com/13367103/43689419-5fad5b18-98f2-11e8-8952-b5279573fb26.PNG)

**Comment by Tbaut** [comment]
Can you please answer these questions:

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_In you issue description try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by panosVeran** [comment]
yes sorry for that

parity version: 1.11.8
os: windows 7
installed: installer
synch: i was fully synched until the point of the failure
network: ropsten
actions: i tried to restart the node several times, didn't work, always giving the same error very quickly, i even tried to kill the db, which even that didnt work, i ended up reinstalling parity and deleting the local db from AppData to have a fresh start, which is not the best since i got to download the blockchain again. it hasnt crashed since then (not synch yet though)

i just wanted to let you know guys if its something you are familiar with or case of worry, or is just my system that failed.

thanks

**Comment by Tbaut** [comment]
As the error says, it's a database error. It's most probably due to  a hardware (RAM error, SSD/HDD failure). Duplicates other issues such as https://github.com/paritytech/parity-ethereum/issues/9047
There is unfortunately very few we can do. Please verify your RAM and Hard drive if this happens again.
