### ISSUE TITLE
Question: What is `traceAddress` in trace_transaction?

### ISSUE THREAD

**Issue by isLishude** [paritytech/parity-ethereum#9286]
https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/types/trace.rs#L474

and subtraces? I found nothing here in wiki.

![image](https://user-images.githubusercontent.com/24730006/43695572-112208de-996c-11e8-99c3-173d7b4602c7.png)

**Comment by tjayrush** [comment]
`traceAddress` is the call graph of the current trace. The first trace is the same level as the transaction itself. If that transaction makes three `calls` then these calls would have 0x0, 0x1, and 0x2 as their `traceAddress`. If the second `call` at the top level called further into another contract, that trace's `traceAddress` would be [ 0x1, 0x0 ]. So, `traceAddress` records the call graph of the trace as they descend down. (Not well explained, but you probably get the idea.)

`subtraces` are the number of `calls` at that level. In the above example, it would be `3` for the top level transactions.

...and I'll add to what I said above...I think. I'm pretty sure this is what these values are, but perhaps someone else can elaborate.

**Comment by isLishude** [comment]
thx @tjayrush
