### ISSUE TITLE
Parity-Ethereum 1.11.8-stable on snap?

### ISSUE THREAD

**Issue by blargity** [paritytech/parity-ethereum#9287]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.7-unstable-085035f-20180717/x86_64-linux-gnu/rustc1.26.2
> - **Which operating system?**: Linux
> - **How installed?**: Snap
> - **Are you fully synchronized?**: No
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I noticed the last version of Parity that got pushed up to snap was `v1.11.7-unstable`, even though v1.11.8 stable was released.

I'd love it if you could push that version up as I'm experiencing a sigkill whenever I try to warp sync, which I think was fixed in 1.11.7-stable (https://github.com/paritytech/parity-ethereum/pull/9088).

**Comment by Tbaut** [comment]
Thanks for the heads-up, we'll have a look.

**Comment by General-Beck** [comment]
snapcraft status parity
Track    Arch    Channel    Version        Revision
latest   amd64   stable     1.11.8         15311
