### ISSUE TITLE
Removing UI Interface was a huge blow to node security.

### ISSUE THREAD

**Issue by Emperornero** [paritytech/parity-ethereum#9291]
I've since rolled back to 1.11.3 but you guys need to put back in the UI.

Not being able to remotely interact and transact with my node while storing my private keys and JSON on another computer is a huge security flaw.

I had a SSH tunnel set up specifically for interacting with my parity node from an air gapped computer.  The traffic never left my network and was never able to.  If someone wanted to steal my keys they would need access to 4 different passwords and need to figure out which ports 2 different authentication methods were using before they got locked out.

With the new 2.0 parity node, if they somehow access my node computer directly, they can get whatever they want.

I don't see the logic behind the removal of this functionality.  Please re-add it.

**Comment by Tbaut** [comment]
I didn't follow you at all. Anything you were doing before is still doable with [Parity UI](https://github.com/Parity-JS/shell/releases). If users like you absolutely need it, feel free to contribute, it's open source :)

Here is an explanation of the UI removal: https://paritytech.io/creating-a-lighter-experience/

**Comment by Emperornero** [comment]
I have been using parity-ui since it's deployment.

With the 2.0 update, the "Parity Wallet" functionality is no longer an option.  You can still interact with the node via the Parity UI, however, you cannot send transactions.

**Comment by Tbaut** [comment]
> you cannot send transactions.

Why? That's most probably a misunderstanding. Please make sure to use the latest version of Parity UI: https://github.com/Parity-JS/shell/releases You can still send transactions with it.
