### ISSUE TITLE
Send transaction get tx but not send

### ISSUE THREAD

**Issue by Vagabondtq** [paritytech/parity-ethereum#9299]
> I'm running: personal_sendTransaction
>
> - **Which Parity version?**: Parity-Ethereum/v2.1.0-unstable-f0c0da8-20180731/x86_64-linux-gnu/rustc1.26.2
> - **Which operating system?**: Linux
> - **How installed?**: via installerfrom source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I'm used command: `personal_sendTransaction`, i get tx string, but, when i check: `parity_localTransactions`:

```
"0x03153de5fb537a1acda8ad3770f01f42cfc8de2036614e9c505e5d7548a164d1": {
            "status": "pending"
        }
```

how to fix? same with parity version 1.11.8

config file:

`no_persistent_txqueue = true`

**Comment by Tbaut** [comment]
Your transaction must have a nonce gap that prevents it to be included in a block. To solve this problem, you need to remove it (1). And send your transaction again with a correct nonce, gasPrice etc (2).

- (1) To delete/override your previous transaction, you can send the exact same transaction with a higher gasPrice and a value of 0. 
- (2) To send a correct transaction, you can first use [parity_composeTransaction](https://wiki.parity.io/JSONRPC-parity-module#parity_composetransaction) to craft the transaction with the correct gasPrice, Nonce etc. and then use personal_sendTransaction.

Read more [here](https://wiki.parity.io/Transactions-Queue) about the reasons for a transaction to get stuck.
