### ISSUE TITLE
Parity UI will not start

### ISSUE THREAD

**Issue by NinjaTurtle007** [paritytech/parity-ethereum#9301]
_Before filing a new issue, please **provide the following information**._

    I'm running:

        Which Parity version?:Parity-Ethereum 1.11.8-stable
        Which operating system?: Linux
        How installed?: via installer snap store
        Are you fully synchronized?: no
        Which network are you connected to?: ethereum
        Did you try to restart the node?: yes
        Latest version of Parity UI from the snap store

parity is running in the terminal on Ubuntu and synced
then i proceed to run Parity UI from the dash icon, nothing happens
and this is the output from the kernel via dmesg

> [  +0.000002] audit: type=1107 audit(1533667670.056:2863461): pid=1013 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" mask="send" name="org.bluez" pid=25725 label="snap.parity-ui.parity-ui" peer_pid=991 peer_label="unconfined"
               exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
[  +0.663763] traps: parity-ui[25725] trap int3 ip:3027769 sp:7ffc4d537a30 error:0 in parity-ui[1802000+3733000]

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by NinjaTurtle007** [comment]
After reinstalling it (again from the snap store) it works now.
Weird.

**Comment by Tbaut** [comment]
Ok, if this ever happen again, please post here what the command line outputs.
