### ISSUE TITLE
Where are my Parity Keys (Local Key)? 

### ISSUE THREAD

**Issue by rasarasan** [paritytech/parity-ethereum#9302]
I'm running:

 - **Which Parity version?**: 2.0.1-20180726 beta
 - **Which operating system?**: MacOS 
 - **How installed?**: via installer 
 - **Are you fully synchronized?**: no 
 - **Which network are you connected to?**: I don't know
 - **Did you try to restart the node?**:  yes

I am trying to transfer my STORJ tokens to an exchange. But it is asking for a Local File when I try to execute the transaction. How do I find my Local File?
![localkey-issue](https://user-images.githubusercontent.com/45295/43797584-e8dd2436-9a55-11e8-96a2-887b7c4d6590.jpeg)

**Comment by Tbaut** [comment]
Could you please open the developer console using Command+Option+J and show a screenshot of the error that you see?

On a Mac, the keys are situated: `~/Library/Application\ Support/io.parity.ethereum/keys/`
