### ISSUE TITLE
it takes 7 days to restart the parity!

### ISSUE THREAD

**Issue by XuHugo** [paritytech/parity-ethereum#9309]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
  I need to reconfigure parity，so restart parity。But it took me a long time，Stopping in this position.

2018-08-08 17:05:34  Updated conversion rate to Ξ1 = US$368.33 (12928365 wei/gas)
Loading config file from /root/.local/share/io.parity.ethereum/config.toml
2018-08-08 17:10:32  Starting Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1
2018-08-08 17:10:32  Keys path /hbdata/app/eth-parity/data/keys/Foundation
2018-08-08 17:10:32  DB path /hbdata/app/eth-parity/data/chains/ethereum/db/906a34e69aec8c0d
2018-08-08 17:10:32  Path to dapps /hbdata/app/eth-parity/data/dapps
2018-08-08 17:10:32  State DB configuration: fast
2018-08-08 17:10:32  Operating mode: active
2018-08-08 17:10:32  Configured for Foundation using Ethash engine
2018-08-08 17:10:34  Updated conversion rate to Ξ1 = US$369.06 (12902792 wei/gas)

➜  bin cat ~/.local/share/io.parity.ethereum/config.toml
[parity]
base_path = "/hbdata/app/eth-parity/data"
db_path = "/hbdata/app/eth-parity/data/chains"
keys_path = "/hbdata/app/eth-parity/data/keys"

[network]
port = 30300
min_peers = 25
max_peers = 50

[rpc]
port = 8542
interface = "all"
apis = ["web3", "eth", "net", "parity", "parity_set", "traces", "rpc", "personal"]

[ui]
interface = "0.0.0.0"

[mining]
tx_queue_size = 81920

**Comment by Tbaut** [comment]
You are using an old version of parity, please upgrade to the latest release: https://github.com/paritytech/parity/releases

**Comment by XuHugo** [comment]
thanks, I have another question, can I delete an transaction which nonce too hight.

**Comment by XuHugo** [comment]
@Tbaut

**Comment by XuHugo** [comment]
@Tbaut  I found a problem like me，But there is no solution

**Comment by Tbaut** [comment]
>can I delete an transaction which nonce too hight.

No you can't but you can override it by sending the same transaction (`from`, `to` and `nonce` should remain identical) but put a value of 0x, and a higher gas price than before, to make this new transaction more important than the older one.
