### ISSUE TITLE
Metamask browser extensions not working.

### ISSUE THREAD

**Issue by alexacostarua** [paritytech/parity-ethereum#9314]
> I'm running:
> - **Which Parity version?**: version Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2

> - **Which operating system?**:  Linux (Ubuntu 16.04_64x)
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: yes

Heres my genesis .json:
```
{
    "name": "PrivatePoA",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "5",
                "validators" : {
                    "list": ["0x62789d0534e1447e5a8ed72fa5846f347673c472",
                             "0xef70615216249f347d184e3d2a4194f8c1cc8c97"]
                }
            }
        }
    },
    "params": {
	        "gasLimitBoundDivisor": "0x0400",
"maximumExtraDataSize": "0x20",
	"minGasLimit": "0x1388",
        "networkID" : "87564"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x1",
        "gasLimit": "0x47b760"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x62789d0534e1447e5a8ed72fa5846f347673c472": { "balance": "30000000000000000000000" },
        "0xef70615216249f347d184e3d2a4194f8c1cc8c97": { "balance": "30000000000000000000000" }
    }
}
```
Heres my node config file:
```toml
[parity]
chain = "privatepoa-spec.json"
base_path = "~/ethereum/poa/node1/"
[network]
port = 30301
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "127.0.0.1" #external access to rpc
[ui]
port = 8181
[websockets]
port = 8451
[ipc]
disable = false
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x62789d0534e1447e5a8ed72fa5846f347673c472"
reseal_on_txs = "none"
```
I've also tested this with a local version of remix IDE and the online version.  And have tested numerous compiler versions.  This node can send transactions, run gobitfly explorer, works with myetherwallet via custom rpc.

Doesn't Work With Metamask:

 (said warnings were Use emitter.setMaxListeners(), and errors were: Setting up Sentry Remote Error Reporting: PROD
background.js:1 Injecting MetaMask Mesh testing client
localhost:8545/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
raven.js:58 MetaMask Mesh Testing - threshold not matched -- skipping test
4localhost:8545/:1 Failed to load resource: the server responded with a status of 403 (Forbidden) )

Warnings associated with the IDE, no matter what my contract is even the basic example of the erc20 0fuks token had the same types.

Fall-back function of contract ChewyToken requires too much gas (infinite). If the fallback function requires more than 2300 gas, the contract cannot receive Ether.
Gas requirement of function ChewyToken.approveAndCall(address,uint256,bytes) high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)

Gas requirement of function ChewyToken.name() high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)
Gas requirement of function ChewyToken.symbol() high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)

Please let me know what I can do to fix this.
My user_default in chain is : {"is_first_launch":false,"pruning":"archive","tracing":true,"fat_db":true,"mode":"active"}
as well

I'm also running parity like this: 

`parity --geth --network-id "87564" --warp --ipc-path='/home/user1/.ethereum/geth.ipc' --tracing=on --fat-db=on --pruning=archive --no-discovery --config ~/ethereum/poa/node1.toml --jsonrpc-cors "null","localhost:3000","localhost:6000"`

Also if parity isn't optimized to work with remix IDE can someone point me in the direction to publish smart contracts on parity?

Thanks.

**Comment by Tbaut** [comment]
Please make sure you allow remix cors header with:
```
[rpc]
port = 8545              #default http port for RPC
apis = ["eth","net"]    # add "eth", "net"
cors = ["http://remix.ethereum.org"]  # allow remix to access this node
```

**Comment by alexacostarua** [comment]
Ok.  I've added cors = ["http://remix.ethereum.org"] to both of my nodes .toml files.  And added the flag jsonrpc-cors "null","localhost:3000","localhost:6000","http://remix.ethereum.org" ... Nothing has changed still same warning messages, still the contract just sits there (creation of ChewyToken pending...) I see the 1 req/s added to the node 1 for one line than it disappears the next line.  What do you recommend I do?  I'm also using the default 3000000 gas limit in Remix IDE if that helps at all too.
@Tbaut 
Thanks for the timely response though.

**Comment by Tbaut** [comment]
Can you try to reproduce on a very basic example, like on kovan network with minimal configuration change, with a simple contract to see if this is related to your chain (I doubt it). I was able to deploy a contract recently with the dev chain without big troubles (as part of this tutorial [here](https://wiki.parity.io/Secret-Store-Tutorial-4.html#3-create-and-deploy-a-permissioning-contract))

**Comment by alexacostarua** [comment]
Ok.  I got the contract to publish finally. I forgot to specify unlock, major goof.   Do you have any clue as to why the metamask extensions on all browsers can't connect and myetherwallet locally can? Its a huge tool for testing especially because myetherwallet isn't showing me the amount of custom tokens I have just stays as loading and won't allow me to send.  I know this same contract works with geth and metamask just tested it 2 mins ago.  Cheers.   @Tbaut

**Comment by alexacostarua** [comment]
5
localhost:8545/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by Tbaut** [comment]
I could connect Metamask to Firefox by allowing the right cors header `--jsonrpc-cors "moz-extension://ae62fc16-c916-4c24-9a36-97f5a850f25c"`

**Comment by alexacostarua** [comment]
Nice.  @Tbaut  .  I just tried adding that exact extension, still didn't work.  I'm using metamask on chromium and brave if those would be any different what would they be?

Thanks!

**Comment by alexacostarua** [comment]
@Tbaut You are correct it does have to do with the --jsonrpc .  I tried "all" for testing purposes and it worked.  I would love if you could give me the ones for brave and chromium though.

**Comment by Tbaut** [comment]
You need to open the Metamask extension in a tab and see what is the domain of the extension it makes the calls from (with ctrl-shift-i and the network tab).
