### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'proof produced by this engine'

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity-ethereum#9317]
> I'm running: windows 10/ ubuntu 18.04.1
>
> - **Which Parity version?**: 1.10.4 (windows)/ 1.10.8 (Ubuntu)
> - **Which operating system?**: Windows / Linux
> - **How installed?**: via installer (.exe)/ ubuntu software center
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: private poa
> - **Did you try to restart the node?**: yes

**I have created a private poa with this spec.json file:** 

```
{
    "name": "PrivatePoA",
    "engine": {
      "authorityRound": {
        "params": {
          "blockReward": "0x4563918244F40000",
          "stepDuration": "5",
          "validators" : {
            "safeContract": "0x0000000000000000000000000000000000000005"
          }
        }
      }
    },
    "params": {
      "gasLimitBoundDivisor": "0x400",
      "maximumExtraDataSize": "0x20",
      "minGasLimit": "0x1388",
      "networkID" : "0x2323"
    },
    "genesis": {
      "seal": {
        "authorityRound": {
          "step": "0x0",
          "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        }
      },
      "difficulty": "0x20000",
      "gasLimit": "0x5B8D80"
    },
    "accounts": {
      "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name":   "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
      "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
      "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
      "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } }
    }
  }
```

**Also, with node1.toml and node2.toml:**

```
[parity]
chain = "privatepoa-spec.json"
base_path = "~/ethereum/poa/node1/"
[network]
port = 30301
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0" #external access to rpc
[ui]
port = 8181
[websockets]
port = 8451
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xf2342c3a147ba26881dff55be95454db84c82177"
reseal_on_txs = "none"
```

```
[parity]
chain = "privatepoa-spec.json"
base_path = "~/ethereum/poa/node2/"
[network]
port = 30302
[rpc]
port = 8546
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0" #external access to rpc
[ui]
port = 8182
[websockets]
port = 8452
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xc4a942c557fba8bd22cd1db33b7ea9459b760d6f"
reseal_on_txs = "none"
```
 
**The problem is that after a few seconds running both nodes I get this error:**

![image](https://user-images.githubusercontent.com/19657718/43850587-bb2ce710-9b0e-11e8-8073-27af410fc63c.png)

**This happens on both windows and ubuntu**

What is happening here? And how can I solve this?

When running node1.toml I get: Thread 'IO Worker #1' panicked at 'proof produced by this engine'

**Comment by Tbaut** [comment]
There are a couple things that could be the origin of your problem.
0. Please update to the latest Parity version (1.11 or 2.0)
0. You use safecontract at the address `0x000..0005` but where do you deploy it?
0 I'd suggest to start small, and build a working PoA network, and iterate to make it better, did you have a look at the [PoA tutorial](https://wiki.parity.io/Demo-PoA-tutorial)?

**Comment by vieiralc** [comment]
I've updated to the 1.11 and followed the PoA tutorial. It worked fine, but now I can't connect the nodes. The log is just: 

![image](https://user-images.githubusercontent.com/19657718/43914093-447dd708-9bdd-11e8-93e4-6e986c5647b3.png)

It should be 1/25 peers
