### ISSUE TITLE
Transactions come and go many times in the txpool

### ISSUE THREAD

**Issue by XuHugo** [paritytech/parity-ethereum#9335]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I met a problem.
What happens when a transaction enters txpool, then is abandoned, then goes in, and then comes out, many times.
I've been expanding tx-queue-size，89120；I detected that the number of transactions in tx-queue reached 20000 。so I guess it might be the problem of tx-queue-mem-limit，because it is a default value。（4M）

**Comment by Tbaut** [comment]
The version you are running is deprecated. A new Tx pool has been implemented. Please upgrade to a newer parity version. you can download it here: https://github.com/paritytech/parity/releases
