### ISSUE TITLE
1.10 and 1.11 return different results

### ISSUE THREAD

**Issue by tyrone98** [paritytech/parity-ethereum#9341]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.8
> - **Which operating system?**:  Linux
> - **How installed?**: via installer  binaries 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I upgraded parity from 1.10.7 to 1.11.8, but when I called a nonexistent method for a contract. 0x is returned in 1.10.7, It's excepted, but VM error is returned in 1.11.8。 the payload is 
`{
  "jsonrpc":"2.0",
  "method":"eth_call",
  "params":[{"to": "0x19587c9dd0160ce4696de36cf77a0081b5dca228", "data": "0x70a0823100000000000000000000000067302fc54adbc7a2627fb070f8c04cb21bb07285"}, "latest"],
  "id":1
}` 。

**Comment by kavu** [comment]
@tyrone98 I guess it will help Parity team a lot if you provide some minimal sources, that helps to reproduce a problem. The sole call of unknown contract may be difficult to debug.

**Comment by Tbaut** [comment]
Using v2.0.1. 
Calling the following: 
`curl --data '{ "jsonrpc":"2.0", "method":"eth_call", "params":[{"to": "0x19587c9dd0160ce4696de36cf77a0081b5dca228", "data": "0x70a0823100000000000000000000000067302fc54adbc7a2627fb070f8c04cb21bb07285"}, "latest"], "id":1 }' -H "Content-Type: application/json" -X POST localhost:8555
`

Returns:
`{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x"},"id":1}`

I personnaly think that answering an error when the function does not exist is much better than answering `0x`. This is actually a "feature" or annoyance fix.
