### ISSUE TITLE
Relationship between --jsonrpc-threads parameter and number of cpu cores

### ISSUE THREAD

**Issue by Caoxuyang** [paritytech/parity-ethereum#9342]
Hi,
I have issues on the threads parameters <--jsonrpc-threads> and <--jsonrpc-server-threads>.
Are they should be equal to the number of cpu cores of the machine?
For example if I have 8 cores in my machine, and I set the --jsonrpc-threads to 16, will it have negative effect on the performance?

**Comment by Tbaut** [comment]
Please have a look at https://github.com/paritytech/parity-ethereum/issues/9260 where the same question was answered. Feel free to open a PR to clarify flags that were not clear enough in you opinion.
