### ISSUE TITLE
How to change/fix or remove a faulty token in the Token Registry?

### ISSUE THREAD

**Issue by JanusGH** [paritytech/parity-ethereum#9348]
Hello,
I noticed that the token "DAY" in the Token Registry is faulty...
The contract for this token is listed with this address...
[0x7268F9C2bc9C9e65B4a16888cB5672531CE8E945](https://etherscan.io/address/0x7268f9c2bc9c9e65b4a16888cb5672531ce8e945)
which is actually the address for the faulty and mistakenly created first token of [Chronologic](https://github.com/chronologic), later renamed as "YESTERDAY" and more or less ignored.
The contract address for the actual DAY token is...
[0xE814aeE960a85208C3dB542C53E7D4a6C8D5f60F](https://etherscan.io/address/0xE814aeE960a85208C3dB542C53E7D4a6C8D5f60F)
Can this error/issue be fixed or can someone delete this faulty token in the registry so a new DAY token with the correct address can be registered? Who is in charge of the Token Registry and can look into or ideally fix this?
Thanks.

https://wiki.parity.io/Token-Registry.html

**Comment by 5chdn** [comment]
> Who is in charge of the Token Registry and can look into or ideally fix this?

I am, stay tuned.

**Comment by Tbaut** [comment]
The token registry is fading out, we should use (in Fether and others) something that is shared with other platforms and not only in the parity ecosystem.
