### ISSUE TITLE
Nodes can only connect via reserved peers or bootnode entry

### ISSUE THREAD

**Issue by YumingHe** [paritytech/parity-ethereum#9351]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.11.8
> - **Which operating system?**: Linux
> - **How installed?**: official docker image
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: yes

The issue is with peers discovery and sharing. Example scenario and steps to reproduce:

There is one mining node that is used as a bootstrap node, let's call it `B`. Then first not-mining node `N1` joins the network by connecting to `B` via reserved peer file. I see that blocks are imported and that each one of them have 1 peer now. That is as expected.

Now add another not-mining node `N2`, it also connects to `B`. `B` now has 2 peers, 

**epected behaviour**
`N1` and `N2` should discover each other through `B` and both have 2 peers.

**actual behaviour**
`N1` and `N2` still only have 1 peer each. If I stop `B`, `N1` and `N2` will lose connection and have 0 peers. 

On all nodes, 30303 port ingress is open for both TCP and UDP. Egress is open for everything.

config file used for `B`:

```[parity]
chain = "chain.json"
auto_update = "all"

[account]
password = ["/key/authority.pwd"]

[mining]
reseal_on_txs = "none"
force_sealing = true
reseal_min_period = 0
min_gas_price = 0

[network]
discovery = false

[footprint]
pruning = "archive"

[rpc]
port = 8545
interface = "0.0.0.0"
apis = ["web3", "eth", "parity", "parity_set", "net", "traces", "rpc"]

[websockets]
disable = true

[dapps]
disable = true

[secretstore]
disable = true

[ui]
disable = true
```

Config file used for nodes:

``` 
[parity]
chain = "chain.json"

[network]
discovery = true
reserved_peers = "bootnodes.txt"

[rpc]
port = 8545
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
apis = ["safe"]
hosts = ["all"]

[websockets]
port = 8546
interface = "local"
origins = ["all"]
apis = ["safe"]
hosts = ["all"]

[dapps]
disable = true

[secretstore]
disable = true

[ui]
disable = true 
```

**Comment by Tbaut** [comment]
It can take ages for 2 nodes sitting next to each other to discover themselves organically. How long did you let the 2 nodes up? I've seen cases where several hours were needed.

This is mainly due to devp2p2 (the networking layer for Ethereum nodes) that is broken. There is not much we can do unfortunately. I'd recommend to use reserved peers if you really need to connect to specific nodes.

**Comment by YumingHe** [comment]
The nodes have been running for more than a day with no sign of discovering each other.
