### ISSUE TITLE
Is it possible to rollback my private chain to a specific block and then fork another chain?

### ISSUE THREAD

**Issue by whitenoiseL** [paritytech/parity-ethereum#9352]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: latest
> - **Which operating system?**: ubuntu
> - **How installed?**: using docker

This might be a stupid question. I am just curious if I can rollback my private to some previous block like the system can restore to a previous version? The chain only has one node connected and mining.

**Comment by Tbaut** [comment]
Theoretically, this could be possible (the question is not stupid at all). Parity Ethereum, however, has no built-in feature I can think of that would allow you to do it.
