### ISSUE TITLE
gasUsed in trace equal 0 

### ISSUE THREAD

**Issue by salisbury-espinosa** [paritytech/parity-ethereum#9358]
> I'm running:
>
> - **Which Parity version?**: 1.10.9
> - **Which operating system?**: Linux
> - **How installed?**:  from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

https://www.etherchain.org/tx/65f437d330a3634f821ab696bcf6478323d57552843f9cb135b3a055e407ca46
```
Gas Used | 21,000
```
trace:
https://www.etherchain.org/tx/65f437d330a3634f821ab696bcf6478323d57552843f9cb135b3a055e407ca46/parityTrace

```
"gasUsed": "0x0",
```

**Comment by Tbaut** [comment]
The 21 000 gas is the default to send a transaction and is not printed in the trace.
