### ISSUE TITLE
Note also that local transactions will never get dropped to ease debugging ????

### ISSUE THREAD

**Issue by XuHugo** [paritytech/parity-ethereum#9361]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11
> - **Which operating system?**: Linux
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

expected behavior:
i found that "Note also that local transactions will never get dropped to ease debugging" in https://wiki.parity.io/Transactions-Queue.html.

actual:
when i send transaction by jsonrpc,  the transaction which gas price is low will be dropped. sometimes the transaction maybe Back to the transaction queue;  

how to keep the transaction that i send  in transaction queue?
What does local transaction mean?

**Comment by Tbaut** [comment]
Please upgrade your node (you didn't mention the minor version, 1.11.?) as it should be present in the latest releases.

"Local transaction" means a transaction that has been sent by an account the private key is found on the node.

**Comment by XuHugo** [comment]
ps，the transacton i said，is not local transaction，how to keep the transaction that i send in transaction queue?

**Comment by Tbaut** [comment]
I am updating the wiki to make things a little easier to understand, please follow https://github.com/paritytech/wiki/pull/220
