### ISSUE TITLE
gasUsed of Tx not equal gasUsed in trace

### ISSUE THREAD

**Issue by salisbury-espinosa** [paritytech/parity-ethereum#9366]
I'm running:
```
Which Parity version?: 1.10.9
Which operating system?: Linux
How installed?: from source
Are you fully synchronized?: yes
Which network are you connected to?: ethereum
Did you try to restart the node?: yes
```

https://etherscan.io/tx/0x481acf75ef5abdcd1efa9c984edc06ee5fdd1aa568588b26048deb3c64b8f8b2
`Gas Used By Txn: 419791`

https://www.etherchain.org/tx/0x481acf75ef5abdcd1efa9c984edc06ee5fdd1aa568588b26048deb3c64b8f8b2/parityTrace
only 1 action and
`"gasUsed": "0x43c67"` 

**277607 != 419791**

why these gas used volume differ?

**Comment by Tbaut** [comment]
This has to do with how the gas is calculated with the input. Have a look at this clear explanation: https://ethereum.stackexchange.com/questions/31443/what-do-the-response-values-of-a-parity-trace-transaction-call-actually-repres
