### ISSUE TITLE
where is --tx-queue-no-early-exit?

### ISSUE THREAD

**Issue by XuHugo** [paritytech/parity-ethereum#9368]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.8
> - **Which operating system?**: 8Linux
> - **How installed?**: via installer  binaries 
> - **Are you fully synchronized?**:yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
hi，the config --tx-queue-no-early-exit，I can‘t find in https://wiki.parity.io/Configuring-Parity-Ethereum#cli-options

**Comment by Tbaut** [comment]
the wiki isn't fully up to date. you can find it using `parity --help` on the latest version.
