### ISSUE TITLE
Unexpected growth of DB after upgrade to ubuntu 18.04

### ISSUE THREAD

**Issue by AntoniosHadji** [paritytech/parity-ethereum#9380]
> I'm running:
>
> - **Which Parity version?**:    Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2
upgraded to this version of parity on 8/3
> - **Which operating system?**: Linux Ubuntu 18.04.1 LTS
upgraded to this version of Ubuntu 8/19
> - **How installed?**: via installer deb file
> - **Are you fully synchronized?**: yes was fully synchronized before error
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Before upgrading to Ubuntu 18.04 my database was 28GB on a 100GB lvm disk. I upgraded late last night from Ubuntu 16.04.5 to 18.04.1.  This morning my 100GB disk was full and I see this error in the parity log file.

```
Aug 20 04:34:38 hadji parity[12076]: 2018-08-20 04:34:38  Verifier #2 INFO import  Imported #6180407 0x3d4c…f691 (145 txs, 7.98 Mgas, 841 ms, 33.19 KiB)
Aug 20 04:34:52 hadji parity[12076]: 2018-08-20 04:34:52  IO Worker #1 INFO import    #5643373   67/128 peers     78 MiB chain  175 MiB db  0 bytes queue   11 MiB sync  RPC:  0 conn,  0 req/s, 1870 µs
Aug 20 04:35:06 hadji parity[12076]: ====================
Aug 20 04:35:06 hadji parity[12076]: stack backtrace:
Aug 20 04:35:06 hadji parity[12076]:    0:     0x5633bea6b51c - <no info>
Aug 20 04:35:06 hadji parity[12076]: Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("IO error: No space left on deviceWhile appending to file: /mnt/ethereum/parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/083687.log: No space left on device"), State { next_error: None, backtrace: None })', libcore/result.rs:945
Aug 20 04:35:06 hadji parity[12076]: This is a bug. Please report it at:
Aug 20 04:35:06 hadji parity[12076]:     https://github.com/paritytech/parity/issues/new

```
using  this config.toml
```
[parity]
base_path = "/mnt/ethereum/parity"
[network]
min_peers = 64
max_peers = 128
max_pending_peers = 128

[mining]
author = "0x00..."

# API and console options – RPC:
[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts"]

[websockets]
origins = ["all"]

[footprint]
cache_size = 2048

[misc]
logging = "own_tx=trace"
```
I increased the size of the disk from 100GB to 200GB and node started normally.  I'm not currently seeing abnormal db growth. Current size of `./chains/ethereum/db` is 92GB.

**Comment by Tbaut** [comment]
>my database was 28GB

This is rather abnormal. The size of the DB after a [full sync is close to 100GB](https://wiki.parity.io/FAQ#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements). It's close to 30GB when ancient blocks are pruned, but it's not your case.
