### ISSUE TITLE
How does the new version of parity-ethereum 2.0.1-beta support UI access Parity

### ISSUE THREAD

**Issue by zhjgit** [paritytech/parity-ethereum#9384]
How does the new version of ps-ethereum 2.0.1-beta support UI access Parity。

I still want to access parity using the UI supported by the old version. Could you tell me how to configure it in the new version parity-ethereum 2.0.1-beta?

**Comment by Tbaut** [comment]
You can still use Parity UI to access your wallet. Here is the documentation about it: https://wiki.parity.io/Parity-Wallet Note that this UI is not maintained anymore and you should consider alternatives.

I'll close this issue, feel free to ask any questions in our [Gitter channel](https://gitter.im/paritytech/parity)
