### ISSUE TITLE
(dockerized parity) libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-ethereum#9390]
Something's wrong with your dockerized parity.

I have documented it over there: https://github.com/paritytech/parity-deploy/issues/51

but I do not think that `./parity-deploy.sh` is causing the problem?

**Comment by drandreaskrueger** [comment]
[giving up](https://github.com/paritytech/parity-deploy/issues/51#issuecomment-414677108) = can de-prioritize

**Comment by Tbaut** [comment]
Closing in favor of https://github.com/paritytech/parity-deploy/issues/51#issuecomment-414677108
