### ISSUE TITLE
Looking for PICOPS

### ISSUE THREAD

**Issue by elie222** [paritytech/parity-ethereum#9394]
Hi,

I understand the PICOPS service has been discontinued, but the code was open source. Is a link to the old source code available?

**Comment by debris** [comment]
I believe it's not open-source (https://github.com/paritytech/certifier-website) @maciejhirsz do you know if we can open source it?

**Comment by elie222** [comment]
Thanks. In this blog post it mentioned it was OS at some point?

https://paritytech.io/parity-technologies-launches-picops/

**Comment by elie222** [comment]
@maciejhirsz do you know if this is available anywhere?

**Comment by maciejhirsz** [comment]
Hey @elie222, we've set the repo to private for the time being until we decide what to do with it. It will probably end up os again.

**Comment by przemyslawlukasz** [comment]
Hi @maciejhirsz, did you decide finally if you open PICOPS source again?

**Comment by mikejanzen** [comment]
I'm interested in this as well. In particular I'm wondering if there would have been a ZK approach to picops that would have sidestepped GDPR.
