### ISSUE TITLE
"eth_call"  interface: VM execution error.  --I need your help.

### ISSUE THREAD

**Issue by zhousi666** [paritytech/parity-ethereum#9395]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.8
> - **Which operating system?**:  Linux  cntos7
> - **How installed?**:  binaries
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

**my issue description as follow:**

test1：
```
curl --data '{"method":"eth_call","params":[{"data":"0x313ce567","to":"0xB8c77482e45F1F44dE1745F52C74426C631bDD52"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://192.168.106.188:3007

{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000012","id":1}
```
test2：
```
curl --data '{"method":"eth_call","params":[{"data":"0x313ce567","to":"0x0ba000163959726c90D41C804386D37718D5edc8"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://192.168.106.188:3007

{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x"},"id":1}
```

1.    I want to get decimals of "0xB8c77482e45F1F44dE1745F52C74426C631bDD52" and "0x0ba000163959726c90D41C804386D37718D5edc8".   
2.   And about the "0xB8c77482e45F1F44dE1745F52C74426C631bDD52" is ok.   
3.   But  about  "0x0ba000163959726c90D41C804386D37718D5edc8"  return "VM execution error."  
4.   I don't know why this is the case. Who can help me?

**Comment by zhousi666** [comment]
@fckt  hi  fckt，I need your help .Can you help me?

**Comment by zhousi666** [comment]
@fckt  Is this a problem with my Parity service or contract execution?

**Comment by zhousi666** [comment]
@niklasad1

**Comment by debris** [comment]
what function (`0x313ce567`) of the contract are you trying to call? It's clearly a problem with contract execution and not with parity
