### ISSUE TITLE
 Stage 5 block verification failed for #8455037 

### ISSUE THREAD

**Issue by pabloruiz55** [paritytech/parity-ethereum#9402]
> I'm running:
>
> - **Which Parity version?**: v1.11.8
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: kovan 
> - **Did you try to restart the node?**:  yes

Out of the sudden I started to get this today.
```
2018-08-22 11:20:23  Stage 5 block verification failed for #8455037 (0x4870…e8ea)
Error: Error(Block(InvalidGasUsed(Mismatch { expected: 0x3674a, found: 0x32cbc })), State { next_error: None, backtrace: None })
2018-08-22 11:20:49  Syncing #8455036 0x1adc…952d     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #8455021    2/25 peers   31 KiB chain 2 MiB db 0 bytes queue 12 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-08-22 11:21:19       #1042    0/25 peers   31 KiB chain 2 MiB db 0 bytes queue 12 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-08-22 11:21:49       #1042    0/25 peers   31 KiB chain 2 MiB db 0 bytes queue 12 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
```

Tried:
* deleting nodes.json
* using --no-warp
* deleting the whole kovan chain folder
* doing db kill

Whatever I do I always get to the point that after the snapshots are synced I get the errors above and then no sync will happen (#0, 0 peers)

Any ideas?

**Comment by Tbaut** [comment]
Related to https://github.com/paritytech/parity-ethereum/issues/9402 ?

**Comment by Tbaut** [comment]
Same as https://github.com/paritytech/parity-ethereum/issues/8506
I looks like you only get connected to misbehaving peers. `--no-warp` should help you to ignore those. Does is always happen on this exact same block?

**Comment by felixwatts** [comment]
I have some information and a workaround that might be useful:

- I got this problem when using a new version of parity with a base-dir created by a very old version.

- parity db kill failed with error message "Error removing database: Os { code: 2, kind: NotFound, message: "No such file or directory" }"

- I fixed the problem by manually deleting <base-dir>/chains/kovan/db

**Comment by JohannesMayerConda** [comment]
Tried it again today using `parity --chain kovan db kill` and then `parity --chain kovan` and it synced correctly. I guess because it started the Syncing after Snapshot Sync with block #9140067 wich is later than my trouble causing #9120001 block.

For me the workaround was waiting for the snapshot to pass the bad block

**Comment by felixwatts** [comment]
Ah, I think I missed --chain kovan when I killed the db.

**Comment by Tbaut** [comment]
Closing as it simply appears to be a misbehaving node you are connected to.
