### ISSUE TITLE
[light client] export-hardcoded-sync is broken

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-ethereum#9411]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 2.0.1
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum, ropsten and kovan 

Running a `--light` node to sync and then doing `export-hardcoded-sync` will output:

- Kovan : `Error: cannot generate hardcoded sync because the database is empty.` whereas the light sync was made.
- Ropsten : Outputs the same CHT as in the chain-spec (whereas the chain is now 1000s of blocks longer)
- Mainnet: `Error: cannot generate hardcoded sync because the database is empty.` whereas the light sync was made.

This is probably linked to https://github.com/paritytech/parity-ethereum/pull/9064

**Comment by cheme** [comment]
Just to confirm, are you using `--light` flag when doing `export-hardcoded-sync` ? (seems to work on my env but you need the flag due to #9064)

**Comment by Tbaut** [comment]
You're totally right, I did not use the flag, as I was not use to. Also `export-hardcoded-sync` only make sense for the light client I guess. This makes the whole issue much less of a problem, thanks a lot :)
