### ISSUE TITLE
Implement EIP-191 Signing API

### ISSUE THREAD

**Issue by tuxxy** [paritytech/parity-ethereum#9422]
Parity lacks an API to perform an EIP-191 conforming signature for a given account. An API should be implemented that allows for arbitrary data to be signed by a specified account. This API will encompass signing as well as verifying functionalities.

Current API: https://wiki.parity.io/JSONRPC-personal-module#personal_sign

**Comment by Tbaut** [comment]
fixed in https://github.com/paritytech/parity-ethereum/pull/9701 (about to be released)
