### ISSUE TITLE
Unable to export blocks from private poa chain

### ISSUE THREAD

**Issue by whitenoiseL** [paritytech/parity-ethereum#9426]
> I'm running:
>
> - **Which Parity version?**: stable
> - **Which operating system?**: ubuntu
> - **How installed?**: via docker
> - **Which network are you connected to?**: private chain

I was trying to export blocks from my own poa chain, but the exported file I got is empty. 
![screencut](https://user-images.githubusercontent.com/16938270/44715086-83321700-aae9-11e8-896a-cf9eadff1478.png)

**Comment by Tbaut** [comment]
I've tried on a private blockchain that I let run a couple minutes without being able to reproduce:
```
$ parity --config config.toml export blocks export.rlp
Loading config file from config.toml
2018-08-28 13:58:13  Configured for DemoPoA using AuthorityRound engine
2018-08-28 13:58:13  Export completed.

$ ll
total 60
drwxrwxr-x 3 user user 4096 Aug 28 13:58 ./
drwxrwxr-x 8 user user 4096 Aug 28 13:49 ../
-rw-rw-r-- 1 user user 1825 Aug 28 13:50 chain.json
-rw-rw-r-- 1 user user  300 Aug 28 13:52 config.toml
-rw-rw-r-- 1 user user 3809 Aug 28 13:58 export.rlp
-rw-rw-r-- 1 user user    1 Aug 28 13:52 node.pwds
drwxrwxr-x 3 user user 4096 Aug 28 13:49 tmp/
```

Can you share a minimal reproducible example with your `spec.json`?

**Comment by whitenoiseL** [comment]
I generated my poa chain from parity-deploy.sh. Here is my authority.toml for miner:
`[parity]
chain = "/parity/chain.json"

[account]
password = ["/parity/password"]

[network]
reserved_peers = "/parity/reserved_peers"

[ui]
interface = "0.0.0.0"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[mining]
reseal_on_txs = "none"
engine_signer = "0x7c7b95a1e1f6f0c186c3f4f6643e94402fc7767d"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["http://127.0.0.1:8180"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]
`
And my spec.json for chain:
`{

	"name": "parity",
    	"engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "2",
                "validators" : {
                    "list": [ "0x7c7b95a1e1f6f0c186c3f4f6643e94402fc7767d", "0x2c36493486fda0dc7682048cfe17ea2eb828ee64" ]
                }
            }
        }
    },

    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "gasLimitBoundDivisor": "0x400",
        "networkID" : "0x11"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x1312D00"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
	"0x50f8019250fe0e016140fa231656d2028e161612": { "balance": "1606938044258990275541962092341162602522202993782792835301376" }
    }
}
`
And my docker-compose file:
`version: '2.0'
services:
   host1:
       container_name: host1
       ports:
       - 8080:8080
       - 8180:8180
       - 8545:8545
       - 8546:8546
       - 30303:30303 
       image: parity/parity:stable
       volumes:
       - ./deployment/chain/spec.json:/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/parity/reserved_peers:ro
       - ./deployment/1/password:/parity/password:ro
       - ./deployment/1/authority.toml:/parity/authority.toml:ro
       - ./deployment/1/${NETWORK_NAME}:/parity/data/keys/${NETWORK_NAME}
       - ./data/1:/parity/data
       command: --chain /parity/spec.json --config /parity/authority.toml -d /parity/data  
`
I noticed that the chain configuration in authority.toml is /parity/chain.json which is not matched with spec.json. The miner does work for my chain and can mine blocks. However I cannot get any blocks with export blocks command. Even after I changed chain configuration in authority.toml to "/parity/spec.json", I still got nothing from that command.

**Comment by Tbaut** [comment]
There is clearly a problem with the config and/or the chain path. Did you specify `-d /parity/data` when exporting? If you forget it, parity will export the chain from the default path, which is likely not present on your computer.

I took your `config` and `chain-spec` and did not have any problem.
You need to make sure the same parameters are used for the `export` command as the one you use to launch the node.

**Comment by whitenoiseL** [comment]
Thanks very much! Once I specified the path of where my data stored, the blocks can be exported.
