### ISSUE TITLE
Warp Restore Won't Complete

### ISSUE THREAD

**Issue by TheDeathryder** [paritytech/parity-ethereum#9442]
- **Parity Ethereum version**: 1.11.8
- **Operating system**: Windows 10
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**: ethereum foundation
- **Restarted**: yes

Actual:  Warp restore starts but stalls out after some time and never completes.
Expected;  Warp restore to start and complete, finish syncing.
Reproduce:   Open Parity, warp restore starts, eventually freezes, close Parity, repeat.

Warp restore always stalls out and fails to complete, usually around 60% to 70%.  I can see that it connects to up to 26 seeders, but never more than 3 active.

**Comment by Tbaut** [comment]
Can you please provide the command line logs?

**Comment by TheDeathryder** [comment]
Where can I find them?  I can't find any logs saved.

**Comment by Tbaut** [comment]
You need to launch parity using command line: https://wiki.parity.io/FAQ#how-to-launch-parity-ethereum-using-the-command-line-on-windows

**Comment by TheDeathryder** [comment]
I ran it in command line mode and the error didn't occur again.

**Comment by Tbaut** [comment]
All right, if it happens again please have a look at the error and feel free to get back here in case this error wasn't reported yet.

**Comment by 5chdn** [comment]
Having the same issue on 1.11.11 ~ should reopen this if someone can reproduce this on 2.0+
