### ISSUE TITLE
A question,   a pending transaction is dropped by txpool,why can get transaction information through eth_get Transaction ByHash, although the information does not contain blocknumber, blockhash, and so on. 

### ISSUE THREAD

**Issue by XuHugo** [paritytech/parity-ethereum#9446]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Why don't pending transactions have information in txpool, but you can get transaction information through eth_get Transaction ByHash, although the information does not contain blocknumber, blockhash, and so on. Where does the information of this transaction come from?

can you tell me?

**Comment by XuHugo** [comment]
@Tbaut ，sorry ，I mean that，the pending transaction was dropped by node；but I can get the transaction by rpcapi（eth_getTransactionByHash). but the information of transaction  does not contain blocknumber, blockhash.
for example,

{u'nonce': u'0x0', 
u'chainId': u'0x1', 
u'from': u'0x8901e54534f82d508523446ff1f6078ff587c17d', 
u'to': u'0xa68920f6d3c996ac3c232e4e93914e9d76150735', 
u'blockHash': None,
u'raw':u'0xf8a980843b9aca0083015f9a94a68920f6d3c996ac3c232e4e93914e9d7615073580b844a9059cbb00000000000000000000000020855c3894821dc535a3437cbbd2ed58d96002b50000000000000000000000000000000000000000000000056bc75e2d6310000025a0daaf838861107dee595df90c149f90aa2cb15b310d7179e6f58df2c6707f8813a024e5f36bc74e81519d43344ed907eefe88766c0cfc1f05cafb2cbe9033a8407d', 
u'standardV': u'0x0', 
u'v': u'0x25', 
u'gas': u'0x15f9a', 
u'value': u'0x0',
 u'blockNumber': None, 
u'creates': None, 
u'publicKey':u'0x35b9a9c3e6e2e8217516d277ef6332a9ebcb95d97f7d7cd13c6cbda23d339f6f248e573c592477de891ada3886d2446bb389214d51c573311fac7b09345f7309',
 u's': u'0x24e5f36bc74e81519d43344ed907eefe88766c0cfc1f05cafb2cbe9033a8407d', 
u'r': u'0xdaaf838861107dee595df90c149f90aa2cb15b310d7179e6f58df2c6707f8813', 
u'gasPrice': u'0x3b9aca00', 
u'input':u'0xa9059cbb00000000000000000000000020855c3894821dc535a3437cbbd2ed58d96002b50000000000000000000000000000000000000000000000056bc75e2d63100000', 
u'hash': u'0x5d151fd98d782b33b1f8cfee4dc39bff8176b9e6cef5136387d917e20e2c1478', u'transactionIndex': None, 
u'condition': None}

1、I want to know where this information is stored.
2、Is it possible to assume that pending transactions are stored somewhere in the node, even though they are discarded by the node?
Ignore my bad English.

**Comment by Tbaut** [comment]
What makes you think that the node dropped the transaction?
Can you please update the information in your first post, what version of parity you use etc?

**Comment by drandreaskrueger** [comment]
Have a look:

https://etherscan.io/tx/0x5d151fd98d782b33b1f8cfee4dc39bff8176b9e6cef5136387d917e20e2c1478

your transaction **has been propagated!**

It is among the 81273 "pending transactions" https://etherscan.io/txsPending

Read more about it https://www.google.co.uk/search?q=ethereum+AND+%28txpool+OR+mempool+OR+%22memory+pool%22

**Comment by drandreaskrueger** [comment]
The reason: [1 GWei gasPrice](https://etherscan.io/tx/0x5d151fd98d782b33b1f8cfee4dc39bff8176b9e6cef5136387d917e20e2c1478) is not enough money (anymore / right now) to have any miner even start bothering about looking at your tx.

Before sending, look at how much the other people are offering, column "GasPrice" on https://etherscan.io/txsPending

Also check out https://ethgasstation.info/

**Comment by XuHugo** [comment]
@drandreaskrueger @Tbaut @yrashk  @skddc  @kavu  ,I send a transaction into my node by "eth_sendRawTransaction". I know the gastrice is too low, so it is dropped by node.  I can't find it in txpool , but I can find it in my node  by "eth_getTransactionByHash". 
1、I want to know where the transaction is stored.
2、Is it possible to assume that pending transactions are stored somewhere in the node, even though they are discarded by the node?

**Comment by Tbaut** [comment]
You did not answer my questions..
>What makes you think that the node dropped the transaction?
Can you please update the information in your first post, what version of parity you use etc?

**Comment by drandreaskrueger** [comment]
>  I know the gastrice is too low, 

It still enters the txpool.

Your transaction is [here](https://etherscan.io/tx/0x5d151fd98d782b33b1f8cfee4dc39bff8176b9e6cef5136387d917e20e2c1478). 


> so it is dropped by node.

Wrong. 

Do some reading, see the links I have given.

**Comment by XuHugo** [comment]
@drandreaskrueger   I mean  it is dropped by my node, because I am developing the wallet of ETH。I don't care about other nodes or browser nodes。I know what you mean is that transactions are not abandoned, and transactions exist in some nodes in the network.

**Comment by XuHugo** [comment]
@Tbaut So sorry，
Which Parity version?: 1.11
Which operating system?: Linux
How installed?: via installer from source
Are you fully synchronized?: yes
Which network are you connected to?: ethereum
Did you try to restart the node?: yes
