### ISSUE TITLE
Feature request - support for efficient receipt merkle proofs via nonstandard rpc.

### ISSUE THREAD

**Issue by dice2-win** [paritytech/parity-ethereum#9449]
- **Parity Ethereum version**: 1.11.8
- **Operating system**: Linux
- **Installation**: Docker container
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

In our new smart contracts we need to provide receipt merkle proofs, which requires rebuilding the Merkle Patricia trie for all the receipts. While it can be done for transactions rather atomically by invoking eth_getBlock with the flag to return transaction objects, the only way that the same can be done for receipts is by invoking eth_getTransactionReceipt for each tx in block. Having up to several hundred JSON RPC calls per block is not robust; maybe it is possible to roll out a custom Parity RPC call (along the lines of parity_getBlockHeaderByNumber), that will return all receipts for a block at once?

**Comment by Tbaut** [comment]
This very much looks like https://github.com/paritytech/parity-ethereum/issues/9430 right?

**Comment by dice2-win** [comment]
@Tbaut thanks for the link. It is exactly what is needed.
