### ISSUE TITLE
Unable to start Parity node 

### ISSUE THREAD

**Issue by Amaleid** [paritytech/parity-ethereum#9454]
`_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: version Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: 
- **Network**: 
- **Restarted**: yes

I followed this [tutorial ](https://wiki.parity.io/Demo-PoA-tutorial.html  )to set up a private chain with PoA . When i try command parity --config node0.toml. 

> Method 1. Using RPC
> Start the node 0 using parity --config node0.toml.

 i get this 

```
root@amal:~# parity --config node0.toml
Loading config file from node0.toml
Option '--dapps-port' has been removed and is no longer supported.
2018-08-31 19:33:23 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
2018-08-31 19:33:23 UTC Keys path /tmp/parity0/keys/DemoPoA
2018-08-31 19:33:23 UTC DB path /tmp/parity0/chains/DemoPoA/db/d0678730db7ea493
2018-08-31 19:33:23 UTC State DB configuration: fast
2018-08-31 19:33:23 UTC Operating mode: active
Consensus signer account not found for the current chain. You can create an account via RPC, UI or "parity account new --chain demo-spec.json --keys-path /tmp/parity0/keys"
```

**Comment by Tbaut** [comment]
The error is quite explicit, it seems that you have specified an account in `node0.toml` that the node can not find. You need to first create an account (with one option given in the tutorial) and then edit the toml file to specify the right address.
