### ISSUE TITLE
Sync the blockchain from the scratch error

### ISSUE THREAD

**Issue by trangir** [paritytech/parity-ethereum#9464]
- **Parity Ethereum version**: 1.11.10-stable
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

c:\Program Files\Parity Technologies\Parity>parity.exe -d D:\G\.parity
2018-09-04 05:00:09  Starting Parity/v1.11.10-stable-31720e615-20180830/x86_64-windows-msvc/rustc1.28.0
2018-09-04 05:00:09  Keys path XXXXX
2018-09-04 05:00:09  DB path XXXXX\db\906a34e69aec8c0d
2018-09-04 05:00:09  XXXXX\dapps
2018-09-04 05:00:09  State DB configuration: fast
2018-09-04 05:00:09  Operating mode: active
2018-09-04 05:00:10  Configured for Foundation using Ethash engine

====================

stack backtrace:
   0:        0x1400976d8 - hid_error
   1:        0x140096c43 - hid_error
   2:        0x13f8d1700 - <no info>
   3:        0x14013e0a2 - hid_error
   4:        0x14013ddf4 - hid_error
   5:        0x14013dac9 - hid_error
   6:        0x14016cc1c - hid_error
   7:        0x14016cb4e - hid_error
   8:        0x13fbf2bbf - <no info>
   9:        0x13fb1fd18 - <no info>
  10:        0x13f8e3081 - <no info>
  11:        0x13f388798 - <no info>
  12:        0x13f39aee8 - <no info>
  13:        0x13f653331 - <no info>
  14:        0x13f659870 - <no info>
  15:        0x13f65b7d4 - <no info>
  16:        0x13f554f16 - <no info>
  17:        0x14013da27 - hid_error
  18:        0x1401662bc - hid_error
  19:        0x1401517f3 - hid_error
  20:        0x13f65bc3a - <no info>
  21:        0x1404ef5d0 - hid_write
  22:              0x3b9 - <no info>
  23:          0x25805b0 - <no info>
  24:          0x25138e0 - <no info>
  25:        0x13f65a74f - <no info>
  26:        0x14045dcc9 - hid_write
  27:         0x76c659cd - BaseThreadInitThunk

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by trangir** [comment]
This happens every time I restart the parity.exe

**Comment by trangir** [comment]
First time it happened at the following point:

2018-09-04 04:59:36  Syncing snapshot 2001/2004    #17850   24/25 peers     74 KiB chain   14 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 чs

====================

stack backtrace:
   0:        0x1407d76d8 - hid_error
   1:        0x1407d6c43 - hid_error
   2:        0x140011700 - <no info>
   3:        0x14087e0a2 - hid_error
   4:        0x14087ddf4 - hid_error
   5:        0x14087dac9 - hid_error
   6:        0x1408acc1c - hid_error
   7:        0x1408acb4e - hid_error
   8:        0x140332bbf - <no info>
   9:        0x140269262 - <no info>
  10:        0x14024772e - <no info>
  11:        0x140248a4c - <no info>
  12:        0x14002473e - <no info>
  13:        0x140036711 - <no info>
  14:        0x140031183 - <no info>
  15:        0x14002954a - <no info>
  16:        0x1408a62bc - hid_error
  17:        0x1400329ce - <no info>
  18:        0x1408999a2 - hid_error
  19:        0x140885959 - hid_error
  20:         0x76c659cd - BaseThreadInitThunk

Thread 'IO Worker #1' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by Tbaut** [comment]
closing as stale
