### ISSUE TITLE
`eth_sendTransactionAsync` to accelerate parity? 

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-ethereum#9471]
Perhaps an idea, to accelerate (the [6.5 times slower](https://github.com/paritytech/parity-ethereum/issues/9393#issuecomment-418325544)) parity?

    eth_sendTransactionAsync

see:  
https://github.com/jpmorganchase/quorum/issues/119#issuecomment-302795521  
https://github.com/jpmorganchase/quorum/releases/tag/v1.0.2

**Comment by Tbaut** [comment]
This would need to go through an EIP.

**Comment by drandreaskrueger** [comment]
@Tbaut 

> This would need to go through an EIP.

... or you look at how it is already implemented in quorum, and take that as the example implementation.

I don't even want to submit async transactions, and with geth I don't need to. 

I only made this suggestion to you parity people, because your client is 5-6 times slower than geth - so this approach might help parity a lot, to catch up?

**Comment by Genysys** [comment]
Dont think that is a concern for Parity see : https://ethereum.stackexchange.com/questions/52185/eth-sendtransaction-vs-eth-sendtransactionasync-asynchronous-or-synchronous-re/55277
