### ISSUE TITLE
one of the node is not work

### ISSUE THREAD

**Issue by Amaleid** [paritytech/parity-ethereum#9474]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.0.1
- **Operating system**: Linux
- **Network**: POA
- **Restarted**: yes

Hi 
when is start my node `parity --config node1.toml` is show me the below  however my other node (node0) is work fine! and that happened after i restart my machine 
![image](https://user-images.githubusercontent.com/32046401/45058208-ed0c6c80-b065-11e8-9d4e-33b103048f10.png)

**Comment by Tbaut** [comment]
Answered on Gitter, please avoid cross-posting without announcement :)

**Comment by Amaleid** [comment]
i get that again
