### ISSUE TITLE
Can't find Ethereum Classic peers

### ISSUE THREAD

**Issue by LoneyNightCoder** [paritytech/parity-ethereum#9476]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**:   version Parity/v1.11.10-stable-31720e6-20180830/x86_64-linux-gnu/rustc1.28.0
- **Operating system**: Linux
4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: classic
- **Restarted**: lol, yes

Can't find any Ethereum Classic peers. It's been 3 days already.

**Comment by Tbaut** [comment]
This is most probably because you have a bad connectivity or there aren't a lot of nodes on the network.
Did you try to remove your nodes.json cf https://wiki.parity.io/FAQ#what-can-i-do-when-parity-ethereum-has-trouble-getting-in-sync ?

**Comment by LoneyNightCoder** [comment]
Network 1GBit/s
I run the ETH and ETC both daemons and ETH is fully working
i've already deleted nodes.js

**Comment by Tbaut** [comment]
I tested all bootnodes separately and I got only this one to connect:
`enode://83b33409349ffa25e150555f7b4f8deebc68f3d34d782129dc3c8ba07b880c209310a4191e1725f2f6bef59bce9452d821111eaa786deab08a7e6551fca41f4f@159.89.223.6:30303`

@pyskell can you help us update the bootnode's list?

**Comment by LoneyNightCoder** [comment]
Yay it's working!
