### ISSUE TITLE
[permission] finalizeChange is not being called in validator contract

### ISSUE THREAD

**Issue by KimiWu123** [paritytech/parity-ethereum#9485]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.3-beta-a0a2bed-20180831
- **Operating system**: Linux
- **Installation**:  one-line installer
- **Network**: private

I followed this [wiki post](https://wiki.parity.io/Validator-Set) to create my validator contract and I checked  [issue#9131](https://github.com/paritytech/parity-ethereum/issues/9131). I can see InitiateChange event, but my validator address is still in pending list not validator list. My validator contract is based on [here](https://github.com/parity-contracts/kovan-validator-set).
Here is my genesis, 

```
"engine": {
        "tendermint": {
            "params": {
               "gasLimitBoundDivisor": "0x400",
                "validators" : {
                   "multi": {
                       "0": {
                           "list": [
                               "0x452e132dad56f288b0bbbd956b064778578cfc71"
                           ]
                       },
                       "100": {
                           "contract": "0x0000000000000000000000000000000000000006"
                       }
                   }
               }
            }
       }
    },
```
And I set force-sealing to true as comment in issue #9193. Now I only have one node because I just want to verify this functionality. Is it okay?

**Comment by Tbaut** [comment]
You genesis uses tendermint consensus that is not supported anymore. You need to use `authorityRound` as seen here: https://wiki.parity.io/Pluggable-Consensus

**Comment by KimiWu123** [comment]
Oh! Thank you. That's why I only can get genesis sample of tendermint on StackOverflow... There are a lot of "not update to date" information on the Internet. Suggest you to comment "tendermint" as deprecated in you wiki. Thanks.

**Comment by KimiWu123** [comment]
@Tbaut , In permission page, Tendermint is still in your [validator set list](https://wiki.parity.io/Permissioning#validator-set), That's why I thought it is supported now.

**Comment by KimiWu123** [comment]
It's still not working after I use authorityRound. Basically, my validator contract copies from  [issue 9193](https://github.com/paritytech/parity-ethereum/issues/9131) and remove all modifier for verifying.


My genesis is like,

```
"engine": {
       "authorityRound": {
           "params": {
               "stepDuration": "3",
               "blockReward": 1000000000000000000,
               "validators" : {
                   "multi": {
                       "0": {
                           "list": [
                               "0x452e132dad56f288b0bbbd956b064778578cfc71"
                           ]
                       },
                       "100": {
                           "contract": "0x0000000000000000000000000000000000000006"
                       }
                   }
               }
           }
       }
    }
```

finalizeChange is still not being called. I still use one node only. Any helps would be appreciate.

**Comment by KimiWu123** [comment]
I found finalizeChange is only called after the validator contract is enabled which means 100th block in my case. 
Another quick question, is it allowed to remove validators? I remove the pending list and emit InitiateChange successfully. However, finalizeChange is still not being called.

**Comment by Tbaut** [comment]
> In permission page, Tendermint is still in your validator set list, That's why I thought it is supported now.

Thanks for the heads-up, I fixed it.

> is it allowed to remove validators? 

yes

>I remove the pending list and emit InitiateChange successfully. However, finalizeChange is still not being called.

How many validators do you have? What kind of change do you do, like just removing one? The change must be signed by 2/3 of the validators right?

**Comment by KimiWu123** [comment]
Oh! I didn't realize that it needs to be signed by 2/3 validators  .  I have 3 validators, 2 of them are active, and want to remove one. It's not allowed, right?! Thanks for your answer.

**Comment by Tbaut** [comment]
Sorry, my mistake, it need the approval of 51% at least. This is not related to the amount of validators, you can switch to 1 validator if you wish to, just that 51% of the validators need to be online and sign on this.

**Comment by KimiWu123** [comment]
Got it! thanks for your explanation. Could you please provide the link about the rule of approval of 51%? I think I missed it. Thanks.

**Comment by Tbaut** [comment]
You can find it under Finality in the following article, it's expressed with `>n/2` with `n` the number of validators: https://wiki.parity.io/Aura
