### ISSUE TITLE
About txReceipt status

### ISSUE THREAD

**Issue by redred77** [paritytech/parity-ethereum#9488]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v1.11.8
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Maybe this is not parity issue but the uncertainity of api
I see that txreceipt's status is 0x1 but the call failed.

(1) This is one of them.
https://etherscan.io/tx/0x1bd2c54df6eef91bdea225958d559d74b9f111ec3d6ebecb2df5b86c69ad6562
This TxReceipt Status is Success, but "Although one or more errors occured [Out of gas] contract execution completed"
When I trace from geth and parity I could find "Out of Gas" like below link.
https://etherscan.io/vmtrace?txhash=0x8aac7bc44d772b8bee44d8597cf855c922a7c004bcb8a92eadbde2f5d215a9b5&type=parity

(2) This transaction says TxReceipt Status is 'Success' but opcode has 'Out of gas'
https://etherscan.io/tx/0x8aac7bc44d772b8bee44d8597cf855c922a7c004bcb8a92eadbde2f5d215a9b5
Here's traces
https://etherscan.io/vmtrace?txhash=0x8aac7bc44d772b8bee44d8597cf855c922a7c004bcb8a92eadbde2f5d215a9b5&type=parity

1. I've found that 'eth_getTransactionReceipt' is returning the success/failure status of only the first call not subsequent calls. Is it intended? Why not other call results then?

2. If Error is only showing the first call's result then it's quite hard to check subsequent call's result. Need to set "--tracing on" which is nearly impossible to sync.

3. What happens to first call if second call fails? Will it be reverted?
What happens to event logs if it's reverted?
I know this is not an issue of parity but want to be sure what txreceipt status was intended for.

**Comment by Tbaut** [comment]
The top level call has full control of what happens over sub level calls. Sub level calls' results are reported back to its parent level calls. And it's always up to the parent level calls for what to do if the sublevel call fails. The status field actually has a well-defined meaning -- it means whether the transaction succeeds or fails, and by transaction succeeding/failing we mean what happens to the top level calls.

> I've found that 'eth_getTransactionReceipt' is returning the success/failure status of only the first call not subsequent calls. Is it intended? Why not other call results then?

The first contract called has been designed not to fail even if a sub-level call fails. This is intended.

> If Error is only showing the first call's result then it's quite hard to check subsequent call's result. Need to set "--tracing on" which is nearly impossible to sync.

The contract could use `requires`/`asserts` to fail accordingly.

> What happens to first call if second call fails? Will it be reverted?

In your case, the first call does not raise an error when the second call fails, so the 1st call is not reverted and marked as successfull, the second is revered and marked as failed.

> What happens to event logs if it's reverted?

There will not be any event.

Thanks a lot to @sorpaas for his help on that.

**Comment by redred77** [comment]
@Tbaut I now understand things better now. Thanks a lot.
