### ISSUE TITLE
[permission] Question: what is best practice to add a node in existing permission chain

### ISSUE THREAD

**Issue by KimiWu123** [paritytech/parity-ethereum#9493]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.3-beta-a0a2bed-20180831
- **Operating system**: Linux
- **Installation**:  one-line installer
- **Network**: private

I use node permission contract to control connections among nodes and also use validator set contract to manage validators.

Here is my scenario, 
I have node A and node B with ID(A) and ID(B) correspondingly. I hard coed ID(A) and ID(B) in validator set contract so node A and node B can validate blocks at beginning. I can connect these two node smoothly. 

Now, I have third node, C with ID(C) ready to join this network. However, only ID(A) and ID(B) are  in the validator contract so if I use ID(C) as `engine_signer` in node C, no blocks would be generated. Therefore, I can't do any transactions(adding anyone in validator contract or adding as a peer) in node C. Now, I only have two options, 
(1). use ID(A) as `engine_signer` in node C to add ID(C) to validator contract, then restart node C with ID(C)
(2) use ID(A) as `engine_signer` in node C to add node C into A and B network (but it will show 
`import  Syncing      #20 0xe34f…0e9c     0.00 blk/s    0.0 tx/s    0 Mgas/s      7+    1 Qed       #24    0/25 peers   23 KiB chain 78 KiB db 13 KiB queue 22 KiB sync  RPC:  0 conn,    0 req/s,    0 µs` forever and can't be stopped. Reboot is the only way to stop)

Any better way to add a new node instead of switching ID(accounts)?
Thanks.

**Comment by Tbaut** [comment]
What you described does not seem to profit from the power of validator set contract as you are hard-coding the nodes. Have you had a look at the contract we present as example: https://github.com/parity-contracts/kovan-validator-set ?

**Comment by KimiWu123** [comment]
No,no, no. You're misunderstanding. I only hard coded for init validators. There are two way to init validators, one is hard coded, the other is init by adding in abi. It's more convenient for me to integrate this function. Actually I read all the materials in parity wiki( although I may miss something). Btw, there are some bugs in the sample contract. 
Another issue I met is if no any init validators in validator contract,  it won't work. For example, I add a validator into the contract before it's enabled, finalizeChange won't be called. So, the validator won't be added in validator contract. After the contract is enabled, there are no validators to validate blocks.that's why I have to have init validators.
Another issue is if I only set contract address in validator section of genesis, it shows an error message like "bad instructions fd". ( if I don't check SYSTEM_ADDRESS in finalizeChange, it doesn't show error messages)

**Comment by Tbaut** [comment]
Please share your chain configuration file and validator set contract (if relevant).
Your question is not clear to me unfortunately.
