### ISSUE TITLE
[PrivateTransactions] wrong return value when calling not yet initialized variables of a private smart contract

### ISSUE THREAD

**Issue by makue1105** [paritytech/parity-ethereum#9494]
- **Parity Ethereum version**: Parity-Ethereum/v2.0.3-unstable-a0a2beddf-20180831/x86_64-macos/rustc1.27.0
- **Operating system**:   MacOS 
- **Installation**: built from source
- **Fully synchronized**:  yes
- **Network**: dev
- **Restarted**: yes

Currently, when trying to call a not yet initialized variable of a private Contract it will return some value (in the tutorial it returned the number of validators). However, a not yet initialized variable should always return 0x0 or false. 

see documentation of secret transactions: 
https://github.com/paritytech/wiki/blob/master/Private-Transactions-Tutorial-4.md

> The result is the current value of x. As it wasn't initialized, it defaults to 1.
> {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000001","id":1}

**Comment by Tbaut** [comment]
Thanks for the issue. cc @grbIzl

**Comment by ngyam** [comment]
Yep, returning the default type values would be nice
