### ISSUE TITLE
No Command Line Option to Disable Account Creation from Parity UI

### ISSUE THREAD

**Issue by ericbinet** [paritytech/parity-ethereum#9495]
- **Parity Ethereum version**: Parity/v1.11.10-stable-31720e6-20180830/x86_64-linux-gnu/rustc1.28.0
- **Operating system**: Linux (Docker on Debian 10 - Buster)
- **Installation**: Docker image: parity/parity:stable or v1.11.10
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

Cannot block Parity UI from connecting and creating account on a Parity instance intended for public access.

We would like to setup a few Parity instances to serve a private sidechain. We first setup our nodes to sync the Kovan chain and were trying to enable JSON-RPC and WS services to allow users to send signed transactions and register for events.

We were trying to disable access from Parity UI or, at least, make it so the UI cannot affect the server in any meaningful way other than what Web3 (0.20 or 1.0) can do.

It turns out that we cannot figure out a clean way to disable Parity UI from connecting and creating accounts. The only workaround I found was to launch the server with the `--unlock=` flag. This makes it so `WsConfiguration.support_token_api` becomes false in `configuration.rs` at line 853.

We expect a command line switch to disable Parity UI.

**Comment by Tbaut** [comment]
If Parity UI can only get access to a local node if it has a token. 

>It turns out that we cannot figure out a clean way to disable Parity UI from connecting and creating accounts. 

Are your users accessing the localhost of the machine that runs Parity Ethereum? Otherwise it won#t be possible for Parity UI to create a token and create accounts.

**Comment by gituser** [comment]
try disabling supported RPCs, e.g. exclude `personal` from the list of `--jsonrpc-apis`
