### ISSUE TITLE
warning: build failed, waiting for other jobs to finish...

### ISSUE THREAD

**Issue by zheng9980419** [paritytech/parity-ethereum#9504]
Compiling gcc v0.3.54
error: aborting due to 61 previous errors

error: Could not compile `byteorder`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by EwoutH** [comment]
I probably got the same issue on Rust Nightly on rust-av.

- See this PR: https://github.com/rust-av/rust-av/pull/74
- [Full AppVeyor build log](https://ci.appveyor.com/project/EwoutH/rust-av/build/job/p43wn7xiu7n789cy)
- [AppVeyor configuration](https://github.com/rust-av/rust-av/blob/06a58e3f8829badd9e296f27fdd2d32aad07ab17/appveyor.yml)

```
cargo build --release --target=%target%
```
```
error: aborting due to 37 previous errors
Some errors occurred: E0206, E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0206`.
error: Could not compile `winapi`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by EwoutH** [comment]
It eventually exited by itself, just took somewhat longer than expected (6 min).
