### ISSUE TITLE
Validator node is down of PoA with validator set contract

### ISSUE THREAD

**Issue by khaschuluu** [paritytech/parity-ethereum#9509]
- **Parity Ethereum version**: 2.0.3
- **Operating system**: Linux Ubuntu 18.04
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: private network with aura
- **Restarted**: yes

I trying to create private network with aura PoA consensus with validator set contract. Contract from Kovan.

First node working on Google Cloud and second is validator and working on my local computer. They are successfully connected each other, but after short time (about 1 minute), second node crushes with following message:

```
====================

stack backtrace:
   0:     0x55b8bab851bc - <no info>
   1:     0x55b8bab84192 - <no info>
   2:     0x55b8bab84208 - <no info>
   3:     0x55b8bab8300a - <no info>
   4:     0x55b8b9842175 - <no info>
   5:     0x55b8babe3733 - <no info>
   6:     0x55b8babe3489 - <no info>
   7:     0x55b8babe31a5 - <no info>
   8:     0x55b8bac46d8b - <no info>
   9:     0x55b8ba445ef8 - <no info>
  10:     0x55b8ba218812 - <no info>
  11:     0x55b8ba21cadf - <no info>
  12:     0x55b8ba21f8db - <no info>
  13:     0x55b8ba499f1a - <no info>
  14:     0x55b8ba21d730 - <no info>
  15:     0x55b8ba43a13d - <no info>
  16:     0x55b8ba2a6a4e - <no info>
  17:     0x55b8ba334a66 - <no info>
  18:     0x55b8bac0dcb9 - <no info>
  19:     0x55b8ba3466f8 - <no info>
  20:     0x55b8babdff2a - <no info>
  21:     0x55b8babe42a5 - <no info>
  22:     0x7f013b91f6da - <no info>
  23:     0x7f013b43088e - <no info>
  24:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'proof produced by this engine; therefore it is valid; qed: Error(Decoder(RlpExpectedToBeList), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

I expected second node starts to seal blocks, but my chain steel with 0 block.

**Comment by Tbaut** [comment]
Can you give us more logs (before it crashes), your genesis contract and your chain-spec.json please?

**Comment by CorentinPacaud** [comment]
Here is my chain-spec.json :

`{
    "name": "DemoPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "5",
                "validators": {
                    "safeContract": "0x0000000000000000000000000000000000000005"
                }
            }
        }
    },
    "params": {
        "gasLimitBoundDivisor": "0x400",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID": "0x2323"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": {
            "balance": "1",
            "builtin": {
                "name": "ecrecover",
                "pricing": {
                    "linear": {
                        "base": 3000,
                        "word": 0
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000002": {
            "balance": "1",
            "builtin": {
                "name": "sha256",
                "pricing": {
                    "linear": {
                        "base": 60,
                        "word": 12
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000003": {
            "balance": "1",
            "builtin": {
                "name": "ripemd160",
                "pricing": {
                    "linear": {
                        "base": 600,
                        "word": 120
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000004": {
            "balance": "1",
            "builtin": {
                "name": "identity",
                "pricing": {
                    "linear": {
                        "base": 15,
                        "word": 3
                    }
                }
            }
        },
        "0x17353a2318f0c4f8e16d6c4d05caf2b02aedae7a": { "balance": "100000000000000000000" }
    }
}`

And the node which failed : 

`[parity]
chain = "demo-spec.json"
base_path = "~/ethereum/poa/node1/"
[network]
port = 30301
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0" #external access to rpc
[ui]
port = 8181
[websockets]
port = 8451
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x17353a2318f0c4f8e16d6c4d05caf2b02aedae7a"
reseal_on_txs = "none"`

**Comment by CorentinPacaud** [comment]
removing the "~/" from this : 
`base_path = "~/ethereum/poa/node1/"`
seems to work.

**Comment by ddorgan** [comment]
@CorentinPacaud is that your whold contract? Where's the value area for 0x0000000000000000000000000000000000000005?

**Comment by CorentinPacaud** [comment]
hmm, right. I remove it too : 
`"validators": {
                    "list":["0xcce5c753ace2729cd655fa0eecdc0e99a4ff7a23"]
                }`

**Comment by Tbaut** [comment]
@CorentinPacaud are you related to @khaschuluu ? if yes please close the issue.

**Comment by khaschuluu** [comment]
I newly setup and now it works fine. I think above problem might be caused by manually added account, I add account of second node (validator) to parity by manually (copy key file to keys folder).

Thank you.

**Comment by CorentinPacaud** [comment]
@Tbaut not related, but the same pb happened at the same time.
Ok, closed for me too, as it happened to be a validator : safecontract pb.
