### ISSUE TITLE
'IO Worker #1' panicked at 'proof produced by this engine

### ISSUE THREAD

**Issue by CorentinPacaud** [paritytech/parity-ethereum#9520]
- Parity Ethereum version: version Parity/v1.11.8-stable-c754a028e-20180725/x86_64-windows-msvc/rustc1.27.2
- Operating system: Windows 
- Installation: windows installer
- Fully synchronized : no / yes ?
- Network: authorityRound
- Restarted: no

I have follow this [tuto ](https://valanter.com/academy/non-classe/create-an-ethereum-owned-proof-of-authority-private-chain-poa/) and this error appears : 
Thread 'IO Worker #1' panicked at 'proof produced by this engine; therefore it is valid; qed: Error(Decoder(RlpExpectedToBeList), State { next_error: None,
backtrace: None })', libcore\result.rs:945

Any idea ?

Moreover, I can't connect metamask or ParityUI to this network.

Thx

**Comment by Tbaut** [comment]
It's indeed a duplicate. Please subscribe to the other thread.
