### ISSUE TITLE
How to achieve Token mutual transfer  No fee is required ether

### ISSUE THREAD

**Issue by anyluck** [paritytech/parity-ethereum#9523]
**Parity Ethereum version**:1.11.8
- **Operating system**:  Linux
- **Installation**: homebrew
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

In the Ethernet client development encountered a tangled problem, users do not have tokens, but other platforms to his wallet address recharged some tokens, their wallet address without ether, how to make his address tokens out of other platforms

**Comment by joshua-mir** [comment]
Have I understood your question correctly? Someone received tokens, but has no ether to send the tokens out so they are stuck. There is no way around it, you need to send a small amount of ether to the address if you want to send the tokens out.

**Comment by joshua-mir** [comment]
Closing as I've answered, and this is a general ethereum question and unrelated to the parity client.
