### ISSUE TITLE
reportBenign in reporting contract does not function properly

### ISSUE THREAD

**Issue by jbentke** [paritytech/parity-ethereum#9524]
- **Parity Ethereum version**: Parity/v1.11.8-stable-c754a02-20180725/x86_64-macos/rustc1.27.2
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

**actual**: The transaction fails (reportBenign)
**expected behavior**: The transaction executes successfully.

I am running a private Aura network in which I test an authority contract. It is a reporting contract. After debigging for ages I broke it down to this minimal test case. The reportBenign function is not behaving as expected. The transaction fails even though it doesn't do anything. I just can not see the error... The code can be found below.

**steps to reproduce**: 
Start a chain with the chain file in the link below. Execute the AddValidator function and then check the transaction hash of the reporting transaction.

The chain file and the corresponding contracts can be found [here](https://github.com/jbentke/PoA-Test)

**Comment by Tbaut** [comment]
I had a quick look at your contract and I can see that the contract address that you are declaring in the genesis `0x1000000000000000000000000000000000000005` corresponds to the contract https://github.com/jbentke/PoA-Test/blob/master/AuthorityProxy.sol that does not itself contains the function `reportBenign` nor does the imported AuthorityDB.sol. I bet that's the reason.

**Comment by jbentke** [comment]
The reporting function is in the SimpleAuthority contract at `0x1000000000000000000000000000000000000006` which is called by the proxy contract through a delegate call. Adding a Validator is functioning fine with that setup.

**Comment by Tbaut** [comment]
@andresilva is this supported?

**Comment by andresilva** [comment]
Yes, this is supported and working properly AFAIK. You can test this with the kovan-validator-set contracts. I fail to understand what the issue actually is though. The reporting functions are supposed to be called by the engine, and if you're calling them directly and the transaction fails then that is an issue with the contract itself (as with any contract). I'd suggest to try debugging your contract in a simpler scenario, e.g. without the proxy and maybe using truffle or some other environment that allows you to easily debug it.

**Comment by jbentke** [comment]
yes, so the issue was actually not on paritys side but on mine. I had not activated any EIPs on my local chain but compiled the contracts with the latest version of solidity. Thats why it failed. Sorry to bother you guys!
