### ISSUE TITLE
Update ring to 0.13 or submit upstream changes

### ISSUE THREAD

**Issue by c0gent** [paritytech/parity-ethereum#9533]
[The version of ring currently in use within parity](https://github.com/paritytech/ring) is a fork.

@tomaka, Is there any reason these changes have not been submitted upstream? If not, I, or someone on my team can take care of it. Please advise.

**Comment by tomaka** [comment]
The reason why we used a fork is https://github.com/paritytech/ring/pull/1

I'm on my phone right now so can't really investigate but this change should be upstreamed if not done already.

**Comment by tomaka** [comment]
I don't think it's a bad idea to have an issue for upgrading to ring 0.13. It's something we really want.

**Comment by ordian** [comment]
I think `ring` no longer defines `__ANDROID_API__`, see https://github.com/briansmith/ring/commit/08ec4f374caf1ef2bc079035642b89fbefdb5ed2.
