### ISSUE TITLE
c3295826d7c9904c 'chain folder redundancy'

### ISSUE THREAD

**Issue by inmathwetrust** [paritytech/parity-ethereum#9555]
- **Parity Ethereum version**: v2.2.0-unstable-6e62d77-20180912/x86_64-linux-gnu/rustc1.28.0
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

Started syncing my node with mainnet. 
Noticed MANY chain folders.
I would like to know why so many files? And which ones can i delete to avoid storage bloat?

**~/.local/share/io.parity.ethereum$ du -h c3295826d7c9904c/**
172K	c3295826d7c9904c/v5.3-sec-refcounted/state
176K	c3295826d7c9904c/v5.3-sec-refcounted
172K	c3295826d7c9904c/v5.3-sec-archive/state
176K	c3295826d7c9904c/v5.3-sec-archive
3.3G	c3295826d7c9904c/v5.3-sec-overlayrecent/db
3.3G	c3295826d7c9904c/v5.3-sec-overlayrecent
172K	c3295826d7c9904c/v5.3-sec-earlymerge/state
176K	c3295826d7c9904c/v5.3-sec-earlymerge
4.0K  	c3295826d7c9904c/snapshot
3.3G	c3295826d7c9904c/

**~/.local/share/io.parity.ethereum$ du -h 906a34e69aec8c0d/**
4.0K	        906a34e69aec8c0d/

**~/.local/share/io.parity.ethereum/chains/ethereum/db$ du -h 906a34e69aec8c0d/**
430M	906a34e69aec8c0d/overlayrecent/db/blooms
4.0K	        906a34e69aec8c0d/overlayrecent/db/trace_blooms
4.9G	906a34e69aec8c0d/overlayrecent/db
4.9G	906a34e69aec8c0d/overlayrecent
2.3G	906a34e69aec8c0d/snapshot/current
2.3G	906a34e69aec8c0d/snapshot
7.1G	        906a34e69aec8c0d/

**Comment by 5chdn** [comment]
What is `c3295826d7c9904c/v5.3-sec`*? That's not ethereum

**Comment by debris** [comment]
> What is `c3295826d7c9904c/v5.3-sec`*? That's not ethereum

I'm not sure what that is, but it may be the leftover of some really really old parity version (~2016?) which was synced with some other network than ethereum. It is not needed.

Don't delete anything else
