### ISSUE TITLE
Deduplicate smallvec dependency

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-ethereum#9558]
Currently we have several versions of the same (transitive) dependency, e.g.:
```text
smallvec v0.2.1
smallvec v0.4.5
smallvec v0.6.5
```
It would be nice to remove duplicates, which in turn will reduce compile time and maybe binary size.
To see the list of dependencies, run: `cargo tree --no-indent | sort | rg -v "\(\*\)$" | uniq`

**Comment by debris** [comment]
I don't think we should have a generic issue for **all** duplicate dependencies in parity. It should be a policy to avoid them, but with so many of them, the duplication is sometimes inevitable

**Comment by ordian** [comment]
closed by #9657
