### ISSUE TITLE
Parity consuming too much CPU

### ISSUE THREAD

**Issue by 0x-genesys** [paritytech/parity-ethereum#9565]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
- **Operating system**:   Linux
- **Installation**: built from source
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**:  yes

Issue 

TL;DR 
Parity consuming entire CPU on dual core machine. Load Average is through the roof.

I tried reducing --max-peers from 250 to 30 and --min-peers from 50 to 20 but without any use.

Originally posted at StackOverflow:
https://ethereum.stackexchange.com/questions/58785/parity-consuming-most-of-my-cpu-resources

Screens of parity config & sever status:

![screen shot 2018-09-15 at 10 34 36 am](https://user-images.githubusercontent.com/40688233/45584214-50f82600-b8ed-11e8-924f-fc360d6ed020.png)
![screen shot 2018-09-15 at 10 33 32 am](https://user-images.githubusercontent.com/40688233/45584215-50f82600-b8ed-11e8-8e1b-2150fcd9f0c8.png)
![screen shot 2018-09-15 at 10 32 33 am](https://user-images.githubusercontent.com/40688233/45584216-5190bc80-b8ed-11e8-8ef5-dbd41f87caf3.png)
![screen shot 2018-09-15 at 10 31 41 am](https://user-images.githubusercontent.com/40688233/45584217-5190bc80-b8ed-11e8-9c36-973adaca80ae.png)
![screen shot 2018-09-15 at 10 31 30 am](https://user-images.githubusercontent.com/40688233/45584218-5190bc80-b8ed-11e8-8067-e7475be7d48e.png)

**Comment by eosclassicteam** [comment]
@0x-genesys It is good to have more cpu usage look at EOS they can handle only single thread of CPU lol

**Comment by Tbaut** [comment]
It looks like your RAM is also well used 5.5/8GB.
Did this happen while syncing?
What happens with this node? Are you using to broadcast RPCs? you have specified 50 RPC threads, if you are sending a lot of TXs and signing them for instance, I wouldn't be surprised to see the CPU get to high values.

**Comment by 0x-genesys** [comment]
I removed rpc threads (default is 4) and CPU usage came down. I did this after reading [here](https://wiki.parity.io/Configuring-Parity-Ethereum) 

>  --jsonrpc-threads=[THREADS]
>         Turn on additional processing threads in all HTTP JSON
>         -RPC servers. Setting this to non-zero value allows
>         parallel execution of cpu-heavy queries. (default: 4)


Thanks @Tbaut for your answer. I am not signing or broadcasting any transactions through parity. Just collecting all erc20 and regular tx in local dbs.

New command looks like:

`nohup parity --warp --no-serve-light --max-peers 10 --snapshot-peers 5 --min-peers 5  --mode active --db-compaction ssd  --base-path=/data/ethereum/parity-data --db-path=/data/ethereum/parity-db --jsonrpc-server-threads=10 --geth --jsonrpc-hosts all  --jsonrpc-port 8545 -lsync,tpc=debug --jsonrpc-interface all --cache-size 4096 --tracing off  --pruning fast --fat-db off --no-hardware-wallets --ws-interface all > /data/ethereum/nohup.out 2>&1 &`


Im not sure what jsonrpc-threads are though.

do you suggest pulling down --jsonrpc-server-threads as well? I have one client listening to the 8546 web socket port.

**Comment by Tbaut** [comment]
You might find [this comment](https://github.com/paritytech/parity-ethereum/issues/9260#issuecomment-409529859) useful. I'd definitely not set those flags to anything that is not default if you're not sure about what they do.
`--warp`, `--tracing off`, `--pruning fast`, `--fat-db off` are the default values and therefore not needed.

**Comment by 0x-genesys** [comment]
I do know these flags. Yes, they are the default behaviour also.

I read your comment. I can further tune them down since I am concerned with listening on 8546 socket for mined txs and not with http requests yet. extremely helpful, thank you.
