### ISSUE TITLE
ECONNRESET after sending many requests to a node

### ISSUE THREAD

**Issue by uluhonolulu** [paritytech/parity-ethereum#9573]
- **Parity Ethereum version**: Parity//v1.11.10-stable-31720e6-20180830/x86_64-linux-gnu/rustc1.28.0
- **Operating system**: Ubuntu
- **Installation**: apt-get
- **Fully synchronized**: yes
- **Network**: private chain
- **Restarted**: yes

I'm synchronizing a private Parity node with a database. I read event logs for a number of past blocks using `token.allEvents`, and then get a transaction receipt for every log entry. Sometimes I have more than 1000 entries, so I'm sending ~1000 GetTransactionReceipt requests to the node. At this point, I start seeing ECONNRESET errors.

Is it a bug or a feature? Is it possible to avoid this problem by changing node parameters, or should I just make the requests go out slower?

P.S. I'm running it in the geth compatibility mode.
P.P.S. I'm connecting to the node from my NodeJS app through an SSH tunnel.

**Comment by Tbaut** [comment]
Can you post here the kind of error you see?
What flags do you use to launch Parity Ehtereum?

**Comment by uluhonolulu** [comment]
> Can you post here the kind of error you see?

```
Error: read ECONNRESET
code: "ECONNRESET"
errno: "ECONNRESET"
message: "read ECONNRESET"
stack: "Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)"
syscall: "read"
```

Here are my flags:
```
--chain /home/parity/chainSpec.json --reserved-peers /home/parity/reserved-peers.txt --jsonrpc-apis=all --jsonrpc-hosts=all --ws-apis=all --ws-hosts=all --ws-origins=all --no-persistent-txqueue --force-sealing --geth
```

**Comment by uluhonolulu** [comment]
@Tbaut the parity process' logs don't show anything -- just mined blocks and transactions.

**Comment by uluhonolulu** [comment]
@Tbaut one thing I noticed is that the errors always start when the number of simultaneous requests reaches 757. Is there a connection number limit? Is it possible to change it?

**Comment by Tbaut** [comment]
If I follow you correctly, you're sending these request to the node right over WebSockets right?
Could you try increasing the amount of rpc threads with `--jsonrpc-threads 8` for instance? There is also `--ws-max-connections` that is set to 100 b default, but you are not opening several connection are you?

**Comment by uluhonolulu** [comment]
@Tbaut No, I don't use WebSockets. I'm just calling web3.eth.GetTransactionReceipt, or submit transactions through web3, but at the end, it's just plain old RPC requests.

Increasing the number of threads made the connection limit go up to 1019.

**Comment by joshua-mir** [comment]
@uluhonolulu a little bit late here, but "handling many near-simultaneous requests" is more effectively improved by using the 

```
    --jsonrpc-server-threads=[NUM]
        Enables multiple threads handling incoming connections
        for HTTP JSON-RPC server.
```

flag.

As it stands right now, if you have more than --jsonrpc-server-threads requests that are processing, and you make another one, things will start going funny. `--jsonrpc-threads` can improve the processing speed of many simultaneous connections, but it's not really useful if it's set higher than server-threads.

**Comment by uluhonolulu** [comment]
@joshua-mir thanks, I've already discovered that this parameter helps. However, I've been told that it doesn't make sense to make it bigger than the number of cores (we have 2). 

Closing this since I doubt we'll be seeing anything near 1000 simultaneous users in the nearest future.
