### ISSUE TITLE
Parity doesn't use more than 4 cores of CPU

### ISSUE THREAD

**Issue by luchenyuxx** [paritytech/parity-ethereum#9575]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 1.11.7
- **Operating system**: Linux
- **Installation**: one-line installer / built from source
- **Fully synchronized**: yes
- **Network**: ethereum / ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When parity is under heavy load (huge RPC requests), it never uses more than 4 cores of CPU. I tried to change the `cpu_pool` in `run.rs` to `let cpu_pool = CpuPool::new_num_cpus();`, but it doesn't help.

**Comment by joshua-mir** [comment]
Answered on gitter, let me know if `--jsonrpc-threads=[THREADS]` worked for you.

**Comment by luchenyuxx** [comment]
Thank you @joshua-mir, it works!
Set `processing_threads = [THREADS]` in config file also works!
