### ISSUE TITLE
Propagate new blocks after verifying PoW but without waiting for them to be imported

### ISSUE THREAD

**Issue by AlexeyAkhunov** [paritytech/parity-ethereum#9576]
- **Parity Ethereum version**: all versions
- **Operating system**: all operating systems
- **Network**: ethereum / ropsten

Go-etherum currently propagates new blocks straight after it checks that Proof Of Work is valid. This makes block propagation speed independent of how fast the clients are able to process them fully. Current version of Parity imports blocks (which includes executing all transactions, computing the new state root, and committing the new state) before it propagates them. This issue requests the change so that Parity also propagates after PoW check.

Propagating after PoW check does not present DoS attack vector, because producing a block with valid PoW is quite expensive, so they cannot be created in large enough quantities to enable such an attack. Miners will have to properly import the blocks before building on top of them, therefore, this change will not lead to invalid block branches growing.

**Comment by ppratscher** [comment]
Interesting, I was under the impression this optimization has already been implemented by Parity? At least thats what the devs told me some time ago when inquiring about that specific optimization.
