### ISSUE TITLE
PIP Request:Block_Body Documentation has Outputs Swapped

### ISSUE THREAD

**Issue by EBGToo** [paritytech/parity-ethereum#9579]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.1.0-nightly-3ecf16a49-20180713/x86_64-macos/rustc1.27.1
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: ??

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

The PIP documentation ([PIP](https://wiki.parity.io/The-Parity-Light-Protocol-(PIP))) shows
```
// Request for a block's transactions
Request::BlockBody {
    ID: 4
    Inputs:
        Loose(H256) // block hash
    Outputs:
        [Header] // uncles
        [Transaction] // txs
}
```
The RLP outputs provided 'on the wire' has the transactions first, followed by the uncles.  

Additionally, the PIP documentation for PIPv1 messages, such as
`Request: [+0x02, req_id: U, [req_1, req_2, …]]`
is formatted in a misleading manner and inconsistent with the P2P documentation ([P2P](https://github.com/ethereum/wiki/wiki/ÐΞVp2p-Wire-Protocol)).  For this 'request' example, the initial '[' suggests that the request should be an RLP list of three elements.  But, that fails to parse and Parity rejects the peer.  Like the P2P documentation a better format is:
`Request: +0x02 [ req_id: U, [req_1, req_2, …]]`

**Comment by EBGToo** [comment]
FYI, here is a low-level parsing of the RLP received:
```
ETH: RECV: L  3: [
ETH: RECV:   I  1: 0x05
ETH: RECV:   I  5: 0x0617a2ab38    // credits
ETH: RECV:   L 27: [
ETH: RECV:     L  2: [
ETH: RECV:       I  1: 0x04    // bodies
ETH: RECV:       L  2: [
ETH: RECV:         L  3: [      // 3 transactions
ETH: RECV:           L  9: [
ETH: RECV:             I  1: 0x14
ETH: RECV:             I  5: 0x0ba43b7400
ETH: RECV:             I  3: 0x01d8a8
ETH: RECV:             I 20: 0x8975dbc1b8f25ec994815626d070899dda896511
ETH: RECV:             I  8: 0x29a2241af62c0000
ETH: RECV:             I  0: 0x
ETH: RECV:             I  1: 0x1c
ETH: RECV:             I 32: 0xa7613602b6225046d7c5560d4ee4f5be7cfbf1607618dc160fbfdf2554e9584a
ETH: RECV:             I 32: 0x4efc7fe0a3a8d40e0b719855f6d1150f015359dd9ed3681bab3ef18afa344aa1
ETH: RECV:           ]
ETH: RECV:           L  9: [
ETH: RECV:             I  1: 0x9d
ETH: RECV:             I  5: 0x0ba43b7400
ETH: RECV:             I  3: 0x015f90
ETH: RECV:             I 20: 0xe4c59eeaf2bd10bc48a3ef967793f83ef838e3a1
ETH: RECV:             I  0: 0x
ETH: RECV:             I132: 0x106650fe0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
ETH: RECV:             I  1: 0x1c
ETH: RECV:             I 32: 0xd9d025d1e83b1b4db8be84af3989572e851face1350b2aaf3f7243810fce7de7
ETH: RECV:             I 32: 0x78648a99f8399164fa6d40159008cf341179ca0bb3e573e83374bd634573942a
ETH: RECV:           ]
ETH: RECV:           L  9: [
ETH: RECV:             I  2: 0x22ab
ETH: RECV:             I  5: 0x0ba43b7400
ETH: RECV:             I  2: 0xa028
ETH: RECV:             I 20: 0xc8fea4ab769162f6f7eafb8c2bd49734a03c60ef
ETH: RECV:             I  8: 0x44b1eec6162f0000
ETH: RECV:             I  0: 0x
ETH: RECV:             I  1: 0x1c
ETH: RECV:             I 32: 0x6a534f938fd864a6fb60a8439b31d222cc81bbab83bc047d8f0630db6fa08722
ETH: RECV:             I 32: 0x5cc44fa5e4f58bf07c653c8178f88c797bdd0c0978369cd99d8bcba38310bb49
ETH: RECV:           ]
ETH: RECV:         ]
ETH: RECV:         L  0: []
ETH: RECV:       ]
ETH: RECV:     ]
...
```

**Comment by EBGToo** [comment]
And yes, the LES documentation has the identical 'error'.  What is sent on-the-wire is *not* RLP-encoded data; what is sent is "a byte identifier, followed by RLP encoded data".  The P2P documentation shows it properly.

**Comment by rphmeier** [comment]
Yeah, let's update the packet spec to not include the discriminant byte directly.

**Comment by joshua-mir** [comment]
I'll close this issue here, if you have any other input @EBGToo I'd suggest making an issue on the [wiki's repo](https://github.com/paritytech/wiki)
