### ISSUE TITLE
eth_getTransactionReceipt always return status null for Ethereum Classic chain

### ISSUE THREAD

**Issue by lsls01** [paritytech/parity-ethereum#9606]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.6
- **Operating system**: Linux
- **Installation**: snap insatll parity
- **Fully synchronized**: yes
- **Network**: ethereum classic
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Every time when I call get transaction receipt rpc, I always get "null", but when I execute with ETC geth, it will return '0x1' when succeed.
```
curl --data '{"method":"eth_getTransactionReceipt","params":["0xf36c91f675359f75c7078090374dab6dd6132416a8c0b0cae27940b844206d7d"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
Parity response:
```
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": "0xa73768c1222938d68a84552fb51163642bd432cc705dad5dbc61b2fe3511de43",
        "blockNumber": "0x649ae3",
        "contractAddress": null,
        "cumulativeGasUsed": "0xcec98",
        "from": "0x50d2eedb5d786de86a6cd0d304ed480e4607652a",
        "gasUsed": "0x5208",
        "logs": [],
        "logsBloom": "0x……0",
        "root": "0xd712b30104a4a2c56c4eaea5e62b89b8e66dfdd70e11668954f4bd6edcf489c5",
        "status": ** null ** ,
        "to": "0x63cefbcdcb51457c3648c84e56c45d31c6532a23",
        "transactionHash": "0xf36c91f675359f75c7078090374dab6dd6132416a8c0b0cae27940b844206d7d",
        "transactionIndex": "0xa"
    },
    "id": 1
}
```
ETC geth response:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0xa73768c1222938d68a84552fb51163642bd432cc705dad5dbc61b2fe3511de43",
        "blockNumber": "0x649ae3",
        "contractAddress": null,
        "cumulativeGasUsed": "0xcec98",
        "from": "0x50d2eedb5d786de86a6cd0d304ed480e4607652a",
        "gasUsed": "0x5208",
        "logs": [],
        "root": "d712b30104a4a2c56c4eaea5e62b89b8e66dfdd70e11668954f4bd6edcf489c5",
        "status": "**0x1**",
        "to": "0x63cefbcdcb51457c3648c84e56c45d31c6532a23",
        "transactionHash": "0xf36c91f675359f75c7078090374dab6dd6132416a8c0b0cae27940b844206d7d",
        "transactionIndex": "0xa"
    }
}
```

**Comment by Tbaut** [comment]
Interesting. 
It's because the [chain spec](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/classic.json) doesn't contain eip658Transition part of the Byzantium hard fork.

I wonder how you get it on geth though. @sorpaas any idea?

**Comment by sorpaas** [comment]
@Tbaut geth-etc contained an extra storage just for the `status` field compatibility. That's not a trivial change, though: https://github.com/ethereumproject/go-ethereum/pull/634

I think on this issue, it may be safe to just wait for the next ETC hard fork (which will include eip658 anyway).

**Comment by Tbaut** [comment]
Thanks. I think we got our answer. I'll close as the change required is part of the next HF.
