### ISSUE TITLE
How can I start synchronization from the specified block?

### ISSUE THREAD

**Issue by jin10086** [paritytech/parity-ethereum#9617]
I want to get synchronized data, including internal transfers.
But all are synchronized, the data is too big.
So I want to delete the sync block after I get the data.
thanks

**Comment by Tbaut** [comment]
You can't unfortunately right now.
You are probably looking for a solution similar to https://github.com/paritytech/parity-ethereum/issues/9541 or https://github.com/paritytech/parity-ethereum/issues/8221
I'll close as I think it's a duplicate.
