### ISSUE TITLE
Ancient blocks are not downloaded, stuck at #57

### ISSUE THREAD

**Issue by alexdupre** [paritytech/parity-ethereum#9618]
- **Parity Ethereum version**: 2.0.6
- **Operating system**: FreeBSD
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum mainnet

**Actual behavior**

The client correctly downloads the snapshot and sync until the most recent block, but ancient blocks are not downloaded correctly and are stuck at block number 57, even after waiting many hours and after restarting the client:

```
% http http://localhost:8545/ jsonrpc=2.0 id:=1 method=parity_chainStatus params:='[]'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 21 Sep 2018 07:36:26 GMT
Transfer-Encoding: chunked

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "blockGap": [
            "0x3a",
            "0x60e4b1"
        ]
    }
}
```

Log file: [parity-sync.txt](https://github.com/paritytech/parity-ethereum/files/2404364/parity-sync.txt)

**Expected behavior**

Ancient blocks download should run.

**Steps to reproduce**

Run the client with default configuration (warp sync).

**Comment by joshua-mir** [comment]
Hey, you may want to follow https://github.com/paritytech/parity-ethereum/issues/9306

Closing this issue as it's a duplicate.
