### ISSUE TITLE
Refactor hardware-wallet EventHandler to only use 1 thread 

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-ethereum#9622]
The [hardware wallet manager](https://github.com/paritytech/parity-ethereum/tree/master/hw) is handling usb events in two different threads for Trezor and Ledger.
This should be replaced by using only one thread for less memory usage!

**Comment by Tbaut** [comment]
Do we still want to do this with Parity UI not actively maintained and the idea to have proxy RPC (handling keys outside of parity) coming some day?

**Comment by niklasad1** [comment]
That is a good question but as long we link the hardware-wallet code into the final binary this issue is valid (as we still do). However, I'm not the right person but as long parity manages keys etc I think we should keep it and other people can use build a UI on top of it?

However, it could be good valid the create another issue and to discuss whether we should keep the support for the hardware wallets or not? Or maybe disable them by default at least.

**Comment by 5chdn** [comment]
Should be removed. ref #9997
