### ISSUE TITLE
Light client hangs after some time of work

### ISSUE THREAD

**Issue by pdgsmf79** [paritytech/parity-ethereum#9627]
Operating System - Debian 9.5 Linux
Installation - Tried *.deb file from website and precompiled binary from github 
Fully syncronized - yes
Network - ropsten and mainnet

Parity stops responding after running a while. Neither it updates blockchain, nor responds to RPC calls via HTTP or WS
Every time it hangs, i cannot stop it by CTRL+C combination and have to kill it.
It happens without any schedule. Can happen right after start and can happen after a day of running.
I have tried different versions, starting from 1.10 and all of them have the same issue.
Also tried on other machines under Ubuntu 18.04. All the same.
I start parity with the following command:

parity --chain=ropsten --light --jsonrpc-interface=all --jsonrpc-hosts=all

With such an issue I cannot rely on parity as a node software, since my project require high availability.

**Comment by Tbaut** [comment]
Can you please share the logs and trace with `-l rpc` for instance?
This might be related to other issues such as: https://github.com/paritytech/parity-ethereum/issues/9551

Do you have the same problem on Kovan ? (Ropsten isnt't the best choice of testnet due to the lack of peers)

**Comment by Tbaut** [comment]
Closing as stale

**Comment by travelvee** [comment]
Anyway light client hangs. No suspicious data in logs, everything just as usual
Tried on two different PCs, one under Debian 9 and another under Ubuntu 18.04
Tried different versions. Tried both Ropsten and Mainnet
I run parity with command:
 parity --light -l sync=debug,rpc=trace

Still no ideas how to fix it?

**Comment by travelvee** [comment]
Also tried yesterday on another VPS, 16GB ram, 8 CPU, 250GB SSD
without --light key, just ./parity. It hung after 10 minutes of running.

**Comment by niklasad1** [comment]
@travelvee 

Can you provide the following:

1. How many peers do you have? (Can be retrieved either from the [net_peercount](https://wiki.parity.io/JSONRPC-net-module#net_peercount) RPC or the import log)
2. Are you performing any RPC's via the JSON-RPC interface? (If you doing requests often the peers might disconnect you or you might run out of credits)

**Comment by travelvee** [comment]
10 net peers. 
Hangs with or without rpc requests - doesn't matter. Last one hung when I just started parity for the first time to download blockchain.

**Comment by travelvee** [comment]
Well looks like this should be considered a feature of parity, rather than a bug. Unfortunately will have to move back to geth, which looks much more stable. Hope in newer versions this will be fixed.
