### ISSUE TITLE
windows ci jobs randomly failing

### ISSUE THREAD

**Issue by debris** [paritytech/parity-ethereum#9640]
job: https://gitlab.parity.io/parity/parity-ethereum/-/jobs/100543
pr: https://github.com/paritytech/parity-ethereum/pull/9639

```
Running with gitlab-runner 11.2.0 (35e8515d)
  on bellatrix effe9fc5
Using Shell executor...
Running on BELLATRIX...
Cloning repository...
fatal: destination path 'c:/r/builds/effe9fc5/0/parity/parity-ethereum' already exists and is not an empty directory.
ERROR: Job failed: exit status 128
```

**Comment by debris** [comment]
cc @paritytech/ci

**Comment by gabreal** [comment]
Thanks for reporting. Devops will work on this on devops issue tracker:
https://github.com/paritytech/devops/issues/215

**Comment by debris** [comment]
thanks! I'll close this issue
