### ISSUE TITLE
Cannot install via binaries - no relevant file extension?

### ISSUE THREAD

**Issue by calfer** [paritytech/parity-ethereum#9642]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.6
- **Operating system**: MacOS
- **Installation**: binaries
- **Fully synchronized**: 
- **Network**: 
- **Restarted**: 

Historically, I have downloaded the desired binary installer from github when updating Parity Ethereum.  However, with the latest binaries being offered I see no file extension for the MacOS installer.  How do I download and install Parity Ethereum 2.0.6 without building from source?

The wiki tells me to:

•Windows and Mac
 Download the Binary and double click on it.

MacOS does not know what to do with a file called "parity".  If I am missing something here, and it seems I am, please tell me what it is.

**Comment by 5chdn** [comment]
Either use homebrew https://github.com/paritytech/homebrew-paritytech/

```
brew tap paritytech/paritytech
brew install parity --devel
```

Or the one-line installer https://wiki.parity.io/Setup#one-line-binary-installer

```
$ bash <(curl https://get.parity.io -L)
```
