### ISSUE TITLE
[Private transactions] Private send: the returned transactionHash is not correct / bad instruction

### ISSUE THREAD

**Issue by ngyam** [paritytech/parity-ethereum#9643]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.0-unstable-93e1040-20180921/x86_64-linux-gnu/rustc1.29.0
- **Operating system**: Linux
- **Installation**: built from source with secretstore feature
- **Fully synchronized**:  yes
- **Network**: Tobalaba
- **Restarted**: yes

**actual**

I was doing the private transactions tutorial on Tobalaba, and didn't succeed with [step 4: modifying the value of x]((https://wiki.parity.io/Private-Transactions-Tutorial-4.html)).

at Step 3: The private contract was successfully deployed and showed up on etherscan: https://tobalaba.etherscan.com/tx/0x81d45da7427b1ffee8d3660911e551c0e46cbbf5b17495150a7a65cac2284302

at Step 4: The private send returned the following:

```
{ contractAddress: '0xaf8cde66b6b3afdc5c435684c09c72d542668334',
  status: 0,
  transactionHash: '0x300ae9a2640388112d326cedabdcd038a92bf9c058fcf30405b300db5c85ced4' }
```
After a while, a failed transaction showed up on etherscan, displaying `Error: Bad instruction`.
https://tobalaba.etherscan.com/tx/0xc0ecd4c6bd2ba94aee7c0711707e8ba6fbb03f9fb9219d2fd728e104e17e728a
https://tobalaba.etherscan.com/address/0xaf8cde66b6b3afdc5c435684c09c72d542668334

This means that the hash returned was not the correct one for the public transaction. It is also a mistery why it got a `Bad Instruction` error.

You can also find the corresponding log here: https://gist.github.com/ngyam/c725cb2ee935adba902cdbd3fae7d3a9

**expected behavior**

Either:
 - The transaction succeeds. Why the Bad Instruction?
 - The correct returned hash by the `private_send` shows up in the blockexplorer: `0x300ae9a2640388112d326cedabdcd038a92bf9c058fcf30405b300db5c85ced4`.

**steps to reproduce**

I made a repo to easily play around with secretstore/private transactions: https://github.com/ngyam/tutorial-secretstore-privatetx 

 0. make sure acl_contracts is none in the config files in `nodes_ss_tobalaba/`
 1.  `./start.sh` in `nodes_ss_tobalaba/` folder  
 2. go to `src/private-tx`:
     1. `node tutorial_part3_deploy.js`
     2. `node tutorial_part4_modify.js`

**Comment by Tbaut** [comment]
@grbIzl can probably help here as well :)

**Comment by grbIzl** [comment]
@ngyam is this issue reproducible on the latest master+ #9999 ?

**Comment by ngyam** [comment]
@grbIzl  Yes it is

**Comment by grbIzl** [comment]
Ok. Got it. I think, that it's a misunderstanding. private_sendTransaction method returns hash of the private transaction, at the same time the resulting public transaction is a different transaction with different hash. You can use new API method from #10056 in order to lookup public transaction hash using private transaction hash.

**Comment by grbIzl** [comment]
From my point of view it's not an issue.

**Comment by ngyam** [comment]
Thanks! If that is the case, it is not an issue indeed
