### ISSUE TITLE
Can't deploy same contract which worked yesterday

### ISSUE THREAD

**Issue by saitam1** [paritytech/parity-ethereum#9645]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**:Parity v1.11.5-20180629 beta
- **Operating system**: Ubuntu 18.04.1
- **Installation**: I think it was  the .deb file
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: no / yes

I am trying to deploy a contract an all I see is this for several minutes:
![parity](https://user-images.githubusercontent.com/23245678/46009617-65dc7280-c0c0-11e8-8ac6-5853fc15229a.png)
The strange thing is that it worked yesterday without problems! Estimated gas is about 700k. In total I have tried it 3 times with 5000000 gas limit and the most expensive gas price. After waiting for several minutes and several restarts I still see this:
![par](https://user-images.githubusercontent.com/23245678/46009664-8c9aa900-c0c0-11e8-9916-93cff75dae05.png)
![par2](https://user-images.githubusercontent.com/23245678/46009675-958b7a80-c0c0-11e8-9838-9d04ee44e629.png)

What can I do? And how to stop the deployment? I guess it will never be done.

**Comment by 5chdn** [comment]
Wait, untill they are mined. Note, 1.11.5 is not supported anymore, please upgrade to 2.1.1.
