### ISSUE TITLE
Doing warp restore on every start?

### ISSUE THREAD

**Issue by NinjaTurtle007** [paritytech/parity-ethereum#9672]
I'm wiht latest parity UI and parity on latest Ubuntu.
I'm starting it by directly starting parity UI (without starting "parity" only in the terminal first, is that the right way?)

and it does warp restore from 0 to 100% every time which takes a while.
Is that expected behaviour?

I remember that in earlier versons I had ot start first only "parity" in the terminal and then start Parity UI for the interface. There was no warp restore everytime back then.

**Comment by joshua-mir** [comment]
Parity UI is unsupported, and the way that it interacts with the client, especially with later verisons, is unpredictable. You should, as you have previously, run parity before you launch the UI to avoid it downloading the latest versions.

**Comment by NinjaTurtle007** [comment]
Parity UI unsupported? Do we have alternative to use with parity then?
