### ISSUE TITLE
How to delete states trash history 

### ISSUE THREAD

**Issue by lyh168** [paritytech/parity-ethereum#9674]
Hi  had some question, if i set fast sync, now my chaindata(include states)  is may 40G, but 1 year later, my chaindata may be large again, because the states trash history have more again, have some Solutions to  delete states trash history in operation? thks

**Comment by 5chdn** [comment]
Parity does not have fast sync, we only have warp sync and a fast _pruning_ mode.

The default fast pruning mode continuously deletes historical states, so what you see on your disk is the actual state and the block chain data.

**Comment by lyh168** [comment]
thank you , have some fast pruning mode detailed introduction or this function related module in source code?
