### ISSUE TITLE
shh jsonrpc methods not accessible to parity_subscribe 

### ISSUE THREAD

**Issue by joshua-mir** [paritytech/parity-ethereum#9675]
- **Parity Ethereum version**: 2.1.1
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: n/a
- **Network**: dev 
- **Restarted**: yes

When trying to use parity_subscribe to subscribe to whisper/shh related methods, we receive a "Method not found" error.

```
~> wscat -c localhost:8546
connected (press CTRL+C to quit)
> {"method":"parity_subscribe","params":["shh_getFilterMessages",["0xe986ce6c7c33bbadf01b872c27a4c019457763cdee915ac16baf66b6b2b001af"]],"id":1,"jsonrpc":"2.0"}
< {"jsonrpc":"2.0","result":"0x32921aece9b80f9a","id":1}
< {"jsonrpc":"2.0","method":"parity_subscription","params":{"error":{"code":-32601,"message":"Method not found"},"subscription":"0x32921aece9b80f9a"}}
>
```

The method gives the expected response when called manually.

```
~> curl --data '{"method":"shh_getFilterMessages","params":["0xe986ce6c7c33bbadf01b872c27a4c019457763cdee915ac16baf66b6b2b001af"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":[],"id":1}
```

This seems to have been an issue in the past in https://github.com/paritytech/parity-ethereum/pull/6161

**Comment by Tbaut** [comment]
It looks like it's not supported, did you try out with [shh_subscribe](https://wiki.parity.io/JSONRPC-shh-module#shh_subscribe)?

**Comment by joshua-mir** [comment]
I see what you mean, that does appear to work... I'll make sure I know how this works before updating docs today (missing examples).

issue still stands that parity_subscribe should have access to shh rpc methods, right?

**Comment by joshua-mir** [comment]
Not an issue; I just didn't expose the api's in my config :sweat_smile:

**Comment by emizzle** [comment]
@joshua-mir - I'm having the same issue but parity with all WS APIs enabled: 
```
parity --chain=dev --network-id=17 --base-path=.embark/development/datadir --password=.embark/development/datadir/devPassword --port=30303 --jsonrpc-port=8545 --jsonrpc-interface=local --jsonrpc-cors=*,http://localhost:8000,http://localhost:8080,http://embark --jsonrpc-hosts=all --ws-port=8546 --ws-interface=local --ws-origins=all --ws-hosts=all --no-discovery --max-peers=0 --whisper --jsonrpc-apis=web3,eth,pubsub,net,parity,private,parity_pubsub,traces,rpc,shh,shh_pubsub --ws-apis=web3,eth,pubsub,net,parity,private,parity_pubsub,traces,rpc,shh,shh_pubsub,personal --unlock=0x00a329c0648769a73afac7f9381e08fb43dbea72 --gas-floor-target=8000000
```

Additionally, the APIs for websockets are enabled in my config:
```
[websockets]
# Allows connecting from Origin 'parity://*,chrome-extension://*,moz-extension://*,,'.
origins = ["parity://*", "chrome-extension://*", "moz-extension://*", ""]
# Allow connections only using specified addresses.
hosts = ["*"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "private", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts"]
```
Which APIs did you enable to get this to work? And did you end up using `shh_subscribe` or `parity_subscribe` with `getFilterMessages`?

Which APIs did you enable
