### ISSUE TITLE
Parity Installation on Windows does not work

### ISSUE THREAD

**Issue by unheal1337** [paritytech/parity-ethereum#9676]
- **Parity Ethereum version**: 2.1.1

- **Operating system**: Windows / MacOS / Linux
Windows 10

- **Installation**: homebrew / one-line installer / built from source
Windows Installer

Double clicking just opens a cmd window. The windows closes after some seconds and nothing happens

**Comment by joshua-mir** [comment]
Hey, please try opening a cmd/powershell manually, and running parity.exe from there. You'll be able to see the output that is closing the executable.

you may find parity is already running, find it in your task manager and close parity.exe if it is already running.

**Comment by unheal1337** [comment]
okay thank you very much 👍
