### ISSUE TITLE
Parity Ethereum does not show version on Ethstats

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-ethereum#9685]
- **Parity Ethereum version**: 2.0.4 ... 2.2.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum, ropsten, and kovan 
- **Restarted**: yes

Something changed around version 2.0.4; all versions after are not displayed on stats.parity.io anymore.

Someone please debug this and compare with a 1.11.11 node ideally which still displays the version.

**Comment by veox** [comment]
There are nodes on https://ethstats.net/ that show:

    Parity-Ethereum//v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0

I have built the same commit locally, with version reported as

    Parity-Ethereum/v2.0.6-unstable-549e202fc-20180919/x86_64-linux-gnu/rustc1.28.0

and its version is not displayed (server name `veox-parity` on `ethstats`).

**Comment by 5chdn** [comment]
question is, is this a parity issue or ethstats?

**Comment by veox** [comment]
@5chdn A bit of both.

`e-n-i-a` is notoriously clumsy on handling unexpected responses.

The relevant code is in `getInfo()`:

https://github.com/cubedro/eth-net-intelligence-api/blob/bdc192ebb76fc9964ef0da83ee88bc86ba69c052/lib/node.js#L338-L349

`e-n-i-a` gets stuck forever trying to get `coinbase` when it doesn't exist (e.g. node has no keys local to it).

Possibly related: PR #9383.

**Comment by veox** [comment]
Short-circuiting line 339 (in `node.js`, link above) with an account address works around the issue.

-----

Creating an account using `parity account new` so that `eth.coinbase` returns something _might_ work; but it doesn't for me: the following query:

``` sh
curl -X POST -H "Content-type: application/json" --data '{"jsonrpc":"2.0","method":"eth_coinbase","params":[],"id":1337}' localhost:8545
```

returns:

```
{"jsonrpc":"2.0","error":{"code":-32023,"message":"No accounts were found","data":"\"\""},"id":1337}
```

 :/

**Comment by 5chdn** [comment]
Aaaaaah, that makes sense. Too bad e-n-i-a does not have an owner. Would be easy to fix this on dashboard server side.

**Comment by CKInvest** [comment]
@5chdn Kannst du mir auch helfen?

Parity-Ethereum v2.2.0-20181102 beta
Parity UI Version 0.3.4 (0.3.4)

Mit dem smart contract von uns würde ich gerne über den Ledger (mintdelegate) eine Funktion (bulkmint) ausführen. Nach Eingabe der ERC-20 Wallets und der dazugehörigen Anzahl an Token/Wallet kommt das Feld pending. Allerdings wird nicht nach meinem Ledger Nano S um allowence gefragt oder um Bestätigung der Trx. Ich weiß allerdings nicht, wo ich den Local Key finde und wie das ganze genau zusammenhängt.

**Comment by 5chdn** [comment]
Fixed in https://github.com/goerli/netstats-client & https://github.com/goerli/netstats-server
