### ISSUE TITLE
Parity do not send local transactions in block / pending in Kovan

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity-ethereum#9691]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.0.1-beta
- **Operating system**: Windows / Linux
- **Installation**: one-line installer 
- **Fully synchronized**:  yes
- **Network**: kovan 
- **Restarted**: yes

Hello, parity do not send local transactions in pending... I see this picture about 2 hours without any changes...
https://prnt.sc/l1lvfi

Parity args:
`--chain kovan --tx-queue-size 256000 --tx-queue-mem-limit 0 --tracing off --min-peers 20 --max-peers 30 --no-ancient-blocks --no-serve-light --pruning fast --db-compaction ssd --jsonrpc-apis all --ws-apis all --ws-interface local --jsonrpc-interface local --ui-interface local --cache-size 1024`

**Comment by famfamfam** [comment]
hm, I try to call token contract via rpc personal_sendTransaction and all transactions was been sent to pending and confirmed...

**Comment by joshua-mir** [comment]
@famfamfam your version of parity was quite out of date when this issue was made; can you confirm this still applies to recent versions of parity? (it is important to note that parity UI will not work well with recent versions of parity)

**Comment by famfamfam** [comment]
@joshua-mir no, I can try to upgrade. But now it works fine (after rpc request)...
