### ISSUE TITLE
running parity from different networks 

### ISSUE THREAD

**Issue by panosVeran** [paritytech/parity-ethereum#9695]
- **Parity Ethereum version**: v1.11.8
- **Operating system**: Windows
- **Installation**: installer
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

hey guys, i have a slight problem, when Im running parity from home everything works fine but when i am at company's desk i cant connect to the any peers.

![parityconnectivity1](https://user-images.githubusercontent.com/13367103/46419106-1122a280-c725-11e8-82b2-3408c6a006d7.PNG)
subsequently:
 
![parityconnectivity2](https://user-images.githubusercontent.com/13367103/46419233-5e067900-c725-11e8-802e-bdb4f65c911d.PNG)

I get that is some sort of network issue, blocking something what is the practical way to do? any suggestions? and how to configure this?

thanks in advance

**Comment by joshua-mir** [comment]
You will likely need to talk to your company's network admins about creating firewall rules for parity.

You aren't running on docker, but this link shows the ports that parity uses by default,
https://wiki.parity.io/Docker.html#open-ports 

of which 30303 (including udp traffic for peer discovery) is critical for connecting to the blockchain.

**Comment by panosVeran** [comment]
hey thanks, on that note i did try to get our the firewall which although turned off looks like this:

![windfirewall1](https://user-images.githubusercontent.com/13367103/46533516-cd52a900-c89c-11e8-938c-e9388a911c5f.PNG)

so because it looks like there are inbound rules for TCP port 30303 but not for UDP port 30303 i added one:

![winfirewall2](https://user-images.githubusercontent.com/13367103/46533571-fa9f5700-c89c-11e8-8987-6718a6e4eab3.PNG)

still no luck. I guess maybe being behind the corporate firewall causes the issue so it need to be opened (the rule) from there? instead of just my machine.

**Comment by joshua-mir** [comment]
Yes definitely. If you have a network wide firewall, disabling the one on your machine wont help out much, which is why I suggested talking to your admins.

**Comment by joshua-mir** [comment]
Is this still an issue @panosVeran ? Let me know and I will reopen.
