### ISSUE TITLE
[Private transactions] Cannot deploy private smart contract

### ISSUE THREAD

**Issue by julienbourdette** [paritytech/parity-ethereum#9708]
Parity Ethereum version: Parity-Ethereum
Operating system: Linux
Installation: built from source with secretstore feature
Fully synchronized: yes
Network: Tobalaba
Restarted: yes

**actual** 
I'm tested the private transactions tutorial https://github.com/ngyam/tutorial-secretstore-privatetx
on tobalaba_local 
All steps on private transactions works well, but when i change the smart contract sample (Test.sol) by a new one, i cannot deploy the contracts with the error:

```
UnhandledPromiseRejectionWarning: Error: Returned error: Transaction cost exceeds current gas limit. Limit: 8012172, got: 10200000. Try decreasing supplied gas.
```

But the deployment of this contract works well in public mode (and cost half time gas)
Imported #133 0xab28…9de3 (1 txs, 0.44 Mgas, 1 ms, 2.12 KiB)

Code of the smart contract that cause the issue.

```solidity
pragma solidity ^0.4.24;

contract Consumption {

   mapping (address => mapping (bytes32 => Data))  consumption;
   mapping (address => mapping (address => bool))  authorization;

   struct Data {
       uint[] timestamp;
       uint256[] value;
   }

   function consume(uint256 _consumption, uint _timestamp,  string _date) public {
       bytes32 hash = keccak256(_date);
       consumption[msg.sender][hash].timestamp.push(_timestamp);
       consumption[msg.sender][hash].value.push(_consumption);
   }

   function getConsumption(address _consumptionAdress, string _date) public returns (uint[],uint256[]) {
       require(authorization[_consumptionAdress][msg.sender]);
       bytes32 hash = keccak256(_date);
       return (consumption[_consumptionAdress][hash].timestamp,consumption[_consumptionAdress][hash].value);
   }

   function authorize(address _address, bool _authorize) public {
       authorization[msg.sender][_address] = _authorize;
   }
```

 **expected behavior** 
Smart contracts can be deployed 

**steps to reproduce** 
Follow the https://github.com/ngyam/tutorial-secretstore-privatetx, by replacing Test.Sol by the code above

**Comment by ngyam** [comment]
I could also reproduce it.
Network: local tobalaba like

```
(node:16565) UnhandledPromiseRejectionWarning: Error: Returned error: Transaction cost exceeds current gas limit. Limit: 8000000, got: 11288000. Try decreasing supplied gas.
```
In the logs:
```
2018-10-05 17:23:30   DEBUG txqueue  [0x0bea5a78ab6272fb6a4908db54c18ed70a81bc4cbace2e865bba36ae17068503] Rejected transaction above gas limit: 11288000 > min(8000000, 115792089237316195423570985008687907853269984665640564039457584007913129639935)
```
Can something be done about the gas cost of private contracts?
This contract doesn't seem to be that complex, so it seems like an uncomfortable limitation.

**Comment by joshua-mir** [comment]
I'm unsure why you're experiencing something different between networks, but it appears that the tutorial attempts to hardcode the gas provided by the transaction:

**Comment by Tbaut** [comment]
This error might indeed be not related to the amount of gas. This is a blanket error (that was fixed in https://github.com/paritytech/parity-ethereum/pull/9615). There must be something weird with the contract itself. If you have a moment to have a look @grbIzl :)

**Comment by ngyam** [comment]
I could deploy it with no issues on the live Tobalaba network:
https://tobalaba.etherscan.com/tx/0x923cc7178246b74a54aed000a64dcdca16eefea37e2bc1da4c56c58e1b95778d
