### ISSUE TITLE
Error(Msg("IO error: While open a file for appending: 

### ISSUE THREAD

**Issue by Duxinghua** [paritytech/parity-ethereum#9714]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v1.11.8-stable-c754a02-20180725
- **Operating system**: Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Thread 'Verifier #3' panicked at 'DB flush failed.: Error(Msg("IO error: While open a file for appending: /home/ethereum/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/5597791.log: Read-only file system"), State { next_error: None, backtrace: None })', libcore/result.rs:945

**Comment by Duxinghua** [comment]
du: cannot access './.local/share/io.parity.ethereum-updates/parity-2.0.6-549e202fc1067ba2ea3d6f7b8f5c1bbe5c7e3372': Input/output error
136M	./.local/share/io.parity.ethereum-updates
127M	./.local/share/io.parity.ethereum/cache
du: cannot access './.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/5392858.sst': Input/output error
du: cannot access './.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/5392859.sst': Input/output error
du: cannot access './.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/5392862.sst': Input/output error

**Comment by joshua-mir** [comment]
@Duxinghua can you reproduce this on an up-to-date stable release? There have been multiple related issues fixed since the release you are using.

**Comment by joshua-mir** [comment]
Please reopen if the issue persists in a recent release
