### ISSUE TITLE
[Private transactions] Public wrapper contract: emit an event on successful private state change with the initiator's address?

### ISSUE THREAD

**Issue by ngyam** [paritytech/parity-ethereum#9719]
Hi all,

Is it possible to add an Event that gets emitted on a state change of the private contract?
Is it possible to know the address who initiated the state change (the caller of private_sendTransaction). What about including the initiator address in such an event?

Might be related to this [other issue](https://github.com/paritytech/parity-ethereum/issues/9641) I already opened.

**Comment by ngyam** [comment]
Neat, can you show me an example to do that? The examples are shown with [private_composeDeploymentTransaction](https://wiki.parity.io/JSONRPC-private-module#private_composeDeploymentTransaction), and I haven't seen option to add a custom public contract data as a parameter. How do I compose with a custom public contract?

**Comment by joshua-mir** [comment]
Yeah, you wouldn't use composeDeploymentTransaction, you'd have to manually deploy. (this clearly isn't a recommended way to set up a private contract). Let me double check what `initialCode` and `initialState` are set to (they are extracted from the signed transaction that you pass to private_composeDeploymentTransaction).

**Comment by ngyam** [comment]
No worries, then I wait :)
