### ISSUE TITLE
Dev account can not be unlocked on first launch of parity

### ISSUE THREAD

**Issue by berndbohmeier** [paritytech/parity-ethereum#9737]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.0.7-stable
- **Operating system**: Linux
- **Installation**: docker hub
- **Fully synchronized**: yes
- **Network**: dev chain
- **Restarted**: yes

I use the the option `--config dev` to run a chain with dev configuration. This creates the default account `0x00a329c0648769a73afac7f9381e08fb43dbea72`. I try to unlock the account with `--unlock=0x00a329c0648769a73afac7f9381e08fb43dbea72`. Sadly this does not work at the first run and gives the error message: `Account 0x00a3…ea72 not found for the current chain. You can create an account via RPC, UI or parity account new --chain dev --keys-path /home/parity/chaindata/keys.`
If I run it without the unlock option first, and after with the unlock option, it works, so it seems it needs to write the account first to disk. This is annoying as it does not work with a fresh docker image. 

Proposed solution: Make it possible to already unlock the account at the first run.

**Comment by debris** [comment]
> This creates the default account `0x00a329c0648769a73afac7f9381e08fb43dbea72`

Is there any documentation that describes this?

> If I run it without the unlock option first, and after with the unlock option, it works, so it seems it needs to write the account first to disk. This is annoying as it does not work with a fresh docker image.

To be honest, I'm not aware of this feature. It seems more like a bug as `0x00a329c0648769a73afac7f9381e08fb43dbea72` is an account created for an empty seedphrase. @tomusdrw do you know anything about this?

**Comment by berndbohmeier** [comment]
Yes, it is documented here https://wiki.parity.io/Private-development-chain

**Comment by debris** [comment]
Thanks! I believe the problems lies in fact that even though the password is an empty string, we still expect the password to be provided.

> An address containing a lot of Ether (`0x00a329c0648769a73afac7f9381e08fb43dbea72`) has automatically added with a password being an empty string.

I believe this should be clarified in the documentation. And parity should also fix wrong behaviour on the first run.

**Comment by joshua-mir** [comment]
@berndbohmeier for a workaround, you can use a simple config file like

```
# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "dev"

[account]
# From: [0x00a329c0648769a73afac7f9381e08fb43dbea72] you'll be able to send transactions without password.
unlock = ["0x00a329c0648769a73afac7f9381e08fb43dbea72"]
# File at ./empty_pass should contain a single empty line. (password is an empty string)
password = ["./empty_pass"]
```
In order to have the account unlocked on first startup.

**Comment by 5chdn** [comment]
we should not use `0x00a329c0648769a73afac7f9381e08fb43dbea72` on the dev chain. IMHO, we shouldn't use it _anywhere_.

**Comment by joshua-mir** [comment]
is there a way to specify that all accounts should have a balance for a dev chain so we don't need to hardcode an account?

**Comment by tomusdrw** [comment]
@joshua-mir that's not really possible with our current approach - this would produce enormous state trie.

We would have to change the idea of "empty account" being an account with zero balance and zero nonce (or actually `nonce = start nonce`) and add some notion of initial balance as well (i.e. if the account is not in the state trie, then assume it has some `start_balance` instead), which might be quite involved.

@5chdn I think the empty phrase drama is over, and I don't see that much of a reason to not use it (but happy to be convinced differently) - I reckon that any account we define as the "dev" account might somehow be abused on other networks. Perhaps we could special case signing for the dev chain and allow transactions from address `0x0` or sth? Might be quite involved too, though.

**Comment by 5chdn** [comment]
> the empty phrase drama

I'm not talking about the drama here, it just seems that restoring using empty seed/password causes confusion. We could just create a valid phrase and an easy to recognize password and document it properly, IMHO

**Comment by tomusdrw** [comment]
@5chdn I see, makes sense. Although for dev-chain the account is just created automatically, so you don't even have to restore. I agree with the sentiment though, creating a different account with a password would also work.

**Comment by berndbohmeier** [comment]
Just to clarify it. For me I thought this feature is there so that I get an account on the dev chain that I can use right away to play around, run tests, etc. So I would assume that the command `parity --config=dev --unlock=0x00a329c0648769a73afac7f9381e08fb43dbea72 --password=passwordfile`, where the passwordfile contains the empty password, just works, but it does not. I have to run `parity --config=dev` first to create the keyfile, stop parity and rerun then the first command.
