### ISSUE TITLE
[Question] hot can I set up `--geth` option in config.toml

### ISSUE THREAD

**Issue by hiroki-money** [paritytech/parity-ethereum#9765]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum//v2.1.1-beta-cb09330-20180919/x86_64-macos/rustc1.29.0
- **Operating system**: MacOS
- **Installation**: `url https://sh.rustup.rs -sSf | sh`
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I just wander how to configure `--geth` option in `config.toml`. It doesn't describe in [Configuring-Parity-Ethereum](https://wiki.parity.io/Configuring-Parity-Ethereum.html?q=geth)

Thanks.

**Comment by Tbaut** [comment]
I don't think it's possible as this is part of legacy options: https://github.com/paritytech/parity-ethereum/blob/2511bc20e023b3a7c01b8cf985f3461990646a33/parity/cli/mod.rs#L894
