### ISSUE TITLE
Sync fails on Block #1590283 (Parent not found)

### ISSUE THREAD

**Issue by thereapman** [paritytech/parity-ethereum#9766]
- **Parity Ethereum version**: 2.0.5
- **Operating system**: Linux
- **Installation**: official docker
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

**actual**
Parity crashes reproducably at sync of block #1590283 w/o warp sync (due to traces+archived)

**expected**
Parity syncs the chain beyond #1590283

**reproduce**

1. Start parity with `docker run -d --name=parity-mainnet -v /tank/parity-mainnet/v2.0.8:/home/parity/.local/share/ -p 30303:30303 -p 30303:30303/udp -p 8545:8545  parity/parity:v2.0.8 --ws-origins=all --ws-interface=all --pruning=archive --jsonrpc-cors all --tracing on --fat-db on --db-compaction ssd --jsonrpc-apis all --jsonrpc-threads=50 --no-color --jsonrpc-interface=all --no-periodic-snapshot --force-direct`
2. Wait until block #1590283 comes around. 
3. Partiy will crash with the output:

```
2018-10-17 08:25:29 UTC Syncing #1589491 0x47dd…8a60   188.66 blk/s 1210.9 tx/s   42 Mgas/s    392+ 6487 Qed  #1596398   25/25 peers      6 MiB chain   17 MiB db   45 MiB queue   10 MiB sync  RPC:  0 conn,    0 req/s,    0 µs

====================

stack backtrace:
   0:     0x55cc0b10360c - <no info>
   1:     0x55cc0b1033c2 - <no info>
   2:     0x55cc0b103438 - <no info>
   3:     0x55cc0b10223a - <no info>
   4:     0x55cc09baa085 - <no info>
   5:     0x55cc0b163233 - <no info>
   6:     0x55cc0b12b076 - <no info>
   7:     0x55cc0b12a474 - <no info>
   8:     0x55cc0a80f0a5 - <no info>
   9:     0x55cc0a7cbe65 - <no info>
  10:     0x55cc0a4f2e19 - <no info>
  11:     0x55cc0a510bb1 - <no info>
  12:     0x55cc0a4f3a90 - <no info>
  13:     0x55cc0a4fa236 - <no info>
  14:     0x55cc0b18d4a9 - <no info>
  15:     0x55cc0a50b752 - <no info>
  16:     0x55cc0b165cba - <no info>
  17:     0x55cc0b163805 - <no info>
  18:     0x7f19206e86b9 - <no info>
  19:     0x7f192020841c - <no info>
  20:                0x0 - <no info>

Thread 'IO Worker #3' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-10-17 08:25:36 UTC Finishing work, please wait...
2018-10-17 08:25:36 UTC Block import failed for #1590283 (0x9505…ee7c): Parent not found (0xcb85…b1d0)
```

Filesystem is verified ok. a ZFS scrub doesn't reveal any errors.

**Comment by Tbaut** [comment]
This PR should have fixed it https://github.com/paritytech/parity-ethereum/pull/9525
@debris any idea?

**Comment by debris** [comment]
`Parity Ethereum version: 2.0.5`

from: https://github.com/paritytech/parity-ethereum/issues/9630#issuecomment-424050022

> I think it is a duplicate of #9180 . The fix has been backported to beta, but not stable.

**Comment by Tbaut** [comment]
Thanks, I didn't realize it didn't get backported to stable. (from the logs,v2.0.8 is used)
@thereapman please use beta if you can.
