### ISSUE TITLE
parity_nextNonce fails to get reliable nonce

### ISSUE THREAD

**Issue by SantonyChoi** [paritytech/parity-ethereum#9768]
- Parity Ethereum version: 2.0.6
- Operating system: Linux
- Installation: https://releases.parity.io/v2.0.6/x86_64-unknown-linux-gnu/parity
- Fully synchronized: yes
- Network: ethereum
- Restarted: no

## What I did:
I called "parity_nextNonce" rpc call every 5 seconds through http. And then I created, signed and sent my signed raw transactions using "sendRawTransaction". All these are done in one local node that is fully synced.

## Expected behavior: 
I expected I could get a reliable nonce by using "parity_nextNonce" api. 

## Actual:
It behaves well most of the time, but fails roughly once in 100 times, returning the same nonce with the previous transaction.

## Steps to reproduce:
Just repeat creating transactions by using "parity_nextNonce" and sending it. Repeat it more than 100 times.

**Comment by Tbaut** [comment]
For anything that is automated and not punctual, we advise to handle the nonce on the Dapp side. Please keep track of the nonce and increment it yourself, and regularly sync with [`eth_getTransactionCount`](https://wiki.parity.io/JSONRPC-eth-module#eth_gettransactioncount).
