### ISSUE TITLE
Ropsten stuck at #4242985 block

### ISSUE THREAD

**Issue by alexdupre** [paritytech/parity-ethereum#9770]
- **Parity Ethereum version**: 2.0.8
- **Operating system**: FreeBSD
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

Even after the upgrade from 2.0.7 to 2.0.8 release the block syncing is stuck at block #4242985.
What am I expected to do to recover from the Constantinople fork?

**Comment by 5chdn** [comment]
`parity db kill` and resync with `parity --chain ropsten --no-warp`
