### ISSUE TITLE
Keep snapcraft up to date

### ISSUE THREAD

**Issue by fubuloubu** [paritytech/parity-ethereum#9771]
Looks like the last time someone updated Snapcraft was 22 days ago. These are the releases for each channel:
- stable: 2.0.6
- candidate: 2.1.1
- beta: 2.1.1
- edge: 2.2.0-5a1dc3e-20180925

From what I can tell, there are more recent versions of all of these we should be using. Are snap installs still supported?

**Comment by 5chdn** [comment]
Hi Bryant, unfortunately, we dropped support for Snapcraft. Please use the one-line installer or convince your linux distro maintainers to add parity to the repositories, like archlinux did two years ago :)

**Comment by fubuloubu** [comment]
@elopio any help finding the right maintainer ^ ?

**Comment by elopio** [comment]
I could maintain it, if the team thinks it's a good idea.

**Comment by elopio** [comment]
I've requested the transfer here:
https://forum.snapcraft.io/t/transfer-parity-snap/8203
They might contact you to confirm.
