### ISSUE TITLE
How do I run the Mac installer?

### ISSUE THREAD

**Issue by benmorrow** [paritytech/parity-ethereum#9772]
Hi, I'm trying to install Parity from the Releases page on GitHub.

I have a Mac. The Mac version used to use a file extension. Now the Mac release doesn't have a file extension:

![screen shot 2018-10-17 at 5 52 04 pm-2](https://user-images.githubusercontent.com/5604/47125773-27a71e80-d23a-11e8-83e7-bffcad286ba0.png)

How can I run the installer? I tried adding the .pkg extension manually, but the Mac still says it can't open the file.

The **parity** file with no extension wants to open in the TextEdit app. I also tried adding .zip and .dmg extensions, but neither works.

**Comment by benmorrow** [comment]
I had to `chmod` the file using Terminal and then launch it from there. I followed these instructions: https://smallbusiness.chron.com/execute-file-macbook-terminal-49381.html The process feels like it isn't very friendly for user experience. On the Setup guide: https://wiki.parity.io/Setup, it just says, "Download the Binary and double click on it." Might want to consider altering the packaging of the file or changing the Wiki instructions.

**Comment by 5chdn** [comment]
Right, the docs might need some love here. The chmod +x is a good find.

In general, I would strongly encourage you to ruse homebrew! It allows you to easily upgrade to future parity ethereum versions. https://github.com/paritytech/homebrew-paritytech#homebrew-tap-for-parity
