### ISSUE TITLE
How to recover from forking?

### ISSUE THREAD

**Issue by qiluge** [paritytech/parity-ethereum#9773]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.0.3-beta-a0a2bed-20180831/x86_64-linux-gnu/rustc1.28.0
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:yes
- **Network**: ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
ropsten has forked latest, and I find my full sync node has forked from ropsten: my node height is 4258655 and the height in ropsten.etherscan.io is 4251617. What should I do to make my node keep same height with ropsten.etherscan.io ?

**Comment by qiluge** [comment]
Should I delete all data and re-sync from height 0?

**Comment by 5chdn** [comment]
Please read the release notes for 

- https://github.com/paritytech/parity-ethereum/releases/tag/v2.1.3
- https://github.com/paritytech/parity-ethereum/releases/tag/v2.0.8

Reset your database with 

    parity --chain ropsten db kill

And resync your chain! :)
