### ISSUE TITLE
An extreme fix for parity full-archive DB size - swapping out some of the *.sst files onto cheaper storage - request for ideas/advice.

### ISSUE THREAD

**Issue by XertroV** [paritytech/parity-ethereum#9776]
You might be aware that the db size of a full archive parity-ethereum node is about 1.7TB and (AFAIK) it's only practical to run them with physically attached SSDs (which are obvs a bit expensive if you need to use AWS - I haven't found cheaper than an i3.2xlarge).

During the migration process I'm going through atm (upgrading nodes to a larger SSD array -- or so I thought), I realised that many of the files _on disk_ are rarely touched. (I think the number of low numbered files is a sort of gut-estimation metric; I only had one 1xxxxx.sst file (158428.sst, last modified 18th March, seven 2xxxxx.sst files, thousands of [7,8]xxxxxx.sst files, though). 

So I had an idea: to run a service that would safely and silently move long untouched .sst files onto something like network attached drives instead. (e.g. EBS)

The main problem I can see here is ensuring the node doesn't accidentally try and write to the file while you do the switch-a-roo. **Does anyone have an advice on how to do this safely?** (Or things to watch out for, etc)

Alternatively: does rocksdb have a caching layer? Would it be difficult to implement a 'pause disk writing' feature to allow a small (1-2 second) window to move files?

Also, does parity's tx processing engine have any sort of tolerance to variable disk latency? Or would one slow read/write slow down all txs behind it as it's processing a block?

**Comment by debris** [comment]
I don't think it's doable.

Not without diving deep into rocksdb internals. And I don't believe it's worth it.

It's *better* to rethink and redesign our database layer entirely.

**Comment by debris** [comment]
@joshua-mir It's not an enhancement, cause it's not doable
