### ISSUE TITLE
Ethereum-classic need more peers

### ISSUE THREAD

**Issue by DeaVulTan** [paritytech/parity-ethereum#9784]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**:   Parity/v1.9.5-stable-ff821da-20180321/x86_64-linux-gnu/rustc1.24.1
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: classic
- **Restarted**:  yes

I need a minimum of 4 feasts to complete the payment. But I find only 2 peers.

**Comment by joshua-mir** [comment]
@DeaVulTan can you try again with a more recent version of parity and get back to us if this is still an issue?

**Comment by iconucell** [comment]
hi can you help me, I saw you have a link ( https://deavultan.github.io ) we also Have a CTF I have exactly this problem cant go ( *** ERROR!: 0x00000404 (0x59170481, 0x0000e1c2, 0xbc28402a, 0x00000050) ***) how to know CTF flag can help

**Comment by iconucell** [comment]
hi can you help me, I saw you have a link ( https://deavultan.github.io ) we also Have a CTF I have exactly this problem cant go ( *** ERROR!: 0x00000404 (0x59170481, 0x0000e1c2, 0xbc28402a, 0x00000050) ***) how to know CTF flag can help
