### ISSUE TITLE
parity eth_call fail to get info

### ISSUE THREAD

**Issue by JokerCatz** [paritytech/parity-ethereum#9797]
Parity version : 1.9.6 & 2.0.6 , docker container : Ubuntu , from release package (.deb / tar.gz)
network : testnet - ropsten
restarted : yes & re-sync checked
 
I deploy a contract , the contract address is

https://ropsten.etherscan.io/address/0xda808b5e301d35c452ee25023343fadc883e78c4

but I can't use `eth_call` get info like call `name()` (method_id = `0x06fdde03`) , `symbol()` (method_id = `0x95d89b41`) ... it always return `0x` , but if I call another contract will get correct response & outside service double check is correct too ...

you can check this like use 

    curl --data '{"method":"eth_call","params":[{"to":"0xda808b5e301d35c452ee25023343fadc883e78c4","data":"0x95d89b41"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8545
    # => {"jsonrpc":"2.0","result":"0x","id":1}

^ it return `0x` but ... this one will be success

    curl --data '{"method":"eth_call","params":[{"to":"0x46cbf5a76295abd76c168a0b36bae88625c2b074","data":"0x95d89b41"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8545
    # => {"jsonrpc":"2.0","result":"0x{SKIP_IT_TO_LONG}","id":1}

& from outside API to double check , like this

https://ropsten.etherscan.io/apis#proxy

and use like this

https://api-ropsten.etherscan.io/api?module=proxy&action=eth_call&to=0xda808b5e301d35c452ee25023343fadc883e78c4&data=0x95d89b41

it success ...

& I use this command to boot my parity node

    parity --chain=ropsten --base-path=/skip --peers=1024 --jsonrpc-apis=all --no-hardware-wallets --no-config --unsafe-expose --jsonrpc-server-threads=8 --ntp-servers=clock.stdtime.gov.tw --force-ui --ui-no-validation

this happen from my old testnet node ( Parity 1.9.6 ) & today I use Parity 2.0.6 sync from empty , it same , so somebody can recheck it? it look like a big issue

**Comment by joshua-mir** [comment]
Just to make sure, can you also try the latest stable?

**Comment by JokerCatz** [comment]
Hi , I tested `Parity-Ethereum/v2.1.3` , it okay with no bug ... but I add "--no-warp" option to sync , so I don't sure when it happen with snapshot sync

**Comment by joshua-mir** [comment]
I'll close this for now until someone replicates.
