### ISSUE TITLE
Block import failed for #9163373

### ISSUE THREAD

**Issue by teodor-pripoae** [paritytech/parity-ethereum#9803]
- **Parity Ethereum version**: v2.0.8-stable-ef8f95e-2018101
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

Hi,

My node was fully synced a few hours ago. It got an error syncing block 9163373 and then even if I restart it, it gets the same error.

```
Block import failed for #9163373 (0xe1ac…4087)
Error: Error(Trie(InvalidStateRoot(0x554206b64fa84679f4b7e359a0bc14182c4382aa2b5ee45cf50df60517d62594)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

```
truffle(kovan-rpc)> web3.eth.syncing
false
```

```
truffle(kovan-rpc)> web3.eth.getBlock('latest').number
9163371
```

**Comment by joshua-mir** [comment]
Hey, answered in gitter, solution is to use warp-barrier, no-warp, or kill db and resync.
Please create a new issue regarding the "`Your chain specification contains one or more hard forks which are required to be on by default. Please remove these forks and start your chain again: eip155Transition.`" issue if it is persisting.

**Comment by 5chdn** [comment]
@joshua-mir was this ever created?

**Comment by joshua-mir** [comment]
I don't believe it was - but wouldn't the issue be addressed by https://github.com/paritytech/parity-ethereum/pull/9972 @5chdn ?

**Comment by 5chdn** [comment]
No, I get this with the latest master for the Rinkeby chain spec which activates EIP-155 on block 0x3 - not sure what to do with that message.

**Comment by joshua-mir** [comment]
Poking [around](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/miner/miner.rs#L1100), this should only complain if you are trying to seal the genesis block, so shouldn't be a showstopper for connecting to rinkeby itself IIUC?
