### ISSUE TITLE
how can I retrieve the "internal transactions" by parity json rpc?

### ISSUE THREAD

**Issue by qiluge** [paritytech/parity-ethereum#9805]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.0.3-beta-a0a2bed-20180831/x86_64-linux-gnu/rustc1.28.0
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:yes
- **Network**: ropsten
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I want to monitor account deposit of ether from contract internal transfer. And I find the question is same with https://github.com/paritytech/parity-ethereum/issues/1969,  but the answer is not found. So how can i retrieve the internal transfer result ???

**Comment by joshua-mir** [comment]
https://wiki.parity.io/JSONRPC-trace-module is where that page now lives.

**Comment by qiluge** [comment]
Can you help me where can I find some golang example code?

**Comment by surindergiri** [comment]
Looking for Parity traces, but this link https://wiki.parity.io is down.

**Comment by ordian** [comment]
@surindergiri The new URL is https://openethereum.github.io/wiki/ (we will fix the URL redirection soon).
