### ISSUE TITLE
High CPU load in Kovan, v2.0.8

### ISSUE THREAD

**Issue by santiagorp** [paritytech/parity-ethereum#9806]
- **Parity Ethereum version**: v2.0.8
- **Operating system**: Linux
- **Installation**: Docker Hub, parity/parity:v2.0.8  
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

My parity node has a high CPU load since the upgrade to to v2.0.8.  The CPU load was one order of magnitude lower with v2.0.7.

I tried removing the DB/parity directories and started a full sync again (in case the DB had a new format for v2.0.8). After the sync finished, I still have high CPU load.

These are the command line parameters I am using:

```
      -d /home/parity/data
      --chain=kovan
      --no-download
      --force-direct
      --mode=active
      --no-serve-light
      --geth
      --no-hardware-wallets
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-apis=all
      --jsonrpc-hosts=all
```

And the output from `top`:

```
top - 09:53:44 up 195 days, 18:51,  1 user,  load average: 7.72, 6.02, 5.93
Tasks: 153 total,   1 running, 152 sleeping,   0 stopped,   0 zombie
%Cpu(s): 23.2 us,  3.5 sy,  0.0 ni,  2.8 id,  2.4 wa,  0.0 hi,  0.3 si, 67.8 st
KiB Mem :  4045092 total,   223608 free,  1037840 used,  2783644 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2654672 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                    
 2386 ubuntu    20   0  722620 253948  20712 S 163.9  6.3   5:10.18 parity                                                                                     
23978 ubuntu    20   0  825980 378988   5456 S  17.9  9.4  23:15.49 ipfs                                                                                       
10456 root      20   0  771684  76396  13184 S   3.0  1.9 100:32.96 dockerd                                                                                    
17275 mongodb   20   0 1410280  81300   6672 S   2.0  2.0   1:17.80 mongod                                                                                     
   13 root      20   0       0      0      0 S   0.7  0.0  66:34.72 ksoftirqd/1                                                                                
    7 root      20   0       0      0      0 S   0.3  0.0  57:21.79 rcu_sched                                                                                  
 3564 root      20   0       0      0      0 S   0.3  0.0   0:00.05 kworker/u30:0 
```

**Comment by ordian** [comment]
@santiagorp nothing (that could have impacted performance) has really changed [between v2.0.7 and v2.0.8](https://github.com/paritytech/parity-ethereum/compare/v2.0.7...v2.0.8) at least in the source code.

**Comment by santiagorp** [comment]
@ordian You are right, I see the changes now. I'm going to do further testing. We started noticing the high CPU load while trying to catch up with the unprocessed blocks since the migration to v2.0.8. So it might be related to the queries to the smart contract logs.

I'll not close this ticket yet till I gather some more details.

**Comment by santiagorp** [comment]
@ordian I thought it might be related to the log/event queries, but after shutting down the web app and restarting the parity node, CPU usage is still high (between 80% and 170%).

Any suggestions regarding how to find the issue? Are there any debug/verbose flags which I am not aware of? Log locations?

Since memory usage is low (6.3%), can I increase some cache in order to decrease CPU workload?

**Comment by santiagorp** [comment]
After using the following parameters I observed a huge difference:

```
      --db-compaction=hdd
      --jsonrpc-threads=2
      --jsonrpc-server-threads=2
```

Now the CPU usage is around 8% (stays between 6-10%)

It would be nice to add it somewhere in your wiki so other users with performance issues can try using this values. Other than this, feel free to close this issue.

Thanks!

**Comment by joshua-mir** [comment]
I'll close this. Maybe reopen if someone can replicate the original issue.
