### ISSUE TITLE
Non-root Parity Docker container unable to use volumes

### ISSUE THREAD

**Issue by thodges-gh** [paritytech/parity-ethereum#9827]
- **Parity Ethereum version**: v2.0.9-stable-09f7757-20181028
- **Operating system**: Linux host running Docker container
- **Installation**: Docker `:stable` tag
- **Fully synchronized**: n/a
- **Network**: n/a
- **Restarted**: yes

I noticed this issue on the `:stable` Docker tag recently. The Parity container is unable to write to a volume created with `docker volume create` when using `--base-path` or `--db-path`.

## Steps to reproduce

Pull the latest `:stable` Docker tag:

```
docker pull parity/parity:stable
```

Create the Docker volume:

```
docker volume create --name parity-test
```

Run the Parity Docker container using the new volume:

```
docker run -p 8546:8546 -v parity-test:/data \
            -it parity/parity:stable --chain ropsten \
           --ws-interface all --ws-origins "all" \
           --base-path /data
```

Observe returned error:

```
Error upgrading parity data: CannotCreateConfigPath
```

## Expected behavior

This may just be a simple documentation fix, but the expected behavior is a `docker run` command that can utilize the volume created by Docker. The existing [Docker documentation](https://wiki.parity.io/Docker) may need an update anyway.

**Comment by Levino** [comment]
I [posted a working docker-compose file](https://github.com/paritytech/parity-ethereum/pull/9689#issuecomment-436545133) which also works in docker swarm.
