### ISSUE TITLE
Can't deploy contract on private chain from authority account

### ISSUE THREAD

**Issue by groCervo** [paritytech/parity-ethereum#9832]
- **Parity Ethereum version**: 2.0.8
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: private chain

**actual** 
I followed the PoA tutorial : https://wiki.parity.io/Demo-PoA-tutorial.html, but when I try to deploy a contract from an authority account, it says that I have not enough funds on the account.

I though PoA didn't rely on mining, how  can I "funds" my account, and do I have to manually credit my authority account each time I want to deploy a contract ?

 **expected behavior**

Contract deployment.

**Comment by joshua-mir** [comment]
Hey, in https://wiki.parity.io/Demo-PoA-tutorial.html#3-complete-the-chain-specification it shows you how to complete your chain spec so your account is preloaded with a balance.
