### ISSUE TITLE
stop breaking docker hub builds

### ISSUE THREAD

**Issue by debris** [paritytech/parity-ethereum#9833]
Our docker hub release process is broken, cause changes on `master` branch of this repo affect how `stable` branch is being released on docker hub (e.g. pr https://github.com/paritytech/parity-ethereum/pull/9689)

**How it works now:**

to release `master`, we use `master/scripts/docker/hub/Dockerfile` 
to release `beta`, we use `master/scripts/docker/hub/Dockerfile` 
to release `stable`, we use `master/scripts/docker/hub/Dockerfile` 

**How it should work:**

to release `master`, we should use `master/scripts/docker/hub/Dockerfile` 
to release `beta`, we should use `**beta**/scripts/docker/hub/Dockerfile` 
to release `stable`, we should use `**stable**/scripts/docker/hub/Dockerfile` 

cc @paritytech/ci 
thanks @fubhy for the report

**Comment by ddorgan** [comment]
@debris but this is expected right? This was backported to both stable and beta.

Stable: https://github.com/paritytech/parity-ethereum/pull/9648

Beta: https://github.com/paritytech/parity-ethereum/pull/9649

**Comment by debris** [comment]
@ddorgan, can you elaborate? Does our docker hub deployment work exactly as I described in `how it should work`? 

If yes, than we made a mistake, cause we should never backport #9689 as it is a breaking change

**Comment by 5chdn** [comment]
> How it works now

Not from what I can tell, the pipeline uses the `scripts/gitlab/publish-docker.sh` on the branch it is running, and the `-f scripts/docker/hub/Dockerfile` from the branch it is running on.

Please give pointers if you think this works differently.
