### ISSUE TITLE
Affordable approach to run an archive node

### ISSUE THREAD

**Issue by mds1** [paritytech/parity-ethereum#9844]
I was wondering if there is a recommend affordable way to run an archive node with tracing on. I found [this Reddit post](https://www.reddit.com/r/ethereum/comments/7if57y/is_anyone_running_a_parity_archive_node/) from about 10 months ago which recommends a 2 TB SSD, but those are pretty expensive.

Have there been updates to Parity since that time that would allow you to sync successfully on an HDD with these settings, and if not, are there any alternative approaches you can recommend?

**Comment by joshua-mir** [comment]
Compared to an equivalent HDD, a 2TB SDD can be pretty expensive, true. You can bring the cost down by using several smaller SDDs and an LVM or RAID setup, but at the end of the day the significant storage and I/O requirements (which mean, no, no HDDs) are just part of running a full archival node (regardless of client you are using).

If the cost of the necessary hardware is a significant obstacle for you, I'd probably look into what you are trying to do and why you need to run an archival node for the task. In almost all cases, unless you want *historical transaction traces* a simple full node should be sufficient.

**Comment by mds1** [comment]
Yea, I can live with a simple full node for now, but was just curious if there were any better ways of running an archive + tracing node. Thanks for the help
