### ISSUE TITLE
setting up ethereum using parity

### ISSUE THREAD

**Issue by akashjain96** [paritytech/parity-ethereum#9849]
![image](https://user-images.githubusercontent.com/43955371/47849059-573b5680-ddf6-11e8-89be-d0093fabe241.png)

Im getting this error while i perform cargo build
Can anyone help me with it?
I tried reinstalling visual studio build tools and also tried it installing cmake but having same error

**Comment by niklasad1** [comment]
1. Verify that `cmake` is in your path (try cmake/cmake.exe on the command prompt) otherwise you have to set it up!
2. `set RUST_BACKTRACE=1` in the command prompt then try to build again and provide the output

**Comment by akashjain96** [comment]
is this issue because of cmake as my cmake is in C:// drive and rest all is on desktop 
let me try using rust backtrace

**Comment by ddorgan** [comment]
@akashjain96 cmake is still not in your %PATH%. Please ensure the path is added to your user or system's %PATH% variable.

**Comment by akashjain96** [comment]
okay let me try

**Comment by akashjain96** [comment]
![image](https://user-images.githubusercontent.com/43955371/47896368-3ecd4980-de93-11e8-83da-bc5cba75a0c2.png)
i done with setting the path still same error

**Comment by joshua-mir** [comment]
It looks like it's trying to run the cmake binary folder (`...CMake\bin`) as an executable. You should add that folder to your path, not the CMake folder itself.

If that doesn't work... and I mentioned this earlier in gitter... Visual Studio 2015 seems not to bundle these tools with it, meaning you have to set it up yourself, but they are included in the 2017 installation. If you still have trouble after correcting the wrong directory in your path, you might want to try using that instead.

**Comment by akashjain96** [comment]
i have set the path of cmake/bin still facing same error.
Sould I install Visual Studio Build Tools 2017??

**Comment by akashjain96** [comment]
![image](https://user-images.githubusercontent.com/43955371/47914511-f11e0480-dec5-11e8-9f0b-999f02806c9f.png)
i tried with VS build tools 2017
Still same error

**Comment by ddorgan** [comment]
If the command ``` which cmake ``` doesn't return the full path to cmake then this will never work. What's the current output of that command?

**Comment by akashjain96** [comment]
the image i send is the current output

**Comment by akashjain96** [comment]
![image](https://user-images.githubusercontent.com/43955371/47948485-18bdad00-df58-11e8-8c3b-c0bd986fd53d.png)
present error

**Comment by akashjain96** [comment]
@ddorgan  okay I'll try this also

**Comment by joshua-mir** [comment]
I'm assuming that this is resolved because you have parity running and are asking questions on gitter :+1:
