### ISSUE TITLE
parity_decryptMessage never responds

### ISSUE THREAD

**Issue by Kdx1999** [paritytech/parity-ethereum#9851]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.0
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes
- **Options**: --tracing=on --pruning=archive --jsonrpc-apis all 
 I just tried the example in the wiki 
`curl --data '{"method":"parity_decryptMessage","params":["0x00a329c0648769a73afac7f9381e08fb43dbea72","0x0405afee7fa2ab3e48c27b00d543389270cb7267fc191ca1311f297255a83cbe8d77a4ba135b51560700a582924fa86d2b19029fcb50d2b68d60a7df1ba81df317a19c8def117f2b9cf8c2618be0e3f146a5272fb9e5528719d2d7a1bd91fa620901cffa756305c79c093e7af30fa3c1587029421351c34a7c1e5a2b"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
, but there has been no response for about 8 hours. Other apis works well.

**Comment by joshua-mir** [comment]
Have you unlocked the account you are decrypting with (using `personal_unlockAccount`) before calling `parity_decryptMessage`?

**Comment by Kdx1999** [comment]
> Have you unlocked the account you are decrypting with (using `personal_unlockAccount`) before calling `parity_decryptMessage`?

I am sorry, but is it possible to decrypt a input message by only providing the contract address? (How does etherscan implement the "Decode Input Data" feature?)
![decode_1](https://user-images.githubusercontent.com/19722199/47923914-98fef680-def5-11e8-8c1e-0de05763772c.png)
![decode_2](https://user-images.githubusercontent.com/19722199/47923919-9b615080-def5-11e8-81c7-3b6265097299.png)
