### ISSUE TITLE
can i rum parity with docker in windows

### ISSUE THREAD

**Issue by rushabh098** [paritytech/parity-ethereum#9861]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by joshua-mir** [comment]
Answered on gitter. Yes. wiki.parity.io/Docker.html as mentioned on gitter as well, it's difficult to use datadirs because of permissions issues in windows.
