### ISSUE TITLE
v2.1.4 Build error on linux

### ISSUE THREAD

**Issue by Laziemo** [paritytech/parity-ethereum#9868]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.4 (beta)
- **Operating system**: Linux d76 4.15.0-38-generic #41-Ubuntu

- **Installation**: built from source
- **Fully synchronized**: yes 
- **Network**: morden 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

eclassic@d76:~/nodes/parity-ethereum-2.1.4$ RUST_BACKTRACE=1 cargo build --release --features final
 Downloading log v0.4.6
 Downloading lazy_static v1.2.0                                                                                                                                                                             
 Downloading byteorder v1.2.7                                                                                                                                                                               
 Downloading rayon v1.0.3                                                                                                                                                                                   
 Downloading cfg-if v0.1.6                                                                                                                                                                                  
 Downloading fixed-hash v0.2.5                                                                                                                                                                              
 Downloading syn v0.15.18                                                                                                                                                                                   
 Downloading quote v0.6.9                                                                                                                                                                                   
 Downloading tokio-io v0.1.10                                                                                                                                                                               
 Downloading memchr v2.1.1                                                                                                                                                                                  
 Downloading aho-corasick v0.6.9                                                                                                                                                                            
 Downloading utf8-ranges v1.0.2                                                                                                                                                                             
 Downloading ucd-util v0.1.2                                                                                                                                                                                
 Downloading tokio-threadpool v0.1.8                                                                                                                                                                        
 Downloading tokio-uds v0.2.3                                                                                                                                                                               
 Downloading tokio-fs v0.1.4                                                                                                                                                                                
   Compiling cfg-if v0.1.6                                                                                                                                                                                  
   Compiling rand_core v0.3.0                                                                                                                                                                               
   Compiling lazy_static v1.2.0                                                                                                                                                                             
   Compiling byteorder v1.2.7                                                                                                                                                                               
   Compiling rayon v1.0.3                                                                                                                                                                                   
   Compiling futures v0.1.25                                                                                                                                                                                
   Compiling proc-macro2 v0.4.20                                                                                                                                                                            
   Compiling serde v1.0.80                                                                                                                                                                                  
   Compiling lazycell v1.2.0                                                                                                                                                                                
   Compiling version_check v0.1.5                                                                                                                                                                           
   Compiling httparse v1.3.3                                                                                                                                                                                
   Compiling num-traits v0.2.6                                                                                                                                                                              
   Compiling gcc v0.3.55                                                                                                                                                                                    
   Compiling ucd-util v0.1.2                                                                                                                                                                                
   Compiling safemem v0.3.0                                                                                                                                                                                 
   Compiling rustc-hex v1.0.0                                                                                                                                                                               
   Compiling utf8-ranges v1.0.2                                                                                                                                                                             
   Compiling termcolor v1.0.4                                                                                                                                                                               
   Compiling mio-named-pipes v0.1.6                                                                                                                                                                         
   Compiling crossbeam-utils v0.2.2                                                                                                                                                                         
   Compiling log v0.4.6                                                                                                                                                                                     
   Compiling net2 v0.2.33                                                                                                                                                                                   
   Compiling thread_local v0.3.6                                                                                                                                                                            
   Compiling cmake v0.1.35                                                                                                                                                                                  
   Compiling eth-secp256k1 v0.5.7 (https://github.com/paritytech/rust-secp256k1#ccc06e74)                                                                                                                   
   Compiling rand_core v0.2.2                                                                                                                                                                               
   Compiling base64 v0.6.0                                                                                                                                                                                  
   Compiling parity-wasm v0.31.3                                                                                                                                                                            
   Compiling base64 v0.9.3                                                                                                                                                                                  
   Compiling regex-syntax v0.5.6                                                                                                                                                                            
   Compiling regex-syntax v0.6.2                                                                                                                                                                            
   Compiling unicase v2.2.0                                                                                                                                                                                 
   Compiling memchr v2.1.1                                                                                                                                                                                  
   Compiling unicase v1.4.2                                                                                                                                                                                 
   Compiling crossbeam-epoch v0.5.2                                                                                                                                                                         
   Compiling lock_api v0.1.4                                                                                                                                                                                
   Compiling bytes v0.4.10                                                                                                                                                                                  
   Compiling crossbeam-epoch v0.3.1                                                                                                                                                                         
   Compiling log v0.3.9                                                                                                                                                                                     
   Compiling trace-time v0.1.1                                                                                                                                                                              
   Compiling stats v0.1.0 (/home/eclassic/nodes/parity-ethereum-2.1.4/util/stats)                                                                                                                           
   Compiling hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)                                                                                                                               
   Compiling rand v0.5.5                                                                                                                                                                                    
   Compiling mio v0.6.16                                                                                                                                                                                    
   Compiling tokio-executor v0.1.5                                                                                                                                                                          
error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)`                                                                                            
process didn't exit successfully: `/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-7b8e690a779853db/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
cargo:warning=etc/hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
cargo:warning= #include <libudev.h>
cargo:warning=          ^~~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum-2.1.4/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/eclassic/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by joshua-mir** [comment]
Have you built parity successfully on this system in the past? It looks like libudev is missing, could you try `apt install libudev-dev`?

**Comment by Laziemo** [comment]
oh right> cargo:warning=etc/hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
cargo:warning= #include <libudev.h>

nice one!!

installed libudev-dev and trying to compile again...

**Comment by Laziemo** [comment]
awesome!
Finished release [optimized] target(s) in 10m 08s.

Cheers @joshua-mir !
