### ISSUE TITLE
How disable "Local key file" for transaction signer?

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity-ethereum#9871]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.4
- **Operating system**: Windows /Linux
- **Installation**:  one-line installer
- **Fully synchronized**:  yes
- **Network**:  kovan  ...
- **Restarted**: yes

Hello, after update parity wants Local key file for sign each transaction. I want use only key password, how can I disable Local key file for signer?

**Comment by joshua-mir** [comment]
Hey, this is an issue for https://github.com/parity-js/shell

But I should add that the "Parity UI" has been unsupported for a while, as stated in the wiki,  and it's repo, and you should consider an alternative if you want to transact with a UI. Let me know if you need help migrating or want suggestions on alternatives.
