### ISSUE TITLE
Potential inconsistency of "parity-vm" and other implementations

### ISSUE THREAD

**Issue by ireneGP** [paritytech/parity-ethereum#9874]
Hello,
- Parity EVM version: Parity-Ethereum/v2.2.0-nightly-f4c421f77-20181024/x86_64-linux-gnu/rustc1.29.2
- Aleth EVM version: aleth-vm 1.5.0-alpha.5-2+commit.ec558b26.dirty 
- Operating system: Ubuntu 18.04
- Fully synchronized: NA
- Network: NA
- Restarted: NA

Please see the stack trace of `parity-vm` and `aleth-vm`:

````
➜  release git:(master) ./parity-evm --code 3330 --json
{"depth":1,"gas":"0xffffffffffffffff","gasCost":"0x2","memory":"0x","op":51,"opName":"CALLER","pc":0,"stack":[],"storage":{}}

{"depth":1,"gas":"0xfffffffffffffffd","gasCost":"0x2","memory":"0x","op":48,"opName":"ADDRESS","pc":1,"stack":["0x0"],"storage":{}}

{"gasUsed":"0x4","output":"0x","time":1346}
````

````
➜  aleth-vm git:(master) ✗ ./aleth-vm trace --code 3330 --log-verbosity 20
[
   {
      "depth" : "0",
      "gas" : "9223372036854775807",
      "gasCost" : "2",
      "memory" : [],
      "pc" : "0",
      "stack" : [],
      "storage" : {}
   },
   {
      "depth" : "0",
      "gas" : "9223372036854775805",
      "gasCost" : "2",
      "pc" : "1",
      "stack" : [ "0x45" ]
   },
   {
      "depth" : "0",
      "gas" : "9223372036854775803",
      "gasCost" : "0",
      "pc" : "2",
      "stack" : [ "0x45", "0x1122334455667788991011121314151617181920" ]
   }
]
````

The stack behavior seems inconsistent. Does this make any sense? Thanks.

**Comment by joshua-mir** [comment]
Hey, it looks like aleth is hardcoding the response to the CALLER opcode for some reason.

**Comment by joshua-mir** [comment]
your other issue in case anyone bumps into these inconsistencies :sweat_smile: : https://github.com/ethereum/go-ethereum/issues/18040

**Comment by ireneGP** [comment]
@joshua-mir  Hey, I didn't get it. Doesn't it seems like a bug of aleth-vm? It shouldn't be hardcoded, right?

**Comment by joshua-mir** [comment]
It might be the case that they have a "testing environment" defined somewhere that they forgot to take out. 

Unless someone is using the binaries in their own projects without initializing state to something sane, this won't come up.

**Comment by ireneGP** [comment]
Thanks @joshua-mir . I am a newbie to this field, could you shed some lights on a good "example" that I can follow to setup consistent "testing environments"?

**Comment by joshua-mir** [comment]
I'm not the most familiar either, but here are the "official" vm tests that you would run with `parity-evm state-test` https://github.com/ethereum/tests/tree/develop/VMTests
