### ISSUE TITLE
Parity not detecting Ledger Nano S, and is incapable of submitting a transaction even with the Nano S attached

### ISSUE THREAD

**Issue by stochastic-thread** [paritytech/parity-ethereum#9882]
- **Parity Ethereum version**: 
```
version Parity/v1.11.3-beta-a66e36b-20180605/x86_64-macos/rustc1.26.1
Parity UI Version 0.3.4 (0.3.4)
```
- **Operating system**: macOS Mojave 10.14
- **Installation**: Parity UI dmg
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes. I tried to restart Parity before plugging in the Nano S, as well as while it was previously plugged in. The Nano S turns on, as expected, implying that it is drawing power from the workstation I'm using, but the Parity UI button remains in a greyed out state, making it impossible to submit a transaction.

There used to be a bug where you had to attach the Nano S prior to starting Parity. To attempt to resolve this, I restarted my computer with the Nano S attached, and as the machine began to boot, the Nano S immediately turned on. When I started Parity, the device does not seem to be recognized, and the submit transaction button remains greyed out. Previously, I have personally observed the button becoming clickable upon insertion of the device, and I am not using a third-party multi-USB dongle (just an Apple USB-C to USB/HDMI/USB-C adapter, which I would assume is natively supported).

**Comment by stochastic-thread** [comment]
To future individuals - browser support must be DISABLED, and not ENABLED, in order for the button to work.
It is a bit confusing, given that Parity UI seems to be running a thin Chromium layer - does anyone have a more contextual explanation for this choice of words?

**Comment by joshua-mir** [comment]
Hey, Parity UI has been deprecated and was only really supported until the 1.10 release, so using it with versions later than that make it act in ways we don't support; to add to that, pre-2.0 releases have been EOL for over a month now and we can't really help out. 

I'm glad you figured out your issue though.
