### ISSUE TITLE
All `ethminer` shares submitted over `stratum` are rejected

### ISSUE THREAD

**Issue by veox** [paritytech/parity-ethereum#9891]
- **Parity Ethereum version**: `v2.0.9` (current stable); also `v2.3.0-unstable-d42d816e7-20181109` (current `master`)
- **Operating system**: Linux: Ubuntu 18.04.1 LTS (Bionic Beaver), VM via QEMU KVM
- **Installation**: built from source (`rustc1.28.0`, `debug` build via `cargo build`)
- **Fully synchronized**: yes
- **Network**: Ropsten
- **Restarted**: yes, I did turn it off and on again :/

Extra:

- **parity run as**:

``` sh
/home/veox/src/parity/target/debug/parity --chain=ropsten \
    --warp-barrier=4350000 --no-ancient-blocks \
    --max-peers=25 --snapshot-peers=1 --reserved-peers=/home/veox/reserved-peers.txt \
    --force-sealing --reseal-on-uncle --stratum \
    --author=0x22328d36545aCeC6C3217FFa61457dBFc07edD83 \
    --gas-floor-target=9000042 --gas-cap=10000042 --extra-data=veox \
    --logging="rpc=trace,stratum=trace" --log-file=/tmp/miner-trace.log
```

- **ethminer version**: 0.17.0.1.20181111.16e214428, locally-built
- **ethminer run as**: see [4 comments below](https://github.com/paritytech/parity-ethereum/issues/9891#issuecomment-437902485)

-----

I've been able to use `ethminer` directly with `parity-ethereum`'s `stratum` previously (about 6 months ago), to mine on Ropsten, but not anymore: `parity` is rejecting all solutions.

What seems to have changed is `ethminer` changing `stratum` mode detection, in https://github.com/ethereum-mining/ethminer/pull/1429.

In particular, [this part in `parity`](https://github.com/paritytech/parity-ethereum/blob/c313039526269f4690f6f3ea006b32f2d81ee6ab/ethcore/src/miner/stratum.rs#L56) expects 3 items in the payload, which - according to `ethminer` - corresponds to the `EthStratumClient::ETHPROXY` mode, and the `eth_submitWork` JSON-RPC method:

https://github.com/ethereum-mining/ethminer/blob/16e214428ddfc0954df10ba3a728149d68409606/libpoolprotocols/stratum/EthStratumClient.cpp#L1379-L1385

However, `ethminer` is using the `mining.submit` JSON-RPC method, and that seems to correspond to the `EthStratumClient::STRATUM` mode:

https://github.com/ethereum-mining/ethminer/blob/16e214428ddfc0954df10ba3a728149d68409606/libpoolprotocols/stratum/EthStratumClient.cpp#L1366-L1374

EDIT: In other words, there seems to be a mix-up of Stratum modes, JSON-RPC methods, and items in payload between latest `ethminer` and `parity`.

-----

Enabling `--logging="rpc=trace,stratum=trace"` does not actually give that much more detailed information, e.g. _why_ the solutions are rejected. These are the only lines given:

```
2018-11-11 23:48:48  jsonrpc-eventloop-1 TRACE rpc  Request: {"id":40,"jsonrpc":"2.0","method":"mining.submit","params":["0x22328d36545acec6c3217ffa61457dbfc07edd83.harbinger","0000000000000000000000000000000000000000000000000000000000000000","0xf45837d93a6d92d7","0x2227accdf394bb406ba017eef8e722f4d4fb41b74489d19b5419e1a35fb3f7a4","0x2749f0bb88df7a32c6721776ae7deed46a7226f968ffc63657b8252aff6eb2e0"],"worker":"harbinger"}.
2018-11-11 23:48:48  jsonrpc-eventloop-1 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":40}.
```

So, the previous reasoning is guesswork. But I'm pretty sure it's correct.

**Comment by veox** [comment]
During the Ropsten Byzantium->Constantinople fork, a few people were mining `parity`-made blocks. However, I believe both of them were using fully-proxying pool solutions (don't remember, which likely masked this issue.

**Comment by veox** [comment]
Surely; via shell script:

``` sh
#!/bin/sh

machine='harbinger'
benefactor='0x22328d36545acec6c3217ffa61457dbfc07edd83' # veox ropsten mining
remote='127.0.0.1:8008'
password='swearword'

nice ionice -c3 ethminer --verbosity=1 \
     --opencl --opencl-device 0 --opencl-platform 1 \
     -P stratum+tcp://$benefactor.$machine:$password@$remote
```

**Comment by joshua-mir** [comment]
I don't think parity has authentication on stratum? What happens if you don't provide `machine` and `password` (afaik you don't even need to provide a benefactor, the node has the author option already... the `-P` value should just be `$remote` in your script.)

https://wiki.parity.io/Mining.html#Stratum

**Comment by veox** [comment]
Ah, why of course - read the fine manual before making noise...

I'll test this as soon as the node syncs up; I have a feeling you're correct. X_X

**Comment by veox** [comment]
Confirming that dropping `$benefactor.$machine:$password@` from the `ethminer -P` option fixes the issue.

For ref, when receiving the solution, `parity` logs:

```
2018-11-12 17:48:40  jsonrpc-eventloop-1 TRACE rpc  Request: {"id":40,"jsonrpc":"2.0","method":"mining.submit","params":["","0000000000000000000000000000000000000000000000000000000000000000","0xc3dd775d84e96d64","0xc13ba2c9ef15d17da1737ab3273603be81b63b834c9f9d4e03ef55fc48ad4857","0x17e7e2379d5b6ee42e9579e738494b672535c55f85dcfc4ce9ea3f6d33926dad"]}.
2018-11-12 17:48:40  jsonrpc-eventloop-1 TRACE stratum  submit_work: Decoded: nonce=0xc3dd…6d64, pow_hash=0xc13b…4857, mix_hash=0x17e7…6dad
2018-11-12 17:48:40  jsonrpc-eventloop-1 INFO miner  Submitted block imported OK. #4415597: 3fb287ac260babb53cbeeeac968a2f27ce7cdb0dd7a4d7053458603bfc2f3453
```

Closing as PEBKAC.
