### ISSUE TITLE
RPC: parity_dropNonReservedPeers -> method not found

### ISSUE THREAD

**Issue by nikita-fuchs** [paritytech/parity-ethereum#9894]
- **Parity Ethereum version**: 02.1.4-beta
- **Operating system**: Linux Ubuntu
- **Installation**: one-line installer 
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**: yes

**actual behavior** 
When doing `curl --data '{"method":"parity_dropNonReservedPeers","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
` as written in the docs [here](https://wiki.parity.io/JSONRPC-parity_set-module#parity_dropnonreservedpeers), I get 
` {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1} `

**expected behavior** 
Actually dropping peers and confirming.

 **steps to reproduce** 
Install the version mentioned above and execute the RPC command.

**Comment by tomusdrw** [comment]
`parity_dropNonReservedPeers` is in `parity_set` namespace. You need to enable this API explicitly via `--[jsonrpc|ws|ipc|-apis=parity_set`
