### ISSUE TITLE
Secret store nodes are unable to connect to each other without a clear reason why

### ISSUE THREAD

**Issue by roderik** [paritytech/parity-ethereum#9898]
I'm trying to setup the secret store like described in the tutorial, but at the point they should connect to each other, I get a weird connection refused error. 

```
ethereum_1  | 2018-11-09 16:26:33 UTC 0xea78…9a38: network error 'Connection refused (os error 111)' when establishing outbound connection with 104.248.196.38:12000
ethereum_1  | 2018-11-09 16:26:33 UTC 0xea78…9a38: network error 'Connection refused (os error 111)' when establishing outbound connection with 104.248.196.27:12000
```
 
The nodes are just basic digital ocean nodes, no firewall. The config for each is

```
[secretstore]
self_secret = "AUTHORITY_ADDRESS"
interface = "all" # local, all or a specific address
port = 12000
server_set_contract = "none"        # required option if you use hardcoded nodes set
nodes = [
    "ea78372834539a56b6909e23a2a5ca9040a77699d87451f307a4b698d7856b317ab0ba544e21851606bf1c57265f4ffd7b6043e228bf48b126c2be6555109a38@104.248.200.130:12000",
    "75ee3191beed34e97c9a74f4efcd15419c37d17e1720b1c471cec38f8f5b99e25129aebbda8885ce949470d35fb2f78b684328fcdc2c4473af732f160a202897@104.248.196.27:12000",
    "18d8853fff3089f02443badf54dbc6cdc87eecd77cea49ff3eab8ed7505f91db34d92e8ce273f161146b3de600c0a092c0bdcf8bdf79d64975901bee792d2543@104.248.196.38:12000"
]
http_interface = "all"
disable = false
disable_http = false
```

with their own AUTHORITY_ADDRESS filled in.  any idea?

A very recent parity master was used as a base to build the docker image.

**Comment by joshua-mir** [comment]
From the [tutorial](https://wiki.parity.io/Secret-Store-Tutorial-1.html#4-add-bootnodes-to-each-configuration-file) :


> You might see some errors 'Connection refused (os error 111)' when establishing outbound connection with 127.0.0.1:8013 when launching node 1 and 2 because not all nodes are online, but once they are all up, you should see logs like this...

So I'm assuming that your issue is some of your nodes are offline, (which is why your connection isn't being refused by all of the nodes in your config).

**Comment by roderik** [comment]
Hmm, they are all online though and each gives errors about the two others.

**Comment by joshua-mir** [comment]
Any chance you aren't using their public ip addresses or haven't configured floating ips for your droplets?

**Comment by roderik** [comment]
nope, their public addresses. Will have some time soon to restart everything and collect some more logs

**Comment by roderik** [comment]
Totally my fault, forgot to map the port in docker...
