### ISSUE TITLE
Local transactions should be accepted over the limit

### ISSUE THREAD

**Issue by iaaly** [paritytech/parity-ethereum#9909]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.4-beta-bee2cb8-20181028
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**: no
- **Network**: Private PoA, single node
- **Restarted**: no

 **Actual behavior**
Node stopped mining transactions, showing this log for every new transaction:

`2018-11-13 11:03:40 UTC Transaction culled (hash 0x2d78652463607f840a0c8116ad864d78e865535c77d0850baf1d8698e97ae98a)`

**Expected behavior**
Node should queue transactions continue mining in order.  

**Steps to reproduce**
I was load testing the node by issuing a large number of transactions using NPM [loadtest](https://www.npmjs.com/package/loadtest) module with concurrency level 2 and number of requests 10000

**Comment by iaaly** [comment]
The command is:
`loadtest -n 10000 -c 2  http://localhost:8080/sendTransaction`

sendTransaction API:
```
app.get('/sendTransaction', function(req, res) {
        web3.eth.personal.sendTransaction({from: acc1, to: acc2, value: 1}, "password", function(err, data) {
                if (err != null) {
                        res.send(err);
                } else {
                        res.send({ref: data})
                }
        });
})
```

After I stopped the load test, I am calling the API and receiving successful responses with transaction hashes, but these transactions are not getting mined.

Note that `web3.eth.isMining()` is returning true.

**Comment by tomusdrw** [comment]
@iaaly can you please provide logs with `-ltxqueue=trace` when running? Did you change `--tx-queue-per-sender` parameter?

**Comment by joshua-mir** [comment]
Are blocks being mined and the transactions aren't being included? Or no blocks being mined at all?

**Comment by iaaly** [comment]
@joshua-mir No blocks are mined, instead I am getting a "Transaction culled"

@tomusdrw I have the basic log output and no I didn't change the `--tx-queue-per-sender` parameter. How can I add `-ltxqueue=trace` if the node is already running? sorry I am new to parity.

**Comment by tomusdrw** [comment]
Could you try re-running with `--tx-queue-per-sender 100000`? I think some transactions might be just dropped. Are you running a dev chain?
You need to restart the node to add any CLI parameters (no way to change log level without it).

**Comment by iaaly** [comment]
adding `--tx-queue-per-sender 100000` has solved my issue, thanks!

**Comment by tomusdrw** [comment]
Seems that transactions are dropped then, I think this should not happen for local transactions

**Comment by iaaly** [comment]
The test passed successfully but I got some weird results.
Now I'm worried that I am having some double spending issues.

Let me explain what happened:
the account has a balance of 9998999999999999943604
web3.eth.getTransactionCount() for the same account is returning: 56570

Now I'm running the load test with concurrency 10 and number of requests 10000:
`loadtest -n 10000 -c 10 http://localhost:8080/sendTransaction`

After the test is finished I have the following:
balance: 9998999999999999933595
transaction count: 66579

What I was expecting:
balance: 9998999999999999933604
transaction count: 66570

Apparently, there are an additional 9 transactions, could it be an issue with [loadtest](https://github.com/alexfernandez/loadtest)?

**Comment by tomusdrw** [comment]
1. Parity saves local transactions in the pool from previous runs, maybe the 9 transactions were just reimported on start? Restart with `--no-persistent-txqueue` to avoid that
2. Is load test re-trying the requests if they fail/timeout? Perhaps Parity received and handled both RPC requests, but `loadtest` assumed it timed out?

**Comment by iaaly** [comment]
The number 9 is not a coincidence, It's increasing with the increase of the concurrency.
After multiple attempts with different concurrency levels, I noticed that the number of extra transactions is always (c - 1) where c is the concurrency parameter.
So in the previous case, it's 9 because the concurrency was set to 10.

I feel like it's a bug in the loadtest script, can it be a parity related issue?

**Comment by tomusdrw** [comment]
Would you mind running with `-lrpc=trace` and filtering out only `eth_sendTransaction` requests?
We can check how many RPC requests were received by Parity.

**Comment by iaaly** [comment]
Thanks, I ran this command on the logs:
>cat logs.log | grep personal_sendTransaction | wc -l
output: 10009

It seems a bug in `loadtest`

**Comment by tomusdrw** [comment]
CC @ascjones that should be implemented already, no?

**Comment by ascjones** [comment]
Yes should be fixed in https://github.com/paritytech/parity-ethereum/pull/10901
