### ISSUE TITLE
Events missing when using event filters

### ISSUE THREAD

**Issue by jurijbajzelj** [paritytech/parity-ethereum#9917]
- **Parity Ethereum version**: Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0
- **Operating system**: Linux 4.4.0-1061-aws
- **Installation**: bash <(curl https://get.parity.io -Lk) -r stable
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Event in question: https://etherscan.io/tx/0x76357a02c8ab0d1b9ab2a4df6f266252d2735b4de7d65a85830c77370bd2de27#eventlog
I'm using _web3py_ to retrieve _Transfer_ events.
```python
event_filter = contract_instance.events.Transfer.createFilter(fromBlock=4800000, toBlock=4800000)
return event_filter.get_all_entries()
```

**actual behaviour - events returned (I'm getting this using Parity)**
[]

**expected behaviour - events returned (I'm getting this using geth)**
[AttributeDict({'args': AttributeDict({'from': '0x4e2171F25e54032A5DF2bEeBBfD3f82C342bBAad', 'to': '0x3f5CE5FBFe3E9af3971dD833D26bA9b5C936f0bE', 'value': 1001000000000000000000}), 'event': 'Transfer', 'logIndex': 24, 'transactionIndex': 58, 'transactionHash': HexBytes('0x76357a02c8ab0d1b9ab2a4df6f266252d2735b4de7d65a85830c77370bd2de27'), 'address': '0xB8c77482e45F1F44dE1745F52C74426C631bDD52', 'blockHash': HexBytes('0x047d5b3aba8e85b61c1ae9eb8ab96bb2b0e1dc6bfc780fd58d5132dd0adbb728'), 'blockNumber': 4800000})]

**Comment by joshua-mir** [comment]
Hey, have you double checked with https://wiki.parity.io/JSONRPC-parity-module.html#parity_chainstatus that the range of blocks you're looking for are actually present on your node?

**Comment by jurijbajzelj** [comment]
```
$ curl --data '{"method":"parity_chainStatus","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <node_endpoint>
{"jsonrpc":"2.0","result":{"blockGap":null},"id":1}
```
@joshua-mir

**Comment by joshua-mir** [comment]
It's quite likely this and https://github.com/paritytech/parity-ethereum/issues/9916 are the same issue. Closing as duplicate, and we'll track this there 👍
