### ISSUE TITLE
Remove incorrectly registered token from Parity Token Registry

### ISSUE THREAD

**Issue by ButteryGuitars** [paritytech/parity-ethereum#9921]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 1.11.11
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Someone has registered this contract with the incorrect number of decimal places

https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

See screenshot

![image](https://user-images.githubusercontent.com/43388326/48498311-9c4e8800-e7fb-11e8-90fe-212e1bf5f496.png)

It should be registered with 6 decimal places. It makes transfers of the current ERC20 token nearly impossible in it's current state. Thank you!

**Comment by Tbaut** [comment]
My take is that this token registry should not be used anymore as it is not flexible enough (no modification/deletion possibility even for the original sender) and not used by any app other than Parity UI (that lacks maintainers). Please refrain from using it and prefer alternatives.
