### ISSUE TITLE
2.2.1-beta Binary checksums are different

### ISSUE THREAD

**Issue by yuelipeng** [paritytech/parity-ethereum#9930]
- **Parity Ethereum version**: 2.2.1
- **Operating system**:  MacOS

After download Parity Ethereum 2.2.1-beta's mac version, my sha256 checksum is adc27b6f7ea7d66eb012a5c2a6036e304f09ebcf2f27b04d93731618c630d840, different from your a2d20e9.  windows and linux are also different.

**Comment by HCastano** [comment]
It looks like the checksums for 2.1.6-stable are also different. For the macOS version I'm getting `d3f6ed4261f283a1c774b5595cf492377c659c3a749ec0abb3d370acc9da0cd1` instead of `41b87ac7`.

**Comment by joshua-mir** [comment]
Do you mean that building from source gives you a binary with a different checksum? Or are the checksums listed on our releases page incorrect? @Tbaut

**Comment by Tbaut** [comment]
Thanks for the heads-up, there is a misalignment between our release and vanity servers (beta != 2.2.1 for vanity). Working on it.

**Comment by Tbaut** [comment]
That should be sorted out now :)
