### ISSUE TITLE
IO error: While open a file for random read: /root/.local/share/io.parity.ethereum/chains/kovan/db/.....sst: Too many open files

### ISSUE THREAD

**Issue by ChristophDFine** [paritytech/parity-ethereum#9936]
- **Parity Ethereum version**:  version Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0
- **Operating system**: Linux Ubuntu: 4.15.0-1023-aws
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: no

Error from the logs:

Oct 17 10:26:58 ip-172-31-47-38 parity[4633]: 2018-10-17 10:26:58 UTC Syncing #8829006 0x3c1d…3ffc     7.49 blk/s   31.8 tx/s    3 Mgas/s      0+ 7958 Qed  #8836965   15/25 peers     75 MiB chain   85 MiB db   41 MiB queue    6 MiB sync  RPC:  0 conn,    2 req/s, 20286 µs
Oct 17 10:26:58 ip-172-31-47-38 parity[4633]: 2018-10-17 10:26:58 UTC Incoming streams error, closing sever: Os { code: 24, kind: Other, message: "Too many open files" }
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: ====================
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: stack backtrace:
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    0:     0x55dfc2609fdc - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    1:     0x55dfc2609d92 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    2:     0x55dfc2609e08 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    3:     0x55dfc2608c0a - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    4:     0x55dfc10e7305 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    5:     0x55dfc2669753 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    6:     0x55dfc26692f9 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    7:     0x55dfc26691f5 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    8:     0x55dfc26caedb - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:    9:     0x55dfc261b748 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   10:     0x55dfc26303d9 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   11:     0x55dfc1f3f1eb - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   12:     0x55dfc1c789a2 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   13:     0x55dfc1f3868f - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   14:     0x55dfc1da3bc6 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   15:     0x55dfc1d2d069 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   16:     0x55dfc1c9dc7f - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   17:     0x55dfc1cb13d8 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   18:     0x55dfc24744bf - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   19:     0x55dfc2469a85 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   20:     0x55dfc1ddfbc9 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   21:     0x55dfc1dedac3 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   22:     0x55dfc1dcb0ff - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   23:     0x55dfc1d3d294 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   24:     0x55dfc1e5ca3a - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   25:     0x55dfc1e5fd7e - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   26:     0x55dfc1cc19df - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   27:     0x55dfc1a2add9 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   28:     0x55dfc1a2010b - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   29:     0x55dfc1a08fcd - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   30:     0x55dfc1a093f6 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   31:     0x55dfc26939c9 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   32:     0x55dfc1a1d0b2 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   33:     0x55dfc266c1da - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   34:     0x55dfc2669d25 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   35:     0x7f4cd32946da - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   36:     0x7f4cd2da588e - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:   37:                0x0 - <no info>
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: Thread 'IO Worker #1' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: StringError("IO error: While open a file for random read: /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/archive/db/140722.sst: Too many open files") }', libcore/result.rs:945
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: This is a bug. Please report it at:
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]:     https://github.com/paritytech/parity/issues/new
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: 2018-10-17 10:27:00 UTC Finishing work, please wait...
Oct 17 10:27:00 ip-172-31-47-38 parity[4633]: 2018-10-17 10:27:00 UTC Block import failed for #8829032 (0xc0b7…35d0): Parent not found (0x973e…4718)
Oct 17 10:28:00 ip-172-31-47-38 parity[4633]: 2018-10-17 10:28:00 UTC Shutdown is taking longer than expected.
Oct 17 10:32:00 ip-172-31-47-38 parity[4633]: 2018-10-17 10:32:00 UTC Shutdown timeout reached, exiting uncleanly.
Oct 17 10:32:12 ip-172-31-47-38 parity[18120]: 2018-10-17 10:32:12 UTC Starting Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0

**Comment by joshua-mir** [comment]
Hey, could you let us know what kind of machine this is running on? You are likely running something else that is IO intensive on the same machine as parity (a web browser can often be enough on a laptop), or are running on a machine that can't really handle the requirements in the first place.

**Comment by joshua-mir** [comment]
Could you follow this issue here https://github.com/paritytech/parity-ethereum/issues/9831? I'll close this as it's a duplicate.
