### ISSUE TITLE
Private network: Using geth to mine for parity nodes

### ISSUE THREAD

**Issue by BlockchainDieter** [paritytech/parity-ethereum#9961]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.0.9
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**:  yes

I want to set up a private Ethereum network using a parity client. Ideally, I want to resemble the "real" Ethereum network as close as possible. Thus, I want to set up a proof of work network. For that, I used the chain configuration below for Parity. I now want to mine on this private chain, but with a cpu miner. I have found only Geth being capable of doing that. However, when I attach to the parity node running the private chain, I can not use the `miner.start()` command. 

How can I use a geth node to mine for a parity node?

Note: This is a duplicate of question I posted on stackexchange: https://ethereum.stackexchange.com/questions/62866/private-network-using-geth-to-mine-for-parity-nodes and then figured I might also get an answer here.

Parity node configuration:

    {
    "name": "CrossClient",
    "dataDir": "CrossClient",
    "engine": {
        "Ethash": {
            "params": {
                "minimumDifficulty": "0x020000",
                "difficultyBoundDivisor": "0x0800",
                "durationLimit": "0x0d",
                "blockReward": "0x4563918244F40000",
                "homesteadTransition": 0,
                "eip150Transition": 0,
                "eip160Transition": 10,
                "eip161abcTransition": 10,
                "eip161dTransition": 10
            }
        }
    },
    "params": {
        "gasLimitBoundDivisor": "0x0400",
        "registrar": "0x81a4b044831c4f12ba601adb9274516939e9b8a2",
        "eip155Transition": 10,
        "accountStartNonce": "0x0",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x539"
    },
    "genesis": {
        "seal": {
            "ethereum": {
                "nonce": "0x0000000000000042",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x10000",
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x3535353535353535353535353535353535353535353535353535353535353535",
        "gasLimit": "0x1000000"
    },
    "accounts": {
        "0000000000000000000000000000000000000001": { "balance": "1", "nonce": "0", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0000000000000000000000000000000000000002": { "balance": "1", "nonce": "0", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0000000000000000000000000000000000000003": { "balance": "1", "nonce": "0", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0000000000000000000000000000000000000004": { "balance": "1", "nonce": "0", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } }
    }
}

**Comment by joshua-mir** [comment]
The main misunderstanding you seem to be having here is that `geth attach` does not run a geth node and attach it to your parity network - it just opens up the *geth console* attached to the rpc interface of the node you give it (and since geth and parity aren't entirely compatible on the rpc front, certain methods don't work).

 You want to run a geth node configured with a compatible chain spec and `geth attach` to *your geth node*, then commands like `miner.start()` will work fine.

**Comment by ddorgan** [comment]
@BlockchainDieter you can also just connect up ``` ethminer ``` to parity on localhost:8545 and it can mine via the parity node. 

See: https://wiki.parity.io/Mining

**Comment by BlockchainDieter** [comment]
Thanks for the replies - I think I can't use `ethminer` because I don't have a GPU with the machine I am testing on. However, I was trying to simulate the behavior described in the link given by @ddorgan. @joshua-mir is running another geth node and attaching to that geth the same as mining via a parity node? It seems to be no - if it is not the same, how can I simulate mining via the parity node without a gpu?

**Comment by joshua-mir** [comment]
@BlockchainDieter parity can't mine without a GPU. Correct me if I'm wrong but you're trying to create a multi-client testnet, so you will need to have a geth instance running anyway - that is what would be mining.

> is running another geth node and attaching to that geth the same as mining via a parity node?

No - you're mining with a geth node, not a parity node. Yes - you have a network that both geth and parity nodes can communicate on, it doesn't matter *which node* is the miner. 

"geth attach" just runs an interactive console that lets you talk to your nodes as a user on the command line, it isn't related to how nodes talk to each other on your private network at all.
