### ISSUE TITLE
No light peers who can serve data

### ISSUE THREAD

**Issue by aghamir** [paritytech/parity-ethereum#9965]
- **Parity Ethereum version**: v2.2.1-beta-5c56fc5-20181114
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

After updating from 2.1.4 to 2.2.1-beta, I've got `No light peers who can serve data` when use `personal_sendTransaction`.

**Comment by joshua-mir** [comment]
Hey @aghamir, are you running a light node? You can't reliably send transactions until your node is in sync, can you try again after that is the case?

**Comment by aghamir** [comment]
Hi @joshua-mir ,
Yes I'm running light node. I've tried it for 3 days(resets, waits, and etc). I can sync in lower version, but in 2.2.1 I'm not syncing. Maybe it is from getting peers in older version and cannot sync through them. You can see my peers here(`parity_netPeers`):

> {"jsonrpc":"2.0","result":{"active":0,"connected":34,"max":50,"peers":[{"caps":["eth/62","eth/63","par/1","par/2","pip/1"],"id":"f860a96f96fef01b0a3e268db7cc96caaaebc711c6e2f88887b1b28c63f5a5d86c1436663aed3d01e134c1fa6a9221a07716693714b07db32a172d16f14d49a4","name":"Parity/v1.7.8-stable-d5fcf3b-20171025/x86_64-windows-msvc/rustc1.20.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"162.205.248.54:49172"},"protocols":{"eth":null,"pip":{"difficulty":"0x1a56d58ec3db3d525c9","head":"5b154df3f06b128ca850b393db9b0742536df959d7b06a7598009cb8085a0422","version":1}}},{"caps":["pip/1"],"id":"37040f37da5a06c5b0087075e3181c7654032211346869050131d84804dadbda47e1d3c94e931c3f7a7caf49d7da0704e2b657f7b7db6520876d8beadbc9c413","name":"Parity-Ethereum/v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:55342","remoteAddress":"80.211.65.54:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b29881588207e6dbad","head":"897d10896473bc4e5df5ea0b0682235a0de3a05040c2c286f95910f8362770b4","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"3ab42bfe3c42f60698abff8efa0cc469b615c76132bfa0b553caefeaa119131823b5e65736ed31735a120c79544af72b7a48460354c5367789a5afd00db3774f","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.74.233.182:53142"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["par/1","par/2","par/3","eth/62","eth/63","pip/1"],"id":"3b4c3f0935d0892aa2e956abf24b2d4f6789a94dc5f50431e3db981f4d5e92c7c21d1f31a0bae5273e9cfae97fd3193efeecc2d3939c4a7e5108776e018b500c","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.90.189.74:55720"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["pip/1"],"id":"5ffe3e7b26617874f626e529c4193ef89ceeb8317a9fcd10989e10d70429c13af1d9deac4ce095104f40ef289fae8080f96dc570ae5de8aecc2b7df874775e92","name":"Parity-Ethereum/v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:55162","remoteAddress":"94.177.204.17:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b29881588207e6dbad","head":"897d10896473bc4e5df5ea0b0682235a0de3a05040c2c286f95910f8362770b4","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"1ba4f7d0f6dcbcbe80c669f5ebdbce22ba54c02e957d3782ff9be69b9625b8484e4998a509901325ee39b5ceb69188bb8e46fc5ab0cd3708c154d6d877609db5","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"60.205.213.158:40572"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["par/1","par/2","par/3","eth/62","eth/63","pip/1"],"id":"d0368bab90a71fac3d4fd182da54f0f268432d1ccf78150126e5cba699c3a62e183a43ef902cb40921ddceb843be0f8ecb7321dd7d151e92764ba81884af464c","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"120.79.200.209:40344"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["par/1","par/2","par/3","eth/62","eth/63","pip/1"],"id":"0bd387b63251bc3f610df1da4bc4377af8b6214b46ea067859090a9c34de0c6ec8e03627af80599d060bad07d8ead01df642620bdfd611c2e42b1da878aaaad0","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"101.201.238.229:50372"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","pip/1"],"id":"ebbd7d8bd015b7a3aee670734205d2ec1c65771b10cd5efc419c9ffa02188a588ed4b84c0a465c350d93da25583249ef27d7ff1f245e5f6f00bd59900cada71d","name":"Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1","network":{"localAddress":"188.212.22.84:33144","remoteAddress":"73.217.96.174:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"8c030617ceb9d718ab26029aca5a6e97199c68297c891dbe854c46a471f82ac9d2cf2c0c5be069f532e6a194aa70d5bf91f0bb035de8d4b99f1b9da423b8139d","name":"Parity-Ethereum/v2.0.8-stable-ef8f95e-20181015/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"52.90.214.40:60686"},"protocols":{"eth":null,"pip":{"difficulty":"0x37fcf74fca7bfd6896","head":"63fdc92d9dcd4b8c0975428de082a8c59b33403eeed8c968bace593f64da20b9","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"77dbd144677699ab65be560975b8260ab5e4f576fc92635b85744c19093afc8596a4ece6be9073d4f05d6d95f139a628397a826f8f054c2d1152bd7aa6291174","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.254.145.69:33624"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"675001a900d338368974347fd5e85d9d9f32173b5d290ab836739c0233166faca0b0d717597c983b7312f1b8df4441fe132988977442e9e8568ede9455fc3b0b","name":"Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.2","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"51.144.86.33:47742"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","pip/1","par/1","par/2"],"id":"f7395b68020f696f050ca3cca588840d24269e799989ff4d7a12582c06aaed20382c77d5272c179a4a4dd002d6fa8ca44ed102f1e40c423c0e35465e98da3ddf","name":"Parity/v1.10.6-unstable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.0","network":{"localAddress":"188.212.22.84:60314","remoteAddress":"165.227.145.96:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"fb74d46d96ca951282aa7bf0e8fd757b3bff641aa2216bffcf0d14531d050e4ab297a2cfd2ed716d60c7b42a2d623de63a68ea2aa85e8f395584bbc244eb257b","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.254.151.55:49754"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"12c4c0d0009191a11fa2b83c650ef5aafe677561838d2a74fc0a529eb5f464b6a561c16dc6fa984ac07acd49d233196e0ae01d08e37956bdbb98d17695692eaf","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.93.38.69:43330"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"3bb598b6838c43939c55df3d156fcd9a117450333ddcd48eb21f20211987e67c74aa9a5d9b683ac9065517c70f79e57fc68925098644187e7854cca494b88b3d","name":"Parity-Ethereum/v2.1.4-beta-bee2cb8-20181028/x86_64-linux-gnu/rustc1.30.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"121.7.96.194:54316"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b285150235fe092688","head":"7853262a330a1aa779689e8126f8960da2e0b15b8092c1910fadbec1019f3ab1","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"8d8305124e872acd3288859909e9d02ee25bc307baf865eeff349265cb4303af40c7d512546c22f57ac0e9f26eb6566d928d484e9952b7f27361d4534c738fa6","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.91.31.183:31542"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["par/1","par/2","par/3","eth/62","eth/63","pip/1"],"id":"e113a2f2c9437b8574b09cbc3db54cd1433332b33502ff469552cc3e27046c1c02c6c5e8d7e5891979ccaa014d3cf9f9dc7b7a87a980ae9d2490d8cb599d4827","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"101.201.66.5:48172"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","pip/1","par/1","par/2","par/3"],"id":"6dc46fa969a8e62eafa045a502c6600b9a1354b8e850121d50719c3e6187b614de7a6d70f34753e41121a10f0b16ac19396395f65b9249f88087894b49cb02aa","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.254.171.128:43338"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","pip/1"],"id":"c071d96b0c0f13006feae3977fb1b3c2f62caedf643df9a3655bc1b60f777f05e69a4e58bf3547bb299210092764c56df1e08380e91265baa845dca8bc0a71da","name":"Parity/v1.10.6-stable-bc0d134bb-20180605/x86_64-linux-gnu/rustc1.26.1","network":{"localAddress":"188.212.22.84:34228","remoteAddress":"68.183.99.5:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"874a95c543e91f18dd912895f6c869b5e13a87174a29f4270fcdf7d7c6afc7d1b8ab5868eb5c58d2a746c4f61eacbf0096896f127ad5f97af56a0655ec7057b3","name":"Parity-Ethereum/v2.0.0-beta-6eae372-20180717/x86_64-linux-gnu/rustc1.27.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"18.221.139.174:59268"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["pip/1"],"id":"6e38ea3762c8d462197c11a89ecd825d56985942738b070d56e387da4aab33549974658437ff8d18adfc11231dbe04ee9d5654421bfff25496c19d6b0517ca2f","name":"Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2","network":{"localAddress":"188.212.22.84:40222","remoteAddress":"62.210.151.2:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b29881588207e6dbad","head":"897d10896473bc4e5df5ea0b0682235a0de3a05040c2c286f95910f8362770b4","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"f5dfc64e79976a9762c85144d46b828f35bd291b244e6f7881c93a93f3f8df4a1cbf516080e97fb3bd1c1b05f5344b6735f2d88621b74f52add0fe8a0534be58","name":"Parity-Ethereum/v2.0.1-unstable/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.90.214.108:45066"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"d8ac916842b2fecc03bbef8568f47ddf6e78ab009a13c540f1431cc62b6d4948ef27daa6de21cf97872e76c33ab8be416f4f2a799cb0825c3324342d0b97297f","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:53460","remoteAddress":"47.88.226.38:30313"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"2795317a8a550fe147352639b66b4790439ac983894d720ea1887b150a6ea8c5b88f2cdd3262def85fb1374a07ed429b68bee7e41a0566c8a2c26b65a5c56a18","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:49548","remoteAddress":"47.74.158.59:30313"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"79d50384aeeac141899275b9456e9c203edb6b342ea33a844d5180832c832634f5edc3842d7abfb83f2f11a07d363b7682ff600afc1dc04d6640c61de69d7090","name":"Parity/v1.11.11-stable-cb03f38-20180910/x86_64-linux-gnu/rustc1.28.0","network":{"localAddress":"188.212.22.84:33268","remoteAddress":"18.231.17.251:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"713cc6d78ffe93010c489ef80e872a1d5fc244ea0aa239cf1613db3b49f19943cd60eb4106aa0d3b508a352a50e7a5b688b0214094b1a2fb1cf0e27f22c55c2e","name":"Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0","network":{"localAddress":"188.212.22.84:44408","remoteAddress":"51.68.79.21:30303"},"protocols":{"eth":null,"pip":{"difficulty":"0x1a29fc4ed009103e0d","head":"31d76855055ccce7daba5660e7463aaf5fd355c18dbfcb7802dbbaf5a0431b74","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","pip/1"],"id":"993e36d644c2f20cdfd4d3740dec47e3485a973f5da6d410a94b95c27a548af66e9d4135a06159d419c17eba327c589922a9951662c068f0e0b879524462b20c","name":"Parity/v1.9.4-beta-6f21a32-20180228/x86_64-linux-gnu/rustc1.24.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"18.221.7.87:49594"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":[],"id":"50c27791a1a1ae7dc9b4eaddd1b91c48be0666c5d26b2beea390a2c7cad30aa987e01e70db8f721839c75cb85ae47e18478b9003d0f09a4eb9a8d6dfd8a5a7be","name":"","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"54.93.105.176:37574"},"protocols":{"eth":null,"pip":null}},{"caps":["pip/1"],"id":"c1b266515a231324568ce90efbe3a30284026f7e9d4065cfb9417825fd587730d5e790e7b463261dac0961b3d1ed2140fc2833a85141e2feca62135bf1eab5ef","name":"Parity-Ethereum/v2.1.1-beta-cb09330-20180919/x86_64-linux-gnu/rustc1.29.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"80.211.76.253:45862"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b29919e9cdea53fe74","head":"2b7708c72fc5ae3e0e2fedd72b4dccd3f96f7f0593d290e0dbe35e4172fa5060","version":1}}},{"caps":["par/1","par/2","par/3","pip/1","eth/62","eth/63"],"id":"42bf4edcb9e1dcd2c9cd0989fba939572b3ee0d1cad50f62f4693688e126a4761141d5b2a17d55c9e96c89c958fa171efa2d69a8939bd41e0d7fafc9821eea8c","name":"Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"34.226.4.114:61935"},"protocols":{"eth":null,"pip":{"difficulty":"0x622f1dee3053c6333a","head":"baffbac169872e675cd7747ec53ae8b95393ed96c1102e09ef08cdbec709d72d","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"34fb115b06218c68f8f27b11a54f230c2935e032ff51ec7ec69ff98c854458039831395ca3d981485f59ce0d7db25533081a08a046157074361e80b95b40d613","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"89.184.83.201:53478"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":[],"id":"6eb2aad876a660a8e7b0511fe787730deffe593c75e555091689e3def374e3422dd0e2552a32a1f871e67ee8cc2eb7ed79fdf0eab526f18dd5f53a09a056f261","name":"","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"218.68.151.9:56337"},"protocols":{"eth":null,"pip":null}},{"caps":["par/1","par/2","par/3","eth/62","eth/63","pip/1"],"id":"3611190092433fcc51255ab6cb23559cabd340d1dd065fba22561200146d05f08b2fc401540e640a5d13f8b27c1ee3271a376e0efc850e03274120b2145a4ca6","name":"Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"92.249.148.207:58022"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}},{"caps":["pip/1"],"id":"b1ac722fb14483516adbcfb0d95e9c9c4eb14369d901f2c47c7fee3083c5819b34af90f6eba1f79969491226564175fef09c713f8ff71fee8207ff1b67f518af","name":"Parity/v1.11.3-beta-a66e36bf4-20180605/x86_64-windows-msvc/rustc1.26.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"92.127.196.138:52185"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b298fd4517bcf3d107","head":"372e82ee4874f5bfe6ca0a243623d5ee7d1f6b3fb3b29ac217c187ae1c2df269","version":1}}},{"caps":["eth/62","eth/63","par/1","par/2","par/3","pip/1"],"id":"c75b14c69035dc7aec9ed25c1faf3d1176650da816c52d4dacce300f7cc815530f00f5a84050fe5325248564744bf9e7b4ace6f0ed72111f4bd669972ff93ca4","name":"Parity-Ethereum/v2.1.6-stable-491f17f-20181114/x86_64-linux-gnu/rustc1.30.1","network":{"localAddress":"188.212.22.84:30304","remoteAddress":"47.74.6.67:57658"},"protocols":{"eth":null,"pip":{"difficulty":"0x1b82252883c0b75a96","head":"5b913b29a14a8054bd3c33cd5cb51fb7f5d7291d38cb17b36a851aca13b09007","version":1}}}]},"id":1}

**Comment by joshua-mir** [comment]
Can you please try `parity --light db kill` and then try again? The hard-coded headers should help you get back to sync in a few minutes. You might have issues with your older db.

**Comment by joshua-mir** [comment]
Let me know if the suggestion above didn't help or this issue is still ongoing on the latest stable.
