### ISSUE TITLE
EIP161 contract nonce

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity-ethereum#9968]
Greetings,

I have an issue with the EIP161. This protocol upgrade should work after block 2,675,000, but this [transaction](https://etherscan.io/tx/0xd852d2191f40581cbacc3403d5f4bddd8836010b2ed78fa4c4d0b49bd79b8bc0) which are mined in block 2,674,998 the created contract has increased nonce. It should be zero?!

I use `Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0`.

**Comment by joshua-mir** [comment]
@iFA88 Contract nonces are incremented when a contract creates another contract - that contract seems to create another contract in it's constructor, if you look at the internal transactions of that transaction, therefore it's nonce is 1, not 0.
