### ISSUE TITLE
When I try to sync the data, it will get stuck here.

### ISSUE THREAD

**Issue by ye21st** [paritytech/parity-ethereum#9986]
> **Parity Ethereum version**: 2.1.7-stable
> **Operating system**: Windows 7
> **Installation**: exe
> **Fully synchronized**: no
> **Network**: ropsten
> **Restarted**: yes

![tim 20181129104709](https://user-images.githubusercontent.com/17704719/49196006-38fc5280-f3c4-11e8-971c-05d0e3ac4884.png)

I have tried it from v2.0.9 - v2.1.7, 2.0.9 can synchronize data normally, when the data is synchronized to 4,500,000 block data, I don't know what the problem is, the number of blocks is going backwards, my colleague is synchronizing The data is also like this. I don't know what caused the problem. Can you help me solve it?

**Comment by Tbaut** [comment]
How do you launch parity?
I'd advise to use `--warp-barrier 4510000` for instance to get to the top of the chain quickly. The sync will then happen in the background from the genesis.

**Comment by joshua-mir** [comment]
@ye21st closing as stale, please let us know if this is still an issue
