### ISSUE TITLE
Programmatic discovery of ancient log sync state.

### ISSUE THREAD

**Issue by AC0DEM0NK3Y** [paritytech/parity-ethereum#9993]
- **Parity Ethereum version**: 2.1.7
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum & kovan
- **Restarted**: yes

I am trying to setup a safety on my log events program that is sat on a default/warp synced node so that it will not let the user continue unless the ancient logs are available from contract creation block number to latest. This is to make sure that all the events that are needed to be visible to the program are available before the logs are inspected.

I have tried to use the web3.eth.isSyncing method (wrapper for eth_syncing) but this does not return an info object and instead returns false if the node is synced to state snapshot but is still not synced to ancient blocks.

As is stands I can't see a way of programmatically checking if a node is "fully synced" in terms of log/events and I think this is a very important feature to have when using snapshot mode, without having to eye the output text while syncing and importing.

Thanks.

**Comment by andresilva** [comment]
You can use `parity_chainStatus` and check if `blockGap` is defined (https://wiki.parity.io/JSONRPC-parity-module#parity_chainstatus).

**Comment by AC0DEM0NK3Y** [comment]
Thanks. FYI will test this soon. Web3 doesn't wrap this, but I guess this is because it is a parity specific function.

Has there been thought of branching web3 or other such tools (like ethers) and creating parity specific extensions to support such things?

**Comment by 5chdn** [comment]
Yes, you can use the parityjs api

https://github.com/paritytech/js-libs/tree/master/packages/api

**Comment by AC0DEM0NK3Y** [comment]
Just wanted to mention blockgap looks to work well and you can easily call through web3 I discovered via an extend call:

`_web3.extend({
        methods: [{
            name: 'getBlockGap',
            call: 'parity_chainStatus',
        }]
    });`

`return await _web3.getBlockGap();`
