### ISSUE TITLE
Parity websocket subscribe not working well.

### ISSUE THREAD

**Issue by kamilk91** [paritytech/parity-ethereum#9995]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
**actual**
'{"method":"parity_subscribe","params":["trace_filter", [{"toAddress":["0x085101821e04da1b5242c8468d96ba287b3176c7"],"fromBlock":"0x663BE0"}]],"id":1,"jsonrpc":"2.0"}'  

gives me 

ethod":"parity_subscribe","params":["trace_filter", [{"toAddress":["0x085101821e04da1b5242c8468d96ba287b3176c7"],"fromBlock":"0x663BE0"}]],"id":1,"jsonrpc":"2.0"}
{"jsonrpc":"2.0","result":"0xbe929954d88fd69e","id":1}
{'jsonrpc': '2.0', 'result': '0xbe929954d88fd69e', 'id': 1}

and then stop responding. Just hang on this result, when im trying to make new websocket client its only connected, but gives me no result. 

When im trying to connect second ws client, it gives me no result, i dont have even id of subscription, my connections limit in config toml is set to 1001

**Comment by tomusdrw** [comment]
`trace_filter` requires running with `--tracing=on`, do you have that enabled?

**Comment by kamilk91** [comment]
@tomusdrw sure. Its working now only if i give him 50-100 blocks back. I need to find transactions in about 10000 blocks without 2 days waiting.

**Comment by joshua-mir** [comment]
@kamilk91 you can't get traces from blocks that were imported before tracing was on - if you need older traces, you need to resync with tracing enabled. 

If you want traces from older blocks, you need to have `--pruning archive` or older blocks are pruned. You can also use the `--pruning-history` and `--pruning-memory` options to fine tune how much is pruned, but none of these changes are retroactive.

Also -  you might want to tweak `server_threads` in the RPC section if you are planning multiple simultaneous ws connections along with `processing_threads`

**Comment by joshua-mir** [comment]
Closing as there's nothing to do here.
