### ISSUE TITLE
High load average on linux server

### ISSUE THREAD

**Issue by itsmylife44** [paritytech/parity-ethereum#9998]
- **Parity Ethereum version**: Parity-Ethereum/v2.2.2-beta-78ceec6-20181129/x86_64-linux-gnu/rustc1.30.1
- **Operating system**: Description:    Ubuntu 16.04.5 LTS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum .
- **Restarted**:  yes

**High load average on linux server**

**./parity --chain ethereum --no-ws --pruning fast --db-compaction ssd --mode active --jsonrpc-port 6432 --port 30308 --min-peers 100 --max-peers 150 --cache-size 10024**

![cattura](https://user-images.githubusercontent.com/34112129/49283985-8eebfb80-f493-11e8-9d4f-be169fb705ef.PNG)

**system works on ssd and its only run parity**

**Comment by 5chdn** [comment]
Yes, your node is executing 10~15 transactions per second and writing the results to a database. There is not much we can do about this. 

You could try to run it in `--mode passive` to have some more relaxed breaks in between.
